### ISSUE TITLE
0.4.3 is broken

### ISSUE THREAD

**Issue by jakzal** [rectorphp/rector#1144]
```
composer require rector/rector
```

```
Using version ^0.4.3 for rector/rector
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 33 installs, 0 updates, 0 removals                                                                                                                         - Installing ocramius/package-versions (1.4.0): Downloading (100%)
  - Installing symfony/yaml (v4.2.4): Downloading (100%)
  - Installing symfony/http-foundation (v4.2.4): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.2.4): Downloading (100%)
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing symfony/debug (v4.2.4): Downloading (100%)
  - Installing symfony/http-kernel (v4.2.4): Downloading (100%)
  - Installing symfony/finder (v4.2.4): Downloading (100%)
  - Installing symfony/dependency-injection (v4.2.4): Downloading (100%)
  - Installing symfony/filesystem (v4.2.4): Downloading (100%)                                                                                                                 - Installing symfony/config (v4.2.4): Downloading (100%)
  - Installing nette/utils (v2.5.3): Downloading (100%)
  - Installing nette/finder (v2.5.0): Downloading (100%)
  - Installing symfony/translation (v4.2.4): Downloading (100%)
  - Installing nesbot/carbon (2.14.2): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing illuminate/contracts (v5.8.2): Downloading (100%)
  - Installing doctrine/inflector (v1.3.0): Downloading (100%)
  - Installing illuminate/support (v5.8.2): Downloading (100%)
  - Installing symplify/package-builder (v5.4.14): Downloading (100%)
  - Installing phpstan/phpdoc-parser (0.3.1): Downloading (100%)                                                                                                               - Installing symplify/better-phpdoc-parser (v5.4.14): Downloading (100%)
  - Installing symfony/process (v4.2.4): Downloading (100%)
  - Installing nikic/php-parser (v4.2.1): Downloading (100%)
  - Installing nette/robot-loader (v3.1.1): Downloading (100%)
  - Installing nette/neon (v3.0.0): Downloading (100%)
  - Installing nette/php-generator (v3.2.1): Downloading (100%)
  - Installing nette/di (v2.4.15): Downloading (100%)
  - Installing nette/bootstrap (v2.4.6): Downloading (100%)
  - Installing jean85/pretty-package-versions (1.2): Downloading (100%)
  - Installing composer/xdebug-handler (1.3.2): Downloading (100%)
  - Installing phpstan/phpstan (0.11.2): Downloading (100%)
  - Installing rector/rector (v0.4.3): Downloading (100%)
```

```
./vendor/bin/rector
```

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockAnalyzer": argument "$phpDocInfoFactory" of method "__construct()" references class "Symplify\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory" but no such service exists. in /path/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /path/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /path/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /path/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php in /path/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 54
```

**Comment by TomasVotruba** [comment]
Is master ok? I'll tag it if so

**Comment by jakzal** [comment]
Seems fine. At least it installs and doesn't crash when I run basic commands ;)

**Comment by TomasVotruba** [comment]
Let's go :+1:

**Comment by jakzal** [comment]
My build seems to be passing: https://github.com/jakzal/toolbox/pull/61

thanks!
