### ISSUE TITLE
AliasToClassRector errors out

### ISSUE THREAD

**Issue by msvrtan** [rectorphp/rector#1342]
We are running on latest Symfony (4.2.7) .. rector version is v0.4.11: do we need to set up something extra?

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Rector\Doctrine\Rector\AliasToClassRector": argument "$aliasesToNamespaces" of method "__construct()" is type-hinted "array", you should configure its value explicitly. in /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(46): Symfony\Comp in /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php on line 54
```

**Comment by TomasVotruba** [comment]
Yes, this rule needs manual configuration. The exception needs to be improved.

I didn't write/test rule myself, so I might be wrong, but I think you need to configure it with entity aliases → entity class:

```yaml
services:
    Rector\Doctrine\Rector\AliasToClassRector:
        $aliasesToNamespaces:
            'product': 'App\Entity\Product'
```

Then it replaces aliases in your application for classes:

```diff
-$this->entityManager->getRepository('product')
+$this->entityManager->getRepository(\App\Entity\Product::class)
```

**Comment by msvrtan** [comment]
Ah OK, than the docs are not explaining the details well :(

Closing

**Comment by TomasVotruba** [comment]
> Will try to check it out (but looks like we dont have this issue) and will send a PR to update docs

Thank you, PR would the best

**Comment by TomasVotruba** [comment]
Issue solved, waits on PR to docs
