### ISSUE TITLE
Error - Argument passed must be an instance of MethodCall, Identifier given

### ISSUE THREAD

**Issue by Einenlum** [rectorphp/rector#1356]
I am trying to update my Symfony2.8 project to Symfony3.0, using the docker version of rector.

Using: ` docker run -v $(pwd):/project rector/rector:latest process /project/src --level symfony30 --dry-run --autoload-file /project/vendor/autoload.php`

I get some errors (always the same):

```
 [ERROR] Could not process "/project/src/App/Controller/CaptchaController.php"  
         file by "Rector\Symfony\Rector\HttpKernel\GetRequestRector", due to:   
         "Argument 1 passed to                                                  
         Rector\Symfony\Rector\HttpKernel\GetRequestRector::isGetMethodCallWithR
         equestParameters() must be an instance of                              
         PhpParser\Node\Expr\MethodCall, instance of PhpParser\Node\Identifier  
         given, called in                                                       
         /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php on 
         line 166".
```

You can see [here](https://gist.github.com/Einenlum/214b3bd9dbe419fd5f9d5b82c0b87ebc) the full output.

**Comment by TomasVotruba** [comment]
Hi, please provide the file you run Rector on causing this.

There will be just one line

**Comment by Einenlum** [comment]
Hi @TomasVotruba, thanks for your answer.

[Here](https://gist.github.com/Einenlum/cba8ace9d43682b1bfac668261903d2c) is the file.

**Comment by Einenlum** [comment]
The stack trace with the -vvv option:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Rector\Symfony\Rector\HttpKernel\GetRequestRector::isGetMethodCallWithRequestParameters() must be an instance of PhpParser\Node\Expr\MethodCall, instance of PhpParser\Node\Identifier given, called in /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php on line 166 and defined in /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php:174
Stack trace:
#0 /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php(166): Rector\Symfony\Rector\HttpKernel\GetRequestRector->isGetMethodCallWithRequestParameters(Object(PhpParser\Node\Identifier))
#1 /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php(93): Rector\Symfony\Rector\HttpKernel\GetRequestRector->isActionWithGetRequestInBody(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /rector/src/Rector/AbstractRector.php(95): Rector\Symfony\Rector\HttpKernel\GetRequestRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraver in /rector/packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php on line 174

```

**Comment by Einenlum** [comment]
Thanks! :)
