### ISSUE TITLE
[Symfony 4.3] EventDispatcher has now constructor

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#1512]
See https://github.com/symfony/symfony/commit/d6a594bf426527a61bb404fdbbf5125d9ef0c9a5#diff-2625d73628ba1f5fe88407a081376b92

```diff
class MyEventDispatcher extends EventDisptacher
{
    public function __construct()
    {
        // my code
+       parent::__construct();
    }
}
```

**Comment by cgkkevinr** [comment]
Hi @TomasVotruba, your change in #1513 made Rector >=0.5.2 incompatible with Symfony <4.3. Was that intended and should I downgrade to 0.5.1 until I can upgrade Symfony? Thanks.

```
Fatal error: Uncaught Error: Cannot call constructor in /app/vendor/rector/rector/src/EventDispatcher/AutowiredEventDispatcher.php:19
Stack trace:
#0 /tmp/_rector/ContainerKmbDEZb/getAutowiredEventDispatcherService.php(9): Rector\EventDispatcher\AutowiredEventDispatcher->__construct(Array)
#1 /tmp/_rector/ContainerKmbDEZb/HttpKernelRector_HttpKernel_RectorKernelProd1260520Container.php(263): require('/tmp/_rector/Co...')
#2 /tmp/_rector/ContainerKmbDEZb/getApplicationService.php(11): ContainerKmbDEZb\HttpKernelRector_HttpKernel_RectorKernelProd1260520Container->load('getAutowiredEve...')
#3 /tmp/_rector/ContainerKmbDEZb/HttpKernelRector_HttpKernel_RectorKernelProd1260520Container.php(263): require('/tmp/_rector/Co...')
#4 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(243): ContainerKmbDEZb\HttpKernelRector_HttpKernel_RectorKernelProd1260520Container->load('getApplicationS...')
#5 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(225): Symfony\Componen in /app/vendor/rector/rector/src/EventDispatcher/AutowiredEventDispatcher.php on line 19
```

**Comment by TomasVotruba** [comment]
Hi, is that related to https://github.com/rectorphp/rector/issues/1546?

It's fixed in master

**Comment by cgkkevinr** [comment]
Partially, but the parent constructor call in `AutowiredEventDispatcher` is also causing issues.

**Comment by TomasVotruba** [comment]
I see. So there is bug one way or another?

**Comment by cgkkevinr** [comment]
I believe that #1558 should fix it.

**Comment by TomasVotruba** [comment]
Perfect :), thank you!
