### ISSUE TITLE
ShouldNotHappenException in RenameMethodRector of phpunit80 level

### ISSUE THREAD

**Issue by cgkkevinr** [rectorphp/rector#1566]
Hi,

Rector threw a ShouldNotHappenException while analysing against level phpunit80 on the following code.

```php
<?php

namespace App\Tests\Exception;

use App\Exception\ErrorHandlerTrait;
use PHPUnit\Framework\TestCase;

class ErrorHandlerTraitTest extends TestCase
{
    public function testErrorHandler(): void
    {
        $this->expectException(\ErrorException::class);
        $class = new class {
            use ErrorHandlerTrait;

            public function triggerError(): void
            {
                $this->startErrorHandling();
                trigger_error('an error has occurred');
                $this->stopErrorHandling();
            }
        };

        $class->triggerError();
    }
}
```

This is the trait code:

```php
<?php

namespace App\Exception;

trait ErrorHandlerTrait
{
    private $errorMessage;
    private $errorSeverity;
    private $errorFile;
    private $errorLine;

    private function startErrorHandling(): void
    {
        $this->errorMessage = null;
        $this->errorSeverity = null;
        $this->errorFile = null;
        $this->errorLine = null;
        set_error_handler([$this, 'errorHandler']);
    }

    /**
     * @throws \ErrorException
     */
    private function stopErrorHandling(): void
    {
        restore_error_handler();
        if ($this->errorMessage !== null) {
            throw new \ErrorException($this->errorMessage, 0, $this->errorSeverity, $this->errorFile, $this->errorLine);
        }
    }

    private function errorHandler($severity, $message, $file, $line): void
    {
        $this->errorSeverity = $severity;
        $this->errorMessage = $message;
        $this->errorFile = $file;
        $this->errorLine = $line;
    }
}
```

Here's the stack trace:

```
Fatal error: Uncaught Rector\Exception\ShouldNotHappenException in /app/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php:382
Stack trace:
#0 /app/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(153): Rector\NodeTypeResolver\NodeTypeResolver->resolveClassNode(Object(PhpParser\Node\Stmt\ClassMethod))
#1 /app/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(144): Rector\NodeTypeResolver\NodeTypeResolver->resolve(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /app/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(118): Rector\NodeTypeResolver\NodeTypeResolver->getTypes(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /app/vendor/rector/rector/src/Rector/NodeTypeResolverTrait.php(30): Rector\NodeTypeResolver\NodeTypeResolver->isType(Object(PhpParser\Node\Stmt\ClassMethod), 'PHPUnit\\Framewo...')
#4 /app/vendor/rector/rector/src/Rector/MethodCall/RenameMethodRector.php(73): Rector\Rector\AbstractRector->isType(Object(PhpParser\Node\Stmt\ClassMet in /app/vendor/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php on line 382
```

It was called with this array of `$oldToNewMethods`:

```
Rector\Rector\MethodCall\RenameMethodRector
array(2) {
  ["setExpectedException"]=>
  string(17) "expectedException"
  ["setExpectedExceptionRegExp"]=>
  string(17) "expectedException"
}
```

I think it might be caused because I'm using an anonymous class. What can I do to help fix this? I tried having a look but I can't really make much sense of it.

**Comment by TomasVotruba** [comment]
You're right, it's related to anonymous method resolving
