### ISSUE TITLE
Bug: Trait with parent call crashes RemoveParentCallWithoutParentRector

### ISSUE THREAD

**Issue by Levivb** [rectorphp/rector#1592]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector --debug  --config rector.yml process Traits/SomeTrait.php -n | 

```yml
# rector.yml
parameters:
  php_version_features: '7.2'

services:
  Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: ~
```

## Current Behaviour 

```
Rector v0.5.5
Config file: /my-project/rector.yml

/my-project/Traits/SomeTrait.php
/my-project/Traits/SomeTrait.php
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\PHPUnit\Rector\ExceptionAnnotationRector
Rector\Rector\MethodCall\RenameMethodRector
Rector\Rector\Annotation\RenameAnnotationRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector
Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\PHPUnit\Rector\DelegateExceptionArgumentsRector
Rector\Rector\MethodCall\RenameMethodRector
Rector\PHPUnit\Rector\MethodCall\UseSpecificWillMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertNotOperatorRector
Rector\PHPUnit\Rector\SpecificMethod\AssertComparisonToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertSameBoolNullToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertFalseStrposToContainsRector
Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseInternalTypeToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertCompareToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertIssetToSpecificMethodRector
Rector\PHPUnit\Rector\SpecificMethod\AssertInstanceOfComparisonRector
Rector\PHPUnit\Rector\SpecificMethod\AssertPropertyExistsRector
Rector\PHPUnit\Rector\SpecificMethod\AssertRegExpRector
Rector\CodeQuality\Rector\FuncCall\SimplifyRegexPatternRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector
Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector
PHP Fatal error:  Uncaught LogicException: leaveNode() returned invalid value of type integer in /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:168
Stack trace:
#0 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#1 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /Users/Levi/Documents/Work/r in /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 168

Fatal error: Uncaught LogicException: leaveNode() returned invalid value of type integer in /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:168
Stack trace:
#0 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#1 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /Users/Levi/Documents/Work/r in /my-project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 168
```

## Minimal PHP Code Causing Issue

```php
<?php namespace Traits;
// Heavily simplified example
trait SomeTrait
{
    protected function bootstrappers(): array
    {
        return parent::bootstrappers();
    }
}
```

## Expected Behaviour
Since a parser can't determine what the parent is and therefor check if the parent call is unnecessary or not I see no other way than for rector to ignore this parent call. It might be unnecessary, but a parser is unable to figure that one out.

I did try to fix the issue through docblocks:

```php
/**
* @mixin \The\Parent\Class
*/
trait SomeTrait {
// code
```

and 

```php
/**
* @method array bootstrappers()
*/
trait SomeTrait {
// code
```

But to no avail

Can this crash be fixed?

**Comment by TomasVotruba** [comment]
Indeed, I think this should only check classes, since Trait/Interface have no ideas about parents' logic.

**Comment by TomasVotruba** [comment]
Just curious, what's the use case for that method in the trait?

**Comment by TomasVotruba** [comment]
In your report I see there are many other Rectors run - from `dead-code`, `coding-style` etc., this one will not be the resonsible for this error.

Could you try to run just single Rector rule to find out which is responsbile?
