### ISSUE TITLE
Fatal error on Template annotation

### ISSUE THREAD

**Issue by jaapio** [rectorphp/rector#2120]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| PHP version    |  PHP 7.2                               |
|Symfony | 3.4.29|
| sensio/framework-extra-bundle| 5.4.1

## Current Behaviour 

```
Fatal error: Uncaught TypeError: Argument 2 passed to Rector\BetterPhpDocParser\PhpDocNode\Sensio\SensioTemplateTagValueNode::__construct() must be of the type array, null given, called in /rector/packages/BetterPhpDocParser/src/PhpDocNodeFactory/Sensio/SensioTemplatePhpDocNodeFactory.php on line 38 and defined in /rector/packages/BetterPhpDocParser/src/PhpDocNode/Sensio/SensioTemplateTagValueNode.php:39
Stack trace:
#0 /rector/packages/BetterPhpDocParser/src/PhpDocNodeFactory/Sensio/SensioTemplatePhpDocNodeFactory.php(38): Rector\BetterPhpDocParser\PhpDocNode\Sensio\SensioTemplateTagValueNode->__construct(NULL, NULL, Array)
#1 /rector/packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php(158): Rector\BetterPhpDocParser\PhpDocNodeFactory\Sensio\SensioTemplatePhpDocNodeFactory->createFromNodeAndTokens(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 /rector/packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php(140): Rector\BetterPhpDocParser\PhpDocPa in /rector/packages/BetterPhpDocParser/src/PhpDocNode/Sensio/SensioTemplateTagValueNode.php on line 39
```
## Minimal PHP Code Causing Issue

```php
<?php

namespace \Bundle\WebsiteBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request as HttpRequest;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * @author redacted <my@email.com>
 */
class PaymentController
{
    /**
     * @var TransactionRepository ;
     */
    private $transactionRepository;

    /**
     * @param TransactionRepository $transactionRepository
     */
    public function __construct(TransactionRepository $transactionRepository)
    {
        $this->transactionRepository = $transactionRepository;
    }

    /**
     * @param HttpRequest $httpRequest
     * @Template
     * @return array
     */
    public function payperEmailResponseAction(HttpRequest $httpRequest)
    {
        if (!$transaction = $this->transactionRepository->findOneByIdentifier(1)
            throw new NotFoundHttpException();
        }

        return [
            'transaction' => $transaction
        ];
    }
}
```

## Expected Behaviour

I would not expect any parse error.

**Comment by TomasVotruba** [comment]
Thanks for reporting!

Fixed in #2121
