### ISSUE TITLE
Rector\Renaming\Rector\Class_\RenameClassRector

### ISSUE THREAD

**Issue by Aerendir** [rectorphp/rector#2305]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | 0.5.21         |
| PHP version    | PHP 7.2                               |
| Full Command   | vendor/bin/rector process /src -vvv --dry-run --debug  | 

I get the following error:

```console
PHP Notice:  Undefined offset: 216 in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 149
PHP Notice:  Undefined offset: 216 in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 40

Notice: Undefined offset: 216 in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 149

Notice: Undefined offset: 216 in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 40
PHP Fatal error:  Uncaught TypeError: Return value of PHPStan\PhpDocParser\Parser\TokenIterator::currentTokenType() must be of the type integer, null returned in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:40
Stack trace:
#0 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocParser/AnnotationContentResolver.php(35): PHPStan\PhpDocParser\Parser\TokenIterator->currentTokenType()
#1 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php(40): Rector\BetterPhpDocParser\PhpDocParser\AnnotationContentResolver->resolveFromTokenIterator(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocNod in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 40

Fatal error: Uncaught TypeError: Return value of PHPStan\PhpDocParser\Parser\TokenIterator::currentTokenType() must be of the type integer, null returned in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:40
Stack trace:
#0 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocParser/AnnotationContentResolver.php(35): PHPStan\PhpDocParser\Parser\TokenIterator->currentTokenType()
#1 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php(40): Rector\BetterPhpDocParser\PhpDocParser\AnnotationContentResolver->resolveFromTokenIterator(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocNod in /Users/Aerendir/Documents/MyProjects/_Projects/MyApp/Apps/app-MyApp-www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 40
```

**Comment by TomasVotruba** [comment]
Failing PHP code is needed

**Comment by Aerendir** [comment]
Yes, I'm investigating...

**Comment by Aerendir** [comment]
This is the bare minimum code that causes the issue:

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

class MyClass
{
    /**
     * @ORM\ManyToMany(targetEntity="Entity\AnotherClass", inversedBy="anotherClasses", cascade={"persist"}))
     */
    private $myProperty;
}
```

It seems it is caused by the `ManyToMany` annotation...

In fact, the error is caused by `/BetterPhpDocParser/src/PhpDocNod`.

**Comment by TomasVotruba** [comment]
I see, thanks :+1:

**Comment by RusiPapazov** [comment]
Subject | Details
-- | --
Rector version | 0.5.20
PHP version | PHP 7.1.28
Full Command | vendor/bin/rector process ./src/Entity/WeeklySchedule.php --set=symfony41


Hey, we are having a similar error.
Minimum code that fails: 
```php
<?php

namespace Clippings\Entity;

use Doctrine\ORM\Mapping as ORM;

class WeeklySchedule
{
    /** @ORM\Column(name="time", type="integer") */
    private $time;
}
```
Minimum changes that fixes this:
```php
<?php

namespace Clippings\Entity;

use Doctrine\ORM\Mapping as ORM;

class WeeklySchedule
{
    /**
     * @ORM\Column(name="time", type="integer")
     */
    private $time;
}
```
The error is:
![image](https://user-images.githubusercontent.com/776688/68843640-22cccc80-06d1-11ea-8fd4-bc8c4bb939d6.png)

Hope this helps 🤞.
