### ISSUE TITLE
Error When Running Rector On Symfony Codebase 

### ISSUE THREAD

**Issue by ahmedbodi** [rectorphp/rector#2357]
Running on Docker with Version 0.5.23 

```
Fatal error: Uncaught TypeError: Argument 1 passed to Rector\Application\Error::__construct() must be an instance of Symplify\SmartFileSystem\SmartFileInfo, instance of Symplify\PackageBuilder\FileSystem\SmartFileInfo given, called in /rector/src/Application/ErrorAndDiffCollector.php on line 145 and defined in /project/vendor/rector/rector/src/Application/Error.php:31
Stack trace:
#0 /rector/src/Application/ErrorAndDiffCollector.php(145): Rector\Application\Error->__construct(Object(Symplify\PackageBuilder\FileSystem\SmartFileInfo), 'Kernel "App\\Ker...', 0)
#1 /rector/src/Application/RectorApplication.php(235): Rector\Application\ErrorAndDiffCollector->addThrowableWithFileInfo(Object(Rector\Exception\ShouldNotHappenException), Object(Symplify\PackageBuilder\FileSystem\SmartFileInfo))
#2 /rector/src/Application/RectorApplication.php(156): Rector\Application\RectorApplication->tryCatchWrapper(Object(Symplify\PackageBuilder\FileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#3 /rector/src/Console/Command/ProcessComm in /project/vendor/rector/rector/src/Application/Error.php on line 31
```

**Comment by TomasVotruba** [comment]
How did you fixed it?

**Comment by ahmedbodi** [comment]
Was running two different versions. Had 0.5 in the composer.json but 0.6 in the docker file

**Comment by TomasVotruba** [comment]
Ah :)
