### ISSUE TITLE
Can't run rector without services

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector#2403]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | e.g. v0.5.11          |
| PHP version    | e.g. PHP 7.3                               |
| Full Command   | vendor/bin/rector process src/ --dry-run  | 

## Current Behaviour 

log:

```shell
Rector v0.5.11
Config file: /var/www/rector.yaml

PHP Fatal error:  Uncaught Rector\Exception\NoRectorsLoadedException: We need some rectors to run:
* register them in rector.yaml under "services:"
* use "--set <set>"
* or use "--config <file>.yaml" in /var/www/vendor/rector/rector/src/Guard/RectorGuard.php:39
Stack trace:
#0 /var/www/vendor/rector/rector/src/Console/Command/ProcessCommand.php(141): Rector\Guard\RectorGuard->ensureSomeRectorsAreRegistered()
#1 /var/www/vendor/symfony/console/Command/Command.php(255): Rector\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vendor/rector/rector/src/Console/Command/AbstractCommand.php(32): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/vendor/symfony/console/Application.php(939): Rector\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Consol in /var/www/vendor/rector/rector/src/Guard/RectorGuard.php on line 39

```

I've followed the docs but can't figure out why it's blaming my, my `rector.yaml` looks like this

```yaml
parameters:
  sets:
    - 'code-quality'

```

## Expected Behaviour
set the `rector.yaml` (as in the docs and above) and run `vendor/bin/rector process src/ --dry-run` with no fatal errors

**Comment by TomasVotruba** [comment]
I think the version `v0.5.11` didn't have the sets feature yet.

**Comment by vladyslavstartsev** [comment]
Got it, will update dependencies than.
