### ISSUE TITLE
CountOnNullRector error

### ISSUE THREAD

**Issue by JoyceBabu** [rectorphp/rector#2425]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.1          |
| PHP version    | PHP 7.3.12                               |
| Full Command   | composer/bin/rector process rector/test.php -vvv  | 

## Current Behaviour 

```
composer/bin/rector process rector -vvv
Rector v0.6.1
Config file: rector.yaml

[parsing] rector/abc.php
[refactoring] rector/abc.php
    [applying] Rector\Php71\Rector\FuncCall\CountOnNullRector
PHP Exception:  Return value of Rector\NodeTypeResolver\NodeTypeResolver::getScopeNode() must implement interface PhpParser\Node, null returned in /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php on line 658

TypeError: Return value of Rector\NodeTypeResolver\NodeTypeResolver::getScopeNode() must implement interface PhpParser\Node, null returned in /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php:658
Stack trace:
#0 /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(666): Rector\NodeTypeResolver\NodeTypeResolver->getScopeNode(Object(PhpParser\Node\Expr\Variable))
#1 /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(626): Rector\NodeTypeResolver\NodeTypeResolver->getVariableUsages(Object(PhpParser\Node\Expr\Variable))
#2 /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php(268): Rector\NodeTypeResolver\NodeTypeResolver->correctPregMatchType(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Type\NullType))
#3 /my/dir/composer/rector/rector/src/Rector/AbstractRector/NodeTypeResolverTrait.php(91): Rector\NodeTypeResolver\NodeTypeResolver->isCountableType(Object(PhpParser\Node\Expr\Variable))
#4 /my/dir/composer/rector/rector/packages/Php71/src/Rector/FuncCall/CountOnNullRector.php(76): Rector\Rector\AbstractRector->isCountableType(Object(PhpParser\Node\Expr\Variable))
#5 /my/dir/composer/rector/rector/src/Rector/AbstractRector.php(116): Rector\Php71\Rector\FuncCall\CountOnNullRector->refactor(Object(PhpParser\Node\Expr\FuncCall))
#6 /my/dir/composer/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#7 /my/dir/composer/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#8 /my/dir/composer/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#9 /my/dir/composer/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(62): PhpParser\NodeTraverser->traverse(Array)
#10 /my/dir/composer/rector/rector/src/Application/FileProcessor.php(134): Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#11 /my/dir/composer/rector/rector/src/Application/RectorApplication.php(155): Rector\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#12 /my/dir/composer/rector/rector/src/Application/RectorApplication.php(221): Rector\Application\RectorApplication->Rector\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#13 /my/dir/composer/rector/rector/src/Application/RectorApplication.php(156): Rector\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#14 /my/dir/composer/rector/rector/src/Console/Command/ProcessCommand.php(188): Rector\Application\RectorApplication->runOnFileInfos(Array)
#15 /my/dir/composer/symfony/console/Command/Command.php(255): Rector\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /my/dir/composer/rector/rector/src/Console/Command/AbstractCommand.php(34): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /my/dir/composer/symfony/console/Application.php(1011): Rector\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /my/dir/composer/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /my/dir/composer/rector/rector/src/Console/Application.php(93): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /my/dir/composer/symfony/console/Application.php(148): Rector\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /my/dir/composer/rector/rector/bin/rector(48): Symfony\Component\Console\Application->run()
#22 {main}
[Fatal Error] Exception: Return value of Rector\NodeTypeResolver\NodeTypeResolver::getScopeNode() must implement interface PhpParser\Node, null returned in /my/dir/composer/rector/rector/packages/NodeTypeResolver/src/NodeTypeResolver.php on line 658

```

## Minimal PHP Code Causing Issue

  

```php
<?php
$arAuth = null;

count($arAuth);

```

## Expected Behaviour

Rector should run without error

**Comment by JoyceBabu** [comment]
```php
    private function getScopeNode(Node $node): Node
    {
        return $node->getAttribute(AttributeKey::METHOD_NODE)
            ?? $node->getAttribute(AttributeKey::FUNCTION_NODE)
            ?? $node->getAttribute(AttributeKey::NAMESPACE_NODE);
    }
```

getScopeNode is attempting to return null, since it is not within any of the above scopes. Is there an attribute for the global scope? Since global scope can be spread over multiple files, shouldn't `correctPregMatchType` return immediately when not inside one of the above scopes?

**Comment by TomasVotruba** [comment]
What exact sets/rules do you use?
