### ISSUE TITLE
phpstan notice during process

### ISSUE THREAD

**Issue by snapshotpl** [rectorphp/rector#2432]
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.1          |
| PHP version    | PHP 7.3.12                               |

## Current Behaviour 

During process:

```
> rector process module/ --dry-run
Rector v0.6.1
Config file: rector.yml

    0/3756 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  165/3756 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   4%
  298/3756 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7%
  360/3756 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9%
  376/3756 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
  471/3756 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  12%
  622/3756 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  16%
  729/3756 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19%
  752/3756 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%
  883/3756 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  23%
  934/3756 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  24%
 1090/3756 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  29%
 1127/3756 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
 1275/3756 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  33%
 1378/3756 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  36%
 1480/3756 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  39%Notice: Undefined offset: 7 in /var/www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 149
Notice: Undefined offset: 7 in /var/www/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php on line 40

 1503/3756 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
 1577/3756 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  41%
 1637/3756 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  43%
 1680/3756 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  44%
 1723/3756 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  45%
 1816/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  48%
 1878/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 1928/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  51%
 1981/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  52%
 2074/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  55%
 2127/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  56%
 2163/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  57%
 2210/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  58%
 2254/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60%
 2345/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  62%
 2371/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  63%
 2447/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  65%
 2630/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70%
 3005/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80%
 3381/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90%
 3756/3756 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
```

**Comment by snapshotpl** [comment]
I receive many other errors after process however I don't know how it is related with this notices:

```
 [ERROR] Could not process                                                      
         "/var/www/module/MyClass.php" file, due   
         to:                                                                    
         "Rector\NodeTypeResolver\StaticTypeMapper::mapPHPStanPhpDocTypeNodeToPH
         PStanType for                                                          
         Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\Type\AttributeAwareGene
         ricTypeNode".
```

**Comment by TomasVotruba** [comment]
It's related to invalid docblock. Extra/missing asterisk
What is there?

**Comment by snapshotpl** [comment]
You ask about error or notice?

**Comment by snapshotpl** [comment]
File with error:
```php
<?php declare(strict_types = 1);

use Ramsey\Uuid\UuidInterface;

interface ImagesQuery
{
    /**
     * @return iterable<UuidInterface>
     */
    public function get(UuidInterface $product): iterable;

    public function getOne(UuidInterface $id): string;
}

```

**Comment by TomasVotruba** [comment]
What exact rules/sets do you use? Bare Rector run does not cause the error

**Comment by snapshotpl** [comment]
```yml
services:
    Rector\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector: ~
    Rector\CodeQuality\Rector\If_\ConsecutiveNullCompareReturnsToNullCoalesceQueueRector: ~
    Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector: ~
    Rector\CodeQuality\Rector\BooleanAnd\SimplifyEmptyArrayCheckRector: ~
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToArrayFilterRector: ~
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToCoalescingRector: ~
    Rector\CodeQuality\Rector\If_\SimplifyIfNotNullReturnRector: ~
    Rector\CodeQuality\Rector\FuncCall\SimplifyRegexPatternRector: ~
    Rector\CodeQuality\Rector\FuncCall\SimplifyStrposLowerRector: ~
    Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: ~
    Rector\Php53\Rector\Ternary\TernaryToElvisRector: ~
    Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector: ~
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertComparisonToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\MethodCall\AssertEqualsParameterToSpecificMethodsTypeRector: ~
    Rector\Php70\Rector\If_\IfToSpaceshipRector: ~
    Rector\Php73\Rector\BinaryOp\IsCountableRector: ~
    Rector\Php71\Rector\BinaryOp\IsIterableRector: ~
    Rector\Php74\Rector\Assign\NullCoalescingOperatorRector: ~
    Rector\CodingStyle\Rector\MethodCall\PreferThisOrSelfMethodCallRector:
        PHPUnit\TestCase: self
    Rector\Php73\Rector\FuncCall\RegexDashEscapeRector: ~
    Rector\Php73\Rector\String_\SensitiveHereNowDocRector: ~
    Rector\Php70\Rector\Ternary\TernaryToNullCoalescingRector: ~
    Rector\Php70\Rector\Ternary\TernaryToSpaceshipRector: ~
    Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector: ~
    Rector\SOLID\Rector\Class_\MakeUnusedClassesWithChildrenAbstractRector: ~
    Rector\TypeDeclaration\Rector\Closure\AddClosureReturnTypeRector: ~
    Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
    Rector\Rector\ClassMethod\AddMethodParentCallRector: ~
```

**Comment by TomasVotruba** [comment]
Could you try current master?
#2435 might fix it

**Comment by snapshotpl** [comment]
Still getting notice and errors. I run rector with `--debug` flag and I get nice stack trace to debug:
```
Fatal error: Uncaught Rector\Exception\NotImplementedException: Rector\NodeTypeResolver\StaticTypeMapper::mapPHPStanPhpDocTypeNodeToPHPStanType for Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\Type\AttributeAwareGenericTypeNode in /var/www/vendor/rector/rector/packages/NodeTypeResolver/src/StaticTypeMapper.php:643
Stack trace:
#0 /var/www/vendor/rector/rector/packages/NodeTypeResolver/src/StaticTypeMapper.php(469): Rector\NodeTypeResolver\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\Type\AttributeAwareGenericTypeNode), Object(PhpParser\Node\Stmt\Property))
#1 /var/www/vendor/rector/rector/packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfo.php(180): Rector\NodeTypeResolver\StaticTypeMapper->mapPHPStanPhpDocTypeToPHPStanType(Object(Rector\BetterPhpDocParser\Attributes\Ast\PhpDoc\AttributeAwareVarTagValueNode), Object(PhpParser\Node\Stmt\Property))
#2 /var/www/vendor/rector/rector/packages/CodingStyle/src/Rector/Class_/AddArrayDefaultToArrayPropertyRecto in /var/www/vendor/rector/rector/packages/NodeTypeResolver/src/StaticTypeMapper.php on line 643
```

**Comment by TomasVotruba** [comment]
What file is causing it?

**Comment by TomasVotruba** [comment]
Resolved by:

- https://github.com/rectorphp/rector/pull/2548
- https://github.com/rectorphp/rector/pull/2534
