### ISSUE TITLE
Code analysis blows up on a comment

### ISSUE THREAD

**Issue by Danack** [rectorphp/rector#3038]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector v0.7.6             |
| Installed as   | composer dependency                     |

Explodes on code analysis.

## Minimal PHP Code Causing Issue

```php
<?php

declare(strict_types=1);

namespace Params\ProcessRule;

class HowDoesThisBreak
{
    // \X an extended Unicode sequence
    private $validCharacters;
}

```

https://getrector.org/demo/2b3df93d-c9e0-4154-bc75-700196e5c51b#result

## Expected Behaviour

No exception.

Actual is: "Call to a member function getByType() on null", 

> PHP Fatal error:  Uncaught Error: Call to a member function getByType() on null in .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php:44

**Comment by TomasVotruba** [comment]
- Could you run it with `--debug`?
- Could you try on `dev-master`? I tried reproduce locally and it works

**Comment by Danack** [comment]
Dev master works.

For info the --debug output is:

```
File ".../vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 63"
File ".../vendor/rector/rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 95"
File ".../vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 63"
File ".../vendor/rector/rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 95"
Rector v0.7.6
Config file: rector.yaml

[parsing] lib/Params/ProcessRule/SaneCharacters.php
[refactoring] lib/Params/ProcessRule/SaneCharacters.php
    [applying] Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector
    [applying] Rector\Php74\Rector\Property\TypedPropertyRector
PHP Fatal error:  Uncaught Error: Call to a member function getByType() on null in .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php:44
Stack trace:
#0 .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php(49): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\DoctrineRelationPropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#1 .../vendor/rector/rector/rules/php-74/src/Rector/Property/TypedPropertyRector.php(94): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#2 .../vendor/rector/rector/src/Rector/AbstractRector.php(165): Rector\Php74\Rector\Property\TypedPropertyRector->refactor(Object(PhpParser\Node\Stmt\Property))
#3 .../vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rect in .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php on line 44
Fatal error: Uncaught Error: Call to a member function getByType() on null in .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php:44
Stack trace:
#0 .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php(49): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer\DoctrineRelationPropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#1 .../vendor/rector/rector/rules/php-74/src/Rector/Property/TypedPropertyRector.php(94): Rector\TypeDeclaration\TypeInferer\PropertyTypeInferer->inferProperty(Object(PhpParser\Node\Stmt\Property))
#2 .../vendor/rector/rector/src/Rector/AbstractRector.php(165): Rector\Php74\Rector\Property\TypedPropertyRector->refactor(Object(PhpParser\Node\Stmt\Property))
#3 .../vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rect in .../vendor/rector/rector/rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php on line 44

```

**Comment by TomasVotruba** [comment]
I tagged `dev-master` few minutes ago, as it's fixed.

Thanks for confirmation
