### ISSUE TITLE
Fatal error somewhere between Rector and PHPStan

### ISSUE THREAD

**Issue by SilverFire** [rectorphp/rector#4024]
The code bellow reduced to a minimum-reproduction set from a real class.
Can't attach a rector link since

![image](https://user-images.githubusercontent.com/4499203/91202961-3353ae00-e70b-11ea-9dfe-163a7725f632.png)

```php
<?php

class TestCase
{
    public function foo()
    {
        $row['ttl'] = 7_200;
    }

    public function bar()
    {
        return array_flip([]);
    }
}
```

```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    $parameters->set(Option::SETS, [      
		SetList::PHP_52,
        SetList::PHP_53,
        SetList::PHP_54,
        SetList::PHP_55,
        SetList::PHP_56,
        SetList::PHP_70,
        SetList::PHP_71,
        SetList::PHP_72,
        SetList::PHP_73,
        SetList::PHP_74,
	]);
};
```

Stacktrace:

```
Fatal error: Uncaught TypeError: Argument 1 passed to PHPStan\Type\Constant\ConstantIntegerType::__construct() must be of the type int, string given, called in phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php on line 831 and defined in phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Type/Constant/ConstantIntegerType.php:20
Stack trace:
#0 phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(831): PHPStan\Type\Constant\ConstantIntegerType->__construct('7_200')
#1 phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(350): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Scalar\LNumber))
#2 phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(604): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Scalar\LNumber))
#3 phar:///Users/silverfire/.composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(350): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#4 /Users/silverfire/.composer/vendor/rector/rector/packages/node-type-resolver/src/NodeTypeResolver.php(335): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#5 /Users/silverfire/.composer/vendor/rector/rector/packages/node-type-resolver/src/NodeTypeResolver.php(129): Rector\NodeTypeResolver\NodeTypeResolver->resolveFirstType(Object(PhpParser\Node\Expr\Assign))
#6 /Users/silverfire/.composer/vendor/rector/rector/packages/node-type-resolver/src/TypeAnalyzer/ArrayTypeAnalyzer.php(56): Rector\NodeTypeResolver\NodeTypeResolver->resolve(Object(PhpParser\Node\Expr\Assign))
#7 /Users/silverfire/.composer/vendor/rector/rector/packages/node-type-resolver/src/NodeTypeResolver.php(347): Rector\NodeTypeResolver\TypeAnalyzer\ArrayTypeAnalyzer->isArrayType(Object(PhpParser\Node\Expr\Assign))
#8 /Users/silverfire/.composer/vendor/rector/rector/packages/node-type-resolver/src/NodeTypeResolver.php(156): Rector\NodeTypeResolver\NodeTypeResolver->isArrayExpr(Object(PhpParser\Node\Expr\Assign))
#9 /Users/silverfire/.composer/vendor/rector/rector/src/Rector/AbstractRector/NodeTypeResolverTrait.php(151): Rector\NodeTypeResolver\NodeTypeResolver->getStaticType(Object(PhpParser\Node\Expr\Assign))
#10 /Users/silverfire/.composer/vendor/rector/rector/rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php(111): Rector\Core\Rector\AbstractRector->getStaticType(Object(PhpParser\Node\Expr\Assign))
```

**Comment by TomasVotruba** [comment]
Thanks for reporting.

- Which single set is causing it?

```php
$parameters->set(Option::SETS, [      
    SetList::???,
]);
```

- What is the output with `--debug` option? There should be mention of single Rector rule

**Comment by TomasVotruba** [comment]
> Can't attach a rector link since

I assume that's related to https://getrector.org/demo

I'm not sure if the server is running on PHP 7.4, so it's possible the syntax is the problem:

```diff
-$row['ttl'] = 7_200;
+$row['ttl'] = 7200;
```

**Comment by SilverFire** [comment]
> * Which single set is causing it?

PHP_70 + 74

**Comment by SilverFire** [comment]
> I'm not sure if the server is running on PHP 7.4, so it's possible the syntax is the problem:

No, you can use just `7200` – same thing

**Comment by SilverFire** [comment]
> * What is the output with `--debug` option? There should be mention of single Rector rule

It differed (with the same error) when I was reducing the scope of the problem, so I cant tell you exactly.

Most time it was `Rector\MysqlToMysqli\Rector\FuncCall\MysqlQueryMysqlErrorWithLinkRector`

**Comment by TomasVotruba** [comment]
I see. Thanks for testing

Seems PHPStan does not the underscore format

> Fatal error: Uncaught TypeError: Argument 1 passed to PHPStan\Type\Constant\ConstantIntegerType::__construct() must be of the type int, string given, called in

**Comment by SilverFire** [comment]
Investigated and submitted a failing test #4042

**Comment by TomasVotruba** [comment]
Closing as this is not repository to fix this
