### ISSUE TITLE
Class model does not exist

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#4126]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.8.6 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                       |

scaning my codebase makes rector crash. its pretty hard to get to the sources which are the cause.

## Minimal PHP Code Causing Issue

not sure how a minimal repro looks like

rector is crashing with the following stacktrace:

```
Class model does not exist
#0 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\rules\php70\src\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector.php(171): ReflectionClass->__construct('model')
#1 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\rules\php70\src\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector.php(117): Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector->isInstantiable('model')
#2 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Rector\AbstractRector.php(203): Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector->refactor(Object(PhpParser\Node\Expr\StaticCall))
#3 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(123): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\StaticCall))
#4 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#5 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#6 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
#7 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Echo_))
#9 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#10 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#11 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#12 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(59): PhpParser\NodeTraverser->traverse(Array)
#13 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Application\FileProcessor.php(136): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#14 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Application\RectorApplication.php(227): Rector\Core\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#15 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Application\RectorApplication.php(242): Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#16 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Application\RectorApplication.php(228): Rector\Core\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#17 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Application\RectorApplication.php(138): Rector\Core\Application\RectorApplication->refactoryNodesWithRectors(Array)
#18 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Console\Command\ProcessCommand.php(235): Rector\Core\Application\RectorApplication->runOnFileInfos(Array)
#19 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\symfony\console\Command\Command.php(258): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Console\Command\AbstractCommand.php(34): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\symfony\console\Application.php(916): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\symfony\console\Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\src\Console\Application.php(101): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\symfony\console\Application.php(140): Rector\Core\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\Users\mstaab\Documents\GitHub\motiontm\vendor-bin\rector\vendor\rector\rector\bin\rector(82): Symfony\Component\Console\Application->run()
#26 {main}

```

## Expected Behaviour

no crash and a error-message/exception which gives me some context where/why rector has a problem with

Sorry for this bad issue report. hopefully the stacktrace is good enough to improve rector in a direction which points us to the actual root cause.

**Comment by TomasVotruba** [comment]
Try running only `StaticCallOnNonStaticToInstanceCallRector` rule

**Comment by powtac** [comment]
@staabm to debug such use cases it is useful to use `-vvv` on the command line. It will at least tell you at which file the parser stoped to work.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback for last 2 months.
