### ISSUE TITLE
Rector process is throwing a syntax error

### ISSUE THREAD

**Issue by Raghu-Kanchiraju** [rectorphp/rector#4151]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.6                                                              |
| Installed as   | composer (global) dependency                      |

## Minimal PHP Code Causing Issue

rector process api/app/models --dry-run --debug

## Expected Behaviour

Should show a progress bar indicating how many files have been processed and then git-diff like output showing the changes that will happen. But the process is crashing with the following error:

```
File "/Users/raghu.kanchiraju/Desktop/project/project/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 98"
File "/Users/raghu.kanchiraju/.composer/vendor/rector/rector/../../autoload.php" is about to be loaded in "AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 132"


 [ERROR] syntax error, unexpected end of file, expecting ';'
```

**Comment by TomasVotruba** [comment]
Hi, 

we need at least demo link with minimal code and Rector setup to reproduce: https://getrector.org/demo

**Comment by TomasVotruba** [comment]
Also, global installation is not support for Rector. 

Use one of 3 options here: https://github.com/rectorphp/rector#install

**Comment by Raghu-Kanchiraju** [comment]
@TomasVotruba Thanks for responding Tomas. I did do much other than installing it (now composer locally) and running rector process. Earlier I even tried it with Docker image, but the result was the same. Except that there was more information.
```
File "/rector/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 98"
File "/rector/bin/../vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeDependencyOrRepositoryVendorAutoloadIfExists()" on line 113"
Rector 0.8.x-dev@d6ff3a9

Fatal error: Uncaught Rector\Core\Exception\NoRectorsLoadedException: We need some rectors to run:
* register them in rector.php under "services():"
* use "--set <set>"
* or use "--config <file>.yaml" in /rector/src/Guard/RectorGuard.php:29
Stack trace:
#0 /rector/src/Console/Command/ProcessCommand.php(212): Rector\Core\Guard\RectorGuard->ensureSomeRectorsAreRegistered()
#1 /rector/vendor/symfony/console/Command/Command.php(258): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /rector/src/Console/Command/AbstractCommand.php(34): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /rector/vendor/symfony/console/Application.php(916): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /rector/vendor/symf in /rector/src/Guard/RectorGuard.php on line 29
```

As for rector.php, this is what we included in it:

```
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // here we can define, what sets of rules will be applied
    $parameters->set(Option::SETS, [
        SetList::CODE_QUALITY
    ]);

    // Rector relies on autoload setup of your project; Composer autoload is included by default; to add more:
    $parameters->set(Option::AUTOLOAD_PATHS, [
        // autoload specific file
        __DIR__ . '/api/app/models',
        __DIR__ . '/api/app/controllers/v2',
    ]);

    $parameters->set(Option::PHP_VERSION_FEATURES, '7.2.1');
    // get services
    $services = $containerConfigurator->services();

    // register single rule
    $services->set(TypedPropertyRector::class);
};
```

**Comment by Raghu-Kanchiraju** [comment]
Re-installing fixed the issue I was having.
