### ISSUE TITLE
Fatal error on PHP 8

### ISSUE THREAD

**Issue by BenMorel** [rectorphp/rector#4790]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56   |
| Installed as   | composer dependency    |

## Minimal PHP Code Causing Issue

```
git clone --single-branch --branch rector-test https://github.com/BenMorel/ebay-sdk-php.git
cd ebay-sdk-php
composer install
vendor/bin/rector process src
```

## Result 

```
PHP Fatal error:  Uncaught TypeError: preg_replace(): Argument #2 ($replacement) must be of type array|string, null given in /home/benjamin/Projects/ebay-sdk-php/vendor/nette/utils/src/Utils/Callback.php:84
Stack trace:
#0 /home/benjamin/Projects/ebay-sdk-php/vendor/nette/utils/src/Utils/Callback.php(84): preg_replace()
#1 /home/benjamin/Projects/ebay-sdk-php/vendor/nette/utils/src/Utils/Strings.php(540): Nette\Utils\Callback::invokeSafe()
#2 /home/benjamin/Projects/ebay-sdk-php/vendor/nette/utils/src/Utils/Strings.php(530): Nette\Utils\Strings::pcre()
#3 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/packages/changes-reporting/src/Output/ConsoleOutputFormatter.php(174): Nette\Utils\Strings::replace()
#4 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/packages/changes-reporting/src/Output/ConsoleOutputFormatter.php(138): Rector\ChangesReporting\Output\ConsoleOutputFormatter->normalizePathsToRelativeWithLine()
#5 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/packages/changes-reporting/src/Output/ConsoleOutputFormatter.php(70): Rector\ChangesReporting\Output\ConsoleOutputFormatter->reportErrors()
#6 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/src/Console/Command/ProcessCommand.php(245): Rector\ChangesReporting\Output\ConsoleOutputFormatter->report()
#7 /home/benjamin/Projects/ebay-sdk-php/vendor/symfony/console/Command/Command.php(255): Rector\Core\Console\Command\ProcessCommand->execute()
#8 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/src/Console/Command/AbstractCommand.php(44): Symfony\Component\Console\Command\Command->run()
#9 /home/benjamin/Projects/ebay-sdk-php/vendor/symfony/console/Application.php(971): Rector\Core\Console\Command\AbstractCommand->run()
#10 /home/benjamin/Projects/ebay-sdk-php/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#11 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/src/Console/Application.php(113): Symfony\Component\Console\Application->doRun()
#12 /home/benjamin/Projects/ebay-sdk-php/vendor/symfony/console/Application.php(166): Rector\Core\Console\Application->doRun()
#13 /home/benjamin/Projects/ebay-sdk-php/vendor/rector/rector/bin/rector(84): Symfony\Component\Console\Application->run()
#14 {main}
  thrown in /home/benjamin/Projects/ebay-sdk-php/vendor/nette/utils/src/Utils/Callback.php on line 84
```

**Comment by TomasVotruba** [comment]
0.8.x does not support PHP 8.

Try `dev-master`, soon to be 0.9. We're working on PHP 8 support there
