### ISSUE TITLE
create_function() with double quoted string breaks CreateFunctionToAnonymousFunctionRector

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4880]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.56              |
| Installed as   | composer dependency                       |

## Minimal PHP Code Causing Issue

B.php
```
<?php

class B {
    function a() {
        $var = 123;
        create_function('$var', "return $var;"); // Problem triggered by the '"'
    }
}
```

rector.php
```
<?php
declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $services = $containerConfigurator->services();

    $services->set(Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector::class);

    $parameters->set(Option::PHP_VERSION_FEATURES, '7.2');

    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/B.php',
    ]);
};
```

Demo does not return a result
https://getrector.org/demo/6bda90fa-7f5c-4fcb-bd7a-10f6af7aa4e9#demo_result

Output in the command line

```
[parsing] B.php
[refactoring] B.php
    [applying] Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected '{', expecting ';' on line 1 in phar:///[...]/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:266
Stack trace:
#0 phar:///[...]/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(142): PhpParser\ParserAbstract->doParse()
#1 phar:///[...]/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(48): PhpParser\ParserAbstract->parse('<?php return {$...', Object(PhpParser\ErrorHandler\Throwing))
#2 phar:///[...]/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php return {$...')
#3 /[...]/vendor/rector/rector/src/PhpParser/Parser/I in phar:///[...]/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 266

```

## Expected Behaviour

It is expected that this does not thow an error. 

## Guess

The problem seems to be related to the double quoted string in second param of the create_function(). With single quoted string there is no error and nice refactoring.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting.
We'll a failing test in `CreateFunctionToAnonymousFunctionRectorTest`.

**Comment by TomasVotruba** [comment]
Closing for missing test
