### ISSUE TITLE
NotImplementedException: Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper::mapToPHPStanType for Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareConstTypeNode.     

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4949]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@24e1758           |
| Installed as   | composer dependency                  |

I'm not sure if I isolated problem correctly. It looks like it breaks when I reference constant in phpdoc type. Is it even supported?

## Minimal PHP Code Causing Issue

https://getrector.org/demo/8a42bd8a-4824-4fcc-9ce5-41b8f5bb601b#demo_result

**Comment by samsonasik** [comment]
could you try with `--debug` to get the exact rector causing it?

**Comment by jkuchar** [comment]
```
    [applying] Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector
PHP Fatal error:  Uncaught Rector\Core\Exception\NotImplementedException: Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper::mapToPHPStanType for Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareConstTypeNode in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php:39
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDocParser/UnionTypeMapper.php(53): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareConstTypeNode), Object(PhpParser\Node\Stmt\Property), Object(PHPStan\Analyser\NameScope))
#1 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php(36): Rector\StaticTypeMapper\PhpDocParser\UnionTypeMapper->mapToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareUnionTypeNode), Object(PhpParser\Node\Stmt\Property), Object(PHPStan\Analyser\NameScope))
#2 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/StaticTypeMapper.php(109): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareUnionTypeNode), Object(PhpParser\Node\Stmt\Property), Object(PHPStan\Analyser\NameScope))
#3 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/StaticTypeMapper.php(92): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareUnionTypeNode), Object(PhpParser\Node\Stmt\Property))
#4 /var/www/html/vendor/rector/rector/packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfo.php(433): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\PhpDoc\AttributeAwareVarTagValueNode), Object(PhpParser\Node\Stmt\Property))
#5 /var/www/html/vendor/rector/rector/packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfo.php(210): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo->getTypeOrMixed(Object(Rector\AttributeAwarePhpDoc\Ast\PhpDoc\AttributeAwareVarTagValueNode))
#6 /var/www/html/vendor/rector/rector/rules/coding-style/src/Rector/Class_/AddArrayDefaultToArrayPropertyRector.php(137): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo->getVarType()

```

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/pull/4967
