### ISSUE TITLE
StaticCallOnNonStaticToInstanceCallRector: broken with dynamic static call

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4954]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master             |
| Installed as   | composer dependency                     |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/645574c7-79a6-4f2b-b13e-96a6315b9582#demo_result

```
PHP Fatal error:  Uncaught ReflectionException: Class "store" does not exist in /var/www/html/vendor/rector/rector/rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php:170
Stack trace:
#0 /var/www/html/vendor/rector/rector/rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php(170): ReflectionClass->__construct('store')
#1 /var/www/html/vendor/rector/rector/rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php(120): Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector->isInstantiable('store')
#2 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(231): Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector->refactor(Object(PhpParser\Node\Expr\StaticCall))
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\StaticCall))
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Catch_))
#10 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#11 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\TryCatch))
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#14 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#15 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#16 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#17 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#18 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#19 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(116): PhpParser\NodeTraverser->traverse(Array)
#20 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(143): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#
```

**Comment by jkuchar** [comment]
Confirming, it is fixed. Thank you! 😊
