### ISSUE TITLE
RemoveUselessReturnTagRector: does not work with shapes

### ISSUE THREAD

**Issue by jkuchar** [rectorphp/rector#4957]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/e80ed34f-4c2d-4f17-a6d8-9a507c7797cd#demo_result

```
PHP Fatal error:  Uncaught Rector\Core\Exception\NotImplementedException: Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper::mapToPHPStanType for Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php:39
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/StaticTypeMapper.php(109): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\NameScope))
#1 /var/www/html/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/TypeComparator.php(76): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#2 /var/www/html/vendor/rector/rector/rules/dead-doc-block/src/DeadReturnTagValueNodeAnalyzer.php(30): Rector\NodeTypeResolver\PHPStan\TypeComparator->arePhpParserAndPhpStanPhpDocTypesEqual(Object(PhpParser\Node\Identifier), Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#3 /var/www/html/vendor/rector/rector/rules/dead-doc-block/src/Rector/ClassMethod/RemoveUselessReturnTagRector.php(89): Rector\DeadDocBlock\DeadReturnTagValueNodeAnalyzer->isDead(Object(Rector\AttributeAwarePhpDoc\Ast\PhpDoc\AttributeAwareReturnTagValueNode), Object(PhpParser\Node\Stmt\ClassMethod))
#4 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(231): Rector\DeadDocBlock\Rector\ClassMethod\RemoveUselessReturnTagRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#10 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#11 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(116): PhpParser\NodeTraverser->traverse(Array)
#12 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(143): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#13 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(212): Rector\Core\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#14 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(227): Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#15 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(213): Rector\Core\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#16 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(138): Rector\Core\Application\RectorApplication->refactorNodesWithRectors(Array)
#17 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(207): Rector\Core\Application\RectorApplication->runOnFileInfos(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(255): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/rector/rector/src/Console/Command/AbstractCommand.php(44): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(971): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/symfony/console/Application.php(166): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/rector/rector/bin/rector.php(75): Symfony\Component\Console\Application->run()
#25 /var/www/html/vendor/rector/rector/bin/rector(4): require_once('/var/www/html/v...')
#26 {main}
  thrown in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php on line 39
Fatal error: Uncaught Rector\Core\Exception\NotImplementedException: Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper::mapToPHPStanType for Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php:39
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/StaticTypeMapper.php(109): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\NameScope))
#1 /var/www/html/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/TypeComparator.php(76): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#2 /var/www/html/vendor/rector/rector/rules/dead-doc-block/src/DeadReturnTagValueNodeAnalyzer.php(30): Rector\NodeTypeResolver\PHPStan\TypeComparator->arePhpParserAndPhpStanPhpDocTypesEqual(Object(PhpParser\Node\Identifier), Object(Rector\AttributeAwarePhpDoc\Ast\Type\AttributeAwareArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#3 /var/www/html/vendor/rector/rector/rules/dead-doc-block/src/Rector/ClassMethod/RemoveUselessReturnTagRector.php(89): Rector\DeadDocBlock\DeadReturnTagValueNodeAnalyzer->isDead(Object(Rector\AttributeAwarePhpDoc\Ast\PhpDoc\AttributeAwareReturnTagValueNode), Object(PhpParser\Node\Stmt\ClassMethod))
#4 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(231): Rector\DeadDocBlock\Rector\ClassMethod\RemoveUselessReturnTagRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#10 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#11 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(116): PhpParser\NodeTraverser->traverse(Array)
#12 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(143): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#13 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(212): Rector\Core\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#14 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(227): Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#15 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(213): Rector\Core\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#16 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(138): Rector\Core\Application\RectorApplication->refactorNodesWithRectors(Array)
#17 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(207): Rector\Core\Application\RectorApplication->runOnFileInfos(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(255): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/rector/rector/src/Console/Command/AbstractCommand.php(44): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(971): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/symfony/console/Application.php(166): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/rector/rector/bin/rector.php(75): Symfony\Component\Console\Application->run()
#25 /var/www/html/vendor/rector/rector/bin/rector(4): require_once('/var/www/html/v...')
#26 {main}
  thrown in /var/www/html/vendor/rector/rector/packages/static-type-mapper/src/PhpDoc/PhpDocTypeMapper.php on line 39
root@5589455b3a5f:/var/www/html# 

```

**Comment by TomasVotruba** [comment]
Duplicated of https://github.com/rectorphp/rector/issues/4958
