### ISSUE TITLE
validate-fixture-* command error after composer update with php8

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5121]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master              |
| Installed as   | -                          |

Running command by pull latest update got error:

```bash
➜  rector git:(master) bin/rector validate-fixture-suffix --ansi
PHP Fatal error:  Uncaught TypeError: Symfony\Component\Console\Application::configureIO(): Argument #1 ($input) must be of type Symfony\Component\Console\Input\InputInterface, array given in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO(Array)
#1 /Users/samsonasik/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(31): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/samsonasik/www/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array)
#3 /Users/samsonasik/www/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/samsonasik/www/rector/bin/rector(4): require_once('/Users/samsonas...')
#5 {main}
  thrown in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php on line 880
Fatal error: Uncaught TypeError: Symfony\Component\Console\Application::configureIO(): Argument #1 ($input) must be of type Symfony\Component\Console\Input\InputInterface, array given in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO(Array)
#1 /Users/samsonasik/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(31): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/samsonasik/www/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array)
#3 /Users/samsonasik/www/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/samsonasik/www/rector/bin/rector(4): require_once('/Users/samsonas...')
#5 {main}
  thrown in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php on line 880
```

Already run:

```bash
composer clear-cache
rm -rf vendor
rm -rf composer.lock
composer update
```
and still error.

**Comment by samsonasik** [comment]
oh, `bin/rector show --ansi` got same error:

```bash
➜  rector git:(master) bin/rector show --ansi
PHP Fatal error:  Uncaught TypeError: Symfony\Component\Console\Application::configureIO(): Argument #1 ($input) must be of type Symfony\Component\Console\Input\InputInterface, array given in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO(Array)
#1 /Users/samsonasik/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(31): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/samsonasik/www/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array)
#3 /Users/samsonasik/www/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/samsonasik/www/rector/bin/rector(4): require_once('/Users/samsonas...')
#5 {main}
  thrown in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php on line 880
Fatal error: Uncaught TypeError: Symfony\Component\Console\Application::configureIO(): Argument #1 ($input) must be of type Symfony\Component\Console\Input\InputInterface, array given in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php:880
Stack trace:
#0 [internal function]: Symfony\Component\Console\Application->configureIO(Array)
#1 /Users/samsonasik/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php(31): ReflectionMethod->invokeArgs(Object(Symfony\Component\Console\Application), Array)
#2 /Users/samsonasik/www/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Array)
#3 /Users/samsonasik/www/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#4 /Users/samsonasik/www/rector/bin/rector(4): require_once('/Users/samsonas...')
#5 {main}
  thrown in /Users/samsonasik/www/rector/vendor/symfony/console/Application.php on line 880
```

**Comment by TomasVotruba** [comment]
It's wip from Symplify. I'm aware of it.
Tagging today will fix it

**Comment by samsonasik** [comment]
Thank you

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/rectorphp/rector/releases/tag/0.9.6
