### ISSUE TITLE
Symplify\PackageBuilder destroys the rector init

### ISSUE THREAD

**Issue by elcheco** [rectorphp/rector#5124]
# Bug Report

Calling `vendor/bin/rector init` throws fatal error 

Rector version: `v0.9.5`
Installed as composer dependency

I installed rector yesterday 2021-01-09 and everything was fine, today I installed it in another project, and later even as an empty project and `vendor/bin/rector init` always dies on the message:

## PHP Code Causing Issue

```
❯ vendor/bin/rector init
PHP Fatal error:  Uncaught TypeError: Symplify\PackageBuilder\Reflection\PrivatesCaller::callPrivateMethod(): Argument #3 ($arguments) must be of type array, Symfony\Component\Console\Input\ArgvInput given, called in /usr/local/www/rector/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php on line 32 and defined in /usr/local/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php:20
Stack trace:
#0 /usr/local/www/rector/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php(32): Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod(Object(Symfony\Component\Console\Application), 'configureIO', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /usr/local/www/rector/vendor/rector/rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#2 /usr/local/www/rector/vendor/rector/rector/bin/rector(4): require_once('/usr/local/ww...')
#3 {main}
  thrown in /usr/local/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php on line 20

Fatal error: Uncaught TypeError: Symplify\PackageBuilder\Reflection\PrivatesCaller::callPrivateMethod(): Argument #3 ($arguments) must be of type array, Symfony\Component\Console\Input\ArgvInput given, called in /usr/local/www/rector/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php on line 32 and defined in /usr/local/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php on line 20

TypeError: Symplify\PackageBuilder\Reflection\PrivatesCaller::callPrivateMethod(): Argument #3 ($arguments) must be of type array, Symfony\Component\Console\Input\ArgvInput given, called in /usr/local/www/rector/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php on line 32 in /usr/local/www/rector/vendor/symplify/package-builder/src/Reflection/PrivatesCaller.php on line 20

Call Stack:
    0.0002     393896   1. {main}() /usr/local/www/rector/vendor/rector/rector/bin/rector:0
    0.0007     413728   2. require_once('/usr/local/www/rector/vendor/rector/rector/bin/rector.php') /usr/local/www/rector/vendor/rector/rector/bin/rector:4
    0.0060     774568   3. Rector\Core\Console\Style\SymfonyStyleFactory->create() /usr/local/www/rector/vendor/rector/rector/bin/rector.php:39
    0.0134    1372232   4. Symplify\PackageBuilder\Reflection\PrivatesCaller->callPrivateMethod($object = class Symfony\Component\Console\Application { private $commands = []; private $wantHelps = FALSE; private $runningCommand = NULL; private $name = 'UNKNOWN'; private $version = 'UNKNOWN'; private $commandLoader = NULL; private $catchExceptions = TRUE; private $autoExit = TRUE; private $definition = NULL; private $helperSet = NULL; private $dispatcher = NULL; private $terminal = class Symfony\Component\Console\Terminal {  }; private $defaultCommand = 'list'; private $singleCommand = FALSE; private $initialized = NULL; private $signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { private $signalHandlers = [...] }; private $signalsToDispatchEvent = [0 => 2, 1 => 15, 2 => 30, 3 => 31] }, $methodName = 'configureIO', $arguments = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'init']; private $parsed = NULL; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE }, class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(45) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(36) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /usr/local/www/rector/vendor/rector/rector/src/Console/Style/SymfonyStyleFactory.php:32
```

## Temporary Solution

I just compared the composer.lock versions and current has `symplify/console-package-builder` in the version `9.0.26` and the working version from yesterday `9.0.24`. When I just downgraded this one package everything started to work properly.

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector/releases/tag/0.9.6
