### ISSUE TITLE
Bug with dead code: leaveNode() returned invalid value of type integer

### ISSUE THREAD

**Issue by brucealdridge** [rectorphp/rector#5152]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.6              |
| Installed as   |  prefixed Rector                           |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b55f427c-3b82-4f7f-9246-41c8bdc4d612

~~~
    public function testFind(): void
    {
        assert($user = User::find('foo bar'));
        assert(User::find('foo bar'));
    }
~~~

## Expected Behaviour

~~~
-       assert($user = User::find('foo bar'));
+       assert(User::find('foo bar'));
~~~

**Comment by samsonasik** [comment]
@brucealdridge  could you run with `--debug` to get the exact rule causing this, thank you.

**Comment by brucealdridge** [comment]
not sure it helps

```
⇒  bin/rector process tests/unit/models/UserTest.php --debug
Rector 0.9.6
Config file: rector.php

[parsing] tests/unit/models/UserTest.php
[refactoring] tests/unit/models/UserTest.php
    [applying] Rector\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector
    [applying] Rector\CodingStyle\Rector\Use_\SplitGroupedUseImportsRector
    [applying] Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector
    [applying] Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector
    [applying] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector
    [applying] Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector
    [applying] Rector\Php74\Rector\Property\TypedPropertyRector
    [applying] Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector
    [applying] Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadRecursiveClassMethodRector
    [applying] Rector\CodingStyle\Rector\ClassMethod\NewlineBeforeNewAssignSetRector
    [applying] Rector\PHPUnit\Rector\ClassMethod\ExceptionAnnotationRector
    [applying] Rector\CodingStyle\Rector\ClassMethod\MakeInheritedMethodVisibilitySameAsParentRector
    [applying] Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
    [applying] Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector
    [applying] Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector
    [applying] Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveAssignOfVoidReturnFunctionRector
    [applying] Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector
    [applying] Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveEmptyMethodCallRector
    [applying] Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector
    [applying] Rector\Php55\Rector\String_\StringClassNameToClassConstantRector
    [applying] Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector
[post rectors] tests/unit/models/UserTest.php
PHP Fatal error:  Uncaught LogicException: leaveNode() returned invalid value of type integer in /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:168
Stack trace:
#0 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#1 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
#3 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#4 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
# in /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 168
Fatal error: Uncaught LogicException: leaveNode() returned invalid value of type integer in /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:168
Stack trace:
#0 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#1 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#2 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
#3 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#4 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
# in /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line **168**
```

**Comment by norgeindian** [comment]
I get the same error message with the following setup:
``` 
class A extends B{
}
```
, whereas class B just does not exist.
That should of course not happen, but might happen in old legacy code.
The issue here is, that the complete scan stops with that error message and one has to debug it more detailed to find the actual issue.
To be honest, I don't know what the best behavior would be in this case, but I think it would be a good start to show a more detailed error message and make sure, that the scan does not stop.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

Could you send failing demo link? 
https://getrector.org/demo

As for non-existing classes - they are needed for static analysis, e.g. for parent behavior of __get/__set etc. It's better to have them in the project. If there is no way other around, I'd create them manually and autoload with composer > classmap.

**Comment by norgeindian** [comment]
@TomasVotruba , sure: https://getrector.org/demo/1ec5cca2-63b0-66e2-be36-43146ba5c048
Strangely, no error is shown here, but maybe you catch them on the demo page somehow?

**Comment by TomasVotruba** [comment]
Thank you. Error should be displayed in demo as well.

Could you create a new issue so we have track on it?
Does it happen with latest 0.12.8?

**Comment by norgeindian** [comment]
@TomasVotruba , strange, I unfortunately can still not reproduce it in the demo. But maybe you find a way...
Created a new issue, please see https://github.com/rectorphp/rector/issues/6873
