### ISSUE TITLE
rector init with empty rector file: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Rector\Core\PhpParser\Printer\BetterStandardPrinter

### ISSUE THREAD

**Issue by strarsis** [rectorphp/rector#5683]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `0.9.31` |
| Installed as   | `composer dependency`                           |
|composer | `2.0.6 2020-11-07 11:21:17` |

## Minimal Causing Issue
1. Enter empty directory.
2. Initialize an empty composer file (`composer init`).
3. Require `rector` as composer development dependency: `composer require rector/rector --dev`
4. Ensure an empty `rector.php` file exists (empty meaning completely empty without `<?php` tag.
5. Initialize rector: `vendor/bin/rector init`
Notice the PHP fatal error:
````
[WARNING] Config file "rector.php" already exists

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Rector\Core\PhpParser\Printer\BetterStandardPrinter::__construct() must be an instance of Rector\Core\PhpParser\Printer\Whitespace\IndentCharacterDetector, instance of Rector\Comments\CommentRemover given, called in /tmp/_rector/ContainerIPexdWK/getBetterStandardPrinterService.php on line 20 and defined in /home/build/src/domain-replacer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php:86
Stack trace:
#0 /tmp/_rector/ContainerIPexdWK/getBetterStandardPrinterService.php(20): Rector\Core\PhpParser\Printer\BetterStandardPrinter->__construct()
#1 /tmp/_rector/ContainerIPexdWK/Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd80709Container.php(967): ContainerIPexdWK\getBetterStandardPrinterService::do()
#2 /tmp/_rector/ContainerIPexdWK/getNodeNameResolverService.php(51): ContainerIPexdWK\Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd80709Container->load()
#3 /tmp/_rector/ContainerIPexdWK/Rector_Core_HttpKernel in /home/build/src/domain-replacer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php on line 86
Fatal error: Uncaught TypeError: Argument 1 passed to Rector\Core\PhpParser\Printer\BetterStandardPrinter::__construct() must be an instance of Rector\Core\PhpParser\Printer\Whitespace\IndentCharacterDetector, instance of Rector\Comments\CommentRemover given, called in /tmp/_rector/ContainerIPexdWK/getBetterStandardPrinterService.php on line 20 and defined in /home/build/src/domain-replacer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php:86
Stack trace:
#0 /tmp/_rector/ContainerIPexdWK/getBetterStandardPrinterService.php(20): Rector\Core\PhpParser\Printer\BetterStandardPrinter->__construct()
#1 /tmp/_rector/ContainerIPexdWK/Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd80709Container.php(967): ContainerIPexdWK\getBetterStandardPrinterService::do()
#2 /tmp/_rector/ContainerIPexdWK/getNodeNameResolverService.php(51): ContainerIPexdWK\Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd80709Container->load()
#3 /tmp/_rector/ContainerIPexdWK/Rector_Core_HttpKernel in /home/build/src/domain-replacer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php on line 86
````

## Expected Behaviour

Initialization with an empty `rector.php` file in place without crashing with fatal error.

## Related
There is another issue where `rector` crashes during initialization with a non-existing `rector.php` file: 
https://github.com/rectorphp/rector/issues/5685

**Comment by TomasVotruba** [comment]
Hi, could you separate the init issue to a new issue? So we have both under own scope

**Comment by strarsis** [comment]
@ThomasVotruba: Sure! So this issue here should become the issue with empty `rector.php` files, and another issue for `rector init` for non-existing `rector.php` file?

**Comment by TomasVotruba** [comment]
Yes :+1:

**Comment by TomasVotruba** [comment]
I think this is fixed on `dev-main`
