### ISSUE TITLE
Uncaught Error: Call to undefined function get_debug_type()

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#5689]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31              |
| Installed as   | prefixed Rector                           |

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_debug_type() in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php:682
Stack trace:
#0 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(671): RectorPrefix20210222\Symfony\Component\Console\Application->doRenderThrowable()
#1 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/Console/ConsoleApplication.php(83): RectorPrefix20210222\Symfony\Component\Console\Application->renderThrowable()
#2 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(137): Rector\Core\Console\ConsoleApplication->renderThrowable()
#3 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(157): RectorPrefix20210222\Symfony\Component\Console\Application->RectorPrefix20210222\Symfony\Component\Console\{closure}()
#4 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/bin/rector.php(46): RectorPrefix20210222\Symfony\C in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php on line 682
Fatal error: Uncaught Error: Call to undefined function get_debug_type() in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php:682
Stack trace:
#0 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(671): RectorPrefix20210222\Symfony\Component\Console\Application->doRenderThrowable()
#1 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/Console/ConsoleApplication.php(83): RectorPrefix20210222\Symfony\Component\Console\Application->renderThrowable()
#2 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(137): Rector\Core\Console\ConsoleApplication->renderThrowable()
#3 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(157): RectorPrefix20210222\Symfony\Component\Console\Application->RectorPrefix20210222\Symfony\Component\Console\{closure}()
#4 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/bin/rector.php(46): RectorPrefix20210222\Symfony\C in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php on line 682
```

## Minimal PHP Code Causing Issue

This issue occurs when calling commands with the -v option, eg. `vendor/bin/rector process -v`

## Expected Behaviour

Don't throw an error

**Comment by TomasVotruba** [comment]
Resolved in latest `rector-main` version:
https://github.com/rectorphp/rector-prefixed
