### ISSUE TITLE
Name called on "PhpParser\Node\Expr\MethodCall" is not possible

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#5690]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31              |
| Installed as   | prefixed Rector                           |

```
Could not process "public/modules/custom/wmcustom/src/Entity/File.php" file, due to:
         "Name called on "PhpParser\Node\Expr\MethodCall" is not possible. Use $this->getName($node->name) instead"
```

I debugged a bit and the `MethodCall` in question is `$this->get`.

## Minimal PHP Code Causing Issue

```bash
vendor/bin/rector process public/modules/custom/wmcustom/src/Entity/File.php
```

```php
<?php

namespace Drupal\wmcustom\Entity;

class File extends \Drupal\file\Entity\File
{
    public function setMd5($md5): void
    {
        $this->get('md5')->value = $md5;
    }
}
```

## Expected Behaviour

Don't fail

**Comment by samsonasik** [comment]
could you run with `--debug` to get the nearest rule that has this issue:

```
vendor/bin/rector process public/modules/custom/wmcustom/src/Entity/File.php --debug
```

**Comment by DieterHolvoet** [comment]
```
[parsing] public/modules/custom/wmcustom/src/Entity/File.php
[refactoring] public/modules/custom/wmcustom/src/Entity/File.php
    [applying] Rector\Renaming\Rector\Name\RenameClassRector
    [applying] Rector\DeadDocBlock\Rector\Node\RemoveNonExistingVarAnnotationRector
    [applying] Rector\Renaming\Rector\FileWithoutNamespace\PseudoNamespaceToNamespaceRector
    [applying] Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector
    [applying] Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector
    [applying] Rector\DeadDocBlock\Rector\ClassMethod\RemoveUselessParamTagRector
    [applying] Rector\DeadDocBlock\Rector\ClassMethod\RemoveUselessReturnTagRector
    [applying] Rector\CodingStyle\Rector\Assign\PHPStormVarAnnotationRector
    [applying] Rector\Php74\Rector\Assign\NullCoalescingOperatorRector
    [applying] Rector\Php74\Rector\MethodCall\ChangeReflectionTypeToStringToGetNameRector
    [applying] Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector
    [applying] Rector\Php73\Rector\String_\SensitiveHereNowDocRector
    [applying] Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector
    [applying] Rector\EarlyReturn\Rector\If_\ChangeIfElseValueAssignToEarlyReturnRector
    [applying] Rector\EarlyReturn\Rector\If_\ChangeNestedIfsToEarlyReturnRector
    [applying] Rector\EarlyReturn\Rector\If_\RemoveAlwaysElseRector
    [applying] Rector\EarlyReturn\Rector\If_\ChangeOrIfReturnToEarlyReturnRector
    [applying] Rector\Php73\Rector\FuncCall\RegexDashEscapeRector
    [applying] Rector\Php74\Rector\StaticCall\ExportToReflectionFunctionRector
    [applying] Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector
    [applying] Rector\CodingStyle\Rector\FuncCall\CallUserFuncCallToVariadicRector
    [applying] Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector
    [applying] Rector\Php73\Rector\FuncCall\SensitiveDefineRector
    [applying] Rector\Renaming\Rector\FuncCall\RenameFunctionRector
    [applying] Rector\Php73\Rector\FuncCall\StringifyStrNeedlesRector
    [applying] Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector
    [applying] Rector\Php74\Rector\FuncCall\ArrayKeyExistsOnPropertyRector
    [applying] Rector\Php74\Rector\FuncCall\FilterVarToAddSlashesRector
    [applying] Rector\Php74\Rector\FuncCall\GetCalledClassToStaticClassRector
    [applying] Rector\Php74\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector
    [applying] Rector\Php74\Rector\Function_\ReservedFnFunctionRector
    [applying] Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Name called on "PhpParser\Node\Expr\MethodCall" is not possible. Use $this->getName($node->name) instead in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/packages/node-name-resolver/src/NodeNameResolver.php:85
Stack trace:
#0 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/NodeManipulator/PropertyFetchAssignManipulator.php(66): Rector\NodeNameResolver\NodeNameResolver->isName()
#1 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/NodeManipulator/PropertyFetchAssignManipulator.php(37): Rector\Core\NodeManipulator\PropertyFetchAssignManipulator->isVariableAssignToThisPropertyFetch()
#2 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symplify/astral/src/NodeTraverser/SimpleCallableNodeTraverser.php(54): Rector\Core\NodeManipulator\PropertyFetchAssignManipulator->Rector\Core\NodeManipulator\{closure}()
#3 /home/vagrant/sites/vlor/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): class@anonymous->enterNo in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/packages/node-name-resolver/src/NodeNameResolver.php on line 85
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Name called on "PhpParser\Node\Expr\MethodCall" is not possible. Use $this->getName($node->name) instead in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/packages/node-name-resolver/src/NodeNameResolver.php:85
Stack trace:
#0 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/NodeManipulator/PropertyFetchAssignManipulator.php(66): Rector\NodeNameResolver\NodeNameResolver->isName()
#1 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/src/NodeManipulator/PropertyFetchAssignManipulator.php(37): Rector\Core\NodeManipulator\PropertyFetchAssignManipulator->isVariableAssignToThisPropertyFetch()
#2 /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/vendor/symplify/astral/src/NodeTraverser/SimpleCallableNodeTraverser.php(54): Rector\Core\NodeManipulator\PropertyFetchAssignManipulator->Rector\Core\NodeManipulator\{closure}()
#3 /home/vagrant/sites/vlor/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): class@anonymous->enterNo in /home/vagrant/sites/vlor/vendor/rector/rector-prefixed/packages/node-name-resolver/src/NodeNameResolver.php on line 85
```

**Comment by samsonasik** [comment]
could you share your `rector.php` config as well? Thank you.

**Comment by samsonasik** [comment]
I can't reproduce it, could you try `rector/rector: "dev-master"` ? If the issue persist, it would be better if you can provide a failing test case PR. 

Thank you.

**Comment by TomasVotruba** [comment]
A https://getrector.org/demo is needed to reproduce

**Comment by Aerendir** [comment]
Same issue here.

Unfortunately, I even can't reproduce the issue, but you can see a live failings in those repositories:

- https://github.com/Aerendir/bundle-stripe/pull/268/checks?check_run_id=1910326004
- https://github.com/Aerendir/component-array-writer/pull/198/checks?check_run_id=1910346021
- https://github.com/Aerendir/component-geo-builder/pull/185/checks?check_run_id=1910366623
- https://github.com/Aerendir/component-stopwatch/pull/45/checks?check_run_id=1910397308
- https://github.com/Aerendir/bundle-aws-ses-monitor/pull/268/checks?check_run_id=1917705296

I cannot reproduce the issue due to the use of PHPUnit, that is not included in the demo, it seems.

Hoping this would help.

**Comment by TomasVotruba** [comment]
Github Action is way to complicated to analyze. Maybe failing PR would do.
Without that, we can't see replicate the bug in isolated controlled space and unable to fix it.

**Comment by Aerendir** [comment]
@TomasVotruba , it is not possible for us to replicate the issue as the demo doesn't use PHPUnit.

It is not complicated, trust me.

Follow those steps:

1. Checkout this branch: https://github.com/Aerendir/bundle-stripe/tree/dependabot/composer/dev/rector/rector-0.9.29
2. Run `composer install`
3. Run `vendor/bin/rector process`

You will see the error and start better understanding what's going on.

You know I can generally create a failing test case, but in this situation it is impossible for me to reproduce the bug as it only happens if the test class inherits from `TestCase` and this is not possible in the current implementation of the Rector's Demo.

**Comment by TomasVotruba** [comment]
I don't talk about Rector demo, but failing test case fixture. It must be replicable in Rector test case here

Here is step by step tutorial how to add it: https://github.com/rectorphp/rector/blob/master/docs/how_to_add_test_for_rector_rule.md

**Comment by DieterHolvoet** [comment]
I tried it using `"rector/rector-prefixed": "dev-master#3f0bca8"` and I'm still having the same issue.

**Comment by noglitchyo** [comment]
I was running into the same issue with version 0.9.31 **for multiple files**.

Here is an extract of the debug output:

```
[refactoring] app/Jobs/Tenant/ScheduledSurvey/SendAdminResultsEmailJob.php
    [applying] Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector
    [applying] Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector
    [applying] Rector\DeadCode\Rector\Class_\RemoveEmptyAbstractClassRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector
    [applying] Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector
    [applying] Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveDeadRecursiveClassMethodRector
    [applying] Rector\DeadCode\Rector\ClassMethod\RemoveUnusedConstructorParamRector
    [applying] Rector\DeadCode\Rector\If_\UnwrapFutureCompatibleIfFunctionExistsRector
    [applying] Rector\DeadCode\Rector\If_\UnwrapFutureCompatibleIfPhpVersionRector
    [applying] Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector
    [applying] Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector
    [applying] Rector\DeadCode\Rector\If_\RemoveUnusedNonEmptyArrayBeforeForeachRector
    [applying] Rector\DeadCode\Rector\If_\RemoveDeadInstanceOfRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector
    [applying] Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector
    [applying] Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector
    [applying] Rector\DeadCode\Rector\MethodCall\RemoveEmptyMethodCallRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector
    [applying] Rector\DeadCode\Rector\Assign\RemoveAssignOfVoidReturnFunctionRector
    [applying] Rector\Naming\Rector\Property\UnderscoreToCamelCasePropertyNameRector
    [applying] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector
    [applying] Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector
    [applying] Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector
    [applying] Rector\DeadCode\Rector\Concat\RemoveConcatAutocastRector
    [applying] Rector\DeadCode\Rector\BinaryOp\RemoveDuplicatedInstanceOfRector
    [applying] Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector
    [applying] Rector\DeadCode\Rector\Return_\RemoveDeadConditionAboveReturnRector
    [applying] Rector\RectorGenerator\Rector\Closure\AddNewServiceToSymfonyPhpConfigRector
    [applying] Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Name called on "PhpParser\Node\Expr\MethodCall" is not possible. Use $this->getName($node->name) instead in /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php:104
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php(200): Rector\NodeNameResolver\NodeNameResolver->isName()
#1 /var/www/html/vendor/rector/rector/rules/naming/src/PropertyRenamer/PropertyFetchRenamer.php(43): Rector\NodeNameResolver\NodeNameResolver->isLocalPropertyFetchNamed()
#2 /var/www/html/vendor/symplify/astral/src/NodeTraverser/SimpleCallableNodeTraverser.php(61): Rector\Naming\PropertyRenamer\PropertyFetchRenamer->Rector\Naming\PropertyRenamer\{closure}()
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): class@anonymous->enterNode()
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode()
#5 /var/www/html/ve in /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php on line 104
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Name called on "PhpParser\Node\Expr\MethodCall" is not possible. Use $this->getName($node->name) instead in /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php:104
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php(200): Rector\NodeNameResolver\NodeNameResolver->isName()
#1 /var/www/html/vendor/rector/rector/rules/naming/src/PropertyRenamer/PropertyFetchRenamer.php(43): Rector\NodeNameResolver\NodeNameResolver->isLocalPropertyFetchNamed()
#2 /var/www/html/vendor/symplify/astral/src/NodeTraverser/SimpleCallableNodeTraverser.php(61): Rector\Naming\PropertyRenamer\PropertyFetchRenamer->Rector\Naming\PropertyRenamer\{closure}()
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): class@anonymous->enterNode()
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode()
#5 /var/www/html/ve in /var/www/html/vendor/rector/rector/packages/node-name-resolver/src/NodeNameResolver.php on line 104
```

and the rector.php:
```
return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // Define what rule sets will be applied
    $parameters->set(Option::SETS, [
        SetList::DEAD_CODE,
    ]);

    // get services (needed for register a single rule)
     $services = $containerConfigurator->services();

    // register a single rule
     $services->set(UnderscoreToCamelCasePropertyNameRector::class);
};
```

However, I tried with dev-master as asked by @samsonasik and I could not reproduce the errors anymore for all files where it was failing.

**Comment by samsonasik** [comment]
latest is currently `dev-main`

**Comment by TomasVotruba** [comment]
@Aerendir Thank you for the repository :+1: , I'm just trying new Rector there

Ref: https://github.com/rectorphp/rector/issues/5690#issuecomment-787918203

I've tried it apart few removed sets the Rector passes well :heavy_check_mark: 

![Peek 2021-03-15 23-34](https://user-images.githubusercontent.com/924196/111229863-f5ef3900-85e6-11eb-95af-adacdfe074eb.gif)

**Comment by Aerendir** [comment]
Glad to be helpful and many thank you for the fix! ❤️
