### ISSUE TITLE
Build docker images github action got error Class "RectorPrefix20210314\Jean85\PrettyVersions" not found

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#5851]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main              |
| Installed as   | in Github action                           |

On `Build docker images` github action, there is error:

```bash
#48 1.754 Fatal error: Uncaught Error: Class "RectorPrefix20210314\Jean85\PrettyVersions" not found in /rector/src/Configuration/Configuration.php:101
1837
#48 1.754 Stack trace:
1838
#48 1.754 #0 /rector/src/Console/ConsoleApplication.php(38): Rector\Core\Configuration\Configuration->getPrettyVersion()
1839
#48 1.754 #1 /tmp/rector/cache/ContainerPjSlY8x/getConsoleApplicationService.php(20): Rector\Core\Console\ConsoleApplication->__construct(Object(Rector\Core\Configuration\Configuration), Object(Rector\Core\Bootstrap\NoRectorsLoadedReporter), Object(RectorPrefix20210314\Symplify\PackageBuilder\Console\Command\CommandNaming), Array)
1840
#48 1.754 #2 /tmp/rector/cache/ContainerPjSlY8x/Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd807098004Container.php(989): ContainerPjSlY8x\getConsoleApplicationService::do(Object(ContainerPjSlY8x\Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd807098004Container), true)
1841
#48 1.754 #3 /rector/vendor/symfony/dependency-injection/Container.php(218): ContainerPjSlY8x\Rector_Core_HttpKernel_RectorKernelDa39a3ee5e6b4b0d3255bfef95601890afd807098004Container->load('getConsoleAppli...')
1842
#48 1.754 #4 /rector/vendor/symfony/dependency-injection/Container.php(203): RectorPrefix20210314\Symfony\Component\DependencyInjection\Container->make('Rector\\Core\\Con...', 1)
1843
#48 1.754 #5 /rector/bin/rector.php(44): RectorPrefix20210314\Symfony\Component\DependencyInjection\Container->get('Rector\\Core\\Con...')
1844
#48 1.754 #6 /rector/bin/rector(5): require_once('/rector/bin/rec...')
1845
#48 1.754 #7 {main}
1846
#48 1.754   thrown in /rector/src/Configuration/Configuration.php on line 101
```

ref https://github.com/rectorphp/rector/runs/2107262664

**Comment by TomasVotruba** [comment]
I tried to fix it here in these 2 callbacks: https://github.com/rectorphp/rector/blob/fc1e842da2b033f69925db15fd35ec8c0e0c9407/scoper.php#L32-L50

Here should change namespace to unprefixed one: https://github.com/rectorphp/rector-prefixed/blob/main/vendor/composer/InstalledVersions.php

If it won't be enough, feel free to take over

**Comment by samsonasik** [comment]
Re-open, it seems it caused error on build-rector-scoped.sh: 

```bash
[NOTE] Dumping Composer Autoload
392

393
 3929/3929 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
394

395
  [ErrorException]                                                   
396
  Class 'RectorPrefix20210314\Composer\InstalledVersions' not found
```

ref https://github.com/rectorphp/rector/runs/2107413916

**Comment by samsonasik** [comment]
It seems it is due https://github.com/rectorphp/rector-prefixed/blob/main/vendor/scoper-autoload.php always re-generated late, @TomasVotruba do you have idea?

**Comment by samsonasik** [comment]
it seems working now, closing 

![Screen Shot 2021-03-15 at 03 06 17](https://user-images.githubusercontent.com/459648/111082546-735d6f80-853b-11eb-945f-1cbfc6dbfb58.png)
