### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getClassReflection() on null in PropertyTypeVendorLockResolver.php:39

### ISSUE THREAD

**Issue by addshore** [rectorphp/rector#5955]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.0       |
| Installed as   | composer dependency                |

While running rector 

```lines=10
[refactoring] packages/mediawiki-api-base/src/Client/Rest/Request/JsonBodyTrait.php
    [applying] Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector
    [applying] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector
    [applying] Rector\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector
    [applying] Rector\PSR4\Rector\Namespace_\MultipleClassFileToPsr4ClassesRector
    [applying] Rector\CodeQuality\Rector\Name\FixClassCaseSensitivityNameRector
    [applying] Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector
    [applying] Rector\CodingStyle\Rector\Property\AddFalseDefaultToBoolPropertyRector
    [applying] Rector\Php52\Rector\Property\VarToPublicPropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
    [applying] Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector
    [applying] Rector\Php74\Rector\Property\TypedPropertyRector
PHP Fatal error:  Uncaught Error: Call to a member function getClassReflection() on null in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/NodeVendorLocker/PropertyTypeVendorLockResolver.php:39
Stack trace:
#0 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/VendorLockResolver.php(65): Rector\VendorLocker\NodeVendorLocker\PropertyTypeVendorLockResolver->isVendorLocked()
#1 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/rules/Php74/Rector/Property/TypedPropertyRector.php(171): Rector\VendorLocker\VendorLockResolver->isPropertyTypeChangeVendorLockedIn()
#2 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/src/Rector/AbstractRector.php(301): Rector\Php74\Rector\Property\TypedPropertyRector->refactor()
#3 /home/adam/dev/git/github/addwiki/addwiki/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode()
#4 /home/adam/dev/git/github/addwiki/addwiki/vendor/nikic/php-parser/lib/PhpP in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/NodeVendorLocker/PropertyTypeVendorLockResolver.php on line 39
Fatal error: Uncaught Error: Call to a member function getClassReflection() on null in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/NodeVendorLocker/PropertyTypeVendorLockResolver.php:39
Stack trace:
#0 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/VendorLockResolver.php(65): Rector\VendorLocker\NodeVendorLocker\PropertyTypeVendorLockResolver->isVendorLocked()
#1 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/rules/Php74/Rector/Property/TypedPropertyRector.php(171): Rector\VendorLocker\VendorLockResolver->isPropertyTypeChangeVendorLockedIn()
#2 /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/src/Rector/AbstractRector.php(301): Rector\Php74\Rector\Property\TypedPropertyRector->refactor()
#3 /home/adam/dev/git/github/addwiki/addwiki/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode()
#4 /home/adam/dev/git/github/addwiki/addwiki/vendor/nikic/php-parser/lib/PhpP in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/VendorLocker/NodeVendorLocker/PropertyTypeVendorLockResolver.php on line 39
```

## Minimal PHP Code Causing Issue

The code being checked while triggering this fatal doesn't seem to be very interesting.
And this code does not trigger an issue in the online demo tool.
https://getrector.org/demo/5769e626-14dc-4fe0-b21f-692b405a3fbc

Though this should be reproducible by checking out `d5b071524cf694859d83cc01deff6f8a11923d0b` on the main branch of https://github.com/addwiki/addwiki and running `vendor/bin/rector process --dry-run --ansi --debug`

```
<?php

namespace Addwiki\Mediawiki\Api\Client\Rest\Request;

trait JsonBodyTrait {

	private $body = null;

	public function setJsonBody( array $body ): self {
		$this->body = $body;
		return $this;
	}

	public function getJsonBody(): ?array {
		return $this->body;
	}

}
```

## Expected Behaviour

No Fatal error

**Comment by addshore** [comment]
Seemingly this fixes the issue

![image](https://user-images.githubusercontent.com/3308769/112067688-60145a80-8b60-11eb-8caa-c6d708b0a59c.png)

Though now looking at the code that seemingly triggers this, this will be due to using `getClassReflection` when `getTraitReflection` would be needed, as it is a trait...

**Comment by TomasVotruba** [comment]
What happens when you use the `getTraitReflection()` in a trait context?

**Comment by addshore** [comment]
> What happens when you use the `getTraitReflection()` in a trait context?

I guess I'm actually going down the wrong route, as the issue is `$scope = $property->getAttribute(AttributeKey::SCOPE);` returning null? when I guess it should be returning something.
And this is the step before the reflection occurs.

I think I need to look at this with a debugger to figure out what is happening, but not tonight!

**Comment by TomasVotruba** [comment]
That's because PHPStan does not provide scope for traits themselves, as they only exist inside a context of a class.

I think in this case it can be skipped, if `$scope === null`

**Comment by TomasVotruba** [comment]
Thanks for the demo link :+1: I was able to reproduce the bug easily
