### ISSUE TITLE
Running process with `--debug` gives: `Uncaught Error: Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::setAttribute`

### ISSUE THREAD

**Issue by ruudk** [rectorphp/rector#6180]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.10.6             |
| Installed as   | prefixed                           |

```
vendor/bin/rector process --debug src/Core/EventBundle/Event/Event/LocationRemovedEvent.php
[parsing] src/Core/EventBundle/Event/Event/LocationRemovedEvent.php
[refactoring] src/Core/EventBundle/Event/Event/LocationRemovedEvent.php
PHP Fatal error:  Uncaught Error: Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::setAttribute() in /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php:129
Stack trace:
#0 /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php(101): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->setPositionOfLastToken(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#1 /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php(73): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->createFromNode(Object(PhpParser\Node\Stmt\Property))
#2 /Volumes/CS/www/website/vendor/rector/rector-prefixed/src/Exclusion/ExclusionManager.php(50): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->createFromNodeOrEmpty(Object(PhpParser\Node\Stmt\Property))
#3 /Volumes/CS/www/website/vendor/rector/rector-prefixed/src/Exclusion/ExclusionManager.p in /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php on line 129
Fatal error: Uncaught Error: Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::setAttribute() in /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php:129
Stack trace:
#0 /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php(101): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->setPositionOfLastToken(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#1 /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php(73): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->createFromNode(Object(PhpParser\Node\Stmt\Property))
#2 /Volumes/CS/www/website/vendor/rector/rector-prefixed/src/Exclusion/ExclusionManager.php(50): Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory->createFromNodeOrEmpty(Object(PhpParser\Node\Stmt\Property))
#3 /Volumes/CS/www/website/vendor/rector/rector-prefixed/src/Exclusion/ExclusionManager.p in /Volumes/CS/www/website/vendor/rector/rector-prefixed/packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php on line 129
```

while this works:
```
vendor/bin/rector process src/Core/EventBundle/Event/Event/LocationRemovedEvent.php
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] Rector is done!


```

**Comment by TomasVotruba** [comment]
That would accidental path invoke.
Bump the phpdoc-parser at least to 0.5.* and phpstan to 0.12.83
