### ISSUE TITLE
SetList::DEAD_CODE with SetList::SAFE_07 causes PHP Fatal error

### ISSUE THREAD

**Issue by lbausch** [rectorphp/rector#6420]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.2             |
| Installed as   | composer dependency                       |

`SetList::DEAD_CODE` with `SetList::SAFE_07` causes `PHP Fatal error`:

<details>
 <summary>terminal output</summary>

```bash
$ ./vendor/bin/rector -v --dry-run process fail.php
[parsing] fail.php
[refactoring] fail.php
[post rectors] fail.php
[printing] fail.php
PHP Notice:  Undefined offset: -1 in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
Notice: Undefined offset: -1 in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
PHP Fatal error:  Uncaught TypeError: Return value of PhpParser\Internal\TokenStream::getIndentationBefore() must be of the type int, null returned in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(608): PhpParser\Internal\TokenStream->getIndentationBefore(-1)
#1 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\FuncCall), true)
#2 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(799): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)
#3 /home/user/project/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(174): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#4 /home/user in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
Fatal error: Uncaught TypeError: Return value of PhpParser\Internal\TokenStream::getIndentationBefore() must be of the type int, null returned in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(608): PhpParser\Internal\TokenStream->getIndentationBefore(-1)
#1 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\FuncCall), true)
#2 /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(799): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)
#3 /home/user/project/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(174): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#4 /home/user in /home/user/project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
```
</details>

## Minimal PHP Code Causing Issue
https://getrector.org/demo/65c1e5e4-a8e7-4fa5-872d-f6adc0457817

## Expected Behaviour
Rector should display a diff which replaces `preg_replace()` with `\Safe\preg_replace()`

**Comment by sabbelasichon** [comment]
@TomasVotruba I took a look into it yesterday. Seems a tough one. The culprit is the RemoveDeadStmtRector which holds context of the nodes. So if a node has changed during the run, PhpParser fails because nodes are not the same anymore.

**Comment by TomasVotruba** [comment]
I see. Could you send a failing test case? I'll see if I can tackle it

**Comment by lbausch** [comment]
Thank you :+1:
