### ISSUE TITLE
AnnotationToAttributeRector TypeError for @paramConverter

### ISSUE THREAD

**Issue by ndench** [rectorphp/rector#6465]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.5              |

Using Rector to convert `@paramConverter` annotations to attributes results in the following error:

```
PHP Fatal error:  Uncaught TypeError: PhpParser\Node\Identifier::__construct(): Argument #1 ($name) must be of type string, int given, called in /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php on line 52 and defined in /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php:21                                                  
```

<details>
<summary>Full stack trace</summary>

```
PHP Fatal error:  Uncaught TypeError: PhpParser\Node\Identifier::__construct(): Argument #1 ($name) must be of type string, int given, called in /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php on line 52 and defined in /srv/www/ap
p/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php:21
Stack trace:
#0 /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php(52): PhpParser\Node\Identifier->__construct(0)
#1 /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php(33): Rector\PhpAttribute\Printer\PhpAttributeGroupFactory->createArgsFromItems(Array)
#2 /srv/www/app/current/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(117): Rector\PhpAttribute\Printer\PhpAttributeGroupFactory->create(Object(Rector\BetterPhpDocParser\PhpDoc\DoctrineAnnotationTagValueNode), Object(Rector\Php80\ValueObject\AnnotationToAttribute))
#3 /srv/www/app/current/vendor/rector/rector/src/Rector/AbstractRector.php(255): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#6 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#7 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#8 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#9 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#10 /srv/www/app/current/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(46): PhpParser\NodeTraverser->traverse(Array)
#11 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor.php(53): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#12 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(167): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File))
#13 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(180): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#14 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(168): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), 'refactoring')
#15 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(111): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Array)
#16 /srv/www/app/current/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(70): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Array)
#17 /srv/www/app/current/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(56): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array)
#18 /srv/www/app/current/vendor/rector/rector/src/Console/Command/ProcessCommand.php(124): Rector\Core\Application\ApplicationFileProcessor->run(Array)
#19 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Command/Command.php(230): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#20 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(826): RectorPrefix20210518\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#21 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(251): RectorPrefix20210518\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#22 /srv/www/app/current/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20210518\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#23 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(152): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#24 /srv/www/app/current/vendor/rector/rector/bin/rector.php(47): RectorPrefix20210518\Symfony\Component\Console\Application->run()
#25 /srv/www/app/current/vendor/rector/rector/bin/rector(5): require_once('/srv/www/app/cu...')
#26 {main}
  thrown in /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php on line 21
Fatal error: Uncaught TypeError: PhpParser\Node\Identifier::__construct(): Argument #1 ($name) must be of type string, int given, called in /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php on line 52 and defined in /srv/www/app/cur
rent/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php:21
Stack trace:
#0 /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php(52): PhpParser\Node\Identifier->__construct(0)
#1 /srv/www/app/current/vendor/rector/rector/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php(33): Rector\PhpAttribute\Printer\PhpAttributeGroupFactory->createArgsFromItems(Array)
#2 /srv/www/app/current/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(117): Rector\PhpAttribute\Printer\PhpAttributeGroupFactory->create(Object(Rector\BetterPhpDocParser\PhpDoc\DoctrineAnnotationTagValueNode), Object(Rector\Php80\ValueObject\AnnotationToAttribute))
#3 /srv/www/app/current/vendor/rector/rector/src/Rector/AbstractRector.php(255): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#6 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#7 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#8 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#9 /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#10 /srv/www/app/current/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(46): PhpParser\NodeTraverser->traverse(Array)
#11 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor.php(53): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#12 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(167): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File))
#13 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(180): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#14 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(168): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), 'refactoring')
#15 /srv/www/app/current/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(111): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Array)
#16 /srv/www/app/current/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(70): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Array)
#17 /srv/www/app/current/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(56): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array)
#18 /srv/www/app/current/vendor/rector/rector/src/Console/Command/ProcessCommand.php(124): Rector\Core\Application\ApplicationFileProcessor->run(Array)
#19 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Command/Command.php(230): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#20 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(826): RectorPrefix20210518\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#21 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(251): RectorPrefix20210518\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#22 /srv/www/app/current/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20210518\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#23 /srv/www/app/current/vendor/rector/rector/vendor/symfony/console/Application.php(152): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20210518\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210518\Symfony\Component\Console\Output\ConsoleOutput))
#24 /srv/www/app/current/vendor/rector/rector/bin/rector.php(47): RectorPrefix20210518\Symfony\Component\Console\Application->run()
#25 /srv/www/app/current/vendor/rector/rector/bin/rector(5): require_once('/srv/www/app/cu...')
#26 {main}
  thrown in /srv/www/app/current/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php on line 21
```

This appears to be because the first parameter in the `@paramConverter` annotation doesn't have a name. So the [PhpAttributeGroupFactory](https://github.com/rectorphp/rector/blob/c92ddc948939f5eeb3256c13c9f11893c45ef81d/packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php#L56) uses the key `0` when instantiating the Identifier, which requires a string in [the constructor](https://github.com/rectorphp/rector/blob/c92ddc948939f5eeb3256c13c9f11893c45ef81d/vendor/nikic/php-parser/lib/PhpParser/Node/Identifier.php#L21).

</details>

## Minimal PHP Code Causing Issue

Here is a [demo](https://getrector.org/demo/99e96118-e9b8-4f99-9c11-8622b9d03589), you'll notice that it says "no change". You need to run rector with `--verbose` to see the error and stack trace.

## Expected Behaviour

```diff
-    /**
-     * @ParamConverter("post", class="App\Entity\Post", options={"id": "post"})
-     */
+    #[ParamConverter('post', Post::class, ['id' => 'post'])]
     public function __invoke(Site $site, Post $post)
```

**Comment by samsonasik** [comment]
the annotation you have seems invalid, missing closing }

**Comment by ndench** [comment]
Good catch @samsonasik, I stuffed up my reproducer. I've updated the issue to have a correct annotation now.

**Comment by samsonasik** [comment]
Fixed by https://github.com/rectorphp/rector-src/pull/142
