### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Rector\DeadCode\ValueObject\VariableNodeUse::__construct(): Argument #1 ($startTokenPosition) must be of type int, null given

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/rector#6557]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

In the following case, if you use RemoveOverriddenValuesRector and RenameVariableToMatchNewTypeRector together, an exception is thrown.

<details>
<summary>Full stack trace</summary>

```
PHP Fatal error: Uncaught TypeError: Rector\DeadCode\ValueObject\VariableNodeUse::__construct(): Argument#1 ($startTokenPosition) must be of type int, null given, called in /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/rules/DeadCode/NodeCollector/NodeByTypeAndPositionCollector.php on line 49 and defined in /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/rules/DeadCode/ValueObject/VariableNodeUse.php:24
Stack trace: 
#0 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/rules/DeadCode/NodeCollector/NodeByTypeAndPositionCollector.php(49): Rector\DeadCode\ValueObject\VariableNodeUse->__construct() 
#1 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/rules/DeadCode/Rector/FunctionLike/RemoveOverriddenValuesRector.php(86): Rector\DeadCode\NodeCollector\NodeByTypeAndPositionCollector->collectNodesByTypeAndPosition() 
#2 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Rector/AbstractRector.php(247): Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector->refactor() 
#3 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Core\Rector\AbstractRector->enterNode() 
#4 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode() 
#5 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray() 
#6 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode() 
#7 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray() 
#8 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode() 
#9 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray() 
#10 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode() 
#11 /home/runner/work/rector-sample/rector-sample/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray() 
#12 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41): PhpParser\NodeTraverser->traverse() 
#13 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/FileProcessor.php(38): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse() 
#14 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(95): Rector\Core\Application\FileProcessor->refactor() 
#15 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(110): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}() 
#16 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper() 
#17 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(52): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors() 
#18 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/ApplicationFileProcessor.php(59): Rector\Core\Application\FileProcessor\PhpFileProcessor->process() 
#19 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Application/ApplicationFileProcessor.php(36): Rector\Core\Application\ApplicationFileProcessor->processFiles() 
#20 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Console/Command/ProcessCommand.php(127): Rector\Core\Application\ApplicationFileProcessor->run() 
#21 /home/runner/work/rector-sample/rector-sample/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute() 
#22 /home/runner/work/rector-sample/rector-sample/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run() 
#23 /home/runner/work/rector-sample/rector-sample/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand() 
#24 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun() 
#25 /home/runner/work/rector-sample/rector-sample/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun() 
#26 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/bin/rector.php(60): Symfony\Component\Console\Application->run() 
#27 /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/bin/rector(4): require_once('...') 
#28 {main}
  thrown in /home/runner/work/rector-sample/rector-sample/vendor/rector/rector-src/rules/DeadCode/ValueObject/VariableNodeUse.php on line 24
```

</details>

## Minimal PHP Code Causing Issue

1. Config`rector.php`

```php
<?php

declare(strict_types=1);

use Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector;
use Rector\Naming\Rector\ClassMethod\RenameVariableToMatchNewTypeRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(RemoveOverriddenValuesRector::class);
    $services->set(RenameVariableToMatchNewTypeRector::class);
};
```

2. Input Code
```php
<?php

final class Demo
{
    public function run()
    {
        return function () {
            $demo = new SomeClass();
            $demo->doSomething();
            return;
        };
    }
}

final class SomeClass
{
    public function doSomething(): void
    {

    }
}
```

## Expected Behaviour

No errors

**Comment by zingimmick** [comment]
It seems that the return value of `$node->getAttribute(AttributeKey::START_TOKEN_POSITION)` is nullable, maybe we can use `$node->getStartTokenPos()` instead.
https://github.com/rectorphp/rector-src/blob/48e89b5bd2067a0788986343e17bafede1fd6ed6/rules/DeadCode/NodeCollector/NodeByTypeAndPositionCollector.php#L37

**Comment by samsonasik** [comment]
@zingimmick could you create PR for it? Thank you.

**Comment by zingimmick** [comment]
> @zingimmick could you create PR for it? Thank you.

PR: rectorphp/rector-src#396
