### ISSUE TITLE
phpstan/phpstan 0.12.92 causes errors

### ISSUE THREAD

**Issue by NotionCommotion** [rectorphp/rector#6564]
# Bug Report

| Subject        | Details                                                         |
| :Imcompatible phpstan | :Invalid lexer token|
| Rector version | rector-src             |

Updated composer which changed phpstan/phpstan from 0.12.91 to 0.12.92.
```
[michael@devserver rector-src]$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading phpstan/phpstan (0.12.91 => 0.12.92)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading phpstan/phpstan (0.12.92)
  - Upgrading phpstan/phpstan (0.12.91 => 0.12.92): Extracting archive
Generating autoload files
80 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
```

Now produces error.
```
[michael@devserver rector-src]$ bin/rector process app/SomeFile.php --dry-run --debug
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 sec/< 1 sec 60.5 MiB[parsing] app/SomeFile.php
[refactoring] app/SomeFile.php
    [applying] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector
    [applying] Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector
    [applying] Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector
PHP Fatal error:  Uncaught RangeException: The lexer returned an invalid token (id=38, value=&) in phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:187
Stack trace:
#0 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(143): PhpParser\ParserAbstract->doParse()
#1 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(246): PhpParser\ParserAbstract->parse()
#2 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(162): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->parseFile()
#3 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(123): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->findClassNode()
#4 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(38): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->generateClassStub()
#5 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->getClassSource()
#6 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(38): PHPStan\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->createLocatedSource()
#7 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/SkipClassAliasSourceLocator.php(24): PHPStan\BetterReflection\SourceLocator\Type\AbstractSourceLocator->locateIdentifier()
#8 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\Reflection\BetterReflection\SourceLocator\SkipClassAliasSourceLocator->locateIdentifier()
#9 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#10 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier()
#11 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#12 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier()
#13 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(39): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#14 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): PHPStan\BetterReflection\Reflector\ClassReflector->reflect()
#15 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/BetterReflectionProvider.php(105): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect()
#16 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(25): PHPStan\Reflection\BetterReflection\BetterReflectionProvider->hasClass()
#17 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(31): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass()
#18 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(439): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass()
#19 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/Soap/SoapClientMethodsClassReflectionExtension.php(13): PHPStan\Reflection\ClassReflection->isSubclassOf()
#20 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(294): PHPStan\Reflection\Php\Soap\SoapClientMethodsClassReflectionExtension->hasMethod()
#21 /var/www/rector-src/rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php(138): PHPStan\Reflection\ClassReflection->hasMethod()
#22 /var/www/rector-src/rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php(83): Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector->shouldSkipClass()
#23 /var/www/rector-src/src/Rector/AbstractRector.php(247): Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector->refactor()
#24 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode()
#25 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#26 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#27 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#28 /var/www/rector-src/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(38): PhpParser\NodeTraverser->traverse()
#29 /var/www/rector-src/src/Application/FileProcessor.php(38): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
#30 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(95): Rector\Core\Application\FileProcessor->refactor()
#31 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(110): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}()
#32 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper()
#33 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(52): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
#34 /var/www/rector-src/src/Application/ApplicationFileProcessor.php(59): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#35 /var/www/rector-src/src/Application/ApplicationFileProcessor.php(36): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#36 /var/www/rector-src/src/Console/Command/ProcessCommand.php(127): Rector\Core\Application\ApplicationFileProcessor->run()
#37 /var/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute()
#38 /var/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#39 /var/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#40 /var/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun()
#41 /var/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun()
#42 /var/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#43 /var/www/rector-src/bin/rector(4): require_once('...')
#44 {main}
  thrown in phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 187
Fatal error: Uncaught RangeException: The lexer returned an invalid token (id=38, value=&) in phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:187
Stack trace:
#0 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(143): PhpParser\ParserAbstract->doParse()
#1 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(246): PhpParser\ParserAbstract->parse()
#2 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(162): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->parseFile()
#3 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php(123): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->findClassNode()
#4 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(38): PHPStan\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->generateClassStub()
#5 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->getClassSource()
#6 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(38): PHPStan\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->createLocatedSource()
#7 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/SkipClassAliasSourceLocator.php(24): PHPStan\BetterReflection\SourceLocator\Type\AbstractSourceLocator->locateIdentifier()
#8 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\Reflection\BetterReflection\SourceLocator\SkipClassAliasSourceLocator->locateIdentifier()
#9 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#10 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier()
#11 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#12 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier()
#13 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(39): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier()
#14 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): PHPStan\BetterReflection\Reflector\ClassReflector->reflect()
#15 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/BetterReflectionProvider.php(105): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect()
#16 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(25): PHPStan\Reflection\BetterReflection\BetterReflectionProvider->hasClass()
#17 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(31): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass()
#18 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(439): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass()
#19 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/Soap/SoapClientMethodsClassReflectionExtension.php(13): PHPStan\Reflection\ClassReflection->isSubclassOf()
#20 phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(294): PHPStan\Reflection\Php\Soap\SoapClientMethodsClassReflectionExtension->hasMethod()
#21 /var/www/rector-src/rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php(138): PHPStan\Reflection\ClassReflection->hasMethod()
#22 /var/www/rector-src/rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php(83): Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector->shouldSkipClass()
#23 /var/www/rector-src/src/Rector/AbstractRector.php(247): Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector->refactor()
#24 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode()
#25 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#26 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#27 /var/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#28 /var/www/rector-src/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(38): PhpParser\NodeTraverser->traverse()
#29 /var/www/rector-src/src/Application/FileProcessor.php(38): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
#30 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(95): Rector\Core\Application\FileProcessor->refactor()
#31 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(110): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}()
#32 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper()
#33 /var/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(52): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
#34 /var/www/rector-src/src/Application/ApplicationFileProcessor.php(59): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#35 /var/www/rector-src/src/Application/ApplicationFileProcessor.php(36): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#36 /var/www/rector-src/src/Console/Command/ProcessCommand.php(127): Rector\Core\Application\ApplicationFileProcessor->run()
#37 /var/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute()
#38 /var/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#39 /var/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#40 /var/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun()
#41 /var/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun()
#42 /var/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#43 /var/www/rector-src/bin/rector(4): require_once('...')
#44 {main}
  thrown in phar:///var/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 187
[michael@devserver rector-src]$ vi composer.json

```

I locked the version down and now no error.
`"phpstan/phpstan": "0.12.91",`

**Comment by samsonasik** [comment]
Yes, you can pin to 0.12.91 for now.

**Comment by samsonasik** [comment]
Actually, if you use as `composer require --dev`, you can use `rector/rector` in composer.json, not the `rector-src` one as it marked as it require ""phpstan/phpstan": ">=0.12.86 <=0.12.91""

https://github.com/rectorphp/rector/blob/7f0c8aacf21fdb495c700b86a5e8f8fed34794e5/composer.json#L10

**Comment by TomasVotruba** [comment]
I'll tag a new version to make sure stable Rector avoid this bug

**Comment by escopecz** [comment]
I'm having the same problem. Has this been released? I cannot have both `rector/rector` and `phpstan/phpstan` in dev dependencies. 

I'm also confused how to trace down if this issue has been addressed. There is no PR associated I see no release notes anywhere (https://github.com/rectorphp/rector/releases nor CHANGELOG.md file) and yet Tomas commented 10 days ago that this will go to a stable release. Latest release 0.11.36 happened 10 days ago. I guess this did not make it?

**Comment by TomasVotruba** [comment]
Thanks for reporting. In Rector 0.11.36 I can see the versoin here locked: https://github.com/rectorphp/rector/blob/0c1004ad176273c2249a1384ffb160167f5f2199/composer.json#L10


Could you run `vendor/bin/rector --version`?

**Comment by escopecz** [comment]
It returns `Rector c424040f97e506d29d32d58d64c2bbb8a5ee417c`. 

Is it only my local that is doing this?:

```
$ php -d memory_limit=2G /usr/local/bin/composer require --dev --with-all-dependencies rector/rector phpstan/phpstan
Using version ^0.11.37 for rector/rector
Using version ^0.12.93 for phpstan/phpstan
./composer.json has been updated
Running composer update rector/rector phpstan/phpstan --with-all-dependencies
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rector/rector ^0.11.37 -> satisfiable by rector/rector[0.11.37].
    - rector/rector 0.11.37 requires phpstan/phpstan 0.12.91 -> found phpstan/phpstan[0.12.91] but it conflicts with your root composer.json require (^0.12.93).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by TomasVotruba** [comment]
> rector/rector 0.11.37 requires phpstan/phpstan 0.12.91 -> found phpstan/phpstan[0.12.91] but it conflicts with your root composer.json require (^0.12.93).

There is a catch. The version must be `0.12.91`

**Comment by escopecz** [comment]
Ok, I removed both packages with 

```
$ php -d memory_limit=2G /usr/local/bin/composer remove --dev rector/rector phpstan/phpstan
./composer.json has been updated
Running composer update rector/rector phpstan/phpstan
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 2 removals
  - Removing phpstan/phpstan (0.12.91)
  - Removing rector/rector (0.11.36)
  - Upgrading aws/aws-sdk-php (3.185.16 => 3.185.17)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 2 removals
  - Downloading aws/aws-sdk-php (3.185.17)
  - Removing rector/rector (0.11.36)
  - Removing phpstan/phpstan (0.12.91)
  - Upgrading aws/aws-sdk-php (3.185.16 => 3.185.17): Extracting archive
Generating autoload files
```

and then installed both packages from scratch:

```
$ php -d memory_limit=2G /usr/local/bin/composer require --dev --with-all-dependencies rector/rector phpstan/phpstan
Using version ^0.11.37 for rector/rector
Using version ^0.12.93 for phpstan/phpstan
./composer.json has been updated
Running composer update rector/rector phpstan/phpstan --with-all-dependencies
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rector/rector ^0.11.37 -> satisfiable by rector/rector[0.11.37].
    - rector/rector 0.11.37 requires phpstan/phpstan 0.12.91 -> found phpstan/phpstan[0.12.91] but it conflicts with your root composer.json require (^0.12.93).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

How should I proceed to have both packages in require-dev section? Right now I continue work by just installing only rector/rector, but the project needs both. I cannot depend on rector/rector package to require it for me as I know you [work hard on removing them](https://twitter.com/rectorphp/status/1391540181120032769?s=20).

**Comment by TomasVotruba** [comment]
See packagist: https://packagist.org/packages/rector/rector#0.11.37

![image](https://user-images.githubusercontent.com/924196/126463324-f78c5ba2-617b-46d0-9f30-db7f7fbab444.png)


Possibly locked in `composer.lock`.

I bet if you remove `composer.lock` and `/vendor`, this would not happen.

**Comment by TomasVotruba** [comment]
I'm just trying it and composer fails to resolve it correctly. Intersting... I have the same issue on raw project.

Possibly race-condition bug in composer itself. Maybe "p" is before "r", so PHPStan version is resolved first, then Rectors.

WIP

**Comment by TomasVotruba** [comment]
Not sure what is wrong there, but it seems like like composer fail. 

Even if I separate it to 2 standalone commands it does not work:

```bash
composer require --dev rector/rector
composer require --dev phpstan/phpstan
```

The best workaround I've found so far is this:

```bash
composer require --dev rector/rector phpstan/phpstan:0.12.91
```

**Comment by escopecz** [comment]
Thanks Tomas! I'll go with that for now.
