### ISSUE TITLE
Error: Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#6573]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

Running rector against `rules` directory got the following error:

```bash
bin/rector process rules

PHP Fatal error:  Uncaught Error: Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php:22
Stack trace:
#0 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(102): Rector\Core\ValueObject\Application\RectorError->getRelativeFilePath()
#1 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(41): Rector\ChangesReporting\Output\ConsoleOutputFormatter->reportErrors(Array)
#2 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(136): Rector\ChangesReporting\Output\ConsoleOutputFormatter->report(Object(Rector\Core\ValueObject\ProcessResult), Object(Rector\Core\ValueObject\Configuration))
#3 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/samsonasik/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#9 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#10 {main}
  thrown in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php on line 22
Fatal error: Uncaught Error: Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php:22
Stack trace:
#0 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(102): Rector\Core\ValueObject\Application\RectorError->getRelativeFilePath()
#1 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(41): Rector\ChangesReporting\Output\ConsoleOutputFormatter->reportErrors(Array)
#2 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(136): Rector\ChangesReporting\Output\ConsoleOutputFormatter->report(Object(Rector\Core\ValueObject\ProcessResult), Object(Rector\Core\ValueObject\Configuration))
#3 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/samsonasik/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#9 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#10 {main}
  thrown in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php on line 22
```

## Expected Behaviour

It should not error.

**Comment by samsonasik** [comment]
@TomasVotruba looking at `RectorError` class, it seems the `fileInfo` property is private and no method for fill it:

https://github.com/rectorphp/rector-src/blob/b001e388ccfb37f8af1f4873c63212a0155f642a/src/ValueObject/Application/RectorError.php#L11

 Is it filled at some Private Acessor somewhere?

**Comment by TomasVotruba** [comment]
I think the fileInfo accessor is here:
https://github.com/rectorphp/rector-src/blob/b001e388ccfb37f8af1f4873c63212a0155f642a/src/ValueObject/Application/RectorError.php#L25

**Comment by samsonasik** [comment]
Looking at the error, the `private` `fileInfo` property is never filled yet?

**Comment by samsonasik** [comment]
It seems the `fileInfo` property never iniitlized yet, ref https://3v4l.org/U5hrv for similar error.

**Comment by samsonasik** [comment]
Run rector twice against `rules` directory seems fixed it.

**Comment by samsonasik** [comment]
@TomasVotruba looking at diff change at https://github.com/rectorphp/rector-src/pull/448 . I tried a removed comment on `EregToPcreTransformer.php` 

https://github.com/rectorphp/rector-src/pull/448/files#diff-e271caa35cd8149cb2b8598ee4e8d0a9ae3ba0703f57d920ee9adb09caa05219L118

and it caused it. It seems the error happen during removing comment, and after comment removed, the error gone, that's why run twice fix it:

***First run*** : 

```
➜  rector-src git:(main) bin/rector process rules/Php70/EregToPcreTransformer.php --dry-run        
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) rules/Php70/EregToPcreTransformer.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
         $rr = 0;
         $l = strlen($content);
         while ($i < $l) {
-            // atom
             $char = $content[$i];
             if ($char === '(') {
                 $i = (int) $i;
@@ @@
                 }
                 $r[$rr] .= $this->_ere2pcre_escape($content[$i]);
             } else {
-                // including ] and } which are allowed as a literal character
                 $r[$rr] .= $this->_ere2pcre_escape($char);
             }
             ++$i;
@@ @@
             if ($i >= $l) {
                 break;
             }
-            // piece after the atom (only ONE of them is possible)
             $char = $content[$i];
             if ($char === '*' || $char === '+' || $char === '?') {
                 $r[$rr] .= $char;
    ----------- end diff -----------

PHP Fatal error:  Uncaught Error: Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php:22
Stack trace:
#0 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(102): Rector\Core\ValueObject\Application\RectorError->getRelativeFilePath()
#1 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(41): Rector\ChangesReporting\Output\ConsoleOutputFormatter->reportErrors(Array)
#2 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(136): Rector\ChangesReporting\Output\ConsoleOutputFormatter->report(Object(Rector\Core\ValueObject\ProcessResult), Object(Rector\Core\ValueObject\Configuration))
#3 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/samsonasik/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#9 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#10 {main}
  thrown in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php on line 22
Fatal error: Uncaught Error: Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php:22
Stack trace:
#0 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(102): Rector\Core\ValueObject\Application\RectorError->getRelativeFilePath()
#1 /Users/samsonasik/www/rector-src/packages/ChangesReporting/Output/ConsoleOutputFormatter.php(41): Rector\ChangesReporting\Output\ConsoleOutputFormatter->reportErrors(Array)
#2 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(136): Rector\ChangesReporting\Output\ConsoleOutputFormatter->report(Object(Rector\Core\ValueObject\ProcessResult), Object(Rector\Core\ValueObject\Configuration))
#3 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(299): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/samsonasik/www/rector-src/bin/rector.php(75): Symfony\Component\Console\Application->run()
#9 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#10 {main}
  thrown in /Users/samsonasik/www/rector-src/src/ValueObject/Application/RectorError.php on line 22
```

***Second Run***

```bash
bin/rector process rules/Php70/EregToPcreTransformer.php          
    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
                                                                                                                        
 [OK] Rector is done!                                                                                                   
```

**Comment by samsonasik** [comment]
It seems it caused by `AssignArrayToStringRector`, I created PR for it at https://github.com/rectorphp/rector-src/pull/450
