### ISSUE TITLE
AddFlashRector is buggy

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector#6755]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0b8fcdaa57061662d684f2653d37f28f1eb8e53f             |

```
[parsing] DemoFile.php
[refactoring] DemoFile.php
Fatal error: Uncaught TypeError: Argument 1 passed to Rector\NodeNameResolver\NodeNameResolver::isSingleName() must implement interface PhpParser\Node, string given, called in /application/vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php on line 80 and defined in /application/vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php:209
Stack trace:
#0 /application/vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php(80): Rector\NodeNameResolver\NodeNameResolver->isSingleName('session', 'getSession')
#1 /application/vendor/rector/rector/rules/Defluent/NodeAnalyzer/FluentChainMethodCallNodeAnalyzer.php(188): Rector\NodeNameResolver\NodeNameResolver->isName('session', 'getSession')
#2 /application/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/AddFlashRector.php(75): Rector\Defluent\NodeAnalyzer\FluentChainMethodCallNodeAnalyzer->isTypeAndChainCalls(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Type\ObjectType), Array)
#3 /application/vendor/rector/ in /application/vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php on line 209
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec30ca2-97dd-6a2c-b608-97a15d06e173

(Demo is correct, but errors for some other reason, though.)

## Expected Behaviour

No exceptions.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

See the error text demo. Class must be completed.

Another way is to create reproducible repository.
