### ISSUE TITLE
DowngradeLevelSetList::DOWN_TO_PHP_71 executes `DowngradeParameterTypeWideningRector` when it should not

### ISSUE THREAD

**Issue by leoloso** [rectorphp/rector#6756]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.59             |

I upgraded to v0.11.59, and use the new `DowngradeLevelSetList::DOWN_TO_PHP_71`. I went from this:

```php
$containerConfigurator->import(DowngradeSetList::PHP_80);
$containerConfigurator->import(DowngradeSetList::PHP_74);
$containerConfigurator->import(DowngradeSetList::PHP_73);
$containerConfigurator->import(DowngradeSetList::PHP_72);
```

to this:

```php
$containerConfigurator->import(DowngradeLevelSetList::DOWN_TO_PHP_71);
```

With Rector v0.11.58, this function:

```php
#[Required]
final public function autowireUserAuthorization(UserAuthorizationSchemeRegistryInterface $userAuthorizationSchemeRegistry): void
{
    $this->userAuthorizationSchemeRegistry = $userAuthorizationSchemeRegistry;
}
```

is downgraded like this:

```php
/**
 * @required
 */
public final function autowireUserAuthorization(UserAuthorizationSchemeRegistryInterface $userAuthorizationSchemeRegistry): void
{
    $this->userAuthorizationSchemeRegistry = $userAuthorizationSchemeRegistry;
}
```

After upgrading to v0.11.59, it is downgraded like this:

```php
/**
 * @param \GraphQLAPI\GraphQLAPI\Registries\UserAuthorizationSchemeRegistryInterface $userAuthorizationSchemeRegistry
 * @required
 */
public final function autowireUserAuthorization($userAuthorizationSchemeRegistry): void
{
    $this->userAuthorizationSchemeRegistry = $userAuthorizationSchemeRegistry;
}
```

So now Symfony DependencyInjection doesn't work anymore, throwing an exception:

```
Cannot autowire service "GraphQLAPI\GraphQLAPI\Security\UserAuthorizationInterface": argument "$userAuthorizationSchemeRegistry" of method "GraphQLAPI\GraphQLAPI\Security\UserAuthorization::autowireUserAuthorization()" has no type-hint, you should configure its value explicitly.

Stack trace:

#0 /app/wordpress/wp-content/plugins/graphql-api/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(77): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(PrefixedByPoP\Symfony\Component\DependencyInjection\Definition), true)
#1 /app/wordpress/wp-content/plugins/graphql-api/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(31): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /app/wordpress/wp-content/plugins/graphql-api/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(42): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true)
#3 /app/wordpress/wp-content/plugins/graphql-api/vendor/symfony/dependency-injection/Compiler/Compiler.php(87): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /app/wordpress/wp-content/plugins/graphql-api/vendor/symfony/dependency-injection/ContainerBuilder.php(648): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /app/wordpress/wp-content/plugins/graphql-api/vendor/getpop/root/src/Container/ContainerBuilderFactoryTrait.php(137): PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#6 /app/wordpress/wp-content/plugins/graphql-api/vendor/getpop/root/src/AppLoader.php(158): PoP\Root\Container\SystemContainerBuilderFactory::maybeCompileAndCacheContainer(Array)
#7 /app/wordpress/wp-content/plugins/graphql-api/src/PluginSkeleton/AbstractMainPlugin.php(438): PoP\Root\AppLoader::bootSystem(true, '_v0.8.1_1634640...', '/app/wordpress/...')
#8 /app/wordpress/wp-content/plugins/graphql-api/src/PluginSkeleton/AbstractMainPlugin.php(366): GraphQLAPI\GraphQLAPI\PluginSkeleton\AbstractMainPlugin->bootSystem()
#9 /app/wordpress/wp-includes/class-wp-hook.php(303): GraphQLAPI\GraphQLAPI\PluginSkeleton\AbstractMainPlugin->GraphQLAPI\GraphQLAPI\PluginSkeleton\{closure}('')
#10 /app/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#11 /app/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#12 /app/wordpress/wp-settings.php(441): do_action('plugins_loaded')
#13 /app/wordpress/wp-config.php(90): require_once('/app/wordpress/...')
#14 /app/wordpress/wp-load.php(50): require_once('/app/wordpress/...')
#15 /app/wordpress/wp-admin/admin.php(34): require_once('/app/wordpress/...')
#16 /app/wordpress/wp-admin/index.php(10): require_once('/app/wordpress/...')
#17 {main}
```

Running Rector with `--dry-run`, I found out the reason: using `DowngradeLevelSetList::DOWN_TO_PHP_71` it is executing an extra rule `DowngradeParameterTypeWideningRector` which was not executed before.

Check out this gif:

![rector-bug](https://user-images.githubusercontent.com/1981996/137900866-4714f1df-07d9-4352-bbc8-3b8f77062850.gif)

**Comment by leoloso** [comment]
Same problem happens when commenting `DowngradeSetList::PHP_80`:

```php
// $containerConfigurator->import(DowngradeSetList::PHP_80);
$containerConfigurator->import(DowngradeSetList::PHP_74);
$containerConfigurator->import(DowngradeSetList::PHP_73);
$containerConfigurator->import(DowngradeSetList::PHP_72);
```

So maybe this set is not being executed?

<img width="1141" alt="Screenshot 2021-10-19 at 8 04 51 PM" src="https://user-images.githubusercontent.com/1981996/137905741-e986e788-a28b-4b4d-a5a7-3fe422b31ad9.png">

**Comment by leoloso** [comment]
These screenshots are better.

This works:

<img width="1141" alt="Screenshot 2021-10-19 at 8 14 56 PM" src="https://user-images.githubusercontent.com/1981996/137907212-330d17ab-ddb7-4888-8658-80407f66edba.png">

This fails:

<img width="1141" alt="Screenshot 2021-10-19 at 8 16 48 PM" src="https://user-images.githubusercontent.com/1981996/137907421-e48b27c4-b1e6-4e19-ad7a-a1c0420179ae.png">

**Comment by samsonasik** [comment]
@leoloso demo page updated to latest 0.11.59

**Comment by leoloso** [comment]
The demo is not working: whenever importing `DowngradeSetList::PHP_72`, and also importing `DowngradeLevelSetList::DOWN_TO_PHP_71`, it returns `Rector could not run due to error: Syntax error`:

https://getrector.org/demo/1ec3149c-ef18-6e3e-851d-91d9af543b79

![Screenshot 2021-10-20 at 10-04-24 Try Rector Online Rector - Automated Way to Instantly Upgrade and Refactor any PHP code](https://user-images.githubusercontent.com/1981996/138015998-3b83af6b-5a99-4255-b994-eb7e682f04cd.png)

Importing the other downgrade sets works well, so there must be some issue with `DowngradeSetList::PHP_72`

**Comment by leoloso** [comment]
To reproduce it, I have the impression that any method that receives a typehint might do. Indeed, this issue is happening all over my downgraded code, not in a single file.

The simplified version of the example I'm using is this one:

```php
<?php

declare(strict_types=1);

use Symfony\Contracts\Service\Attribute\Required;

class UserAuthorization
{
    #[Required]
    final public function autowireUserAuthorization(UserAuthorizationSchemeRegistryInterface $userAuthorizationSchemeRegistry): void
    {
        // ...
    }
}
```

That `UserAuthorizationSchemeRegistryInterface` typehint will be removed from the downgraded code. It should not be.

When you use this config, the problem doesn't happen, and there's no `DowngradeParameterTypeWideningRector` being applied:

```php
<?php

use Rector\Set\ValueObject\DowngradeSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(DowngradeSetList::PHP_80);
    $containerConfigurator->import(DowngradeSetList::PHP_74);
    $containerConfigurator->import(DowngradeSetList::PHP_73);
    $containerConfigurator->import(DowngradeSetList::PHP_72);
};
```

If you alter the order of the downgrades, making PHP 8.0 happen after PHP 7.2, then `DowngradeParameterTypeWideningRector` is applied, and `UserAuthorizationSchemeRegistryInterface` is removed:

```php
<?php

use Rector\Set\ValueObject\DowngradeSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(DowngradeSetList::PHP_74);
    $containerConfigurator->import(DowngradeSetList::PHP_73);
    $containerConfigurator->import(DowngradeSetList::PHP_72);
    $containerConfigurator->import(DowngradeSetList::PHP_80);
};
```

The same problem happens when using the new `$containerConfigurator->import(DowngradeLevelSetList::DOWN_TO_PHP_71);`:

```php
<?php

use Rector\Set\ValueObject\DowngradeLevelSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(DowngradeLevelSetList::DOWN_TO_PHP_71);
};
```

**Comment by leoloso** [comment]
In other words, I guess the issue has been solved
