### ISSUE TITLE
Call to a member function getOriginalValues() on string

### ISSUE THREAD

**Issue by bmo-viously** [rectorphp/rector#6782]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 07736c1ab4d45d348d5054625499f10f97d671be             |

When trying to rectorify some doctrine entities, I get this error : `Call to a member function getOriginalValues() on string`.

There is the stacktrace : 
```php
PHP Fatal error:  Uncaught Error: Call to a member function getOriginalValues() on string in /Users/bastien/git/viously-api/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php:221
Stack trace:
#0 /Users/bastien/git/viously-api/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(201): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->addNestedDoctrineTagAndAnnotationToAttribute(Object(Rector\BetterPhpDocParser\PhpDoc\DoctrineAnnotationTagValueNode), Array)
#1 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeVisitor/CallablePhpDocNodeVisitor.php(28): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->Rector\Php80\Rector\Class_\{closure}(Object(Rector\BetterPhpDocParser\PhpDoc\SpacelessPhpDocTagNode), '')
#2 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(152): RectorPrefix20211020\Symplify\SimplePhpDocParser\PhpDocNodeVisitor\CallablePhpDocNodeVisitor->enterNode(Object(Rector\BetterPhpDocParser\PhpDoc\SpacelessPhpDocTagNode))
#3 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(97): RectorPrefix20211020\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseArray(Array)
#4 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(74): RectorPrefix20211020\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#5 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(83): RectorPrefix20211020\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverse(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#6 /Users/bastien/git/viously-api/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(210): RectorPrefix20211020\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseWithCallable(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode), '', Object(Closure))
#7 /Users/bastien/git/viously-api/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(124): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->processDoctrineAnnotationClasses(Object(Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo))
#8 /Users/bastien/git/viously-api/vendor/rector/rector/src/Rector/AbstractRector.php(249): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->refactor(Object(PhpParser\Node\Stmt\Class_))
#9 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))
#10 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#11 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#12 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#13 /Users/bastien/git/viously-api/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(52): PhpParser\NodeTraverser->traverse(Array)
#14 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/FileProcessor.php(54): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#15 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(132): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File))
#16 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(144): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#17 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(133): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), Object(Rector\Core\Enum\ApplicationPhase))
#18 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(91): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File))
#19 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(76): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#20 /Users/bastien/git/viously-api/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#21 /Users/bastien/git/viously-api/vendor/rector/rector/src/Console/Command/ProcessCommand.php(152): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#22 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symfony/console/Command/Command.php(274): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symfony/console/Application.php(870): RectorPrefix20211020\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symfony/console/Application.php(266): RectorPrefix20211020\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/bastien/git/viously-api/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211020\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/bastien/git/viously-api/vendor/rector/rector/vendor/symfony/console/Application.php(162): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#27 /Users/bastien/git/viously-api/vendor/rector/rector/bin/rector.php(63): RectorPrefix20211020\Symfony\Component\Console\Application->run()
#28 /Users/bastien/git/viously-api/vendor/rector/rector/bin/rector(5): require_once('/Users/bastien/...')
#29 {main}
  thrown in /Users/bastien/git/viously-api/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php on line 221
```

FYI, I removed the second parameter from the `Table` annotation (line 10) and rector worked fine.
Not working:
```php
/**
 * UserProduct
 *
 * @ORM\Table(name="user_product", uniqueConstraints={@ORM\UniqueConstraint(name="UX_ID_USER_PRODUCT", columns={"ID_USER_PRODUCT"})})
 * @ORM\Entity
 */
```
Working:
```php
/**
 * UserProduct
 *
 * @ORM\Table(name="user_product")
 * @ORM\Entity
 */
```

It seems that rector fails on nested annotations.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec3cb33-06dd-66b2-93a9-d1fa45c98df0

## Expected Behaviour
I think rector should ignore nested annotations (and maybe trigger a warning).
Also, I think rector should still process the rest of the file to convert valid annotations to attributes.

**Comment by samsonasik** [comment]
This should already fixed at https://github.com/rectorphp/rector-src/pull/1099

Please try latest `"rector/rector": "dev-main"`
