### ISSUE TITLE
Rector is broken (BetterReflection problem)

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector#6857]
PHPStan\BetterReflection\Reflection\ReflectionClass "AutoMapperPlus\AutoMapperPlusBundle\AutoMapperConfiguratorInterface" could not be found in the located source

![image](https://user-images.githubusercontent.com/25783196/145679659-a1b9aeee-8532-4e4e-a7bb-dcdcb1c237ae.png)

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.7             |

This message means absolutely nothing. What located source? I can't even debug this  because rector uses phpstan.phar.
I'm using rector via composer-bin. 
PHP 8.0

I did add this:
```php
    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/vendor/autoload.php',
    ]);
```
and I am running rector from project root dir.

Additional info:
Error happens in line 47 `ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47)` however this file https://github.com/ondrejmirtes/BetterReflection/blob/master/src/Reflector/ClassReflector.php shows that it can happen in line 55. 

<details>
  <summary>Output from rector with --debug option</summary>
  
```sh
PHP Fatal error:  Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "AutoMapperPlus\AutoMapperPlusBundle\AutoMapperConfiguratorInterface" could not be found in the located source in phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(PHPStan\BetterReflection\Identifier\Identifier))
#1 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(25): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('AutoMapperPlus\\...')
#2 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(767): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('AutoMapperPlus\\...')
#3 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(1052): PHPStan\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode(Object(PhpParser\Node\Name\FullyQualified))
#4 [internal function]: PHPStan\BetterReflection\Reflection\ReflectionClass->PHPStan\BetterReflection\Reflection\{closure}(Object(PhpParser\Node\Name\FullyQualified))
#5 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(1053): array_map(Object(Closure), Array)
#6 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(922): PHPStan\BetterReflection\Reflection\ReflectionClass->getCurrentClassImplementedInterfacesIndexedByName()
#7 [internal function]: PHPStan\BetterReflection\Reflection\ReflectionClass::PHPStan\BetterReflection\Reflection\{closure}(Object(PHPStan\BetterReflection\Reflection\ReflectionClass))
#8 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(923): array_map(Object(Closure), Array)
#9 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionClass.php(258): PHPStan\BetterReflection\Reflection\ReflectionClass->getInterfaces()
#10 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(510): PHPStan\BetterReflection\Reflection\Adapter\ReflectionClass->getInterfaces()
#11 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(463): PHPStan\Reflection\ClassReflection->getImmediateInterfaces()
#12 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(226): PHPStan\Reflection\ClassReflection->getInterfaces()
#13 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(204): PHPStan\PhpDoc\PhpDocBlock::getParentReflections(Object(PHPStan\Reflection\ClassReflection))
#14 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(172): PHPStan\PhpDoc\PhpDocBlock::resolveParentPhpDocBlocks(Object(PHPStan\Reflection\ClassReflection), 'configure', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', true, Array)
#15 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(154): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockTree('/**\n     * {@in...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', '/app/src/AutoMa...', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', NULL, Array, Array)
#16 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(37): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockForMethod('/**\n     * {@in...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', '/app/src/AutoMa...', NULL, Array, Array)
#17 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3004): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod('/**\n     * {@in...', '/app/src/AutoMa...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', Array)
#18 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(373): PHPStan\Analyser\NodeScopeResolver->getPhpDocs(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Stmt\ClassMethod))
#19 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#20 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(502): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#21 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#22 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(468): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#23 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(221): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#24 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(152): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#25 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(144): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20211209\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#26 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(63): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20211209\Symplify\SmartFileSystem\SmartFileInfo))
#27 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#28 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(153): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#29 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(87): Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObject\Application\File))
#30 /app/vendor-bin/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#31 /app/vendor-bin/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(74): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#32 /app/vendor-bin/rector/vendor/rector/rector/src/Console/Command/ProcessCommand.php(165): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#33 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Command/Command.php(296): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#34 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(897): RectorPrefix20211209\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#35 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(300): RectorPrefix20211209\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#36 /app/vendor-bin/rector/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211209\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#37 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(196): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#38 /app/vendor-bin/rector/vendor/rector/rector/bin/rector.php(56): RectorPrefix20211209\Symfony\Component\Console\Application->run()
#39 /app/vendor-bin/rector/vendor/rector/rector/bin/rector(5): require_once('/app/vendor-bin...')
#40 {main}
  thrown in phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
Fatal error: Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "AutoMapperPlus\AutoMapperPlusBundle\AutoMapperConfiguratorInterface" could not be found in the located source in phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(PHPStan\BetterReflection\Identifier\Identifier))
#1 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(25): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('AutoMapperPlus\\...')
#2 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(767): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('AutoMapperPlus\\...')
#3 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(1052): PHPStan\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode(Object(PhpParser\Node\Name\FullyQualified))
#4 [internal function]: PHPStan\BetterReflection\Reflection\ReflectionClass->PHPStan\BetterReflection\Reflection\{closure}(Object(PhpParser\Node\Name\FullyQualified))
#5 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(1053): array_map(Object(Closure), Array)
#6 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(922): PHPStan\BetterReflection\Reflection\ReflectionClass->getCurrentClassImplementedInterfacesIndexedByName()
#7 [internal function]: PHPStan\BetterReflection\Reflection\ReflectionClass::PHPStan\BetterReflection\Reflection\{closure}(Object(PHPStan\BetterReflection\Reflection\ReflectionClass))
#8 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(923): array_map(Object(Closure), Array)
#9 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionClass.php(258): PHPStan\BetterReflection\Reflection\ReflectionClass->getInterfaces()
#10 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(510): PHPStan\BetterReflection\Reflection\Adapter\ReflectionClass->getInterfaces()
#11 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(463): PHPStan\Reflection\ClassReflection->getImmediateInterfaces()
#12 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(226): PHPStan\Reflection\ClassReflection->getInterfaces()
#13 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(204): PHPStan\PhpDoc\PhpDocBlock::getParentReflections(Object(PHPStan\Reflection\ClassReflection))
#14 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(172): PHPStan\PhpDoc\PhpDocBlock::resolveParentPhpDocBlocks(Object(PHPStan\Reflection\ClassReflection), 'configure', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', true, Array)
#15 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(154): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockTree('/**\n     * {@in...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', '/app/src/AutoMa...', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', NULL, Array, Array)
#16 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(37): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockForMethod('/**\n     * {@in...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', '/app/src/AutoMa...', NULL, Array, Array)
#17 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3004): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod('/**\n     * {@in...', '/app/src/AutoMa...', Object(PHPStan\Reflection\ClassReflection), NULL, 'configure', Array)
#18 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(373): PHPStan\Analyser\NodeScopeResolver->getPhpDocs(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Stmt\ClassMethod))
#19 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#20 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(502): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#21 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#22 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(468): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#23 phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(221): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#24 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(152): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#25 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(144): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20211209\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#26 /app/vendor-bin/rector/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(63): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20211209\Symplify\SmartFileSystem\SmartFileInfo))
#27 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#28 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(153): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#29 /app/vendor-bin/rector/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(87): Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObject\Application\File))
#30 /app/vendor-bin/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(96): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#31 /app/vendor-bin/rector/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(74): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#32 /app/vendor-bin/rector/vendor/rector/rector/src/Console/Command/ProcessCommand.php(165): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#33 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Command/Command.php(296): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#34 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(897): RectorPrefix20211209\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#35 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(300): RectorPrefix20211209\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#36 /app/vendor-bin/rector/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211209\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#37 /app/vendor-bin/rector/vendor/rector/rector/vendor/symfony/console/Application.php(196): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211209\Symfony\Component\Console\Output\ConsoleOutput))
#38 /app/vendor-bin/rector/vendor/rector/rector/bin/rector.php(56): RectorPrefix20211209\Symfony\Component\Console\Application->run()
#39 /app/vendor-bin/rector/vendor/rector/rector/bin/rector(5): require_once('/app/vendor-bin...')
#40 {main}
  thrown in phar:///app/vendor-bin/rector/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
```
</details>

**Comment by javaDeveloperKid** [comment]
I've just dug out this comment https://github.com/rectorphp/rector/issues/303#issuecomment-372870425
and installed rector/rector in my root vendor (depends only on phpstan which depends on nothing so no dependency issues). And it worked.
I think this should be mentioned in the README file, because this caused me a few hours to debug.

PS. Does rector have phar distribution? I saw you dropped docker images, but can't find anything about PHAR whether it was also dropped or is still maintained.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

> I think this should be mentioned in the README file, because this caused me a few hours to debug.

Could you send PR to update README with wording that would help you?

> PS. Does rector have phar distribution? I saw you dropped docker images, but can't find anything about PHAR whether it was also dropped or is still maintained.

The phar was not making sense and made debugging of changes impossible, so we dropped in Rector 0.9:  https://getrector.org/blog/2020/12/28/rector-09-released

The best way to install Rector is like PHPUnit and PHPStan:

```bash
composer require rector/rector --dev
```

That way you don't have to include `__DIR__ . '/vendor/autoload.php'` as it loads it by composer. And it has access to all existing classes of your projects.

**Comment by TomasVotruba** [comment]
I just saw "composer-bin". That does not make sense for Rector, as Rector is already scoped :). 
Most of bug reports related to such autoloading is actually caused by this plugin. I wish there way to warn about it in runtime.

**Comment by javaDeveloperKid** [comment]
>The best way to install Rector is like PHPUnit and PHPStan
For Rector and PHPStan yes, for PHPUnit it's better to use symfony/phpunit-bridge as PHPUnit has dependencies so if possible let's keep them out of project's dependencies.

PS. PR with README change will come shortly.

**Comment by TomasVotruba** [comment]
>  it's better to use symfony/phpunit-bridge as PHPUnit has dependencies so if possible let's keep them out of project's dependencies.

There is 5 more issues here about bugs with autoloading of PHPUnit bridge package, as it kills native PHPUnit autoload. I recommend using phpunit natively, unless you need to support PHPUnit on PHP 7 without `void`.
