### ISSUE TITLE
[PHPStan][ReflectionClass] could not be found in the located source

### ISSUE THREAD

**Issue by guelosuperstart** [rectorphp/rector#6866]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.60 (`07736c1ab4d45d348d5054625499f10f97d671be`)             |
| php version | 8.0.13            |
| SF version | 5.4            |
| PHPSTAN version | 0.12.99           |

[ERROR] Could not process "src/Entity/Customer/Alert/SettingTranslation.php" file, due to:                             
         "PHPStan\BetterReflection\Reflection\ReflectionClass "App\Entity\Customer\AbstractTranslation" could not be    
         found in the located source". On line: 24          

## Error
[ERROR] Could not process "src/Entity/Customer/Alert/SettingTranslation.php" file, due to:"PHPStan\BetterReflection\Reflection\ReflectionClass "App\Entity\Customer\AbstractTranslation" could not be found in the located source". On line: 24

## Error log

```
[parsing] src/Entity/Customer/Alert/SettingTranslation.php
[13-Dec-2021 13:08:02 UTC] PHP Fatal error:  Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "App\Entity\Customer\AbstractTranslation" could not be found in the located source in phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(PHPStan\BetterReflection\Identifier\Identifier))
#1 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('App\\Entity\\Cust...')
#2 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(649): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('App\\Entity\\Cust...')
#3 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionClass.php(368): PHPStan\BetterReflection\Reflection\ReflectionClass->getParentClass()
#4 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(170): PHPStan\BetterReflection\Reflection\Adapter\ReflectionClass->getParentClass()
#5 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(222): PHPStan\Reflection\ClassReflection->getParentClass()
#6 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(204): PHPStan\PhpDoc\PhpDocBlock::getParentReflections(Object(PHPStan\Reflection\ClassReflection))
#7 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(172): PHPStan\PhpDoc\PhpDocBlock::resolveParentPhpDocBlocks(Object(PHPStan\Reflection\ClassReflection), '__construct', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', false, Array)
#8 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(154): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockTree(NULL, Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', '/var/www/feedba...', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', NULL, Array, Array)
#9 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(37): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockForMethod(NULL, Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', '/var/www/feedba...', NULL, Array, Array)
#10 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2940): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod(NULL, '/var/www/feedba...', Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', Array)
#11 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(379): PHPStan\Analyser\NodeScopeResolver->getPhpDocs(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Stmt\ClassMethod))
#12 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(259): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#13 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(508): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#14 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(259): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(474): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(227): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(155): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(143): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithMixinHandling(Object(RectorPrefix20211020\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(81): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20211020\Symplify\SmartFileSystem\SmartFileInfo))
#20 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#21 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(80): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#22 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(144): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#23 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(81): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), Object(Rector\Core\Enum\ApplicationPhase))
#24 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(76): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Console/Command/ProcessCommand.php(152): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#27 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Command/Command.php(274): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(870): RectorPrefix20211020\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(266): RectorPrefix20211020\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211020\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(162): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/feedback/api-feedback-v2/vendor/rector/rector/bin/rector.php(63): RectorPrefix20211020\Symfony\Component\Console\Application->run()
#33 /var/www/feedback/api-feedback-v2/vendor/rector/rector/bin/rector(5): require_once('/var/www/feedba...')
#34 {main}
  thrown in phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
Fatal error: Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "App\Entity\Customer\AbstractTranslation" could not be found in the located source in phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(PHPStan\BetterReflection\Identifier\Identifier))
#1 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('App\\Entity\\Cust...')
#2 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(649): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('App\\Entity\\Cust...')
#3 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionClass.php(368): PHPStan\BetterReflection\Reflection\ReflectionClass->getParentClass()
#4 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(170): PHPStan\BetterReflection\Reflection\Adapter\ReflectionClass->getParentClass()
#5 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(222): PHPStan\Reflection\ClassReflection->getParentClass()
#6 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(204): PHPStan\PhpDoc\PhpDocBlock::getParentReflections(Object(PHPStan\Reflection\ClassReflection))
#7 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(172): PHPStan\PhpDoc\PhpDocBlock::resolveParentPhpDocBlocks(Object(PHPStan\Reflection\ClassReflection), '__construct', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', false, Array)
#8 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(154): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockTree(NULL, Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', '/var/www/feedba...', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', NULL, Array, Array)
#9 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanceResolver.php(37): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockForMethod(NULL, Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', '/var/www/feedba...', NULL, Array, Array)
#10 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2940): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod(NULL, '/var/www/feedba...', Object(PHPStan\Reflection\ClassReflection), NULL, '__construct', Array)
#11 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(379): PHPStan\Analyser\NodeScopeResolver->getPhpDocs(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Stmt\ClassMethod))
#12 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(259): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#13 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(508): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#14 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(259): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(474): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(227): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(155): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(143): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithMixinHandling(Object(RectorPrefix20211020\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 /var/www/feedback/api-feedback-v2/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(81): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20211020\Symplify\SmartFileSystem\SmartFileInfo))
#20 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#21 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(80): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#22 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(144): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#23 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(81): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), Object(Rector\Core\Enum\ApplicationPhase))
#24 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(76): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Console/Command/ProcessCommand.php(152): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#27 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Command/Command.php(274): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(870): RectorPrefix20211020\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(266): RectorPrefix20211020\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/feedback/api-feedback-v2/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211020\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/symfony/console/Application.php(162): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211020\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211020\Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/feedback/api-feedback-v2/vendor/rector/rector/bin/rector.php(63): RectorPrefix20211020\Symfony\Component\Console\Application->run()
#33 /var/www/feedback/api-feedback-v2/vendor/rector/rector/bin/rector(5): require_once('/var/www/feedba...')
#34 {main}
  thrown in phar:///var/www/feedback/api-feedback-v2/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 24
```

## code

```php
<?php

declare(strict_types=1);

namespace App\Entity\Customer\Alert;

use App\Entity\Customer\AbstractTranslation;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'table')]
class SettingTranslation extends AbstractTranslation
{
}

```

```php
<?php

declare(strict_types=1);

namespace App\Entity\Customer;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation;
use Symfony\Component\Serializer\Annotation\Groups;

/** @SuppressWarnings(PHPMD.ShortVariable) */
#[ORM\MappedSuperclass]
abstract class AbstractTranslation extends AbstractPersonalTranslation
{
}

```

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);
    $containerConfigurator->import(SetList::PHP_74);
    $containerConfigurator->import(SetList::PHP_80);
    $containerConfigurator->import(SetList::DEAD_CODE);
    $containerConfigurator->import(SetList::CODE_QUALITY);
    $containerConfigurator->import(SetList::CODING_STYLE);
    $containerConfigurator->import(SetList::CODING_STYLE_ADVANCED);
    $containerConfigurator->import(DoctrineSetList::DOCTRINE_CODE_QUALITY);
    $containerConfigurator->import(DoctrineSetList::DOCTRINE_DBAL_30);
    $containerConfigurator->import(SymfonySetList::SYMFONY_52);
    $containerConfigurator->import(SymfonySetList::SYMFONY_50_TYPES);
    $containerConfigurator->import(SymfonySetList::SYMFONY_50);
    $containerConfigurator->import(SymfonySetList::SYMFONY_CODE_QUALITY);
    $containerConfigurator->import(SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION);
    $containerConfigurator->import(SymfonySetList::SYMFONY_52_VALIDATOR_ATTRIBUTES);
};
```

Thank you for your help ;)

**Comment by samsonasik** [comment]
You may need to register to "files" in autoload in composer.json, please check the doc for it https://github.com/rectorphp/rector/blob/main/docs/static_reflection_and_autoload.md#dealing-with-class--was-not-found-while-trying-to-analyse-it

**Comment by guelosuperstart** [comment]
Hello @samsonasik,

Thank you for your reply.

it's working well with your advice 👌 

i added this code : 

```php
    $parameters->set(Option::AUTOLOAD_PATHS, [
        __DIR__ . '/src/Entity/Customer/AbstractTranslation.php',
        __DIR__ . '/vendor/gedmo/doctrine-extensions/src/Translatable/Entity',
    ]);
```

it's a bit difficult/overkill if I have to add each file/directory to my rector conf no ?

**Comment by samsonasik** [comment]
indeed, but PHPStan may late on load file, so that's the workaround for now I think.

**Comment by TomasVotruba** [comment]
@guelosuperstart This should work out of the box as project's `vendor/autoload.php` is loaded :thinking:  Could you share your repository with minimal reproducible code?

**Comment by guelosuperstart** [comment]
@samsonasik, it's possible
In my application, PHPStan(level 5) works well :/, so it's for why i didn't understand why it doesn't work with rector ^^

**Comment by samsonasik** [comment]
@guelosuperstart ok, I am closing it as answered.

**Comment by guelosuperstart** [comment]
@samsonasik 
Before closing this issue, I will try to update rector to version 0.12.7 and try to run rector without the workaround to see if the problem no longer exists.

At the moment, i was blocker to rector ^0.11.60 and phpstan to ^0.12.99 :/

I didn't notice that I was blocked on the non-blocking versions

i'm going to tell you quicky if I no longer have the problem

**Comment by samsonasik** [comment]
@guelosuperstart ok, re-open

**Comment by guelosuperstart** [comment]
Hello @samsonasik, @TomasVotruba 

So, With Recto ^0.12.7 and PHPStan ^1.2.0, everything is ok 👌  without the workaround.

However, sometimes i have a mistake with this rule `$containerConfigurator->import(SetList::TYPE_DECLARATION);` :/  :

```
Cannot create PHPStan\Type\UnionType with: string|null, string, string
```

<details>
  <summary>error stack!</summary>
  

</details>

it's a know mistake ? Did you get this mistake ?

I have a last question :-)

if i use this rule `$containerConfigurator->import(SetList::TYPE_DECLARATION_STRICT);`, i have to use this rule `$containerConfigurator->import(SetList::TYPE_DECLARATION);` too ?

And this code : 

```php
    $containerConfigurator->import(SetList::PHP_74);
    $containerConfigurator->import(SetList::PHP_80);
    $containerConfigurator->import(SymfonySetList::SYMFONY_50_TYPES);
    $containerConfigurator->import(SymfonySetList::SYMFONY_50);
    $containerConfigurator->import(SymfonySetList::SYMFONY_52);
    $containerConfigurator->import(SymfonySetList::SYMFONY_52_VALIDATOR_ATTRIBUTES);
    $containerConfigurator->import(SymfonySetList::SYMFONY_53);
    $containerConfigurator->import(SymfonySetList::SYMFONY_54);
```

can be only : 

```php
    $containerConfigurator->import(SetList::PHP_80);
    $containerConfigurator->import(SymfonySetList::SYMFONY_54);
```

Thank you to both for your advice

**Comment by samsonasik** [comment]
That's probably same with issue https://github.com/rectorphp/rector/issues/6875 .

You can narrow rules one by one or half by half to get the rule that cause it.

You can check the constants, and see the list of the services to compare what different between rule set.

**Comment by samsonasik** [comment]
I am closing it as the solution provided, the issue answered as possibly resolved at `"rector/rector": "dev-main"` already. 

Feel free to create failing test case if you found a bug.

**Comment by DaveLiddament** [comment]
I seem to have a similar problem. I've used PHPStan 1.2. I've tried rector 0.12.7, 0.12.8 and dev-main. All give me errors similar to this: 

```
[ERROR] Could not process                                                                                              
         "tests/AppBundle/Helpers/Mocks/OutboundMessageService/MockSingleMessageForTeamOutboundMessageService.php" file,
         due to:                                                                                                        
         "PHPStan\BetterReflection\Reflection\ReflectionClass                                                           
         "AppBundle\HuntEngine\BusinessLogic\OutboundMessage\OutboundMessageServiceInterface" could not be found in the 
         located source". On line: 24                
```


The key problem being `PHPStan\BetterReflection\Reflection\ReflectionClass` and `On line: 24`


I am using composer-bin if that helps diagnose the problem?

**Comment by Koricz** [comment]
Hi,

I have similar issue. The problem is only with interfaces, e.g. IStatement, IDatabaseConnection, etc.
