### ISSUE TITLE
Test suite exhausts file descriptors

### ISSUE THREAD

**Issue by jtojnar** [rectorphp/rector#6904]
# Bug Report

Running `vendor/bin/phpunit` in the main branch of https://github.com/rectorphp/rector-src, I eventually reach the soft file descriptor limit of 1024, making all the test to fail:

```bash
............................................................. 1281 / 3866 ( 33%)
...........................................EEE
Warning: include(/home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): Failed to open stream: Too many open files in /home/jtojnar/Projects/rector-src/vendor/composer/ClassLoader.php on line 571

Warning: include(): Failed opening '/home/jtojnar/Projects/rector-src/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/nix/store/h2gghwnw476q8ibp6a7wyqnzcvrwcs8j-php-8.1.1/lib/php') in /home/jtojnar/Projects/rector-src/vendor/composer/ClassLoader.php on line 571
E
```

Even if I increase it significantly using `ulimit -Sn 16384`, it still only delays the failure.

I tried closing some open processes (https://github.com/symfony/symfony/pull/44882, https://github.com/squizlabs/PHP_CodeSniffer/pull/3523) but to no avail

Running `lsof +E -p $(pidof php)` repeatedly reveals there are new pseudoterminals opened every second, hundreds of them:

```nc
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
[…]
.php-wrap 92064 jtojnar    0u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    1u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    2u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    3r   REG  254,2     2342 22683967 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/phpunit
.php-wrap 92064 jtojnar    4u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    5u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    6u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    7u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    8u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar    9u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   10u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   11u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   12u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   13u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   14u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   15u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   16u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   17u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   18u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   19u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   20u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
.php-wrap 92064 jtojnar   21u   CHR  136,1      0t0        4 /dev/pts/1 4716,.gnome-te,16u
[…]
```

I am using PHP 8.1.1 on NixOS.

**Comment by jtojnar** [comment]
I can no longer reproduce this to the same degree in a new environment. The resource leak still exists but running `lsof` in the loop now shows maximum of 2574 open descriptors.

**Comment by samsonasik** [comment]
Run tests once for all seems will take long time, you can run only on test class that related with changes, or run per-directory tests, ref

https://github.com/rectorphp/rector-src/blob/34c61ba4498150972db843fca807416540ca71e8/.github/workflows/tests.yaml#L20

You may also try with paratest, ref

https://github.com/rectorphp/rector-src/blob/34c61ba4498150972db843fca807416540ca71e8/.github/workflows/tests.yaml#L36

**Comment by jtojnar** [comment]
Running `strace -o strace.log -yy -s 1000 -f vendor/bin/phpunit` and `grep`ing the log for `/dev/pts` reveals the file descriptors originate like this:

```
4438299:501924 dup(1</dev/pts/5<char 136:5>>)   = 776</dev/pts/5<char 136:5>>
4438300:501924 newfstatat(776</dev/pts/5<char 136:5>>, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x5), ...}, AT_EMPTY_PATH) = 0
4438301:501924 newfstatat(776</dev/pts/5<char 136:5>>, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x5), ...}, AT_EMPTY_PATH) = 0
4438302:501924 ioctl(776</dev/pts/5<char 136:5>>, TCGETS, {B38400 opost isig icanon echo ...}) = 0
```

**Comment by jtojnar** [comment]
I ran `gdb -p $(pidof php)` after some time, which attached a debugger. In it, I ran `catch syscall dup` to stop at that syscall. Then I ran `continue` a few times to see how often it is duplicated. Then I used `backtrace` to find out what functions are responsible:

```
#0  0x00007ff6455869e7 in dup () at ../sysdeps/unix/syscall-template.S:120
#1  0x000000000077191a in php_stream_url_wrap_php (wrapper=0xddc3c0 <php_stream_php_wrapper>, path=0x7ff64511ff46 "stdout", mode=0x27b7028 "w", options=0, opened_path=0x0, context=<optimized out>)
    at /build/php-8.1.1/ext/standard/php_fopen_wrapper.c:271
#2  0x00000000007a45cc in _php_stream_open_wrapper_ex (path=path@entry=0x7ff64511ff40 "php://stdout", mode=mode@entry=0x27b7028 "w", options=<optimized out>, opened_path=opened_path@entry=0x0, 
    context=0x7ff64506ec40) at /build/php-8.1.1/main/streams/streams.c:2080
#3  0x00000000007270b7 in zif_fopen (execute_data=<optimized out>, return_value=0x7ff64501c890) at /build/php-8.1.1/ext/standard/file.c:888
#4  0x00000000006b0da2 in phar_fopen (execute_data=0x7ff64501c8c0, return_value=0x7ff64501c890) at /build/php-8.1.1/ext/phar/func_interceptors.c:430
#5  0x0000000000862191 in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /build/php-8.1.1/Zend/zend_vm_execute.h:1558
#6  execute_ex (ex=0x1) at /build/php-8.1.1/Zend/zend_vm_execute.h:54543
#7  0x0000000000864b58 in zend_execute (op_array=0x7ff64508f100, return_value=0x0) at /build/php-8.1.1/Zend/zend_vm_execute.h:58882
#8  0x00000000007f5ec2 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /build/php-8.1.1/Zend/zend.c:1761
#9  0x000000000078c9a7 in php_execute_script (primary_file=primary_file@entry=0x7ffd6260b8a0) at /build/php-8.1.1/main/main.c:2534
#10 0x00000000008db3e2 in do_cli (argc=2, argv=0x27a6bb0) at /build/php-8.1.1/sapi/cli/php_cli.c:965
#11 0x0000000000638d6c in main (argc=2, argv=0x27a6bb0) at /build/php-8.1.1/sapi/cli/php_cli.c:1367
```

**Comment by jtojnar** [comment]
This is definitely either symfony/console or simplify bug:

```
#0 /home/jtojnar/Projects/rector-src/vendor/symfony/console/Output/ConsoleOutput.php(42): Symfony\Component\Console\Output\ConsoleOutput->openOutputStream()
#1 /home/jtojnar/Projects/rector-src/vendor/symplify/package-builder/src/Console/Style/SymfonyStyleFactory.php(35): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#2 /home/jtojnar/Projects/rector-src/src/DependencyInjection/Collector/ConfigureCallValuesCollector.php(30): Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory->create()
#3 /home/jtojnar/Projects/rector-src/src/Kernel/RectorKernel.php(35): Rector\Core\DependencyInjection\Collector\ConfigureCallValuesCollector->__construct()
#4 /home/jtojnar/Projects/rector-src/packages/Testing/PHPUnit/AbstractTestCase.php(38): Rector\Core\Kernel\RectorKernel->__construct()
#5 /home/jtojnar/Projects/rector-src/tests/Application/ApplicationFileProcessor/ApplicationFileProcessorTest.php(24): Rector\Testing\PHPUnit\AbstractTestCase->bootFromConfigFiles(Array)
#6 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestCase.php(1144): Rector\Core\Tests\Application\ApplicationFileProcessor\ApplicationFileProcessorTest->setUp()
#7 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestResult.php(726): PHPUnit\Framework\TestCase->runBare()
#8 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\Framework\TestResult->run(Object(Rector\Core\Tests\Application\ApplicationFileProcessor\ApplicationFileProcessorTest))
#9 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#10 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(670): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#14 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#15 /home/jtojnar/Projects/rector-src/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
```

**Comment by jtojnar** [comment]
It was fixed on symfony side by https://github.com/symfony/symfony/pull/45053.

**Comment by TomasVotruba** [comment]
Thank you :+1: 

How can we update our code to use it?

**Comment by jtojnar** [comment]
It should be included in the next symfony release. Looking at the [release cadence](https://symfony.com/doc/current/contributing/community/releases.html) and [last release date](https://github.com/symfony/console/releases/tag/v6.0.2), I would expect 6.0.3 any day now.

**Comment by jtojnar** [comment]
Looks like repo already updated to 6.0.3: https://github.com/rectorphp/rector/commit/28f8cfafaf9b19934ed2af2a85bfb9335617bdfe
