### ISSUE TITLE
Crash when using psalm with Rector

### ISSUE THREAD

**Issue by leighman** [rectorphp/rector#6951]
# Bug Report

Not sure if this is a psalm issue or rector but it did work and breaks when updating from rector `0.11.52` to `0.12.12`.

When I run psalm I get the following error:
```
> Composer\Config::disableProcessTimeout
> psalm --config=psalm-ci.xml --no-cache
Scanning files...
Uncaught RuntimeException: PHP Error: Class 'RectorPrefix20220107\Attribute' not found in /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php:23 in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php(23): class_alias()
#2 /var/www/html/vendor/composer/ClassLoader.php(476): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 [internal function]: spl_autoload_call()
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(385): class_exists()
#7 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(344): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::functionEvaluatesToTrue()
#8 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(288): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#9 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(294): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#10 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(294): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#11 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(297): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#14 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse()
#15 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(579): Psalm\Internal\Scanner\FileScanner->scan()
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(330): Psalm\Internal\Codebase\Scanner->scanFile()
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(449): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(294): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#19 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(473): Psalm\Internal\Codebase\Scanner->scanFiles()
#20 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(594): Psalm\Codebase->scanFiles()
#21 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(360): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#22 /var/www/html/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run()
#23 {main}
(Psalm 4.13.1@5cf660f63b548ccd4a56f62d916ee4d6028e01a3 crashed due to an uncaught Throwable)
Script psalm --config=psalm-ci.xml --no-cache handling the psalm event returned with error code 1
```

Psalm config has
```
        <ignoreFiles>
          <directory name="vendor/rector" />
        </ignoreFiles>
```
so I wouldn't even expect the situation.

Any pointers? Not that familiar with the RectorPrefix stuff.

**Comment by samsonasik** [comment]
That's possibly psalm issue if the `vendor/rector` already ignored. The `"rector/rector": "dev-main"` now support global installation, you can try remove local project rector dependency and use global rector instead:

```bash
# install global dev-main version with pinned commit hash as no release for global installation support yet
# you can use pinned version when next rector released
composer global require --dev rector/rector:dev-main#c4b2af01d7d9e5131a78853e1574abf29e880a7b

# remove rector from local installation
composer remove rector/rector

# try if rector is working ok
rector process --dry-run

# try if psalm is working ok
psalm --config=psalm-ci.xml --no-cache
```

**Comment by leighman** [comment]
It seems to be specifically a problem with `RectorPrefix20220107\Attribute` since I commented out various things in `rector.php` and even via different rules it fails on that class

**Comment by leighman** [comment]
https://github.com/vimeo/psalm/issues/7458

**Comment by samsonasik** [comment]
for return type `: string` bring from parent, it seems needs new DowngradePhp80 rector rule as it only error in php 7.x when parent has return type and child has no return type, ref https://3v4l.org/N6kmu

**Comment by samsonasik** [comment]
when method name is not `__toString()`, eg: `foo()`, it seems error even on php 8.x https://3v4l.org/cnOAH,

 So the issue possibly happen on `__toString()` method.

**Comment by samsonasik** [comment]
@leighman it should be fixed in latest `"rector/rector": "dev-main"`, ref  https://github.com/rectorphp/rector/commit/3ebcd0c7baab406140e4f797d18646d722746df2#diff-be08106ae719ccbdbdb5bc47abffc854c9050d8a40c87b2e0187ae014bf1702d 

please give it a try.

```bash
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```

**Comment by leighman** [comment]
Looking good, thank you :pray:

**Comment by samsonasik** [comment]
@leighman thank you for verify, I am closing it then ;)
