### ISSUE TITLE
Symfony set doesn't work without phpunit

### ISSUE THREAD

**Issue by xorik** [rectorphp/rector#6999]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.16             |

Hi. I have a typical symfony 5.4 project. But I don't have full phpunit package, just `/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php` (I think it's default since a while in symfony).

I want to update symfony to 6.0 so I've created a rector.php file:
```php
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Symfony\Set\SymfonyLevelSetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_60);
    $containerConfigurator->parameters()->set(Option::AUTO_IMPORT_NAMES, true);
    $containerConfigurator->parameters()->set(Option::IMPORT_SHORT_CLASSES, false);
    $containerConfigurator->parameters()->set(Option::APPLY_AUTO_IMPORT_NAMES_ON_CHANGED_FILES_ONLY, true);
};
```
And when I run it, it fails:
```
 $ ./vendor/bin/rector process src/ --debug
[parsing] src/Command/CloudflareCommand.php
[refactoring] src/Command/CloudflareCommand.php
    [applying] Rector\Renaming\Rector\Name\RenameClassRector
    [applying] Rector\Php80\Rector\Class_\AnnotationToAttributeRector
    [applying] Rector\Renaming\Rector\PropertyFetch\RenamePropertyRector
    [applying] Rector\Symfony\Rector\Class_\LogoutHandlerToLogoutEventSubscriberRector
    [applying] Rector\Symfony\Rector\Class_\LogoutSuccessHandlerToLogoutEventSubscriberRector
    [applying] Rector\Renaming\Rector\String_\RenameStringRector
    [applying] Rector\Symfony\Rector\ClassConstFetch\ConsoleExceptionToErrorEventConstantRector
    [applying] Rector\TypeDeclaration\Rector\ClassMethod\AddReturnTypeDeclarationRector
    [applying] Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector
    [applying] Rector\Renaming\Rector\MethodCall\RenameMethodRector
    [applying] Rector\Symfony\Rector\ClassMethod\RouteCollectionBuilderToRoutingConfiguratorRector
    [applying] Rector\Symfony\Rector\ClassMethod\ConsoleExecuteReturnIntRector
    [applying] Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector
    [applying] Rector\DependencyInjection\Rector\ClassMethod\AddMethodParentCallRector
    [applying] Rector\Visibility\Rector\ClassMethod\ChangeMethodVisibilityRector
    [applying] Rector\Transform\Rector\ClassMethod\WrapReturnRector
    [applying] Rector\Arguments\Rector\ClassMethod\ReplaceArgumentDefaultValueRector
    [applying] Rector\Removing\Rector\ClassMethod\ArgumentRemoverRector
    [applying] Rector\Symfony\Rector\ClassMethod\MergeMethodAnnotationToRouteAnnotationRector
    [applying] Rector\Symfony\Rector\ClassMethod\GetRequestRector
    [applying] Rector\Symfony\Rector\ClassMethod\FormTypeGetParentRector
    [applying] Rector\Symfony\Rector\ClassMethod\RemoveDefaultGetBlockPrefixRector
    [applying] Rector\Symfony\Rector\StaticCall\BinaryFileResponseCreateToNewInstanceRector
    [applying] Rector\Transform\Rector\StaticCall\StaticCallToNewRector
    [applying] Rector\Symfony\Rector\StaticCall\ProcessBuilderInstanceRector
    [applying] Rector\Symfony\Rector\StaticCall\ParseFileRector
    [applying] Rector\Symfony\Rector\MethodCall\GetHelperControllerToServiceRector
    [applying] Rector\Symfony\Rector\MethodCall\ReflectionExtractorEnableMagicCallExtractorRector
    [applying] Rector\Symfony\Rector\MethodCall\DefinitionAliasSetPrivateToSetPublicRector
    [applying] Rector\Symfony\Rector\MethodCall\FormBuilderSetDataMapperRector
    [applying] Rector\Symfony\Rector\MethodCall\ValidatorBuilderEnableAnnotationMappingRector
    [applying] Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector
PHP Fatal error:  Uncaught PHPStan\Broker\ClassAutoloadingException: Class PHPUnit\Framework\TestCase not found. in phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php:185
Stack trace:
#0 project/vendor/symfony/framework-bundle/Test/KernelTestCase.php(25): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->PHPStan\Reflection\Runtime\{closure}('PHPUnit\\Framewo...')
#1 project/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include('/Users/...')
#2 project/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/...')
#3 project/vendor/symfony/framework-bundle/Test/WebTestCase.php(22): Composer\Autoload\ClassLoader->loadClass('Symfony\\Bundle\\...')
#4 project/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include('/Users/...')
#5 project/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Bundle\\...')
#7 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php(189): class_exists('Symfony\\Bundle\\...')
#8 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ClassBlacklistReflectionProvider.php(51): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->hasClass('Symfony\\Bundle\\...')
#9 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(32): PHPStan\Reflection\ReflectionProvider\ClassBlacklistReflectionProvider->hasClass('Symfony\\Bundle\\...')
#10 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(34): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('Symfony\\Bundle\\...')
#11 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(567): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('Symfony\\Bundle\\...')
#12 project/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php(131): PHPStan\Reflection\ClassReflection->isSubclassOf('Symfony\\Bundle\\...')
#13 project/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php(96): Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector->isInWebTestCase(Object(PhpParser\Node\Expr\MethodCall))
#14 project/vendor/rector/rector/src/Rector/AbstractRector.php(246): Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
#15 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#16 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#17 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#18 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#19 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#20 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#21 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#22 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#23 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#24 project/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(56): PhpParser\NodeTraverser->traverse(Array)
#25 project/vendor/rector/rector/src/Application/FileProcessor.php(54): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#26 project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(131): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#27 project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(95): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#28 project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#29 project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#30 project/vendor/rector/rector/src/Console/Command/ProcessCommand.php(147): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput))
#31 project/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#32 project/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220209\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#33 project/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220209\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#34 project/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20220209\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#35 project/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#36 project/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220209\Symfony\Component\Console\Application->run()
#37 project/vendor/rector/rector/bin/rector(5): require_once('/Users/...')
#38 project/vendor/bin/rector(97): include('/Users/...')
#39 {main}
  thrown in phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php on line 185
Fatal error: Uncaught PHPStan\Broker\ClassAutoloadingException: Class PHPUnit\Framework\TestCase not found. in phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php:185
Stack trace:
#0 project/vendor/symfony/framework-bundle/Test/KernelTestCase.php(25): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->PHPStan\Reflection\Runtime\{closure}('PHPUnit\\Framewo...')
#1 project/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include('/Users/...')
#2 project/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/...')
#3 project/vendor/symfony/framework-bundle/Test/WebTestCase.php(22): Composer\Autoload\ClassLoader->loadClass('Symfony\\Bundle\\...')
#4 project/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include('/Users/...')
#5 project/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Bundle\\...')
#7 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php(189): class_exists('Symfony\\Bundle\\...')
#8 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ClassBlacklistReflectionProvider.php(51): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->hasClass('Symfony\\Bundle\\...')
#9 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(32): PHPStan\Reflection\ReflectionProvider\ClassBlacklistReflectionProvider->hasClass('Symfony\\Bundle\\...')
#10 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(34): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('Symfony\\Bundle\\...')
#11 phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(567): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('Symfony\\Bundle\\...')
#12 project/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php(131): PHPStan\Reflection\ClassReflection->isSubclassOf('Symfony\\Bundle\\...')
#13 project/vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php(96): Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector->isInWebTestCase(Object(PhpParser\Node\Expr\MethodCall))
#14 project/vendor/rector/rector/src/Rector/AbstractRector.php(246): Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
#15 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#16 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#17 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#18 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#19 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#20 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#21 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#22 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#23 project/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#24 project/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(56): PhpParser\NodeTraverser->traverse(Array)
#25 project/vendor/rector/rector/src/Application/FileProcessor.php(54): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#26 project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(131): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#27 project/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(95): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#28 project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#29 project/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#30 project/vendor/rector/rector/src/Console/Command/ProcessCommand.php(147): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput))
#31 project/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#32 project/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220209\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#33 project/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220209\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#34 project/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20220209\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#35 project/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#36 project/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220209\Symfony\Component\Console\Application->run()
#37 project/vendor/rector/rector/bin/rector(5): require_once('/Users/...')
#38 project/vendor/bin/rector(97): include('/Users/...')
#39 {main}
  thrown in phar://project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php on line 185
```

## Minimal PHP Code Causing Issue

See above, phpunit should be not installed.

## Expected Behaviour

Rector should not crash :)

P.S. After installing `phpunit/phpunit` everything works without issues, so it's not super critical, but would be nice to make it work with default setup.

**Comment by TomasVotruba** [comment]
Hi, we had similar report in the past. In general, Rector has to know about classes you work with. If any packages hides those from autoload or static reflection, it's not possible to about e.g. about types of methods or arguments.

In this case it's a `TestCase` class, but it could be any class.

The best solution is to include it manually in `rector.php` or use a package, that includes it in `composer.json`. E.g.

```bash
composer require phpunit/phpunit --dev
```

See for more the same issue: https://github.com/rectorphp/rector/issues/6714#issuecomment-932261575

**Comment by xorik** [comment]
Ok, thanks. As I can see actually phpunit is installed on demand inside "vendor/bin/phpunit", which is weird but ok. But I cannot see any autoloader, that could be easily added to rector config

**Comment by TomasVotruba** [comment]
That's the issue, the PHPUnit is not there.
Adding dependency to composer helps.
