### ISSUE TITLE
Unable to load project phpstan config with doctrine extension loaded when objectManagerLoader is used

### ISSUE THREAD

**Issue by janedbal** [rectorphp/rector#7091]
# Question

When using[ phpstan-for-rector.neon](https://github.com/rectorphp/rector/issues/7089) with following setup:

```neon
includes:
    - ./vendor/phpstan/phpstan-doctrine/extension.neon

parameters:
    doctrine:
        repositoryClass: 'Doctrine\ORM\EntityRepository'
        objectManagerLoader: build/object-manager.php
```

and having the object-manager.php according to [readme](https://github.com/phpstan/phpstan-doctrine):
```php
require __DIR__ . '/../vendor/autoload.php';

$kernel = new Kernel('test', false);
$kernel->boot();
return $kernel->getContainer()->get(EntityManager::class);
```

I'm getting fatal error about incompatible types due to prefixed namespaces, see stacktrace:

```
vendor/bin/rector process src/Fulfillment/AccountApiBundle/Controller/AccountsDialController.php --debug
[parsing] src/Fulfillment/AccountApiBundle/Controller/AccountsDialController.php
[05-Apr-2022 08:01:39 America/New_York] PHP Fatal error:  Uncaught TypeError: RectorPrefix20220209\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator::__construct(): Argument #1 ($container) must be of type RectorPrefix20220209\Symfony\Component\DependencyInjection\ContainerBuilder, Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder given, called in /app/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php on line 67 and defined in /app/vendor/rector/rector/vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php:37
Stack trace:
#0 /app/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(67): RectorPrefix20220209\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator->__construct(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder), Object(Symfony\Component\DependencyInjection\Loader\PhpFileLoader), Array, '...', '...', NULL)
#1 /app/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php(251): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load('...')
#2 /app/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /app/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /app/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /app/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /app/vendor/symfony/http-kernel/Kernel.php(548): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#7 /app/vendor/symfony/http-kernel/Kernel.php(789): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#8 /app/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#9 /app/build/object-manager.php(9): Symfony\Component\HttpKernel\Kernel->boot()
#10 /app/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(163): require('...')
#11 /app/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(59): PHPStan\Type\Doctrine\ObjectMetadataResolver->loadObjectManager('...')
#12 /app/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/QueryBuilderGetQueryDynamicReturnTypeExtension.php(93): PHPStan\Type\Doctrine\ObjectMetadataResolver->getObjectManager()
#13 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3886): PHPStan\Type\Doctrine\QueryBuilder\QueryBuilderGetQueryDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#14 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1842): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\Doctrine\QueryBuilder\BranchingQueryBuilderType), '...', Object(PhpParser\Node\Expr\MethodCall))
#15 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1848): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#16 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(534): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#17 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1842): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#18 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1848): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#19 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(534): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#20 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(804): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#21 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(534): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Assign))
#22 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1390): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
#23 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(499): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope))
#24 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(301): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#25 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(463): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#26 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(301): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#27 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(547): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#28 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(301): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#29 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(513): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#30 phar:///app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(272): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#31 /app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(150): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#32 /app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(142): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20220209\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#33 /app/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(63): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20220209\Symplify\SmartFileSystem\SmartFileInfo))
#34 /app/vendor/rector/rector/src/Application/FileProcessor.php(49): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#35 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(141): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#36 /app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(85): Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObject\Application\File))
#37 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#38 /app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#39 /app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(147): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput))
#40 /app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#41 /app/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220209\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#42 /app/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220209\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#43 /app/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20220209\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#44 /app/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220209\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220209\Symfony\Component\Console\Output\ConsoleOutput))
#45 /app/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220209\Symfony\Component\Console\Application->run()
#46 /app/vendor/rector/rector/bin/rector(5): require_once('...')
#47 /app/vendor/bin/rector(117): include('...')
```

Is there any way to use rector with phpstan-doctrine and objectManagerLoader? Thank you

**Comment by janedbal** [comment]
Unable to replicate on fresh repo so far, closing till I manage to do it.
