### ISSUE TITLE
BooleanInIfConditionRuleFixerRector crashes when there is \Doctrine\DBAL\Query\QueryBuilder::execute() inside if statement

### ISSUE THREAD

**Issue by dorrogeray** [rectorphp/rector#7095]
Output from running rector with --debug flag:

```
src/Repository/SomeRepository.php
Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\Node\Expr\BinaryOp::__construct() must be an instance of PhpParser\Node\Expr, null given, called in /var/www/symfony/vendor/rector/rector/rules/Strict/NodeFactory/ExactCompareFactory.php on line 114 and defined in /var/www/symfony/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/BinaryOp.php:20
Stack trace:
#0 /var/www/symfony/vendor/rector/rector/rules/Strict/NodeFactory/ExactCompareFactory.php(114): PhpParser\Node\Expr\BinaryOp->__construct(NULL, Object(PhpParser\Node\Expr\BinaryOp\NotIdentical))
#1 /var/www/symfony/vendor/rector/rector/rules/Strict/NodeFactory/ExactCompareFactory.php(93): Rector\Strict\NodeFactory\ExactCompareFactory->resolveFromCleanedNullUnionType(Object(PHPStan\Type\UnionType), Object(PhpParser\Node\Expr\MethodCall), false)
#2 /var/www/symfony/vendor/rector/rector/rules/Strict/NodeFactory/ExactCompareFactory.php(76): Rector\Strict\NodeFactory\ExactCompareFactory->createFromUnionType(Object(PHPStan\Type\UnionType), Ob in /var/www/symfony/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/BinaryOp.php on line 20
```
rector version: `0.12.20`
phpstan version: `1.5.4`

The offending code:
```php
    public function insert(): AdminUser
        // ... prepare the query builder
        if ($queryBuilder->execute()) {
            return $adminUser->setId((int)$this->connection->lastInsertId());
        }

        throw new \RuntimeException('...');
    }
```

It does not crash when explicit `(bool)` cast is added:
```php
    public function insert(): AdminUser
        // ... prepare the query builder
        if ((bool)$queryBuilder->execute()) {
            return $adminUser->setId((int)$this->connection->lastInsertId());
        }

        throw new \RuntimeException('...');
    }
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

Could you share http://getrector.org/demo link with failing use case?

**Comment by dorrogeray** [comment]
> Hi, thanks for reporting.
> 
> Could you share http://getrector.org/demo link with failing use case? It should be as isolated as possible, just with local code and no vendor deps. You can type the `QueryBuilder` as local class with only `execute()` method.

Yes, very cool to have this playground! Didn't know it existed. :+1: 

[Failing use case demo](https://getrector.org/demo/2014c9d4-1723-42b1-adc1-0be9d0a3002c)

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/2016 for it, for note: it only reproducible on non-namespaced file in fixture tests, so I add collection of classes in the fixture itself.
