### ISSUE TITLE
Node "PhpParser\Node\Expr\FuncCall" on line 3 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.

### ISSUE THREAD

**Issue by mfn** [rectorphp/rector#7147]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.23             |

## Minimal PHP Code Causing Issue

```
<?php
$foo = [];
$a = reset($foo);
$b = key($foo);
```

## Step by step example
```
+ $ mkdir rector-test

+ $ cd rector-test

+ $ composer require rector/rector
Using version ^0.12.23 for rector/rector
./composer.json has been created
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (1.6.4)
  - Locking rector/rector (0.12.23)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phpstan/phpstan (1.6.4): Extracting archive
  - Installing rector/rector (0.12.23): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

+ $ cat ->test.php
<?php
$foo = [];
$a = reset($foo);
$b = key($foo);

+ $ vendor/bin/rector process test.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] Rector is done!


+ $ cat ->rector.php
<?php

declare(strict_types = 1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->import(LevelSetList::UP_TO_PHP_74);
};

+ $ vendor/bin/rector process test.php --debug
test.php
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\FuncCall" on line 3 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead. in /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/BreakingRemovalGuard.php:25
Stack trace:
#0 /home/user/tmp/rector-test/vendor/rector/rector/packages/PostRector/Collector/NodesToRemoveCollector.php(76): Rector\NodeRemoval\BreakingRemovalGuard->ensureNodeCanBeRemove(Object(PhpParser\Node\Expr\FuncCall))
#1 /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/NodeRemover.php(44): Rector\PostRector\Collector\NodesToRemoveCollector->addNodeToRemove(Object(PhpParser\Node\Expr\FuncCall))
#2 /home/user/tmp/rector-test/vendor/rector/rector/src/Rector/AbstractRector.php(309): Rector\NodeRemoval\NodeRemover->removeNode(Object(PhpParser\Node\Expr\FuncCall))
#3 /home/user/tmp/rector-test/vendor/rector/rector/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php(100): Rector\Core\Rector\AbstractRector->removeNode(Object(PhpParser\Node\Expr\FuncCall))
#4 /home/user/tmp/rector-test/vendor/rector/rector/src/Rector/AbstractRector.php(207): Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector->refactor(Object(PhpParser\Node\Expr\FuncCall))
#5 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#6 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#7 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#8 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#9 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#10 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#11 /home/user/tmp/rector-test/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#12 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#13 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#14 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#15 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#16 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#17 /home/user/tmp/rector-test/vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput))
#18 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220501\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220501\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/user/tmp/rector-test/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220501\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/user/tmp/rector-test/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220501\Symfony\Component\Console\Application->run()
#24 /home/user/tmp/rector-test/vendor/rector/rector/bin/rector(5): require_once('/home/user/tmp/...')
#25 /home/user/tmp/rector-test/vendor/bin/rector(117): include('/home/user/tmp/...')
#26 {main}
  thrown in /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/BreakingRemovalGuard.php on line 25
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\FuncCall" on line 3 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead. in /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/BreakingRemovalGuard.php:25
Stack trace:
#0 /home/user/tmp/rector-test/vendor/rector/rector/packages/PostRector/Collector/NodesToRemoveCollector.php(76): Rector\NodeRemoval\BreakingRemovalGuard->ensureNodeCanBeRemove(Object(PhpParser\Node\Expr\FuncCall))
#1 /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/NodeRemover.php(44): Rector\PostRector\Collector\NodesToRemoveCollector->addNodeToRemove(Object(PhpParser\Node\Expr\FuncCall))
#2 /home/user/tmp/rector-test/vendor/rector/rector/src/Rector/AbstractRector.php(309): Rector\NodeRemoval\NodeRemover->removeNode(Object(PhpParser\Node\Expr\FuncCall))
#3 /home/user/tmp/rector-test/vendor/rector/rector/rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php(100): Rector\Core\Rector\AbstractRector->removeNode(Object(PhpParser\Node\Expr\FuncCall))
#4 /home/user/tmp/rector-test/vendor/rector/rector/src/Rector/AbstractRector.php(207): Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector->refactor(Object(PhpParser\Node\Expr\FuncCall))
#5 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#6 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#7 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#8 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#9 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#10 /home/user/tmp/rector-test/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#11 /home/user/tmp/rector-test/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#12 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#13 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#14 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#15 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#16 /home/user/tmp/rector-test/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#17 /home/user/tmp/rector-test/vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput))
#18 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220501\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220501\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/user/tmp/rector-test/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220501\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/user/tmp/rector-test/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/user/tmp/rector-test/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220501\Symfony\Component\Console\Application->run()
#24 /home/user/tmp/rector-test/vendor/rector/rector/bin/rector(5): require_once('/home/user/tmp/...')
#25 /home/user/tmp/rector-test/vendor/bin/rector(117): include('/home/user/tmp/...')
#26 {main}
  thrown in /home/user/tmp/rector-test/vendor/rector/rector/packages/NodeRemoval/BreakingRemovalGuard.php on line 25
```

I know that the code itself is non-sensical, I reduced it from an actual file part of a private codebase I cannot share.

🤞🏼

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

**Comment by mfn** [comment]
> We'll need an isolated failing demo link

I guess this is obsolete, now that it was already fixed 😅

Damn you all were fast 🚤 !
