### ISSUE TITLE
Fatal error: During class fetch: Uncaught Error: Call to undefined function

### ISSUE THREAD

**Issue by ziming** [rectorphp/rector#7152]
# Bug Report

I'm using rector php in a laravel 9 project. In the past it is working fine but recently it did not.

I'm on PHP 8.1, Laravel 9.11 and rectorphp 0.12.23

My rector php config file looks like this

```php
<?php

declare(strict_types=1);

use Rector\Set\ValueObject\SetList;
use Rector\Config\RectorConfig;


return static function (RectorConfig $rectorConfig): void {

    $rectorConfig->paths([
        __DIR__ . '/app',
    ]);

    $rectorConfig->sets([
        SetList::PHP_81,
    ]);

};
```

Upon running it, I keep getting `Fatal error: During class fetch: Uncaught Error: Call to undefined function`

I went to check the code and the function is basically how all laravel helper functions are defined. In this specific situation the helper function is in the backpack/pro package. But I don't think it is a laravel backpack issue as laravel also define helper functions this way. Other packages that define global helper functions also define them this way.

```php
if (! function_exists('backpack_pro')) {
    /**
     * Check if the backpack/pro package is installed.
     *
     * @return bool
     */
    function backpack_pro()
    {
        if (! \Composer\InstalledVersions::isInstalled('backpack/pro')) {
            return false;
        }

        return \PackageVersions\Versions::getVersion('backpack/pro');
    }
}
```

In the past before I switched to the new $rectorConfig I did not face this issue. I have not switched back to the old way of using $containerConfigurator to see if it works yet.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. Nothing rings a bell from this description. 

Could you share output with `--debug`? We'll need minimal reproducible repository to able find out the root of this issue.

**Comment by ziming** [comment]
You mean `vendor/bin/rector process --dry-run --debug` ?

**Comment by TomasVotruba** [comment]
Yes :+1:

**Comment by ziming** [comment]
Here you go. I censor some folder path names

```php
Fatal error: During class fetch: Uncaught Error: Call to undefined function Backpack\CRUD\app\Http\Controllers\Operations\backpack_pro() in /Users/me/my-projects/my-app/vendor/backpack/crud/src/app/Http/Controllers/Operations/FetchOperation.php:7
```

Meanwhile here is the code for FetchOperation.php

https://github.com/Laravel-Backpack/CRUD/blob/v5/src/app/Http/Controllers/Operations/FetchOperation.php

**Comment by ziming** [comment]
And the helpers.php of Backpack is here

https://github.com/Laravel-Backpack/CRUD/blob/v5/src/helpers.php

**Comment by TomasVotruba** [comment]
This is onle the last message. We need the full stack trace to be able to discover the path in code we can affect.

We'll need the reproducer repository.

**Comment by ziming** [comment]
Here is the stack trace right after the error

```bash
Stack trace:
#0 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include()
#1 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/me...')
#2 /Users/me/laravel-projects/my-app/app/Http/Controllers/Admin/BookCrudController.php(25): Composer\Autoload\ClassLoader->loadClass('Backpack\\CRUD\\a...')
#3 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/composer/ClassLoader.php(571): include('/Users/me...')
#4 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/me...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Http\\Contro...')
#6 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php(189): class_exists('App\\Http\\Contro...')
#7 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ClassBlacklistReflectionProvider.php(51): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->hasClass('App\\Http\\Contro...')
#8 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(32): PHPStan\Reflection\ReflectionProvider\ClassBlacklistReflectionProvider->hasClass('App\\Http\\Contro...')
#9 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(34): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('App\\Http\\Contro...')
#10 /Users/me/laravel-projects/my-app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(173): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('App\\Http\\Contro...')
#11 /Users/me/laravel-projects/my-app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(130): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->resolveClassOrInterfaceScope(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope))
#12 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(369): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->Rector\NodeTypeResolver\PHPStan\Scope\{closure}(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope))
#13 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(314): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(526): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(285): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 /Users/me/laravel-projects/my-app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(151): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 /Users/me/laravel-projects/my-app/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(142): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20220501\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 /Users/me/laravel-projects/my-app/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(49): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, Object(RectorPrefix20220501\Symplify\SmartFileSystem\SmartFileInfo))
#19 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Application/FileProcessor.php(55): Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile(Object(Rector\Core\ValueObject\Application\File), Array)
#20 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(136): Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\File))
#21 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(84): Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObject\Application\File))
#22 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#23 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#24 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput))
#25 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220501\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#27 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220501\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#28 /Users/me/laravel-projects/my-app/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220501\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#29 /Users/me/laravel-projects/my-app/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220501\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220501\Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/me/laravel-projects/my-app/vendor/rector/rector/bin/rector.php(57): RectorPrefix20220501\Symfony\Component\Console\Application->run()
#31 /Users/me/laravel-projects/my-app/vendor/rector/rector/bin/rector(5): require_once('/Users/me...')
#32 /Users/me/laravel-projects/my-app/vendor/bin/rector(117): include('/Users/me...')
#33 {main} in /Users/me/laravel-projects/my-app/app/Http/Controllers/Admin/BookCrudController.php on line 25
```

Line 25 in my controller is this line of code

```php
class BookCrudController extends CrudController // This is Line 25
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation {
        update as traitUpdate;
    }

    use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\FetchOperation; // This is the FetchOperation

    public function setup(): void
    {
        // Censored
    }
```

**Comment by ziming** [comment]
Another thing to add on. Before the error on BookCrudController it parsed 1 other CrudController that also uses the FetchOperation trait.

**Comment by ziming** [comment]
Okay it worked!

All I did is this add this comment above the class

```php
/**
 * Class BookCrudController.
 * @property-read \Backpack\CRUD\app\Library\CrudPanel\CrudPanel $crud
 */
class BookCrudController extends CrudController
```

So should this be closed or remain a bug? As far as I recall the last time I used rector php a couple weeks ago I did not get this error, I also do not have this comment above my CrudController class back then.

**Comment by ziming** [comment]
Okay now I no longer have the stack trace after adding that comment above the class but I now got this

```
 file with changes
===================

1) app/Providers/RouteServiceProvider.php:16

    ---------- begin diff ----------
@@ @@
      *
      * @var string
      */
-    public const HOME = '/home';
+    public final const HOME = '/home';
     //

     /**
    ----------- end diff -----------

Applied rules:
 * FinalizePublicClassConstantRector (https://php.watch/versions/8.1/final-class-const)
                                                                                                                        
 [ERROR] Could not process "app/Http/Controllers/Admin/BookCrudController.php" file, due to:                       
         "Analyze error: "Error (Call to undefined function Backpack\CRUD\app\Http\Controllers\Operations\backpack_pro())
         thrown while looking for class Backpack\CRUD\app\Http\Controllers\Operations\FetchOperation.". Include your files
         in "$rectorConfig->autoloadPaths([...]);" or "$rectorConfig->bootstrapFiles([...]);" in "rector.php" config.   
         See https://github.com/rectorphp/rector#configuration".
```

**Comment by samsonasik** [comment]
The functions defined possibly overlapped with autoload, you can setup a phpstan.neon like this:

```neon
# phpstan.neon
parameters:
	scanDirectories:
		- src/Helpers
```

then, register it in `rector.php`:

```php
$rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon');
```

**Comment by ziming** [comment]
hmm I have no helpers directory in my codebase.

so not too sure how I can apply that.

**Comment by samsonasik** [comment]
You can define the any paths that require directory to be scanned:

```
# phpstan.neon
parameters:
	scanDirectories:
		- vendor/some/package/Helpers
```

if the file is single file, you can define it as bootstrap files, something like this: :

```php
$rectorConfig->bootstrapFiles([
    __DIR__ . '/vendor/backpack/crud/src/helpers.php'
]);
```

**Comment by ziming** [comment]
Thank you @samsonasik 

This code snippet from you worked
```php
$rectorConfig->bootstrapFiles([
    __DIR__ . '/vendor/backpack/crud/src/helpers.php'
]);
```

As a side question, on backpack side, how could they fix this?

**Comment by samsonasik** [comment]
I don't know, that's possibly some autoload update on `backpack/crud` or different autoload update in your vendor or projects.

We don't get a reproducible repository sample project from you, so all we can do is assumption.
