### ISSUE TITLE
Error upgrading phpexcel to phpspreadsheet

### ISSUE THREAD

**Issue by lucian303** [rectorphp/rector#7187]
# Bug Report

rector version 0.13.0

Tried to upgrade phpexcel to phpspreadsheet and got the below error. Our codebase is not too great admittedly, but if the tool is to be useful in the future, it shouldn't fail at the first minor code smell it finds (or the second or the nth issue). Anyway, I'll just do it manually.

```
   115/12413 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%Fatal error: Uncaught TypeError: Rector\Core\NodeAnalyzer\UnreachableStmtAnalyzer::isStmtPHPStanUnreachable(): Argument #1 ($stmt) must be of type ?PhpParser\Node\Stmt, PhpParser\Node\Expr\BinaryOp\NotEqual given, called in /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/NodeAnalyzer/UnreachableStmtAnalyzer.php on line 24 and defined in /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/NodeAnalyzer/UnreachableStmtAnalyzer.php:14
Stack trace:
#0 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/NodeAnalyzer/UnreachableStmtAnalyzer.php(24): Rector\Core\NodeAnalyzer\UnreachableStmtAnalyzer->isStmtPHPStanUnreachable(Object(PhpParser\Node\Expr\BinaryOp\NotEqual))
#1 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(67): Rector\Core\NodeAnalyzer\UnreachableStmtAnalyzer->isStmtPHPStanUnreachable(Object(PhpParser\Node\Stmt\Expression))
#2 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Rector/AbstractRector.php(249): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\MethodCall), Object(RectorPrefix20220523\Symplify\SmartFileSystem\SmartFileInfo), NULL)
#3 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#4 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#5 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#6 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#8 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#10 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#11 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#12 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/FileProcessor.php(61): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#13 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#14 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#15 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(176): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#16 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(148): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#17 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Console/Command/ProcessCommand.php(129): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput))
#18 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/symfony/console/Command/Command.php(282): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/symfony/console/Application.php(861): RectorPrefix20220523\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/symfony/console/Application.php(289): RectorPrefix20220523\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/Console/ConsoleApplication.php(66): RectorPrefix20220523\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/vendor/symfony/console/Application.php(187): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20220523\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20220523\Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/bin/rector.php(129): RectorPrefix20220523\Symfony\Component\Console\Application->run()
#24 /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/bin/rector(5): require_once('/Users/lucian30...')
#25 /Users/lucian303/Desktop/docker/cch/vendor/bin/rector(117): include('/Users/lucian30...')
#26 {main}
  thrown in /Users/lucian303/Desktop/docker/cch/vendor/rector/rector/src/NodeAnalyzer/UnreachableStmtAnalyzer.php on line 14
```

## Expected Behaviour

Not crash.

## Config
```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\PHPOffice\Set\PHPOfficeSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__
    ]);

    $rectorConfig->import(PHPOfficeSetList::PHPEXCEL_TO_PHPSPREADSHEET);
};
```

**Comment by samsonasik** [comment]
should be fixed in latest dev-main , please try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by lucian303** [comment]
Great! Thank you @samsonasik
