### ISSUE TITLE
Unable to pass specified arguments to PhpDocParser::__construct()

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7226]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.15            |

I'm getting this. 0.13.14 works

```
PHP Fatal error:  Uncaught _PHPStan_98a3b0791\Nette\DI\ServiceCreationException: Service of type PHPStan\PhpDocParser\Parser\PhpDocParser: Unable to pass specified arguments to PhpDocParser::__construct(). in phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:421
Stack trace:
#0 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php(170): _PHPStan_98a3b0791\Nette\DI\Resolver::autowireArguments()
#1 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(158): _PHPStan_98a3b0791\Nette\DI\Resolver->completeStatement()
#2 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php(123): _PHPStan_98a3b0791\Nette\DI\Definitions\ServiceDefinition->complete()
#3 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php(252): _PHPStan_98a3b0791\Nette\DI\Resolver->completeDefinition()
#4 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(203): _PHPStan_98a3b0791\Nette\DI\ContainerBuilder->complete()
#5 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(159): _PHPStan_98a3b0791\Nette\DI\Compiler->processBeforeCompile()
#6 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_98a3b0791\Nette\DI\Compiler->compile()
#7 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(66): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->generate()
#8 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->loadFile()
#9 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(40): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->load()
#10 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(175): PHPStan\DependencyInjection\Configurator->loadContainer()
#11 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(81): _PHPStan_98a3b0791\Nette\Bootstrap\Configurator->createContainer()
#12 /builds/projects/project/vendor/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(45): PHPStan\DependencyInjection\ContainerFactory->create()
#13 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#14 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(894): ReflectionClass->newInstanceArgs()
#15 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#16 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#17 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(870): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#18 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#19 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#20 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#21 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#22 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#23 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#24 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#25 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#26 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#27 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#28 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#29 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#30 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#31 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#32 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#33 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#34 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#35 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#36 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#37 /builds/projects/project/vendor/rector/rector/bin/rector.php(127): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->get()
#38 /builds/projects/project/vendor/rector/rector/bin/rector(5): require_once('...')
#39 /builds/projects/project/vendor/bin/rector(117): include('...')
#40 {main}
  thrown in phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php on line 421
Fatal error: Uncaught _PHPStan_98a3b0791\Nette\DI\ServiceCreationException: Service of type PHPStan\PhpDocParser\Parser\PhpDocParser: Unable to pass specified arguments to PhpDocParser::__construct(). in phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:421
Stack trace:
#0 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php(170): _PHPStan_98a3b0791\Nette\DI\Resolver::autowireArguments()
#1 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(158): _PHPStan_98a3b0791\Nette\DI\Resolver->completeStatement()
#2 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php(123): _PHPStan_98a3b0791\Nette\DI\Definitions\ServiceDefinition->complete()
#3 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php(252): _PHPStan_98a3b0791\Nette\DI\Resolver->completeDefinition()
#4 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(203): _PHPStan_98a3b0791\Nette\DI\ContainerBuilder->complete()
#5 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(159): _PHPStan_98a3b0791\Nette\DI\Compiler->processBeforeCompile()
#6 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_98a3b0791\Nette\DI\Compiler->compile()
#7 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(66): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->generate()
#8 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->loadFile()
#9 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(40): _PHPStan_98a3b0791\Nette\DI\ContainerLoader->load()
#10 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(175): PHPStan\DependencyInjection\Configurator->loadContainer()
#11 phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(81): _PHPStan_98a3b0791\Nette\Bootstrap\Configurator->createContainer()
#12 /builds/projects/project/vendor/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(45): PHPStan\DependencyInjection\ContainerFactory->create()
#13 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#14 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(894): ReflectionClass->newInstanceArgs()
#15 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#16 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#17 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(870): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#18 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#19 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#20 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#21 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#22 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#23 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#24 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#25 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#26 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#27 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#28 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#29 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#30 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#31 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#32 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#33 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#34 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#35 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#36 /builds/projects/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#37 /builds/projects/project/vendor/rector/rector/bin/rector.php(127): RectorPrefix20220609\Symfony\Component\DependencyInjection\ContainerBuilder->get()
#38 /builds/projects/project/vendor/rector/rector/bin/rector(5): require_once('...')
#39 /builds/projects/project/vendor/bin/rector(117): include('...')
#40 {main}
  thrown in phar:///builds/projects/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php on line 421
```

**Comment by TomasVotruba** [comment]
Thank for reporting.

What is your phpstan and phpdoc-parser versions? It might require to upgrade, as both share the same phpdoc-parser 1.6.
PHPStan in 1.7.12.

**Comment by samsonasik** [comment]
The phpdoc-parser conflict config seems need to be updated:

https://github.com/rectorphp/rector/blob/a9ffd906d721fc9013de7145c3abbf65bcc078cd/composer.json#L22-L23

to <1.6

**Comment by simPod** [comment]
Yup. I have every direct dependency at latest version but indirect are sometimes behind. This time my phpdoc-parser is `1.5.1`.
