### ISSUE TITLE
--debug doesn't show stack trace on parallel

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7254]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

The PR:

- https://github.com/rectorphp/rector-src/pull/2307

only fixed the display applied rules that previously not shown in parallel. 

The stack trace still not shown when throw the Exception. It only happen in parallel.

## Expected Behaviour

The stack trace should be shown.

**Comment by TomasVotruba** [comment]
Actually, I looked into it and hour exception still works properly. The issue is with PHPStan analyzer throwing error in parallel analysis, but AFAIK there is nothing we can do to throw strack trace from inside PHPStan as it is the code we do not own.

**Comment by samsonasik** [comment]
I tried to add : 

```diff
+        throw new ShouldNotHappenException('test');
```

in `RemoveUnusedPrivatePropertyRector`, and it only show:

**In Parallel**

```bash
[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
                                                                                                                        
 [ERROR] Could not process "src/Config/Loader/ConfigureCallMergingLoaderFactory.php" file, due to:                      
         "System error: "test"                                                                                          
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 112    
```

**call disableParallel()**, it show the stack trace:

in rector.php: 

```php
$rectorConfig->disableParallel();
```

```bash
[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector

PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: test in /Users/samsonasik/www/rector-src/rules/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector.php:112
Stack trace:
#0 /Users/samsonasik/www/rector-src/src/Rector/AbstractRector.php(218): Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector->refactor(Object(PhpParser\Node\Stmt\Class_))
#1 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))
#2 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#4 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/samsonasik/www/rector-src/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(33): PhpParser\NodeTraverser->traverse(Array)
#6 /Users/samsonasik/www/rector-src/src/Application/FileProcessor.php(42): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
```

**Comment by TomasVotruba** [comment]
I see.
