### ISSUE TITLE
Error when upgrading from 0.12 to 0.13

### ISSUE THREAD

**Issue by rotexdegba** [rectorphp/rector#7290]
# Question

My project https://github.com/rotexsoft/versatile-acl has been running fine using rector 0.12. When I upgraded to rector 0.13.8, I get the error below and I am not sure why exactly it's happening. 

```
[ERROR] Could not process "src/VersatileAcl.php" file, due to:                                                         
         "System error: "leaveNode() returned invalid value of type integer"                                            
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(58): PhpParser\NodeTraverser->traverse()
         #16 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(95):                               
         Rector\PostRector\Application\PostFileProcessor->traverse()                                                    
         #17 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #18 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #19 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202207\Evenement\EventEmitter->emit()                                                              
         #20 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202207\Clue\React\NDJson\Decoder->handleData()                                                     
         #21 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202207\Evenement\EventEmitter->emit()
         #22 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202207\React\Stream\Util::RectorPrefix202207\React\Stream\{closure}()                              
         #23 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202207\Evenement\EventEmitter->emit()                                                              
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202207\React\Stream\DuplexResourceStream->handleData()                                             
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #26 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->run()                                                     
         #27 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(891):                                          
         RectorPrefix202207\Symfony\Component\Console\Command\Command->run()                                            
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(310):                                          
         RectorPrefix202207\Symfony\Component\Console\Application->doRunCommand()                                       
         #30 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202207\Symfony\Component\Console\Application->doRun()                                              
         #31 vendor/rector/rector/vendor/symfony/console/Application.php(208): Rector\Core\Console\ConsoleApplication->doRun()
         #32 vendor/rector/rector/bin/rector.php(128): RectorPrefix202207\Symfony\Component\Console\Application->run()  
         #33 vendor/rector/rector/bin/rector(4): require_once('/home/rotimi/So...')                                     
         #34 vendor/bin/rector(115): include('/home/rotimi/So...')                                                      
         #35 {main}". On line: 150                    
```

Could someone please help me figure out what the problem is?

Thanks

**Comment by samsonasik** [comment]
It seems reproduced with the following sample code:

```php

final class DemoFile
{
    public function run()
    {
            $a
                && $this->execute(
                        $a instanceof stdClass ? 'a' : 'b',
                        $a instanceof stdClass ? 'a' : 'b'
                    );
            
    }
}
```

with `RemoveDuplicatedInstanceOfRector` rule:

```php
<?php

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(Rector\DeadCode\Rector\BinaryOp\RemoveDuplicatedInstanceOfRector::class);

};
```

ref https://getrector.org/demo/2f88749f-5804-4a85-a7c2-5776e6102012

**Comment by rotexdegba** [comment]
@samsonasik Thanks for the update. I will keep an eye out for the next 0.13 release.

**Comment by rotexdegba** [comment]
Seems like it worked. I pulled in changes from dev-main today & rector ran fine on the repository. I will wait for the next 0.13 release to fully confirm.
