### ISSUE TITLE
`Object of class PhpParser\\Node\\IntersectionType could not be converted to string` with `TYPE_DECLARATION_STRICT` set

### ISSUE THREAD

**Issue by canvural** [rectorphp/rector#7311]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.9             |

Code and error is in this demo link: https://getrector.org/demo/88bae302-e888-4208-8485-f2f3acaf19dd

<details>
<summary>Here is the output if I run with `--debug`</summary>

```
[ERROR] Could not process "app/Payone/Requests/BaseRequest.php" file, due to:                                          
         "System error: "Object of class PhpParser\Node\IntersectionType could not be converted to string"              
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php(284): array_unique(Array)
         #1 vendor/rector/rector/packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php(211):                  
         Rector\PHPStanStaticTypeMapper\TypeMapper\UnionTypeMapper->matchPhpParserUnionType(Object(PHPStan\Type\UnionType),
         'param')                                                                                                       
         #2 vendor/rector/rector/packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php(139):                  
         Rector\PHPStanStaticTypeMapper\TypeMapper\UnionTypeMapper->matchTypeForUnionedObjectTypes(Object(PHPStan\Type\UnionType
         ), 'param')                                                                                                    
         #3 vendor/rector/rector/packages/PHPStanStaticTypeMapper/PHPStanStaticTypeMapper.php(63):                      
         Rector\PHPStanStaticTypeMapper\TypeMapper\UnionTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\UnionType), 'param')
         #4 vendor/rector/rector/packages/StaticTypeMapper/StaticTypeMapper.php(85):                                    
         Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper->mapToPhpParserNode(Object(PHPStan\Type\UnionType), 'param')
         #5 vendor/rector/rector/rules/TypeDeclaration/NodeAnalyzer/ClassMethodParamTypeCompleter.php(61):              
         Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanTypeToPhpParserNode(Object(PHPStan\Type\UnionType), 'param')
         #6 vendor/rector/rector/rules/TypeDeclaration/Rector/ClassMethod/AddMethodCallBasedStrictParamTypeRector.php(96):
         Rector\TypeDeclaration\NodeAnalyzer\ClassMethodParamTypeCompleter->complete(Object(PhpParser\Node\Stmt\ClassMethod),
         Array, 3)                                                                                                      
         #7 vendor/rector/rector/src/Rector/AbstractRector.php(204):                                                    
         Rector\TypeDeclaration\Rector\ClassMethod\AddMethodCallBasedStrictParamTypeRector->refactor(Object(PhpParser\Node\Stmt</>
         ClassMethod))                                                                                                  
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))                          
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #14 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #15 vendor/rector/rector/src/Application/FileProcessor.php(61):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #16 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #17 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))                                                     
         #18 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #20 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202207\Evenement\EventEmitter->emit('data', Array)                                                 
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202207\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #22 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202207\Evenement\EventEmitter->emit('data',
         Array)                                                                                                         
         #23 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202207\React\Stream\Util::RectorPrefix202207\React\Stream\{closure}('{"action":"main...')          
         #24 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202207\Evenement\EventEmitter->emit('data', Array)                                                 
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202207\React\Stream\DuplexResourceStream->handleData(Resource id #3548)                            
         #26 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #27 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->run()                                                     
         #28 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202207\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202207\Symfony\Component\Console\Output\ConsoleOutput))                                   
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(891):                                          
         RectorPrefix202207\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202207\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202207\Symfony\Component\Console\Output\ConsoleOutput))                    
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(310):                                          
         RectorPrefix202207\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202207\Symfony\Component\Console\Input\ArgvInput),                                       
         Object(RectorPrefix202207\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #31 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202207\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202207\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202207\Symfony\Component\Console\Output\ConsoleOutput))                      
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(208):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202207\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202207\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #33 vendor/rector/rector/bin/rector.php(128): RectorPrefix202207\Symfony\Component\Console\Application->run()  
         #34 vendor/rector/rector/bin/rector(5): require_once('v...')                                                   
         #35 vendor/bin/rector(120): include('v...')                                                                    
         #36 {main}". On line: 284
```

</details>

It looks like it may come from `AddMethodCallBasedStrictParamTypeRector` but if I run Rector only with this rule, error does not happen 🤷🏽‍♂️ 

## Minimal PHP Code Causing Issue

[](https://getrector.org/demo/88bae302-e888-4208-8485-f2f3acaf19dd)

## Expected Behaviour

No error.

**Comment by samsonasik** [comment]
Thats' seems reproduced with the following config:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\ClassMethod\AddMethodCallBasedStrictParamTypeRector;
use Rector\TypeDeclaration\Rector\Param\ParamTypeFromStrictTypedPropertyRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rules([
        ParamTypeFromStrictTypedPropertyRector::class,
        AddMethodCallBasedStrictParamTypeRector::class,
    ]);
};
```

ref https://getrector.org/demo/da597d6f-3ffe-4ec9-b026-2a825be860e7

**Comment by samsonasik** [comment]
Found in single rule

https://getrector.org/demo/a259f6fa-69bc-4db4-b491-3614aa012a79
