### ISSUE TITLE
Crash Unsupported operand types: string * int on RemoveDeadZeroAndOneOperationRector

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/rector#7321]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.13.9            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/9caf7439-0dd0-45fe-998b-3d25dc9e6038

Given the following code:

```php
final class DemoFile
{
    protected const CSRF_HASH_BYTES      = 16;
    
    protected function derandomize(string $token): string
    {
        $key   = substr($token, -static::CSRF_HASH_BYTES * 2);
    }
}
```

It produce error:

```bash
 [ERROR] Could not process "DemoFile.php" file, due to:                                                 
         "System error: "Unsupported operand types: string * int"                                                       
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(96):                      
         PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\UnaryMinus))                                 
         #1 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(105):          
```

## Expected Behaviour

should not error.

**Comment by samsonasik** [comment]
It seems current `ValueResolver::resolveClassConstFetch()` only handle `self`, but not `static` 

https://github.com/rectorphp/rector-src/blob/f0df3c5101f4b9465708589a2c13027bc84f898c/src/PhpParser/Node/Value/ValueResolver.php#L261-L270
