### ISSUE TITLE
ExplicitMethodCallOverMagicGetSetRector - exception

### ISSUE THREAD

**Issue by MartinMystikJonas** [rectorphp/rector#7325]
# Bug Report

Rector 0.13.9

```
"System error: "Property $token was not found in reflection of class Nette\Http\SessionSection."

         Stack trace:
         #0 phar://tools/devstack/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(152):       
         PHPStan\Reflection\ClassReflection->getProperty()
         #1 phar://tools/devstack/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(129):       
         PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype()
         #2 tools/devstack/rector/rector/rules/CodeQuality/Rector/PropertyFetch/ExplicitMethodCallOverMagicGetSetRector.php(133):
         PHPStan\Type\ObjectType->getProperty()
         #3 tools/devstack/rector/rector/rules/CodeQuality/Rector/PropertyFetch/ExplicitMethodCallOverMagicGetSetRector.php(99):
         Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGetSetRector->refactorPropertyFetch()       
         #4 tools/devstack/rector/rector/src/Rector/AbstractScopeAwareRector.php(49):
         Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGetSetRector->refactorWithScope()
         #5 tools/devstack/rector/rector/src/Rector/AbstractRector.php(204):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor()
         #6 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):
         Rector\Core\Rector\AbstractRector->enterNode()                                                                 
         #7 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #8 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #9 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #10 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #11 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #12 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #13 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #14 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #15 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #16 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #17 tools/devstack/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #18 tools/devstack/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse()
         #19 tools/devstack/rector/rector/src/Application/FileProcessor.php(61):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #20 tools/devstack/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):
         Rector\Core\Application\FileProcessor->refactor()
         #21 tools/devstack/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
         #22 tools/devstack/rector/rector/packages/Parallel/WorkerRunner.php(99):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
         #23 tools/devstack/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()
         #24 tools/devstack/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):
         RectorPrefix202207\Evenement\EventEmitter->emit()
         #25 tools/devstack/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202207\Clue\React\NDJson\Decoder->handleData()
         #26 tools/devstack/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202207\Evenement\EventEmitter->emit()
         #27 tools/devstack/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202207\React\Stream\Util::RectorPrefix202207\React\Stream\{closure}()
         #28 tools/devstack/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202207\Evenement\EventEmitter->emit()
         #29 tools/devstack/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202207\React\Stream\DuplexResourceStream->handleData()
         #30 tools/devstack/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #31 tools/devstack/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->run()
         #32 tools/devstack/rector/rector/vendor/symfony/console/Command/Command.php(307):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #33 tools/devstack/rector/rector/vendor/symfony/console/Application.php(891):
         RectorPrefix202207\Symfony\Component\Console\Command\Command->run()
         #34 tools/devstack/rector/rector/vendor/symfony/console/Application.php(310):
         RectorPrefix202207\Symfony\Component\Console\Application->doRunCommand()
         #35 tools/devstack/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202207\Symfony\Component\Console\Application->doRun()
         #36 tools/devstack/rector/rector/vendor/symfony/console/Application.php(208):
         Rector\Core\Console\ConsoleApplication->doRun()
         #37 tools/devstack/rector/rector/bin/rector.php(128): RectorPrefix202207\Symfony\Component\Console\Application->run()
         #38 tools/devstack/rector/rector/bin/rector(5): require_once('...')
         #39 tools/devstack/bin/rector(120): include('...')
         #40 {main}". On line: 520
```

Relevant parts of code tahat can cause it:

```php
return isset($session->token) ? $session->token : null;
```
```php
unset(self::getCsrfTokenSession($session, $namespace)->token);
```
```php
self::getCsrfTokenSession($session, $namespace)->token = Random::generate(10)
```

Similar error in different file caused by code with dynamic property access:

```php
        if($this->{$key} !== $second->{$key}) {
          $result[$key] = [$this->{$key}, $second->{$key}];
        }
```
## Expected Behaviour

No error

## Fix suggestion

Error arises here in `ExplicitMethodCallOverMagicGetSetRector`:

```php
        $propertyName = $this->getName($propertyFetch->name);
        if ($propertyName === null) {
            return null;
        }

        $propertyReflection = $callerType->getProperty($propertyName, $scope); // <==
```
I guess there should be another check of `$callerType->hasProperty($propertyName)` and skip this rule if false.

I can prepare PR with this fix if it is ok.

**Comment by TomasVotruba** [comment]
You're right, there should be check for property existance.

>  can prepare PR with this fix if it is ok.

That would be great :+1:

**Comment by MartinMystikJonas** [comment]
PR here: https://github.com/rectorphp/rector-src/pull/2719
