### ISSUE TITLE
Rector just hanged with error.

### ISSUE THREAD

**Issue by shinsenter** [rectorphp/rector#7410]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.14.0            |

Rector just hanged with the below error:
```
Fatal error: Uncaught TypeError: PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null returned
```

## Config

```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

use Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector;
use Rector\CodingStyle\Rector\Closure\StaticClosureRector;
use Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector;
use Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
use Rector\Naming\Rector\ClassMethod\RenameParamToMatchTypeRector;
use Rector\Php70\Rector\If_\IfToSpaceshipRector;
use Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php80\Rector\FunctionLike\MixedTypeRector;
use Rector\Php80\Rector\FunctionLike\UnionTypesRector;
use Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->disableParallel();
    $rectorConfig->importNames();
    $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon');

    // scan paths
    $rectorConfig->paths([
        '/var/www/html/application',
    ]);

    // skip rules
    $rectorConfig->skip([
        // paths
        '/var/www/html/application/cache',
        '/var/www/html/application/logs',
        '/var/www/html/application/views',

        // rules
        ClosureToArrowFunctionRector::class,
        CompleteDynamicPropertiesRector::class,
        EncapsedStringsToSprintfRector::class,
        IfToSpaceshipRector::class,
        JsonThrowOnErrorRector::class,
        MixedTypeRector::class,
        NewlineAfterStatementRector::class,
        RenameParamToMatchTypeRector::class,
        ReturnTypeDeclarationRector::class,
        StaticClosureRector::class,
        UnionTypesRector::class,
        VarConstantCommentRector::class,
    ]);

    // rule sets
    $rectorConfig->sets([
        SetList::EARLY_RETURN,
        SetList::DEAD_CODE,
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        LevelSetList::UP_TO_PHP_81,
    ]);
};
```

phpstan.neon
```
parameters:
	level: 5
	phpVersion: 80100
	paths:
		- /var/www/html/application/
	excludePaths:
		- /var/www/html/application/cache/*
		- /var/www/html/application/logs/*
		- /var/www/html/application/views/*
	scanFiles:
	    - /var/www/html/index.php
	scanDirectories:
	    - /var/www/html/vendor/
	    - /var/www/html/system/
	fileExtensions:
		- php
	parallel:
		processTimeout: 300.0

```

## Error log

```
Fatal error: Uncaught TypeError: PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null returned in /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(608): PhpParser\Internal\TokenStream->getIndentationBefore()
#1 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(142): PhpParser\PrettyPrinterAbstract->p()
#2 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()
#3 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(192): PhpParser\PrettyPrinterAbstract->pArray()
#4 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()
#5 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(142): PhpParser\PrettyPrinterAbstract->p()
#6 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()
#7 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(192): PhpParser\PrettyPrinterAbstract->pArray()
#8 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()
#9 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(142): PhpParser\PrettyPrinterAbstract->p()
#10 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()
#11 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(192): PhpParser\PrettyPrinterAbstract->pArray()
#12 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()
#13 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(142): PhpParser\PrettyPrinterAbstract->p()
#14 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()
#15 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(192): PhpParser\PrettyPrinterAbstract->pArray()
#16 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()
#17 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(142): PhpParser\PrettyPrinterAbstract->p()
#18 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()
#19 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(192): PhpParser\PrettyPrinterAbstract->pArray()
#20 /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(471): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()
#21 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(106): PhpParser\PrettyPrinterAbstract->printFormatPreserving()
#22 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(40): Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving()
#23 /var/www/fixer/vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(53): Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printToFile()
#24 /var/www/fixer/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(162): Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokens()
#25 /var/www/fixer/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(101): Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile()
#26 /var/www/fixer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(168): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#27 /var/www/fixer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(141): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#28 /var/www/fixer/vendor/rector/rector/src/Console/Command/ProcessCommand.php(119): Rector\Core\Application\ApplicationFileProcessor->run()
#29 /var/www/fixer/vendor/rector/rector/vendor/symfony/console/Command/Command.php(307): Rector\Core\Console\Command\ProcessCommand->execute()
#30 /var/www/fixer/vendor/rector/rector/vendor/symfony/console/Application.php(891): RectorPrefix202208\Symfony\Component\Console\Command\Command->run()
#31 /var/www/fixer/vendor/rector/rector/vendor/symfony/console/Application.php(310): RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand()
#32 /var/www/fixer/vendor/rector/rector/src/Console/ConsoleApplication.php(49): RectorPrefix202208\Symfony\Component\Console\Application->doRun()
#33 /var/www/fixer/vendor/rector/rector/vendor/symfony/console/Application.php(208): Rector\Core\Console\ConsoleApplication->doRun()
#34 /var/www/fixer/vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()
#35 /var/www/fixer/vendor/rector/rector/bin/rector(5): require_once('...')
#36 /var/www/fixer/vendor/bin/rector(120): include('...')
#37 {main}
  thrown in /var/www/fixer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
Script /var/www/fixer/vendor/bin/rector process handling the rector event returned with error code 255
```

**Comment by samsonasik** [comment]
Could you try latest dev-main ? 

```bash
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by shinsenter** [comment]
@samsonasik 
It gave me more errors:

```

[ERROR] "System error: "Node "PhpParser\Node\Expr\BinaryOp\NotEqual" with
        parent of "PhpParser\Node\Stmt\If_" is missing scope required for scope
        refresh."
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 88
        
[ERROR] "System error: "PhpParser\Internal\TokenStream::getIndentationBefore():
        Return value must be of type int, null returned"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 205
        
[ERROR] "Child process error: Killed
        ".
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "System error: "Scope not available on "PhpParser\Node\Expr\Assign"
        node with parent node of "PhpParser\Node\Stmt\Expression", but is
        required by a refactorWithScope() method of
        "Rector\CodeQuality\Rector\PropertyFetch\ExplicitMethodCallOverMagicGet
        SetRector" rule. Fix scope refresh on changed nodes first"
        Run Rector with "--debug" option and post the report here:
        https://github.com/rectorphp/rector/issues/new". On line: 54
        
[ERROR] "Child process error: PHP Warning:  Undefined array key -1 in
        vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/Tok
        enStream.php:205
        Warning: Undefined array key -1 in
        vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Internal/Tok
        enStream.php:205
        Killed
        ".
```

**Comment by samsonasik** [comment]
Could you narrow it down to specific rules and the code that cause it? For multiple rules applied, you can create failing test case PR to 
https://github.com/rectorphp/rector-src/tree/main/tests/Issues

You can copy and modify on of the tests

**Comment by shinsenter** [comment]
@samsonasik 
The source code that I'm working with contains too many files for me to go deeper.
I think I should close this issue and find some workarounds.
