### ISSUE TITLE
Symfony 44 - error for 4 Controllers

### ISSUE THREAD

**Issue by ksiatka** [rectorphp/rector#7419]
Debug trace for single Controller:

``` [ERROR] Could not process "src/Controller/Api/Recipe/RecipeController.php" file, due to:    
"System error: "Internal error."       

Stack trace:
#0 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(302):    
PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), 
Object(PHPStan\Analyser\MutatingScope), Object(Closure)) 
#1 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(299):    
PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#2 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(213):    
Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles(Object(RectorPrefix20220
8\Symplify\SmartFileSystem\SmartFileInfo), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))     
#3 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(99): 
Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, 
Object(RectorPrefix202208\Symplify\SmartFileSystem\SmartFileInfo), Object(PHPStan\Analyser\MutatingScope))     
#4 vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php(39):       
Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Stmt\ClassMethod),   
Object(PHPStan\Analyser\MutatingScope), Object(RectorPrefix202208\Symplify\SmartFileSystem\SmartFileInfo))     
#5 vendor/rector/rector/src/Rector/AbstractRector.php(206):       
Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))        
#6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):        
Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))        
#7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):        
PhpParser\NodeTraverser->traverseArray(Array)   
#8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):        
PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))  
#9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):        
PhpParser\NodeTraverser->traverseArray(Array)   
#10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):       
PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))       
#11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):        
PhpParser\NodeTraverser->traverseArray(Array)   
#12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):   
PhpParser\NodeTraverser->traverse(Array)        
#13 vendor/rector/rector/src/Application/FileProcessor.php(61):   
Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)   
#14 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):   
Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),     
Object(Rector\Core\ValueObject\Configuration))  
#15 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):    
Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
tion\File), Object(Rector\Core\ValueObject\Configuration))        
#16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):  
Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
Object(Rector\Core\ValueObject\Configuration))  
#17 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): 
Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)    
#18 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):    
RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)    
#19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): 
RectorPrefix202208\Clue\React\NDJson\Decoder->handleData(Array)   
#20 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202208\Evenement\EventEmitter->emit('data',
Array)      
#21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): 
RectorPrefix202208\React\Stream\Util::RectorPrefix202208\React\Stream\{closure}('{"action":"main...') 
#22 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):     
RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)    
#23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):     
RectorPrefix202208\React\Stream\DuplexResourceStream->handleData(Resource id #2876) 
#24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):     
RectorPrefix202208\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)    
#25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):        
RectorPrefix202208\React\EventLoop\StreamSelectLoop->run()        
#26 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):  
Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput)
, Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))        
#27 vendor/rector/rector/vendor/symfony/console/Application.php(891):      
RectorPrefix202208\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202208\Symfony\Component\Console\I
nput\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))  
#28 vendor/rector/rector/vendor/symfony/console/Application.php(310):      
RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
), Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),   
Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput)) 
#29 vendor/rector/rector/src/Console/ConsoleApplication.php(49):  
RectorPrefix202208\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Inp
ut\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))    
#30 vendor/rector/rector/vendor/symfony/console/Application.php(208):      
Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput)) 
#31 vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()  
#32 vendor/rector/rector/bin/rector(5): require_once('/var/www/xyz...') 
#33 {main}". On line: 372```

**Comment by TomasVotruba** [comment]
Hi, 

this does not tell anything useful.
we'll need a reproducible demo or repository.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with the reproducer :+1:
