### ISSUE TITLE
Fatal Error : Uncaught ReflectionException Symplify\SmartFileSystem

### ISSUE THREAD

**Issue by amalricBzh** [rectorphp/rector#7449]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector Version | 0.14.1             |

## Description
New Symfony 6.1.4 (last version) application on php 8.1 with a single controller diplaying static page.

    composer require rector/rector --dev
    vendor/bin/rector init

Customize rector.php with

    // register a single rule
    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        LevelSetList::UP_TO_PHP_81,
        SymfonySetList::SYMFONY_STRICT,
        SymfonySetList::SYMFONY_60,
        SymfonySetList::SYMFONY_CODE_QUALITY,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
        SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
        //DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
        SensiolabsSetList::FRAMEWORK_EXTRA_61,
    ]);

Then start rector:

    vendor/bin/recor process src --dry-run

Result:
````
Fatal error: Uncaught ReflectionException: Class "RectorPrefix202209\Symplify\SmartFileSystem\SmartFileSystem" does not exist in /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php:893
Stack trace:
#0 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(893): ReflectionClass->__construct('RectorPrefix202...')
#1 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'RectorPrefix202...')
#2 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('RectorPrefix202...', 1, Array, true)
#3 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#4 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#5 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Symfony\\...')
#6 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Symfony\\...', 1, Array, true)
#7 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#8 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#9 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Symfony\\...')
#10 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Symfony\\...', 1, Array, true)
#11 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#12 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#13 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Symfony\\...')
#14 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Symfony\\...', 1, Array, true)
#15 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#16 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#17 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Symfony\\...')
#18 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Symfony\\...', 1, Array, true)
#19 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Reference), Array, true)
#20 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#21 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#22 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Rep...')
#23 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Rep...', 1, Array, true)
#24 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#25 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#26 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Con...')
#27 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Con...', 1, Array, true)
#28 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Reference), Array, true)
#29 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#30 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#31 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Con...')
#32 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Con...', 1)
#33 /var/www/vendor/rector/rector/bin/rector.php(127): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->get('Rector\\Core\\Con...')
#34 /var/www/vendor/rector/rector/bin/rector(5): require_once('/var/www/vendor...')
#35 /var/www/vendor/bin/rector(120): include('/var/www/vendor...')
#36 {main}
  thrown in /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php on line 893
````

## No issue with version 0.14.0

Downgrading to rector 0.14.0 makes rector ok :

    composer require rector/rector:0.14.0 --dev
    vendor/bin/rector process src --dry-run

=> Rector will work fine.

**Comment by TomasVotruba** [comment]
Hi, I've just tried the same install process and everything works well:

![image](https://user-images.githubusercontent.com/924196/188289394-24349335-c9d4-48cd-a771-23dd1692e18e.png)


Could you share a reproducible repository with Github Action on Github? We'll need it to find out what is wrong.

**Comment by samsonasik** [comment]
You may need to ensure remove cache:

```bash
# ensure remove cache directory
php -r 'shell_exec("rm -rf " . sys_get_temp_dir() . "/rector_cached_files");';

bin/rector --version --clear-cache
```

**Comment by PhilETaylor** [comment]
I hate to be that person that puts a +1 but I do have this :)

**Comment by PhilETaylor** [comment]
So I have debugged this rule by rule (based on my 155 line rector.php) 

If I enable ANY ONE of these Rules or Sets then the problem is replicated:
If I comment out JUST these rules and leave all my other rules, then the problem disappears.

```
    $rectorConfig->rule(ContainerGetToConstructorInjectionRector::class);
    $rectorConfig->rule(FormTypeGetParentRector::class);
    $rectorConfig->rule(ChangeStringCollectionOptionToConstantRector::class);
    $rectorConfig->sets(
        [
            SymfonySetList::SYMFONY_CODE_QUALITY,
            SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
        ]
    );
```

**Comment by Slurp** [comment]
Seems that with the build the vendor map is missing for the SmartFileSystem

![image](https://user-images.githubusercontent.com/155636/188314091-34f1eb26-21f5-4cd5-b255-7386d9a3a9db.png)

**Comment by amalricBzh** [comment]
@samsonasik : A fresh new Rector install ? There is no cache yet. But ok, I tried it:

    rm -rf /tmp/rector_cached_files/
    php vendor/bin/rector process src --dry-run

=> Same error. The rector cache is not the problem.

**Comment by PhilETaylor** [comment]
Its simple to replicate

Here is a reproducer https://github.com/PhilETaylor/rector-bug-7449 this was created with:

```
symfony new my_project_directory --version="6.1.*" --webapp
cd my_project_directory
composer require rector/rector
```

```php 
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Symfony\Rector\ClassMethod\FormTypeGetParentRector;
use Rector\Symfony\Rector\MethodCall\ChangeStringCollectionOptionToConstantRector;
use Rector\Symfony\Rector\MethodCall\ContainerGetToConstructorInjectionRector;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->parallel();
    $rectorConfig->paths([__DIR__ . '/src']);

    $rectorConfig->rule(ContainerGetToConstructorInjectionRector::class);

    // All these rules fail with the same error
//    $rectorConfig->rule(FormTypeGetParentRector::class);
//    $rectorConfig->rule(ChangeStringCollectionOptionToConstantRector::class);
//    $rectorConfig->sets(
//        [
//            SymfonySetList::SYMFONY_CODE_QUALITY,
//            SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
//        ]
//    );
};
```

**Comment by TomasVotruba** [comment]
Thank you for sponsoring :tada: 

I'm looking into this..

**Comment by PhilETaylor** [comment]
> I'm looking into this...

Absolutely no rush at all, especially on a Sunday unless you have free time. The fix for most people for now is to simply downgrade or remove the rules that cause this temporarily. Nothing here is broken that causes a huge issue in a pipeline.

**Comment by TomasVotruba** [comment]
I have a few dozens minutes to help out :+1: 

This should do the job:
https://github.com/rectorphp/rector-symfony/commit/805e0080e23561ae59087536d1695e1773fee9ad

New Rector version is being build, ETA 10 mins: https://github.com/rectorphp/rector


Thanks for perfect repository reproducer :clap:  You made it easier for me to find the broken place and find the fix.

**Comment by TomasVotruba** [comment]
Looks good :+1: 

![Uploading image.png…]()

**Comment by PhilETaylor** [comment]
<img width="334" alt="Screen Shot 2022-09-04 at 17 23 06" src="https://user-images.githubusercontent.com/400092/188323361-59586784-8b7e-408d-a492-44b65564f29d.png">

**Comment by PhilETaylor** [comment]
Just to circle back to say I upgraded to 0.4.12 and this problem is resolved like a boss in the reproducer - and in my project for real! 🎉 🍺 Thanks! 

<img width="1480" alt="Screen Shot 2022-09-04 at 18 32 00" src="https://user-images.githubusercontent.com/400092/188326130-32adaa0f-ea72-4ae0-8f2f-cbeb2073117e.png">

**Comment by TomasVotruba** [comment]
Thanks for reachign out with good news.

I'm glad it works well :clap:

**Comment by amalricBzh** [comment]
Version 0.14.2 is OK for me too ! Thank you so much :ok_hand:
