### ISSUE TITLE
No support for phpstan/phpstan-strict-rules 1.4.4

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector#7509]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.3           |

https://github.com/phpstan/phpstan-strict-rules/commit/23e5f377ee6395a1a04842d3d6ed4bd25e7b44a6 added array value to `disallowedLooseComparison`

I'm getting to no error when running phpstan. Rector throws exception though

```
PHP Fatal error:  Uncaught _PHPStan_52b7bec27\Nette\DI\InvalidConfigurationException: The item 'conditionalTags › PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule › phpstan.rules.rule' expects to be bool, array given. in phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:219
Stack trace:
#0 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(178): _PHPStan_52b7bec27\Nette\DI\Compiler->processSchema()
#1 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(158): _PHPStan_52b7bec27\Nette\DI\Compiler->processExtensions()
#2 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_52b7bec27\Nette\DI\Compiler->compile()
#3 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(66): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->generate()
#4 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->loadFile()
#5 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(40): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->load()
#6 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(175): PHPStan\DependencyInjection\Configurator->loadContainer()
#7 phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(81): _PHPStan_52b7bec27\Nette\Bootstrap\Configurator->createContainer()
#8 /project/vendor/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(45): PHPStan\DependencyInjection\ContainerFactory->create()
#9 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#10 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(894): ReflectionClass->newInstanceArgs()
#11 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#12 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#13 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(870): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#14 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#15 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#16 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#17 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#18 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#19 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#20 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#21 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#22 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#23 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#24 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#25 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#26 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#27 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#28 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#29 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#30 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#31 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#32 /project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#33 /project/vendor/rector/rector/bin/rector.php(127): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->get()
#34 /project/vendor/rector/rector/bin/rector(5): require_once('...')
#35 /project/vendor/bin/rector(117): include('...')
  thrown in phar:///project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php on line 219#36 {main}
```

**Comment by VincentLanglet** [comment]
I don't know how rector works/rely on phpstan. Why is the reason that such a "tiny" modification in phpstan is breaking rector ? It would having rector to be more permissive about phpstan upgrade.

**Comment by simPod** [comment]
I guess it might be the breaking change on phpstan's side. Since Rector relies on older phpstan version it does not accept array values because only boolean was accepted previously.

**Comment by samsonasik** [comment]
`phpstan-strict-rules` released 3 days ago, latest build dev-main is 2 days ago.

That’s should already in dev-main, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by simPod** [comment]
Cool. I'll wait for release then.

**Comment by samsonasik** [comment]
Rector 0.14.4 released for it https://github.com/rectorphp/rector/releases/tag/0.14.4

**Comment by simPod** [comment]
Fix confirmed, thanks
