### ISSUE TITLE
Missing scope required for scope refresh

### ISSUE THREAD

**Issue by RijaRR** [rectorphp/rector#7522]
# Bug Report

| Missing scope required for scope refresh        | Error when running the process on a specific file                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.5            |

I am launching  a `process --dry-run ` command to analyze a directory. Every thing works fine except for a specific file. It gets this error.

```
[ERROR] Could not process                                                                                              
         "/var/www/html/SPIP32/client/plugins/datepromotion/datepromotion_admin_produit_onglet_information_td_promo.php" file,
         due to:                                                                                                        
         "System error: "Node "Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace" with parent of               
         "Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace" is missing scope required for scope refresh."     
                                                                                                                        
         Stack trace:                                                                                                   
         #0 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Rector/AbstractRector.php(244):        
         Rector\Core\Application\ChangedNodeScopeRefresher->refresh()                                                   
         #1                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php
         (176): Rector\Core\Rector\AbstractRector->enterNode()                                                          
         #2                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php
         (105): PhpParser\NodeTraverser->traverseArray()                                                                
         #3                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php
         (196): PhpParser\NodeTraverser->traverseNode()                                                                 
         #4                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php
         (85): PhpParser\NodeTraverser->traverseArray()                                                                 
         #5                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42)
         : PhpParser\NodeTraverser->traverse()                                                                          
         #6 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Application/FileProcessor.php(60):     
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                            
         #7                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(133)
         : Rector\Core\Application\FileProcessor->refactor()                                                            
         #8                                                                                                             
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100)
         : Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()                           
         #9 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/packages/Parallel/WorkerRunner.php(98):    
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #10                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTr
         ait.php(97): Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                         
         #11 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):
         RectorPrefix202209\Evenement\EventEmitter->emit()                                                              
         #12                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTr
         ait.php(97): RectorPrefix202209\Clue\React\NDJson\Decoder->handleData()                                        
         #13 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/react/stream/src/Util.php(62):     
         RectorPrefix202209\Evenement\EventEmitter->emit()                                                              
         #14                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTr
         ait.php(97): RectorPrefix202209\React\Stream\Util::RectorPrefix202209\React\Stream\{closure}()                 
         #15                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202209\Evenement\EventEmitter->emit()                                                              
         #16                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202209\React\Stream\DuplexResourceStream->handleData()                                             
         #17                                                                                                            
         /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202209\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #18 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202209\React\EventLoop\StreamSelectLoop->run()                                                     
         #19 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #20 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/symfony/console/Application.php(894):
         RectorPrefix202209\Symfony\Component\Console\Command\Command->run()                                            
         #21 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/symfony/console/Application.php(310):
         RectorPrefix202209\Symfony\Component\Console\Application->doRunCommand()                                       
         #22 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/src/Console/ConsoleApplication.php(49):   
         RectorPrefix202209\Symfony\Component\Console\Application->doRun()                                              
         #23 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/vendor/symfony/console/Application.php(208):
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #24 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/bin/rector.php(128):                      
         RectorPrefix202209\Symfony\Component\Console\Application->run()                                                
         #25 /home/rija/Documents/tickets/suppr/testpush/vendor/rector/rector/bin/rector(5): require_once('/home/rija/Docu...')
         #26 {main}". On line: 85
```

## Minimal PHP Code Causing Issue

```
<?php 

	$plugin = new Datemdpt();
	$plugin->charger_produit($GLOBALS['produit']->id);
	$zdrt = $plugin->siDansPeriodezdrt(true);

	$infoCasInzdrt = '';
	if(is_bool($zdrt)) $infoCasInzdrt = "
		<tr zdrt='$zdrt' finzdrt='$plugin->zfdt'>
			<td colspan='2'>
				le ".$plugin->tempsLabel($plugin->zfdtm).",  de $plugin->zfdtmfdse et de $plugin->sdfezr jour(s).
			</td>
		</tr>";
	
	$templateDF = "
		<table id='datemdpt_container' class='table table-striped'>
			<tbody>
				$infoCasInzdrt
				<tr>
					<td>Date limite</td>
					<td><input type='date' name='datemdpt_fin' value='$plugin->amldf' class='pull-right'/></td>
				</tr>
				<tr>
					<td>Durée bost zdrt (en jour)</td>
					<td><input type='number' min='0' name='datemdpt_zfdtmfdse' value='$plugin->zfdtmfdse' class='pull-right'/></td>
				</tr>
				<tr>
					<td>Durée bost inzdrt (en jour)</td>
					<td><input type='number' min='0' name='datemdpt_sdfezr' value='$plugin->sdfezr' class='pull-right'/></td>
				</tr>
				<tr>
					<td>Texte</td>
					<td><textarea name='datemdpt_texte' class='pull-right'>$plugin->texte</textarea></td>
				</tr>
			</tbody>
		</table>
	";

	echo $templateDF;
?>
```

## Expected Behaviour

no error

**Comment by samsonasik** [comment]
Could you reproduce at https://getrector.org/demo ?
