### ISSUE TITLE
Error on rector process (PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule)

### ISSUE THREAD

**Issue by Methraen** [rectorphp/rector#7526]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.3 |
| PHP version | 8.1.10 |
| Symfony version | 6.1 |
| PHPSTAN version | 1.8.6 |
| PHPCSFIXER version | 3.11.0 |

Error on `rector process` :
`The item 'conditionalTags › PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule › phpstan.rules.rule' expects to be bool, array given.`

If i comment those lines in the rules.neon (phpstan's vendor) it works fine but well it's not really a solution :
```
#	PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule:
#		phpstan.rules.rule: %strictRules.disallowedLooseComparison%
```

## Minimal PHP Code Causing Issue
```
Fatal error: Uncaught _PHPStan_52b7bec27\Nette\DI\InvalidConfigurationException: The item 'conditionalTags › PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule › phpstan.rules.rule' expects to be bool, array given. in phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:219
Stack trace:
#0 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(178): _PHPStan_52b7bec27\Nette\DI\Compiler->processSchema(Object(_PHPStan_52b7bec27\Nette\Schema\Elements\Type), Array, 'conditionalTags')
#1 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(158): _PHPStan_52b7bec27\Nette\DI\Compiler->processExtensions()
#2 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_52b7bec27\Nette\DI\Compiler->compile()
#3 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(66): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->generate('Container_06472...', Array)
#4 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->loadFile('Container_06472...', Array)
#5 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(40): _PHPStan_52b7bec27\Nette\DI\ContainerLoader->load(Array, Array)
#6 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(175): PHPStan\DependencyInjection\Configurator->loadContainer()
#7 phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(81): _PHPStan_52b7bec27\Nette\Bootstrap\Configurator->createContainer()
#8 /var/www/vendor/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(45): PHPStan\DependencyInjection\ContainerFactory->create('/tmp', Array, Array)
#9 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct(Object(Rector\Core\Configuration\Parameter\ParameterProvider))
#10 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(894): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\NodeType...')
#12 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\NodeType...', 1, Array, true)
#13 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(870): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Reference), Array, true)
#14 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\NodeType...')
#15 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\NodeType...', 1, Array, true)
#16 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#17 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#18 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Sta...')
#19 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Sta...', 1, Array, true)
#20 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#21 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#22 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Aut...')
#23 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Aut...', 1, Array, true)
#24 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\TypedReference), Array, true)
#25 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#26 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Con...')
#27 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Con...', 1, Array, true)
#28 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Reference), Array, true)
#29 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#30 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, true)
#31 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(RectorPrefix202209\Symfony\Component\DependencyInjection\Definition), Array, true, 'Rector\\Core\\Con...')
#32 /var/www/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Rector\\Core\\Con...', 1)
#33 /var/www/vendor/rector/rector/bin/rector.php(127): RectorPrefix202209\Symfony\Component\DependencyInjection\ContainerBuilder->get('Rector\\Core\\Con...')
#34 /var/www/vendor/rector/rector/bin/rector(5): require_once('/var/www/vendor...')
#35 /var/www/vendor/bin/rector(120): include('/var/www/vendor...')
#36 {main}
  thrown in phar:///var/www/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php on line 219
```

## Expected Behaviour

CODE (rector.php) :
```
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector;
use Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector;
use Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector;
use Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
use Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector;
use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\EarlyReturn\Rector\If_\ChangeIfElseValueAssignToEarlyReturnRector;
use Rector\EarlyReturn\Rector\If_\RemoveAlwaysElseRector;
use Rector\EarlyReturn\Rector\StmtsAwareInterface\ReturnEarlyIfVariableRector;
use Rector\Naming\Rector\ClassMethod\RenameParamToMatchTypeRector;
use Rector\PHPUnit\Set\PHPUnitSetList;
use Rector\Privatization\Rector\Class_\ChangeReadOnlyVariableWithDefaultValueToConstantRector;
use Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector;
use Rector\Privatization\Rector\Property\ChangeReadOnlyPropertyWithDefaultValueToConstantRector;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;
use Rector\TypeDeclaration\Rector\ClassMethod\ArrayShapeFromConstantArrayReturnRector;
use Rector\Visibility\Rector\ClassMethod\ExplicitPublicClassMethodRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
        __DIR__ . '/*.php',
    ]);

    $rectorConfig->importNames();

    // Sets
    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
        SetList::NAMING,
        SetList::PRIVATIZATION,
        SetList::TYPE_DECLARATION_STRICT,
    ]);

    // Symfony
    $rectorConfig->symfonyContainerXml(__DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml');

    $rectorConfig->sets([
        SymfonySetList::SYMFONY_60,
        SymfonySetList::SYMFONY_CODE_QUALITY,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,
    ]);

    // Doctrine
    $rectorConfig->sets([
        DoctrineSetList::DOCTRINE_CODE_QUALITY,
    ]);

    // PHPUnit
    $rectorConfig->sets([
        PHPUnitSetList::PHPUNIT_91,
        PHPUnitSetList::PHPUNIT_CODE_QUALITY,
        PHPUnitSetList::PHPUNIT_EXCEPTION,
        PHPUnitSetList::REMOVE_MOCKS,
        PHPUnitSetList::PHPUNIT_SPECIFIC_METHOD,
        PHPUnitSetList::PHPUNIT_YIELD_DATA_PROVIDER,
    ]);

    // PHPStan
    $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon');

    // Rules
    $rectorConfig->rules([
        ExplicitPublicClassMethodRector::class,
        ChangeIfElseValueAssignToEarlyReturnRector::class,
        RemoveAlwaysElseRector::class,
        ReturnEarlyIfVariableRector::class,
    ]);

    // Remove rules
    $rectorConfig->skip([
        ArrayShapeFromConstantArrayReturnRector::class,
        BinarySwitchToIfElseRector::class => [__DIR__ . '/src/*/DTO/*'],
        CallableThisArrayToAnonymousFunctionRector::class,
        ChangeReadOnlyVariableWithDefaultValueToConstantRector::class,
        ChangeReadOnlyPropertyWithDefaultValueToConstantRector::class => [__DIR__ . '/src/*/Entity/*'],
        ConsistentImplodeRector::class,
        FinalizeClassesWithoutChildrenRector::class,
        NewlineAfterStatementRector::class,
        RemoveAlwaysTrueIfConditionRector::class,
        RenameParamToMatchTypeRector::class,
        VarConstantCommentRector::class,
    ]);

    // Risky rules (uncomment them and launch rector with --dry-run to check that you did not do a potential mistake)
//    $rectorConfig->rules([
//        RemoveAlwaysTrueIfConditionRector::class
//    ]);
};
```

**Comment by samsonasik** [comment]
That’s should already solved in dev-main that include latest phpstan, you can try:

```
composer config minimum-stability dev
composer config prefer-stable true
composer update --dev rector/rector:dev-main -W
```

**Comment by Methraen** [comment]
Indeed, ty for your quick answer, sorry about the duplicate, 'should have looked in closed issues first.
