### ISSUE TITLE
Crash due to passing VariadicPlaceholder to BuilderHelpers::normalizeValue

### ISSUE THREAD

**Issue by alcohol** [rectorphp/rector#7548]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

## Minimal PHP Code Causing Issue

[https://getrector.org/demo/9a1bd169-dd1f-45bf-9e6c-378b355038ff](https://getrector.org/demo/9a1bd169-dd1f-45bf-9e6c-378b355038ff)

## Expected Behaviour

Should not crash. Shortened stacktrace with --debug:

```
Fatal error: Uncaught LogicException: Invalid value in /srv/tools/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/BuilderHelpers.php:212
Stack trace:
#0 /srv/tools/rector/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/BuilderFactory.php(248): PhpParser\BuilderHelpers::normalizeValue(Object(PhpParser\Node\VariadicPlaceholder))
#1 /srv/tools/rector/vendor/rector/rector/src/PhpParser/Node/NodeFactory.php(145): PhpParser\BuilderFactory->args(Array)
#2 /srv/tools/rector/vendor/rector/rector/src/PhpParser/Node/NodeFactory.php(283): Rector\Core\PhpParser\Node\NodeFactory->createArgs(Array)
#3 /srv/tools/rector/vendor/rector/rector/rules/Php70/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php(123): Rector\Core\PhpParser\Node\NodeFactory->createStaticCall('static', 'topLevelDomain', Array)
#4 /srv/tools/rector/vendor/rector/rector/src/Rector/AbstractRector.php(214): Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
```

**Comment by samsonasik** [comment]
It seems on `ThisCallOnStaticMethodToStaticCallRector`, ref https://getrector.org/demo/bfd9a296-3622-4ec2-bef3-c5c75704c2c0
