### ISSUE TITLE
Could not process "/var/www/html/src/XXX/Command/XXXCommandTrait.php" file, due to: System error: "Class 'RectorPrefix202210\Symplify\PackageBuilder\Reflection\PrivatesCaller' not found"

### ISSUE THREAD

**Issue by PhilippSchreiber** [rectorphp/rector#7613]
```Stack trace:
         #0 vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php(125):
         Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector->splitProcessCommandToItems()
         #1 vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php(100):
         Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector->processStringType()
         #2 vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php(69):
         Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector->processArgumentPosition()
         #3 vendor/rector/rector/src/Rector/AbstractRector.php(214):
         Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector->refactor()
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode()
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode()
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #14 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse()
         #15 vendor/rector/rector/src/Application/FileProcessor.php(60):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #16 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(133):
         Rector\Core\Application\FileProcessor->refactor()
         #17 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
         #18 vendor/rector/rector/packages/Parallel/WorkerRunner.php(98):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()
         #20 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):
         RectorPrefix202210\Evenement\EventEmitter->emit()
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202210\Clue\React\NDJson\Decoder->handleData()
         #22 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202210\Evenement\EventEmitter->emit()
         #23 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202210\React\Stream\Util::RectorPrefix202210\React\Stream\{closure}()
         #24 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202210\Evenement\EventEmitter->emit()
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202210\React\Stream\DuplexResourceStream->handleData()
         #26 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202210\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #27 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202210\React\EventLoop\StreamSelectLoop->run()
         #28 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(894):
         RectorPrefix202210\Symfony\Component\Console\Command\Command->run()
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(310):
         RectorPrefix202210\Symfony\Component\Console\Application->doRunCommand()
         #31 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202210\Symfony\Component\Console\Application->doRun()
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(208): Rector\Core\Console\ConsoleApplication->doRun()
         #33 vendor/rector/rector/bin/rector.php(128): RectorPrefix202210\Symfony\Component\Console\Application->run()
         #34 vendor/rector/rector/bin/rector(4): require_once('v...')
         #35 bin/rector(115): include('v...')
         #36 {main}". On line: 135```

**Comment by samsonasik** [comment]
@PhilippSchreiber It seems due to `vendor/symplify/package-builder` not in prefixed vendor:

https://github.com/rectorphp/rector/tree/dcc7f6941eab170f4e021c52e05c709df3b7ae64/vendor/symplify

The code should can be replaced with: `Rector\Core\Util\Reflection\PrivatesAccessor`

could you try provide a PR patch to rector-symfony at 

https://github.com/rectorphp/rector-symfony/blob/695c960e7713438ef1077bebcbc6d298a95020d1/src/Rector/New_/StringToArrayArgumentProcessRector.php#L152

to something like:

```php
        $privatesCaller = new \Rector\Core\Util\Reflection\PrivatesAccessor();
        return $privatesCaller->callPrivateMethod(new StringInput(''), 'tokenize', [$process]);

```

thank you.

**Comment by PhilippSchreiber** [comment]
Thanks @samsonasik. PR created.
