### ISSUE TITLE
NullToStrictStringFuncCallArgRector error: in_array(): Argument #2 ($haystack) must be of type array, null given

### ISSUE THREAD

**Issue by tourze** [rectorphp/rector#7618]
# Bug Report

Stack:

```
 [ERROR] Could not process "LoyaltyService.php" file, due to:
         "System error: "in_array(): Argument #2 ($haystack) must be of type array, null given"

         Stack trace:
         #0 vendor/rector/rector/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php(217): in_array('string',
         NULL, true)
         #1 vendor/rector/rector/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php(99):
         Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector->resolveOriginalPositions(Object(PhpParser\Node\Expr\F
         uncCall))
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(204):
         Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector->refactor(Object(PhpParser\Node\Expr\FuncCall))
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #16 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse(Array)
         #17 vendor/rector/rector/src/Application/FileProcessor.php(61):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #18 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #19 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))
         #20 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #22 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)
         #23 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202208\Clue\React\NDJson\Decoder->handleData(Array)
         #24 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202208\Evenement\EventEmitter->emit('data',
         Array)
         #25 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202208\React\Stream\Util::RectorPrefix202208\React\Stream\{closure}('{"action":"main...')
         #26 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)
         #27 [internal function]: RectorPrefix202208\React\Stream\DuplexResourceStream->handleData(Resource id #3222)
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201): call_user_func(Array, Resource id #3222)
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->run()
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(891):
         RectorPrefix202208\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202208\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(310):
         RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202208\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(208):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))
         #36 vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()
         #37 vendor/rector/rector/bin/rector(5): require_once('/Users/lzp/work...')
         #38 vendor/bin/rector(120): include('/Users/lzp/work...')
         #39 {main}". On line: 217
```

In this line https://github.com/rectorphp/rector/blob/fde9488adfea6c97e97e44bd2366e8d87b010aa8/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php#L214, seems that $argNames will be null sometimes.

For developer, it is really hard to detect which line is wrong.
How about add some check and throw Exception:

```
        $argNames = self::ARG_POSITION_NAME_NULL_TO_STRICT_STRING[$functionName];
        if ($argNames === null) {
            throw new \Exception("Error to get arguments while passing function:{$functionName}");
        }
```

## Expected Behaviour

Run passed.

**Comment by tourze** [comment]
In my case, the error code is that: developer use "MD5" function, and the normal function name should be "md5". It is hard to find it out.

**Comment by samsonasik** [comment]
I can't reproduce it https://getrector.org/demo/27160983-7876-4585-b5d1-ee1f702f16be

Please try latest version.
