### ISSUE TITLE
process fails with newest phpstan/* `deprecationRulesInstalled` parameer

### ISSUE THREAD

**Issue by mvhirsch** [rectorphp/rector#7663]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| php | 8.1 |
| Rector version | v0.15.0  |
| phpstan/phpstan | 1.9.3 | 
| phpstan/phpstan-deprecation-rules | 1.1.0 |
| phpstan/phpstan-phpunit | 1.3.1 |

Rector throws an exception, using up-to-date phpstan-deps: `Uncaught _PHPStan_582a9cb8b\Nette\InvalidArgumentException: Missing parameter 'deprecationRulesInstalled'`

```
symfony php vendor/bin/rector process
PHP Fatal error:  Uncaught _PHPStan_582a9cb8b\Nette\InvalidArgumentException: Missing parameter 'deprecationRulesInstalled'. in phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php:62
Stack trace:
#0 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_582a9cb8b\Nette\DI\Helpers::expand()
#1 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_582a9cb8b\Nette\DI\Helpers::expand()
#2 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/DefinitionSchema.php(139): _PHPStan_582a9cb8b\Nette\DI\Helpers::expand()
#3 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/DefinitionSchema.php(41): _PHPStan_582a9cb8b\Nette\DI\Config\DefinitionSchema->expandParameters()
#4 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Elements/Type.php(153): _PHPStan_582a9cb8b\Nette\DI\Config\DefinitionSchema->complete()
#5 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php(57): _PHPStan_582a9cb8b\Nette\Schema\Elements\Type->complete()
#6 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(217): _PHPStan_582a9cb8b\Nette\Schema\Processor->processMultiple()
#7 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(185): _PHPStan_582a9cb8b\Nette\DI\Compiler->processSchema()
#8 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(158): _PHPStan_582a9cb8b\Nette\DI\Compiler->processExtensions()
#9 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_582a9cb8b\Nette\DI\Compiler->compile()
#10 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(66): _PHPStan_582a9cb8b\Nette\DI\ContainerLoader->generate()
#11 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_582a9cb8b\Nette\DI\ContainerLoader->loadFile()
#12 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(51): _PHPStan_582a9cb8b\Nette\DI\ContainerLoader->load()
#13 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(175): PHPStan\DependencyInjection\Configurator->loadContainer()
#14 phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(107): _PHPStan_582a9cb8b\Nette\Bootstrap\Configurator->createContainer()
#15 /path/to/project/vendor/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(45): PHPStan\DependencyInjection\ContainerFactory->create()
#16 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#17 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(894): ReflectionClass->newInstanceArgs()
#18 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#19 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#20 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(870): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#21 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#22 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#23 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#24 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#25 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#26 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#27 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#28 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#29 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#30 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#31 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#32 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#33 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#34 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(1002): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#35 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#36 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(955): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#37 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(880): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#38 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(490): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#39 /path/to/project/vendor/rector/rector/vendor/symfony/dependency-injection/ContainerBuilder.php(441): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#40 /path/to/project/vendor/rector/rector/bin/rector.php(127): RectorPrefix202211\Symfony\Component\DependencyInjection\ContainerBuilder->get()
#41 /path/to/project/vendor/rector/rector/bin/rector(5): require_once('...')
#42 /path/to/project/vendor/bin/rector(120): include('...')
#43 {main}
  thrown in phar:///path/to/project/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php on line 62
```

## Minimal PHP Code Causing Issue

Needs dependencies above (in latest versions). Does not require a special rector.php (will fail on a simple one too):

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__.'/src',
    ]);
```

**Comment by mvhirsch** [comment]
Current workaround: downgrading and pinning both phpstan-deps:

```bash
composer require phpstan/phpstan-deprecation-rules 1.0.0
composer require phpstan/phpstan-phpunit 1.3.0
```

**Comment by samsonasik** [comment]
You can use `"rector/rector": "dev-main"` while wait for next release.

**Comment by samsonasik** [comment]
Rector 0.15.1 released for it https://github.com/rectorphp/rector/releases/tag/0.15.1
