### ISSUE TITLE
After a recent composer update rector is unable to audit some files

### ISSUE THREAD

**Issue by chris-archer-whisky** [rectorphp/rector#7664]
`"System error: "Undefined constant PHPStan\PhpDocParser\Ast\Type\GenericTypeNode::VARIANCE_INVARIANT"          
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 369`
         
``` Stack trace:                                                                                                   
         #0 vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(330):                                                
         PHPStan\PhpDocParser\Parser\TypeParser->parseGenericTypeArgument(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
         #1 vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(115):                                                
         PHPStan\PhpDocParser\Parser\TypeParser->parseGeneric(Object(PHPStan\PhpDocParser\Parser\TokenIterator),        
         Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))                                                      
         #2 vendor/phpstan/phpdoc-parser/src/Parser/TypeParser.php(29):                                                 
         PHPStan\PhpDocParser\Parser\TypeParser->parseAtomic(Object(PHPStan\PhpDocParser\Parser\TokenIterator))         
         #3 vendor/phpstan/phpdoc-parser/src/Parser/PhpDocParser.php(266):                                              
         PHPStan\PhpDocParser\Parser\TypeParser->parse(Object(PHPStan\PhpDocParser\Parser\TokenIterator))               
         #4 vendor/phpstan/phpdoc-parser/src/Parser/PhpDocParser.php(130):                                              
         PHPStan\PhpDocParser\Parser\PhpDocParser->parseParamTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
         #5 vendor/phpstan/phpdoc-parser/src/Parser/PhpDocParser.php(115):                                              
         PHPStan\PhpDocParser\Parser\PhpDocParser->parseTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator),     
         '@psalm-param')                                                                                                
         #6 vendor/phpstan/phpdoc-parser/src/Parser/PhpDocParser.php(76):                                               
         PHPStan\PhpDocParser\Parser\PhpDocParser->parseTag(Object(PHPStan\PhpDocParser\Parser\TokenIterator))          
         #7 vendor/phpstan/phpdoc-parser/src/Parser/PhpDocParser.php(49):                                               
         PHPStan\PhpDocParser\Parser\PhpDocParser->parseChild(Object(PHPStan\PhpDocParser\Parser\TokenIterator))        
         #8 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocStringResolver.php(28):    
         PHPStan\PhpDocParser\Parser\PhpDocParser->parse(Object(PHPStan\PhpDocParser\Parser\TokenIterator))             
         #9 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(156):           
         PHPStan\PhpDoc\PhpDocStringResolver->resolve('/**\n * Asserts ...')                                            
         #10 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(263):          
         PHPStan\Type\FileTypeMapper->resolvePhpDocStringToDocNode('/**\n * Asserts ...')                               
         #11 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(289):          
         PHPStan\Type\FileTypeMapper->PHPStan\Type\{closure}()                                                          
         #12 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(185):          
         PHPStan\Type\FileTypeMapper::PHPStan\Type\{closure}()                                                          
         #13 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(164):          
         PHPStan\Type\FileTypeMapper->createResolvedPhpDocMap('/Users/chrisarc...')                                     
         #14 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/FileTypeMapper.php(113):          
         PHPStan\Type\FileTypeMapper->getNameScopeMap('/Users/chrisarc...')                                             
         #15 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(1107):  
         PHPStan\Type\FileTypeMapper->getResolvedPhpDoc('/Users/chrisarc...', 'PHPUnit\\Framewo...', NULL, NULL, '/**\n *
         @no-name...')                                                                                                  
         #16 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(1137):  
         PHPStan\Reflection\ClassReflection->getResolvedPhpDoc()                                                        
         #17 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(1053):  
         PHPStan\Reflection\ClassReflection->getTemplateTags()                                                          
         #18 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(867):              
         PHPStan\Reflection\ClassReflection->isGeneric()                                                                
         #19 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(258):              
         PHPStan\Type\ObjectType->getClassReflection()                                                                  
         #20 vendor/rector/rector/vendor/rector/rector-phpunit/src/NodeAnalyzer/TestsNodeAnalyzer.php(79):              
         PHPStan\Type\ObjectType->isSuperTypeOf(Object(Rector\StaticTypeMapper\ValueObject\Type\FullyQualifiedObjectType))
         #21 vendor/rector/rector/vendor/rector/rector-phpunit/src/Rector/Class_/AddProphecyTraitRector.php(98):        
         Rector\PHPUnit\NodeAnalyzer\TestsNodeAnalyzer->isAssertMethodCallName(Object(PhpParser\Node\Expr\StaticCall),  
         'prophesize')                                                                                                  
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/FirstFindingVisitor.php(42):        
         Rector\PHPUnit\Rector\Class_\AddProphecyTraitRector->Rector\PHPUnit\Rector\Class_\{closure}(Object(PhpParser\Node\Expr</>
         StaticCall))                                                                                                   
         #23 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                         
         PhpParser\NodeVisitor\FirstFindingVisitor->enterNode(Object(PhpParser\Node\Expr\StaticCall))                   
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #25 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #26 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #27 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #28 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #29 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #30 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #31 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeFinder.php(59):                             
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #32 vendor/rector/rector/src/PhpParser/Node/BetterNodeFinder.php(230): PhpParser\NodeFinder->findFirst(Array,  
         Object(Closure))                                                                                               
         #33 vendor/rector/rector/vendor/rector/rector-phpunit/src/Rector/Class_/AddProphecyTraitRector.php(99):        
         Rector\Core\PhpParser\Node\BetterNodeFinder->findFirst(Object(PhpParser\Node\Stmt\Class_), Object(Closure))    
         #34 vendor/rector/rector/vendor/rector/rector-phpunit/src/Rector/Class_/AddProphecyTraitRector.php(89):        
         Rector\PHPUnit\Rector\Class_\AddProphecyTraitRector->shouldSkipClass(Object(PhpParser\Node\Stmt\Class_))       
         #35 vendor/rector/rector/src/Rector/AbstractRector.php(204):                                                   
         Rector\PHPUnit\Rector\Class_\AddProphecyTraitRector->refactor(Object(PhpParser\Node\Stmt\Class_))              
         #36 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                         
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))                               
         #37 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #38 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #39 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #40 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #41 vendor/rector/rector/src/Application/FileProcessor.php(61):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #42 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #43 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))                                                     
         #44 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #45 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #46 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #47 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #48 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202208\Evenement\EventEmitter->emit('data',
         Array)                                                                                                         
         #49 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202208\React\Stream\Util::RectorPrefix202208\React\Stream\{closure}('{"action":"main...')          
         #50 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202208\Evenement\EventEmitter->emit('data', Array)                                                 
         #51 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202208\React\Stream\DuplexResourceStream->handleData(Resource id #12530)                           
         #52 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #53 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202208\React\EventLoop\StreamSelectLoop->run()                                                     
         #54 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                   
         #55 vendor/rector/rector/vendor/symfony/console/Application.php(891):                                          
         RectorPrefix202208\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202208\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                    
         #56 vendor/rector/rector/vendor/symfony/console/Application.php(310):                                          
         RectorPrefix202208\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),                                       
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #57 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202208\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                      
         #58 vendor/rector/rector/vendor/symfony/console/Application.php(208):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202208\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202208\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #59 vendor/rector/rector/bin/rector.php(128): RectorPrefix202208\Symfony\Component\Console\Application->run()  
         #60 vendor/rector/rector/bin/rector(5): require_once('/Users/chrisarc...')                                     
         #61 vendor/bin/rector(120): include('/Users/chrisarc...')                                                      
         #62 {main}". On line: 369```

**Comment by samsonasik** [comment]
Please try "rector/rector": "dev-main" while wait for next release.
