### ISSUE TITLE
Could not locate constant while trying to evaluate constant expression

### ISSUE THREAD

**Issue by DieterHolvoet** [rectorphp/rector#7726]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.15.7             |

Rector fails when using an enum case as a default value for a class property.

```
[ERROR] Could not process
         "<redacted>/SomeController.php" file, due to:
         "System error: "Could not locate constant Drupal\some_module\Enum\Sort::DATE
         while trying to evaluate constant expression in class
         Drupal\some_module\Request\SomeRequest in file
         web/modules/custom/some_module/src/Request/SomeRequest.php (line 14)"

         Stack trace:
         #0
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/NodeC
         ompiler/CompileNodeToValue.php(196):
         PHPStan\BetterReflection\NodeCompiler\Exception\UnableToCompileNode::becauseOfNotFoundClassConstantReference(Ob
         ject(PHPStan\BetterReflection\NodeCompiler\CompilerContext),
         Object(PHPStan\BetterReflection\Reflection\ReflectionEnum), Object(PhpParser\Node\Expr\ClassConstFetch))
         #1
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/NodeC
         ompiler/CompileNodeToValue.php(49):
         PHPStan\BetterReflection\NodeCompiler\CompileNodeToValue->getClassConstantValue(Object(PhpParser\Node\Expr\Cla
         ssConstFetch), 'Drupal\\mms_moni...', Object(PHPStan\BetterReflection\NodeCompiler\CompilerContext))
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(131):
         PHPStan\BetterReflection\NodeCompiler\CompileNodeToValue->PHPStan\BetterReflection\NodeCompiler\{closure}(Obje
         ct(PhpParser\Node\Expr\ClassConstFetch))
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(96):
         PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\ClassConstFetch))
         #4
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/NodeC
         ompiler/CompileNodeToValue.php(99):
         PhpParser\ConstExprEvaluator->evaluateDirectly(Object(PhpParser\Node\Expr\ClassConstFetch))
         #5
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Refle
         ction/ReflectionProperty.php(307):
         PHPStan\BetterReflection\NodeCompiler\CompileNodeToValue->__invoke(Object(PhpParser\Node\Expr\ClassConstFetch)
         , Object(PHPStan\BetterReflection\NodeCompiler\CompilerContext))
         #6
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Refle
         ction/Adapter/ReflectionProperty.php(139):
         PHPStan\BetterReflection\Reflection\ReflectionProperty->getDefaultValue()
         #7 vendor/rector/rector/packages/NodeTypeResolver/TypeAnalyzer/ArrayTypeAnalyzer.php(168):
         PHPStan\BetterReflection\Reflection\Adapter\ReflectionProperty->getDefaultValue()
         #8 vendor/rector/rector/packages/NodeTypeResolver/TypeAnalyzer/ArrayTypeAnalyzer.php(78):
         Rector\NodeTypeResolver\TypeAnalyzer\ArrayTypeAnalyzer->isPropertyFetchWithArrayDefault(Object(PhpParser\Node\
         Expr\PropertyFetch))
         #9 vendor/rector/rector/rules/CodeQuality/Rector/If_/ExplicitBoolCompareRector.php(142):
         Rector\NodeTypeResolver\TypeAnalyzer\ArrayTypeAnalyzer->isArrayType(Object(PhpParser\Node\Expr\PropertyFetch))
         #10 vendor/rector/rector/rules/CodeQuality/Rector/If_/ExplicitBoolCompareRector.php(115):
         Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector->resolveNewConditionNode(Object(PhpParser\Node\Expr\Pr
         opertyFetch), false)
         #11 vendor/rector/rector/src/Rector/AbstractRector.php(216):
         Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector->refactor(Object(PhpParser\Node\Stmt\If_))
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\If_))
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #20 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse(Array)
         #21 vendor/rector/rector/src/Application/FileProcessor.php(60):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #22 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #23 vendor/rector/rector/packages/Parallel/WorkerRunner.php(135):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil
         e), Object(Rector\Core\ValueObject\Configuration))
         #24 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106):
         Rector\Parallel\WorkerRunner->processFiles(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration), Array)
         #25 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #26 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)
         #27 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202301\Clue\React\NDJson\Decoder->handleData(Array)
         #28 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)
         #29 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202301\React\Stream\Util::RectorPrefix202301\React\Stream\{closure}('{"action":"main...')
         #30 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)
         #31 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202301\React\Stream\DuplexResourceStream->handleData(Resource id #3079)
         #32 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202301\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #33 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202301\React\EventLoop\StreamSelectLoop->run()
         #34 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202301\Symfony\Component\Console\Input\A
         rgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(899):
         RectorPrefix202301\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202301\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))
         #36 vendor/rector/rector/vendor/symfony/console/Application.php(320):
         RectorPrefix202301\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work
         erCommand), Object(RectorPrefix202301\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))
         #37 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202301\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202301\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))
         #38 vendor/rector/rector/vendor/symfony/console/Application.php(206):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202301\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))
         #39 vendor/rector/rector/bin/rector.php(128): RectorPrefix202301\Symfony\Component\Console\Application->run()
         #40 vendor/rector/rector/bin/rector(5): require_once('/Users/dieterho...')
         #41 vendor/bin/rector(120): include('/Users/dieterho...')
         #42 {main}". On line: 31
```

## Minimal PHP Code Causing Issue
Didn't actually try to execute this code, but this is the idea:
```php
<?php

namespace Drupal\some_module\Enum;

enum Sort: string
{
    case DATE = 'date';
}

```
```php
<?php

namespace Drupal\some_module\Request;

class SomeRequest extends ApiRequestBase
{
    public Sort $sort = Sort::DATE;
}
```

## Expected Behaviour

Not fail.

**Comment by samsonasik** [comment]
You may need to define autoload or bootstrap the file, ref https://getrector.com/documentation/static-reflection-and-autoload for it.

**Comment by tomekpolska** [comment]
Similar here:

Could not locate constant "FF_DEFAULT" while evaluating expression in class AxisPrototype in file ....jpgraph-4.0.2/src/jpgraph.php 

I have used autoloadPaths as well as bootstrapFiles but it didn't help.

**Comment by DieterHolvoet** [comment]
I tried the following, but it didn't make a difference:
```
$config->bootstrapFiles([
    __DIR__ . '/web/modules/custom/some_module/src/Enum/Sort.php',
]);

$config->autoloadPaths([
    __DIR__ . '/web/modules/custom/some_module/src/Enum/Sort.php',
    __DIR__ . '/web/modules/custom/some_module/src',
]);
```

I also tried installing [fenetikm/autoload-drupal](https://github.com/fenetikm/autoload-drupal) which includes the needed files in the default Composer autoloader. After configuring, the autoloader contained this line, but it still didn't fix the issue:
```
# vendor/composer/autoload_psr4.php
'Drupal\\some_module\\' => array($baseDir . '/web/modules/custom/some_module/src'),
```

Seems to be an issue specific to Enums.

**Comment by samsonasik** [comment]
This may possibly already resolved at PR:

- https://github.com/rectorphp/rector-src/pull/3317

Could you try latest version? Otherwise, we need failing test case or reproduced github repo for it, better with github action.
