### ISSUE TITLE
Error using parent:: in a extended class

### ISSUE THREAD

**Issue by juagarc4** [rectorphp/rector#7746]
I apologize if it is a duplicate, but I couldn't find any other related issue, therefore I open this new one.

Environment:
```
PHP Version: PHP 8.1.14
Rector Version: 0.15.8
Symfony 5.4
```

I'm getting the follow ERROR trying to update a project to PHP 8.1. 

```
[ERROR] Could not process "XXXX.php" file, due to:       
         "System error: "Look at                                                                                        
         "Rector\Core\PhpParser\Node\Value\ValueResolver::resolveClassFromSelfStaticParent()"296"   
```

This error happens in a class in which I access to the parent class using **parent::**

You can see a small demo at: https://getrector.com/demo/d6b4fbb4-d3af-46ef-a7fc-be032127e3b4

If I empty the array  $this->parameters = [] it works fine. It's happening in all classes where I use **parent::**

The full output using the --debug option is:

```
[file] src/Request/XXX.php
[rule] Rector\Php54\Rector\Array_\LongArrayToShortArrayRector

[file] src/Request/XXX.php
[rule] Rector\Symfony\Rector\MethodCall\CascadeValidationFormBuilderRector
                                                                                                                        
 [ERROR] Could not process "XXX.php" file, due to:       
         "System error: "Look at                                                                                        
         "Rector\Core\PhpParser\Node\Value\ValueResolver::resolveClassFromSelfStaticParent()"296"                       
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(260):                                       
         Rector\Core\PhpParser\Node\Value\ValueResolver->resolveClassFromSelfStaticParent(Object(PhpParser\Node\Expr\Cl 
         assConstFetch), 'parent')                                                                                      
         #1 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(199):                                       
         Rector\Core\PhpParser\Node\Value\ValueResolver->resolveClassConstFetch(Object(PhpParser\Node\Expr\ClassConstFe 
         tch))                                                                                                          
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(131):                     
         Rector\Core\PhpParser\Node\Value\ValueResolver->Rector\Core\PhpParser\Node\Value\{closure}(Object(PhpParser\No 
         de\Expr\ClassConstFetch))                                                                                      
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(96):                      
         PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\ClassConstFetch))                            
         #4 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(174):                                       
         PhpParser\ConstExprEvaluator->evaluateDirectly(Object(PhpParser\Node\Expr\ClassConstFetch))                    
         #5 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(106):                                       
         Rector\Core\PhpParser\Node\Value\ValueResolver->resolveExprValueForConst(Object(PhpParser\Node\Expr\ClassConst 
         Fetch))                                                                                                        
         #6 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(83):                                        
         Rector\Core\PhpParser\Node\Value\ValueResolver->getValue(Object(PhpParser\Node\Expr\ClassConstFetch))          
         #7                                                                                                             
         vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/CascadeValidationFormBuilderRector.php(
         158): Rector\Core\PhpParser\Node\Value\ValueResolver->isValue(Object(PhpParser\Node\Expr\ClassConstFetch),     
         'cascade_validat...')                                                                                          
         #8                                                                                                             
         vendor/rector/rector/vendor/rector/rector-symfony/src/Rector/MethodCall/CascadeValidationFormBuilderRector.php(
         88):                                                                                                           
         Rector\Symfony\Rector\MethodCall\CascadeValidationFormBuilderRector->refactorArrayItem(Object(PhpParser\Node\E 
         xpr\ArrayItem))                                                                                                
         #9 vendor/rector/rector/src/Rector/AbstractRector.php(217):                                                    
         Rector\Symfony\Rector\MethodCall\CascadeValidationFormBuilderRector->refactor(Object(PhpParser\Node\Expr\Array 
         Item))                                                                                                         
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                         
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\ArrayItem))                            
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Array_))                                      
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ArrayItem))                                   
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Array_))                                      
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #21 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #23 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #25 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #26 vendor/rector/rector/src/Application/FileProcessor.php(60):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #27 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #28 vendor/rector/rector/packages/Parallel/WorkerRunner.php(135):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #29 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106):                                              
         Rector\Parallel\WorkerRunner->processFiles(Object(Rector\Core\ValueObject\Application\File),                   
         Object(Rector\Core\ValueObject\Configuration), Array)                                                          
         #30 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #31 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)                                                 
         #32 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202301\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #33 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)                                                 
         #34 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202301\React\Stream\Util::RectorPrefix202301\React\Stream\{closure}('{"action":"main...')          
         #35 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202301\Evenement\EventEmitter->emit('data', Array)                                                 
         #36 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202301\React\Stream\DuplexResourceStream->handleData(Resource id #3125)                            
         #37 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202301\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #38 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202301\React\EventLoop\StreamSelectLoop->run()                                                     
         #39 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202301\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))                          
         #40 vendor/rector/rector/vendor/symfony/console/Application.php(899):                                          
         RectorPrefix202301\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202301\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))           
         #41 vendor/rector/rector/vendor/symfony/console/Application.php(320):                                          
         RectorPrefix202301\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202301\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #42 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202301\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202301\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))             
         #43 vendor/rector/rector/vendor/symfony/console/Application.php(206):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202301\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202301\Symfony\Component\Console\Output\ConsoleOutput))                               
         #44 vendor/rector/rector/bin/rector.php(128): RectorPrefix202301\Symfony\Component\Console\Application->run()  
         #45 vendor/rector/rector/bin/rector(5): require_once('/var/www/html/a...')                                     
         #46 vendor/bin/rector(120): include('/var/www/html/a...')                                                      
         #47 {main}". On line: 296 
```

Let me know If I should post more information.
Thanks in advance

**Comment by samsonasik** [comment]
That's because you don't define parent class, when there is parent constant, it will work, see https://getrector.com/demo/06543d9a-2642-4087-995d-92a0e5d8fa1e

If the parent class is load too late, you can read the doc how parent class be registered in autoload early, see https://getrector.com/documentation/static-reflection-and-autoload

**Comment by juagarc4** [comment]
Hi @samsonasik, 

The parent class was already defined and properly loaded, but now it seems to work without having changed anything. 
Really strange.
Anyway, thank you for your response.

**Comment by samsonasik** [comment]
That's how cache work, after parent loaded, it will work on 2nd try.

 You may got error again on next clear-cache, the solution is register parent to autoload so it always loaded early.

**Comment by TomasVotruba** [comment]
This should at least not crash, I'll see if we can mitigate the bug
