### ISSUE TITLE
Uncaught TypeError when using SetList::TYPE_DECLARATION

### ISSUE THREAD

**Issue by Knallcharge** [rectorphp/rector#7759]
# Bug Report

Using rector v0.15.12 I get an uncaught TypeError on each "first" run about halfway through (I have 500+ files to be checked). When I restart rector, the error disappears, rector starts where it left off (probably due to some kind of cache).
I now discovered that all errors from the first half of the run are being skipped (so I've been thinking my code is ok for months until I noticed what was going on).

I have narrowed the error down to SetList::TYPE_DECLARATION by uncommenting setlists one by one, all other setlists run just fine.

Here's the stacktrace:

```
PHP Fatal error:  Uncaught TypeError: PHPStan\PhpDoc\TypeNodeResolver::PHPStan\PhpDoc\{closure}(): Argument #1 ($parameterNode) must be of type PHPStan\PhpDocParser\Ast\Type\CallableTypeParameterNode, PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode given in phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php:607
Stack trace:
#0 [internal function]: PHPStan\PhpDoc\TypeNodeResolver->PHPStan\PhpDoc\{closure}(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))
#1 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(614): array_map(Object(Closure), Array)
#2 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(166): PHPStan\PhpDoc\TypeNodeResolver->resolveCallableTypeNode(Object(Rector\BetterPhpDocParser\ValueObject\Type\SpacingAwareCallableTypeNode), Object(PHPStan\Analyser\NameScope))
#3 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(637): PHPStan\PhpDoc\TypeNodeResolver->resolve(Object(Rector\BetterPhpDocParser\ValueObject\Type\SpacingAwareCallableTypeNode), Object(PHPStan\Analyser\NameScope))
#4 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(168): PHPStan\PhpDoc\TypeNodeResolver->resolveArrayShapeNode(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PHPStan\Analyser\NameScope))
#5 (...)\vendor\rector\rector\packages\StaticTypeMapper\PhpDoc\PhpDocTypeMapper.php(44): PHPStan\PhpDoc\TypeNodeResolver->resolve(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PHPStan\Analyser\NameScope))
#6 (...)\vendor\rector\rector\packages\StaticTypeMapper\StaticTypeMapper.php(133): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\NameScope))
#7 (...)\vendor\rector\rector\rules\TypeDeclaration\Rector\ClassMethod\ReturnAnnotationIncorrectNullableRector.php(118): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#8 (...)\vendor\rector\rector\src\Rector\AbstractRector.php(217): Rector\TypeDeclaration\Rector\ClassMethod\ReturnAnnotationIncorrectNullableRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#9 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#10 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#11 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#12 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#13 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#14 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#15 (...)\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#16 (...)\vendor\rector\rector\src\Application\FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#17 (...)\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(100): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#18 (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(159): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#19 (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(132): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#20 (...)\vendor\rector\rector\src\Console\Command\ProcessCommand.php(119): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput))
#21 (...)\vendor\rector\rector\vendor\symfony\console\Command\Command.php(311): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#22 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(899): RectorPrefix202302\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#23 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(320): RectorPrefix202302\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#24 (...)\vendor\rector\rector\src\Console\ConsoleApplication.php(49): RectorPrefix202302\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#25 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(206): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#26 (...)\vendor\rector\rector\bin\rector.php(128): RectorPrefix202302\Symfony\Component\Console\Application->run()
#27 (...)\vendor\rector\rector\bin\rector(5): require_once('C:\\xampp\\htdocs...')
#28 (...)\vendor\bin\rector(120): include('C:\\xampp\\htdocs...')
#29 {main}
  thrown in phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php on line 607
Fatal error: Uncaught TypeError: PHPStan\PhpDoc\TypeNodeResolver::PHPStan\PhpDoc\{closure}(): Argument #1 ($parameterNode) must be of type PHPStan\PhpDocParser\Ast\Type\CallableTypeParameterNode, PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode given in phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php:607
Stack trace:
#0 [internal function]: PHPStan\PhpDoc\TypeNodeResolver->PHPStan\PhpDoc\{closure}(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))
#1 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(614): array_map(Object(Closure), Array)
#2 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(166): PHPStan\PhpDoc\TypeNodeResolver->resolveCallableTypeNode(Object(Rector\BetterPhpDocParser\ValueObject\Type\SpacingAwareCallableTypeNode), Object(PHPStan\Analyser\NameScope))
#3 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(637): PHPStan\PhpDoc\TypeNodeResolver->resolve(Object(Rector\BetterPhpDocParser\ValueObject\Type\SpacingAwareCallableTypeNode), Object(PHPStan\Analyser\NameScope))
#4 phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php(168): PHPStan\PhpDoc\TypeNodeResolver->resolveArrayShapeNode(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PHPStan\Analyser\NameScope))
#5 (...)\vendor\rector\rector\packages\StaticTypeMapper\PhpDoc\PhpDocTypeMapper.php(44): PHPStan\PhpDoc\TypeNodeResolver->resolve(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PHPStan\Analyser\NameScope))
#6 (...)\vendor\rector\rector\packages\StaticTypeMapper\StaticTypeMapper.php(133): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\NameScope))
#7 (...)\vendor\rector\rector\rules\TypeDeclaration\Rector\ClassMethod\ReturnAnnotationIncorrectNullableRector.php(118): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\ArrayShapeNode), Object(PhpParser\Node\Stmt\ClassMethod))
#8 (...)\vendor\rector\rector\src\Rector\AbstractRector.php(217): Rector\TypeDeclaration\Rector\ClassMethod\ReturnAnnotationIncorrectNullableRector->refactor(Object(PhpParser\Node\Stmt\ClassMethod))
#9 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#10 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#11 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#12 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#13 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#14 (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#15 (...)\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#16 (...)\vendor\rector\rector\src\Application\FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#17 (...)\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(100): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#18 (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(159): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#19 (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(132): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#20 (...)\vendor\rector\rector\src\Console\Command\ProcessCommand.php(119): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput))
#21 (...)\vendor\rector\rector\vendor\symfony\console\Command\Command.php(311): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#22 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(899): RectorPrefix202302\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#23 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(320): RectorPrefix202302\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#24 (...)\vendor\rector\rector\src\Console\ConsoleApplication.php(49): RectorPrefix202302\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#25 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(206): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202302\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202302\Symfony\Component\Console\Output\ConsoleOutput))
#26 (...)\vendor\rector\rector\bin\rector.php(128): RectorPrefix202302\Symfony\Component\Console\Application->run()
#27 (...)\vendor\rector\rector\bin\rector(5): require_once('C:\\xampp\\htdocs...')
#28 (...)\vendor\bin\rector(120): include('C:\\xampp\\htdocs...')
#29 {main}
  thrown in phar://(...)/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/TypeNodeResolver.php on line 607
```

My best guess is that there's some weird DocType somewhere in my project but I can't really find out which one as the error is thrown inside phpstan.phar, trying to catch it in rectors PhpDocTypeMapper didn't work.

I'll try to get to the file (and the DocBlock) that causes this, but this may take some time considering the size of the project.

## Minimal PHP Code Causing Issue

can't tell

## Expected Behaviour

Rector should catch the error produced in phpstan.phar and report it.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.org/demo,
that way we can reproduce the bug.

As for debugging, the best way to discover the breaking line is narrow scoping: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by Knallcharge** [comment]
Using -vvv I found the file and the rule that causes the error but unfortunately can't provide a reproducable code.
The rule is Rector\TypeDeclaration\Rector\ClassMethod\ReturnAnnotationIncorrectNullableRector and it throws the error in a file that doesn't have an incorrect nullable return annotation. I tried all of the files methods one by one in the demo (as the file has 400+ lines), but no error occurred.

So for now I guess I'll have to deactivate the rules to keep rector running for me.

**Comment by Knallcharge** [comment]
This wouldn't let me rest, so I tested all methods in the failing class one by one and finally came up with some code that makes this reproducable: https://getrector.com/demo/587325f8-5de2-4b21-96c2-c1be9937c81c

The failing code is
```
    /**
     * @return mixed
     */
    public static function testMethod(): array
    {
        return [
            'query_builder' => static fn(TestRepository $testRepository): QueryBuilder => $testRepository->createQb(),
        ];
    }
```
When I change the return annotation to "array", it still fails, if I remove it, rector tells me to use `@return array{query_builder: Closure(TestRepository):QueryBuilder}` - doing so fixes the error.

**Comment by TomasVotruba** [comment]
This is perfect! I'll check the test fixture :+1:  thank you

**Comment by TomasVotruba** [comment]
Here is a minimal reproducer: https://github.com/rectorphp/rector-src/pull/3353

**Comment by TomasVotruba** [comment]
Fixed inhttps://github.com/rectorphp/rector-src/pull/3353
