### ISSUE TITLE
Method assertEqual() was not found in reflection

### ISSUE THREAD

**Issue by GuillaumeDuveau** [rectorphp/rector#7766]
Hi,

I'm getting this error while trying to run Drupal Rector on the [Required API module](https://www.drupal.org/project/required_api) :

```
 [ERROR] Could not process                                                                                          
         "/var/www/html/web/modules/contrib/required_api/tests/modules/required_api_test/tests/src/RequiredApiTest.p
         hp" file, due to:                                                                                          
         "System error: "Method assertEqual() was not found in reflection of class                                  
         Drupal\required_api_test\Tests\RequiredApiTest."                                                           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 454
```

It says to post the run with --debug here. I'm not sure it's the right place, I would have said this belongs on Drupal.org's Drupal Rector project so I posted also [there](https://www.drupal.org/project/rector/issues/3340556). Please let me know if I should close this here.

```
 [ERROR] Could not process                                                                                          
         "/var/www/html/web/modules/contrib/required_api/tests/modules/required_api_test/tests/src/RequiredApiTest.p
         hp" file, due to:                                                                                          
         "System error: "Method assertEqual() was not found in reflection of class                                  
         Drupal\required_api_test\Tests\RequiredApiTest."                                                           
                                                                                                                    
         Stack trace:                                                                                               
         #0 vendor/palantirnet/drupal-rector/src/Utility/GetDeclaringSourceTrait.php(33):                           
         PHPStan\Reflection\ClassReflection->getMethod()                                                            
         #1 vendor/palantirnet/drupal-rector/src/Rector/Deprecation/Base/AssertLegacyTraitBase.php(47):             
         DrupalRector\Rector\Deprecation\Base\AssertLegacyTraitBase->getDeclaringSource()                           
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(217):                                                
         DrupalRector\Rector\Deprecation\Base\AssertLegacyTraitBase->refactor()                                     
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                      
         Rector\Core\Rector\AbstractRector->enterNode()                                                             
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                      
         PhpParser\NodeTraverser->traverseNode()                                                                    
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                      
         PhpParser\NodeTraverser->traverseArray()                                                                   
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                      
         PhpParser\NodeTraverser->traverseNode()                                                                    
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                      
         PhpParser\NodeTraverser->traverseArray()                                                                   
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                      
         PhpParser\NodeTraverser->traverseNode()                                                                    
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                      
         PhpParser\NodeTraverser->traverseArray()                                                                   
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                     
         PhpParser\NodeTraverser->traverseNode()                                                                    
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                      
         PhpParser\NodeTraverser->traverseArray()                                                                   
         #12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                          
         PhpParser\NodeTraverser->traverse()                                                                        
         #13 vendor/rector/rector/src/Application/FileProcessor.php(60):                                            
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                        
         #14 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(100):                          
         Rector\Core\Application\FileProcessor->refactor()                                                          
         #15 vendor/rector/rector/packages/Parallel/WorkerRunner.php(135):                                          
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                          
         #16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106):                                          
         Rector\Parallel\WorkerRunner->processFiles()                                                               
         #17 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):               
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                  
         #18 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                    
         RectorPrefix202302\Evenement\EventEmitter->emit()                                                          
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):               
         RectorPrefix202302\Clue\React\NDJson\Decoder->handleData()                                                 
         #20 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                             
         RectorPrefix202302\Evenement\EventEmitter->emit()                                                          
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):               
         RectorPrefix202302\React\Stream\Util::RectorPrefix202302\React\Stream\{closure}()                          
         #22 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                            
         RectorPrefix202302\Evenement\EventEmitter->emit()                                                          
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                            
         RectorPrefix202302\React\Stream\DuplexResourceStream->handleData()                                         
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                            
         RectorPrefix202302\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                               
         #25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                        
         RectorPrefix202302\React\EventLoop\StreamSelectLoop->run()                                                 
         #26 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):                                  
         Rector\Core\Console\Command\WorkerCommand->execute()                                                       
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(899):                                      
         RectorPrefix202302\Symfony\Component\Console\Command\Command->run()                                        
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(320):                                      
         RectorPrefix202302\Symfony\Component\Console\Application->doRunCommand()                                   
         #29 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                           
         RectorPrefix202302\Symfony\Component\Console\Application->doRun()                                          
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(206):                                      
         Rector\Core\Console\ConsoleApplication->doRun()                                                            
         #31 vendor/rector/rector/bin/rector.php(128):                                                              
         RectorPrefix202302\Symfony\Component\Console\Application->run()                                            
         #32 vendor/rector/rector/bin/rector(5): require_once('...')                                                
         #33 vendor/bin/rector(120): include('...')                                                                 
         #34 {main}". On line: 454
```

**Comment by samsonasik** [comment]
Looking at the stack trace, the issue seems on `drupal-rector` lib : 

```
         Stack trace:                                                                                               
         #0 vendor/palantirnet/drupal-rector/src/Utility/GetDeclaringSourceTrait.php(33):                           
         PHPStan\Reflection\ClassReflection->getMethod()     
```

https://github.com/palantirnet/drupal-rector/blob/09d3dc6a422483de4c7c9b17692a48252b6b0af3/src/Utility/GetDeclaringSourceTrait.php#L33

You can report on there :)
