### ISSUE TITLE
Crashed while processing

### ISSUE THREAD

**Issue by Bjornar97** [rectorphp/rector#7874]
Rector crashed with the following exception. It did change a lot of files successfully before the crash.

         64\www\pni-intra\import\reader.php" file, due to: 

         #0 C:\wamp64\www\pni-intra\vendor\rector\rector\src\PhpParser\Parser\RectorParser.php(32):
         PHPStan\Parser\RichParser->parseFile('C:\\wamp64\\www\\p...')
         #1 C:\wamp64\www\pni-intra\vendor\rector\rector\src\PhpParser\Parser\RectorParser.php(36):
         Rector\Core\PhpParser\Parser\RectorParser->parseFile('C:\\wamp64\\www\\p...')
         #2 C:\wamp64\www\pni-intra\vendor\rector\rector\src\Application\FileProcessor.php(51):
         Rector\Core\PhpParser\Parser\RectorParser->parseFileToStmtsAndTokens('C:\\wamp64\\www\\p...')
         #3 C:\wamp64\www\pni-intra\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(143):       
         Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache(Object(Rector\Core\ValueObject\Application\Fi 
         le))
         #4 C:\wamp64\www\pni-intra\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(97):        
         Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes(Object(Rector\Core\ValueObje 
         ct\Application\File))
         #5 C:\wamp64\www\pni-intra\vendor\rector\rector\packages\Parallel\WorkerRunner.php(130):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))
         #6 C:\wamp64\www\pni-intra\vendor\rector\rector\packages\Parallel\WorkerRunner.php(106):
         Rector\Parallel\WorkerRunner->processFiles(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration), Array)
         #7
         C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97)
         : Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #8 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(117):
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)
         #9
         C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97)
         : RectorPrefix202304\Clue\React\NDJson\Decoder->handleData(Array)
         #10 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)
         #11
         C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97)
         : RectorPrefix202304\React\Stream\Util::RectorPrefix202304\React\Stream\{closure}('{"action":"main...')        
         #12 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):        
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)
         #13 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):        
         RectorPrefix202304\React\Stream\DuplexResourceStream->handleData(Resource id #2827)
         #14 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):        
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #15 C:\wamp64\www\pni-intra\vendor\rector\rector\src\Console\Command\WorkerCommand.php(63):
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->run()
         #16 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\symfony\console\Command\Command.php(311):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202304\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))
         #17 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\symfony\console\Application.php(899):
         RectorPrefix202304\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202304\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))
         #18 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\symfony\console\Application.php(320):
         RectorPrefix202304\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202304\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))
         #19 C:\wamp64\www\pni-intra\vendor\rector\rector\src\Console\ConsoleApplication.php(49):
         RectorPrefix202304\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202304\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))
         #20 C:\wamp64\www\pni-intra\vendor\rector\rector\vendor\symfony\console\Application.php(206):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202304\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))
         #21 C:\wamp64\www\pni-intra\vendor\rector\rector\bin\rector.php(128):
         RectorPrefix202304\Symfony\Component\Console\Application->run()
         #22 C:\wamp64\www\pni-intra\vendor\rector\rector\bin\rector(5): require_once('C:\\wamp64\\www\\p...')
         #23 C:\wamp64\www\pni-intra\vendor\bin\rector(120): include('C:\\wamp64\\www\\p...')
         #24 {main}". On line: 54

**Comment by Bjornar97** [comment]
Adding .inc to file extensions worked. Thank you :)
