### ISSUE TITLE
FuncCall\RenameFunctionRector throws ShouldNotHappenException()

### ISSUE THREAD

**Issue by holdmann** [rectorphp/rector#7877]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.24         |
| Php version | 7.3.33        |

`RenameFunctionRector` causes unrecoverable failure on bellow code that works fine.

```
% ../php_interface/vendor/bin/rector process --clear-cache --debug

...

[file] ../../bitrix/modules/statistic/admin/adv_detail.php
[rule] Rector\Renaming\Rector\FuncCall\RenameFunctionRector

[file] ../../bitrix/modules/statistic/admin/adv_detail.php
[rule] Rector\Renaming\Rector\FuncCall\RenameFunctionRector

[file] ../../bitrix/modules/statistic/admin/adv_detail.php
[rule] Rector\Renaming\Rector\FuncCall\RenameFunctionRector

[file] ../../bitrix/modules/statistic/admin/adv_detail.php
[rule] Rector\Renaming\Rector\FuncCall\RenameFunctionRector

[file] ../../bitrix/modules/statistic/admin/adv_detail.php
[rule] Rector\Renaming\Rector\FuncCall\RenameFunctionRector

PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\FuncCall" with parent of "PhpParser\Node\Expr\BinaryOp\Concat" is missing scope required for scope refresh. in /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php:85
Stack trace:
#0 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(342): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\FuncCall), NULL, '/Users/holdmann...')
#1 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(253): Rector\Core\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\FuncCall), '/Users/holdmann...', NULL)
#2 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\Ab in /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php on line 85
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\FuncCall" with parent of "PhpParser\Node\Expr\BinaryOp\Concat" is missing scope required for scope refresh. in /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php:85
Stack trace:
#0 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(342): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\FuncCall), NULL, '/Users/holdmann...')
#1 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(253): Rector\Core\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\FuncCall), '/Users/holdmann...', NULL)
#2 /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\Ab in /Users/holdmann/Documents/Projects/php74/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php on line 85
```

## Minimal PHP Code Causing Issue

```php
$isParallel = true;

return static function (RectorConfig $rectorConfig) use ($isParallel): void {

    $rectorConfig->parallel(600, 3, 3);

    if (!$isParallel)
    {
        $rectorConfig->disableParallel();
    }

    $rectorConfig->paths([__DIR__ . '/../../bitrix/modules/statistic/admin/adv_detail.php']);
    $rectorConfig->ruleWithConfiguration(RenameFunctionRector::class, [
            'substr' => 'mb_substr',
            'strtolower' => 'mb_strtolower',
            'strtoupper' => 'mb_strtoupper',
            'strpos' => 'mb_strpos',
            'substr_count' => 'mb_substr_count',
            'strlen' => 'mb_strlen'
        ]);

};
```
for source code see [attached file](https://disk.yandex.ru/d/hjxFdc37m1SiCA)
## Expected Behaviour

should work as expected

**Comment by samsonasik** [comment]
This may probably already solved in latest dev-main while fix your previous issue, please try latest dev-main:

```
"rector/rector": "dev-main"
```

If the issue persist, please provide repro issue at https://getrector.com/demo

**Comment by holdmann** [comment]
@samsonasik I have been check with dev-main version, works like a charm, thx 👍
issue can be closed now as already resolved.

**Comment by yguedidi** [comment]
@samsonasik just curious, what is the release policy of Rector? when versions are tagged? 🙂

**Comment by samsonasik** [comment]
Rector 0.15.25 just released :+1: https://github.com/rectorphp/rector/releases/tag/0.15.25
