### ISSUE TITLE
PrivatesAccessor:  use selectFromArgs() instead

### ISSUE THREAD

**Issue by staabm** [rectorphp/rector#7945]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | https://github.com/rectorphp/rector-src/commit/71f00d95fc16f31f7af4a524d5e179f467089e16       |

## Minimal PHP Code Causing Issue

running https://github.com/rectorphp/rector-src/commit/71f00d95fc16f31f7af4a524d5e179f467089e16 locally with
`time php bin/rector --dry-run --clear-cache --debug` 

leads to 

```
 [ERROR] Could not process "C:\dvl\Workspace\rector-src-staabm\src\Util\Reflection\PrivatesAccessor.php" file, due to:
                                             use selectFromArgs() instead."


         #0 C:\dvl\Workspace\rector-src-staabm\rules\CodingStyle\NodeAnalyzer\SpreadVariablesCollector.php(23):
         PHPStan\Reflection\ParametersAcceptorSelector::selectSingle()
         #1 C:\dvl\Workspace\rector-src-staabm\rules\CodingStyle\Rector\ClassMethod\UnSpreadOperatorRector.php(133):
         Rector\CodingStyle\NodeAnalyzer\SpreadVariablesCollector->resolveFromMethodReflection()
         #2 C:\dvl\Workspace\rector-src-staabm\rules\CodingStyle\Rector\ClassMethod\UnSpreadOperatorRector.php(88):
         Rector\CodingStyle\Rector\ClassMethod\UnSpreadOperatorRector->refactorMethodCall()
         #3 C:\dvl\Workspace\rector-src-staabm\src\Rector\AbstractRector.php(218):
         Rector\CodingStyle\Rector\ClassMethod\UnSpreadOperatorRector->refactor()
         #4 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(123):
         Rector\Core\Rector\AbstractRector->enterNode()
         #5 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223):
         PhpParser\NodeTraverser->traverseNode()
         #6 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114):
         PhpParser\NodeTraverser->traverseArray()
         #7 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223):
         PhpParser\NodeTraverser->traverseNode()
         #8 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114):
         PhpParser\NodeTraverser->traverseArray()
         #9 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223):
         PhpParser\NodeTraverser->traverseNode()
         #10 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114):
         PhpParser\NodeTraverser->traverseArray()
         #11 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223):
         PhpParser\NodeTraverser->traverseNode()
         #12 C:\dvl\Workspace\rector-src-staabm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(91):
         PhpParser\NodeTraverser->traverseArray()
         #13 C:\dvl\Workspace\rector-src-staabm\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(33):
         PhpParser\NodeTraverser->traverse()
         #14 C:\dvl\Workspace\rector-src-staabm\src\Application\FileProcessor.php(41):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #15 C:\dvl\Workspace\rector-src-staabm\src\Application\FileProcessor\PhpFileProcessor.php(76):
         Rector\Core\Application\FileProcessor->refactor()
         #16 C:\dvl\Workspace\rector-src-staabm\packages\Parallel\WorkerRunner.php(141):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
         #17 C:\dvl\Workspace\rector-src-staabm\packages\Parallel\WorkerRunner.php(96):
         Rector\Parallel\WorkerRunner->processFile()
         #18 C:\dvl\Workspace\rector-src-staabm\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()
         #19 C:\dvl\Workspace\rector-src-staabm\vendor\clue\ndjson-react\src\Decoder.php(139):
         Evenement\EventEmitter->emit()
         #20 C:\dvl\Workspace\rector-src-staabm\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123):
         Clue\React\NDJson\Decoder->handleData()
         #21 C:\dvl\Workspace\rector-src-staabm\vendor\react\stream\src\Util.php(71): Evenement\EventEmitter->emit()
         #22 C:\dvl\Workspace\rector-src-staabm\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123):
         React\Stream\Util::React\Stream\{closure}()
         #23 C:\dvl\Workspace\rector-src-staabm\vendor\react\stream\src\DuplexResourceStream.php(196):
         Evenement\EventEmitter->emit()
         #24 C:\dvl\Workspace\rector-src-staabm\vendor\react\event-loop\src\StreamSelectLoop.php(246):
         React\Stream\DuplexResourceStream->handleData()
         #25 C:\dvl\Workspace\rector-src-staabm\vendor\react\event-loop\src\StreamSelectLoop.php(213):
         React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #26 C:\dvl\Workspace\rector-src-staabm\src\Console\Command\WorkerCommand.php(66):
         React\EventLoop\StreamSelectLoop->run()
         #27 C:\dvl\Workspace\rector-src-staabm\vendor\symfony\console\Command\Command.php(312):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #28 C:\dvl\Workspace\rector-src-staabm\vendor\symfony\console\Application.php(1022):
         Symfony\Component\Console\Command\Command->run()
         #29 C:\dvl\Workspace\rector-src-staabm\vendor\symfony\console\Application.php(314):
         Symfony\Component\Console\Application->doRunCommand()
         #30 C:\dvl\Workspace\rector-src-staabm\src\Console\ConsoleApplication.php(58):
         Symfony\Component\Console\Application->doRun()
         #31 C:\dvl\Workspace\rector-src-staabm\vendor\symfony\console\Application.php(168):
         Rector\Core\Console\ConsoleApplication->doRun()
         #32 C:\dvl\Workspace\rector-src-staabm\bin\rector.php(164): Symfony\Component\Console\Application->run()
         #33 C:\dvl\Workspace\rector-src-staabm\bin\rector(4): require_once('...')
         #34 {main}". On line: 60
```

**Comment by samsonasik** [comment]
Change with : `ParametersAcceptorSelector::combineAcceptors($methodReflection->getVariants())` should resolve it.
