### ISSUE TITLE
System error: "assert(!$this->isFirstClassCallable())

### ISSUE THREAD

**Issue by thbley** [rectorphp/rector#7962]
# Bug Report

v0.17.0 gives "System error: "assert(!$this->isFirstClassCallable())"
v0.16.0 does not give the error

TasksRepository.php is here:
https://github.com/thbley/php_frameworkless/blob/master/tasks/src/Repositories/TasksRepository.php

```
[ERROR] Could not process "/var/www/src/Repositories/TasksRepository.php" file, due to:                                
         "System error: "assert(!$this->isFirstClassCallable())"                                                        
                                                                                                                        
         Stack trace:                                                                                                   
         #0 /tmp/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php(37): assert(false, 'assert(!$this->...')  
         #1 /tmp/rules/CodeQuality/Rector/FuncCall/IntvalToTypeCastRector.php(64):                                      
         PhpParser\Node\Expr\CallLike->getArgs()                                                                        
         #2 /tmp/src/Rector/AbstractRector.php(234):                                                                    
         Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector->refactor(Object(PhpParser\Node\Expr\FuncCall))      
         #3 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))                             
         #4 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))                                              
         #5 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #6 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))                                    
         #7 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))                                              
         #8 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #9 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))                                    
         #10 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #11 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #12 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #13 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #14 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #15 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #16 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #17 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #18 /tmp/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #19 /tmp/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)     
         #20 /tmp/src/Application/FileProcessor.php(60):                                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #21 /tmp/src/Application/FileProcessor/PhpFileProcessor.php(115):                                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #22 /tmp/packages/Parallel/WorkerRunner.php(144):                                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #23 /tmp/packages/Parallel/WorkerRunner.php(114):                                                              
         Rector\Parallel\WorkerRunner->processFile(Object(Rector\Core\ValueObject\Application\File),                    
         Object(Rector\Core\ValueObject\Configuration), Array)                                                          
         #24 /tmp/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #25 /tmp/vendor/clue/ndjson-react/src/Decoder.php(117):                                                        
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)                                                 
         #26 /tmp/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                                   
         RectorPrefix202306\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #27 /tmp/vendor/react/stream/src/Util.php(62): RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)  
         #28 /tmp/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                                   
         RectorPrefix202306\React\Stream\Util::RectorPrefix202306\React\Stream\{closure}('{"action":"main...')          
         #29 /tmp/vendor/react/stream/src/DuplexResourceStream.php(154):                                                
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)                                                 
         #30 /tmp/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                                
         RectorPrefix202306\React\Stream\DuplexResourceStream->handleData(Resource id #3006)                            
         #31 /tmp/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                                
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #32 /tmp/src/Console/Command/WorkerCommand.php(63): RectorPrefix202306\React\EventLoop\StreamSelectLoop->run() 
         #33 /tmp/vendor/symfony/console/Command/Command.php(325):                                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))                          
         #34 /tmp/vendor/symfony/console/Application.php(944):                                                          
         RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))           
         #35 /tmp/vendor/symfony/console/Application.php(326):                                                          
         RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #36 /tmp/src/Console/ConsoleApplication.php(49):                                                               
         RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))             
         #37 /tmp/vendor/symfony/console/Application.php(212):                                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))                               
         #38 /tmp/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()                  
         #39 /tmp/bin/rector(5): require_once('/tmp/bin/rector...')                                                     
         #40 {main}". On line: 37
```

**Comment by thbley** [comment]
my rector.php
```
<?php

use Rector\CodeQuality\Rector\Expression\InlineIfToExplicitIfRector;
use Rector\CodeQuality\Rector\Identical\FlipTypeControlToUseExclusiveTypeRector;
use Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector;
use Rector\Config\RectorConfig;
use Rector\EarlyReturn\Rector\If_\ChangeOrIfReturnToEarlyReturnRector;
use Rector\Naming\Rector\Assign\RenameVariableToMatchMethodCallReturnTypeRector;
use Rector\Naming\Rector\Class_\RenamePropertyToMatchTypeRector;
use Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\Privatization\Rector\Class_\ChangeReadOnlyVariableWithDefaultValueToConstantRector;
use Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $rectorConfig->sets([
        SetList::CODE_QUALITY,
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
        SetList::NAMING,
        SetList::PRIVATIZATION,
        SetList::PSR_4,
        SetList::TYPE_DECLARATION,
        SetList::EARLY_RETURN,
        SetList::ACTION_INJECTION_TO_CONSTRUCTOR_INJECTION,
        SetList::PHP_82,
        LevelSetList::UP_TO_PHP_82,
    ]);

    $rectorConfig->skip([
        RenamePropertyToMatchTypeRector::class,
        RenameVariableToMatchMethodCallReturnTypeRector::class,
        ReadOnlyPropertyRector::class,
        FinalizeClassesWithoutChildrenRector::class,
        ChangeReadOnlyVariableWithDefaultValueToConstantRector::class,
        ChangeOrIfReturnToEarlyReturnRector::class,
        AddArrayDefaultToArrayPropertyRector::class,
        InlineIfToExplicitIfRector::class,
        ClassPropertyAssignToConstructorPromotionRector::class,
        RestoreDefaultNullToNullableTypePropertyRector::class,
        FlipTypeControlToUseExclusiveTypeRector::class,
        __DIR__ . '/src/vendor',
    ]);
};
```

**Comment by thbley** [comment]
https://github.com/rectorphp/rector-src/pull/4040
