### ISSUE TITLE
Scope not available on "PhpParser\Node\Name\FullyQualified" node

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector#7972]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector c9fc74baf53ce9104403c492fcd13dec435dad9c           |

This only started erroring recently, Ive ignored it because the MLYMMFMSr6.php file is not part of my project - its the Opcache Control Panel file from https://gist.github.com/ck-on/4959032/?ocp.php but Im guessing you would like rector to not fail on such code 

```
[ERROR] Could not process "/Users/phil/Sites/manage.mysites.guru/public/MLYMMFMSr6.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Name\FullyQualified" node with parent node of
         "PhpParser\Node\Expr\ConstFetch", but is required by a refactorWithScope() method of
         "Rector\Renaming\Rector\Name\RenameClassRector" rule. Fix scope refresh on changed nodes first"

         Stack trace:
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(234):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Name\FullyQualified))
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Name\FullyQualified))
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ConstFetch))
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Param))
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Function_))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse(Array)
         #10 vendor/rector/rector/src/Application/FileProcessor.php(60):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #11 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #12 vendor/rector/rector/packages/Parallel/WorkerRunner.php(144):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil
         e), Object(Rector\Core\ValueObject\Configuration))
         #13 vendor/rector/rector/packages/Parallel/WorkerRunner.php(114):
         Rector\Parallel\WorkerRunner->processFile(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration), Array)
         #14 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #15 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #16 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202306\Clue\React\NDJson\Decoder->handleData(Array)
         #17 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #18 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202306\React\Stream\Util::RectorPrefix202306\React\Stream\{closure}('{"action":"main...')
         #19 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #20 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202306\React\Stream\DuplexResourceStream->handleData(Resource id #3035)
         #21 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #22 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->run()
         #23 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\A
         rgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #24 vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #25 vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work
         erCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #26 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #28 vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
         #29 vendor/rector/rector/bin/rector(5): require_once('/Users/phil/Sit...')
         #30 vendor/bin/rector(119): include('/Users/phil/Sit...')
         #31 {main}". On line: 53
```

## Minimal PHP Code Causing Issue

Run rector on this file https://gist.github.com/ck-on/4959032/?ocp.php

using any one of these set lists will cause the issue

```
    $rectorConfig->sets(
        [
// Choose one of the following
            SwiftmailerSetList::SWIFTMAILER_TO_SYMFONY_MAILER,
            TwigSetList::TWIG_240,
            SymfonySetList::SYMFONY_62,
            LevelSetList::UP_TO_PHP_82,
        ]
    );
```

## Expected Behaviour

Not to crash :)

**Comment by samsonasik** [comment]
Could you provide reproducible test on https://getrector.com/demo/  , or we need simple reproducible code for that that show error, with only 1 or 2 rules, you can provide reproducible github repo, better with github action running

https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/

**Comment by PhilETaylor** [comment]
Not with the full file I cannot, because the source PHP file is too long for the input restrictions on that form. I tried that before  logging the ticket and it only allows 100 lines - and I could not find just 100 lines that replicated the problem :( 

<img width="1058" alt="ScreenShot-2023-06-03-11 02 57" src="https://github.com/rectorphp/rector/assets/400092/343ea17d-0be8-4e67-ac53-ccf270f51cb0">

**Comment by samsonasik** [comment]
That's take time to reduce lines to get reproducible bug, it usually only about +10 lines for actual bug, feel free to provide it when you have a chance ;)

**Comment by PhilETaylor** [comment]
ok, as Im deleting lines, I can replicate many other error messages now



```
 [ERROR] Could not process "/Users/phil/Sites/manage.mysites.guru/public/MLYMMFMSr6.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of
         "PhpParser\Node\Expr\BooleanNot", but is required by a refactorWithScope() method of
         "Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector" rule. Fix scope refresh on changed nodes
         first"
```


```
 [ERROR] Could not process "/Users/phil/Sites/manage.mysites.guru/public/MLYMMFMSr6.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Stmt\Expression" node with parent node of
         "PhpParser\Node\Stmt\Function_", but is required by a refactorWithScope() method of
         "Rector\Php74\Rector\FuncCall\MoneyFormatToNumberFormatRector" rule. Fix scope refresh on changed nodes first"
```

I think it all relates to `exit` being before more functions

This is a simple reproducer https://getrector.com/demo/20c4b326-96a0-4f92-ab85-6c690ea79197

Another with a different Set List with the same code, a different error https://getrector.com/demo/3aba78fe-d831-4782-a85b-1c50dbea65b8

**Comment by samsonasik** [comment]
Thank you, yes, `exit` is unreachable statement, so it possibly that after that, scope is not fully filled, there is already handling for after unreachable statement for it, but probably currenlty don't cover deep inside stmt

https://github.com/rectorphp/rector-src/blob/c9fc74baf53ce9104403c492fcd13dec435dad9c/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L332-L339

**Comment by PhilETaylor** [comment]
No worries, like I said this is not impacting me in my project's codebases at all - I just noticed it on this one example file (The Opcache Control Panel code - which is old and badly written anyway) so there is absolutely no pressure from me for it to be fixed :)

**Comment by samsonasik** [comment]
It seems only happen when no namespace in the file, you can add an empty namespace just as workaround it for now 

https://getrector.com/demo/4aa0f413-cbd0-4281-a740-d370b41f764d

**Comment by PhilETaylor** [comment]
Ive confirmed that works when used in the full file too - thanks, so for now I'll just wrap this code in a namespace

**Comment by samsonasik** [comment]
Thank you for verify, no namespaced file is a hard one to cover Scope after exit, as `FileWithoutNamespaceNodeTraverser` for custom `FileWithoutNamespace` seems currently filled late. 

I've been looking on this, but not sure if it fixable yet. I am glad that empty namespace is working for you ;)
