### ISSUE TITLE
Rector not recognizing "assert" methods in Dfp unit tests.

### ISSUE THREAD

**Issue by dvenckusvh** [rectorphp/rector#7979]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.5 (invoke `vendor/bin/rector --version`)             |

| Rector version | 0.15.25                                                         |

"System error: "Method assertPattern() was not found in reflection of class
         Drupal\Tests\dfp\Functional\DfpTestBase."

"System error: "Method assertRaw() was not found in reflection of class                                        
         Drupal\Tests\dfp\Functional\DisplayTagTest."
         
"System error: "Method assertNoRaw() was not found in reflection of class                                      
         Drupal\Tests\dfp\Functional\GlobalSettingsTest."

## Minimal PHP Code Causing Issue

Stack trace:                                                                                                   
         #0 vendor/palantirnet/drupal-rector/src/Utility/GetDeclaringSourceTrait.php(33):                               
         PHPStan\Reflection\ClassReflection->getMethod('assertPattern', Object(PHPStan\Analyser\MutatingScope))         
         #1 vendor/palantirnet/drupal-rector/src/Rector/Deprecation/Base/AssertLegacyTraitBase.php(47):                 
         DrupalRector\Rector\Deprecation\Base\AssertLegacyTraitBase->getDeclaringSource(Object(PhpParser\Node\Expr\Meth 
         odCall))                                                                                                       
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(220):                                                    
         DrupalRector\Rector\Deprecation\Base\AssertLegacyTraitBase->refactor(Object(PhpParser\Node\Expr\MethodCall))   
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))                           
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))                                     
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #13 vendor/rector/rector/src/Application/FileProcessor.php(60):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #14 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(106):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #15 vendor/rector/rector/packages/Parallel/WorkerRunner.php(130):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106):                                              
         Rector\Parallel\WorkerRunner->processFiles(Object(Rector\Core\ValueObject\Application\File),                   
         Object(Rector\Core\ValueObject\Configuration), Array)                                                          
         #17 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #18 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)                                                 
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202304\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #20 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)                                                 
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202304\React\Stream\Util::RectorPrefix202304\React\Stream\{closure}('{"action":"main...')          
         #22 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202304\Evenement\EventEmitter->emit('data', Array)                                                 
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202304\React\Stream\DuplexResourceStream->handleData(Resource id #14703)                           
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->run()                                                     
         #26 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202304\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))                          
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(899):                                          
         RectorPrefix202304\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202304\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))           
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(320):                                          
         RectorPrefix202304\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202304\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #29 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202304\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202304\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))             
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(206):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202304\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202304\Symfony\Component\Console\Output\ConsoleOutput))                               
         #31 vendor/rector/rector/bin/rector.php(128): RectorPrefix202304\Symfony\Component\Console\Application->run()  
         #32 vendor/rector/rector/bin/rector(5): require_once('/Users/debra/ht...')                                     
         #33 vendor/bin/rector(120): include('/Users/debra/ht...')                                                      
         #34 {main}". On line: 454       

## Expected Behaviour

Run to completion.

Handle the error and/or report it and end gracefully.

**Comment by samsonasik** [comment]
Duplicate with https://github.com/rectorphp/rector/issues/7766, you need to report there :) https://github.com/palantirnet/drupal-rector/blob/09d3dc6a422483de4c7c9b17692a48252b6b0af3/src/Utility/GetDeclaringSourceTrait.php#L33
