### ISSUE TITLE
Using Larastan (Laravel for PHPStan) through Rector

### ISSUE THREAD

**Issue by stefandoorn** [rectorphp/rector#8006]
- Larastan Version: v2.6.2
- Rector Version: v0.17.0

Running PHPStan works fine, but running it through `Rector` I get this error.

Rector config loads PHPStan config:

```
$config->phpstanConfig(__DIR__ . '/phpstan.neon.dist');
```

PHPStan loads Larastan:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
```

Works fine: `./vendor/bin/phpstan analyse`

Error: `./vendor/bin/rector process`

Error output below. I do see that in `bootstrap.php` a LARAVEL_VERSION is set derived from `$app->version()`. Somehow loading this config through Rector does something where - I assume - bootstrap is not being processed.

Tried to debug this a bit, but I'm a bit stuck on how this works.

I'm slightly in doubt whether this is more of a Rector issue or a Larastan issue.. removing the config does make Rector work again, but with less rules of course. So I also filed an issue with Larastan under https://github.com/nunomaduro/larastan/issues/1664. 

```
[ERROR] Could not process "/var/www/html/app/Filters/Single/BelongsToFilter.php" file, due to:                 
         "System error: "Undefined constant "NunoMaduro\Larastan\ReturnTypes\LARAVEL_VERSION""                          
                                                                                                                        
         Stack trace:                                                                                                   
         #0 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3364):       
         NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->isMethodSupport 
         ed()                                                                                                           
         #1 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1356):       
         PHPStan\Analyser\MutatingScope->methodCallReturnType()                                                         
         #2 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1362):       
         PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                   
         #3 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(558):        
         PHPStan\Analyser\MutatingScope->resolveType()                                                                  
         #4 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2412):   
         PHPStan\Analyser\MutatingScope->getType()                                                                      
         #5 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1711):   
         PHPStan\Analyser\NodeScopeResolver->getMethodThrowPoint()                                                      
         #6 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(546):    
         PHPStan\Analyser\NodeScopeResolver->processExprNode()                                                          
         #7 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
         #8 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(531):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
         #9 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):    
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
         #10 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(609):   
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
         #11 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362):   
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
         #12 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(581):   
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                                                         
         #13 phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(331):   
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
         #14 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(332):            
         PHPStan\Analyser\NodeScopeResolver->processNodes()                                                             
         #15 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(215):            
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithDependentFiles()               
         #16 vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(41):                      
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()                                 
         #17 vendor/rector/rector/src/Application/FileProcessor.php(54):                                                
         Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile()                                 
         #18 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(165):                              
         Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache()                                             
         #19 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(104):                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->parseFileAndDecorateNodes()                            
         #20 vendor/rector/rector/packages/Parallel/WorkerRunner.php(144):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #21 vendor/rector/rector/packages/Parallel/WorkerRunner.php(114): Rector\Parallel\WorkerRunner->processFile()  
         #22 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
         #24 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202306\Clue\React\NDJson\Decoder->handleData()                                                     
         #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
         #26 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202306\React\Stream\Util::RectorPrefix202306\React\Stream\{closure}()                              
         #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202306\Evenement\EventEmitter->emit()                                                              
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202306\React\Stream\DuplexResourceStream->handleData()                                             
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->run()                                                     
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202306\Symfony\Component\Console\Command\Command->run()                                            
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand()                                       
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202306\Symfony\Component\Console\Application->doRun()                                              
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #36 vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()  
         #37 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #38 vendor/bin/rector(120): include('...')                                                                     
         #39 {main}". On line: 47                                                                                      
```

**Comment by stefandoorn** [comment]
To add, this started in an upgrade where this happens. Before that it did work without error.

```
laravel/framework ^v9.0 -> ^v10.0
rector/rector ^0.14 -> ^0.17
Installed driftingly/rector-laravel at ^0.20
```

**Comment by TomasVotruba** [comment]
Hi,

thanks for questions. We're working making a Rector core here.
For Laravel specific questions, it's better to go to Laravel package for Rector → https://github.com/driftingly/rector-laravel

There you'll be able to get better answer and help, as it's maintained by much experienced Laravel developers :+1:

**Comment by philbates35** [comment]
@stefandoorn Were you ever able to resolve this? I just came across this exact just now on latest rector, phpstan, larastan on an empy fresh Laravel project.

```neon
# phpstan.dist.neon
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon

parameters:
    paths:
        - app
        - bootstrap
        - config
        - database
        - routes
        - tests
    level: 9
    excludePaths:
        - bootstrap/cache/
```
```php
// rector.php
declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/app',
        __DIR__ . '/bootstrap',
        __DIR__ . '/config',
        __DIR__ . '/public',
        __DIR__ . '/resources',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ]);
    $rectorConfig->skip([
        __DIR__ . '/bootstrap/cache',
    ]);
    $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon.dist');
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_83,
    ]);
};
```
Then run `vendor/bin/rector process --dry-run` and get:
```
 [ERROR] Could not process "/app/routes/channels.php" file, due to:                                                     
         "System error: "Undefined constant "Larastan\Larastan\LARAVEL_VERSION""                                        
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/symfony/finder/Iterator/CustomFilterIterator.php(54):                                                
         Larastan\Larastan\LarastanStubFilesExtension->Larastan\Larastan\{closure}(Object(Symfony\Component\Finder\SplF 
         ileInfo))                                                                                                      
         #1 [internal function]: Symfony\Component\Finder\Iterator\CustomFilterIterator->accept()                       
         #2 [internal function]: FilterIterator->rewind()                                                               
         #3 [internal function]: FilterIterator->rewind()                                                               
         #4 vendor/symfony/finder/Iterator/SortableIterator.php(93):                                                    
         iterator_to_array(Object(Symfony\Component\Finder\Iterator\PathFilterIterator), true)       
        ...
```

**Comment by stefandoorn** [comment]
@philbates35 I've disabled the PHPStan import & filed https://github.com/larastan/larastan/issues/1664 which didn't provide too much helpful insights. It's still disabled on our end, haven't put any more effort into it unfortunately.

**Comment by philbates35** [comment]
Thanks @stefandoorn, I tried the suggestion in the linked thread https://github.com/larastan/larastan/issues/1664#issuecomment-1637152828 which appears to have fixed it!

```diff
+    $rectorConfig->bootstrapFiles([__DIR__ . '/vendor/larastan/larastan/bootstrap.php']);
     $rectorConfig->phpstanConfig(__DIR__ . '/phpstan.neon.dist');
```
As Larastan works fine when running PHPStan manually, I can only assume its something related to the way in which Rector is internally booting PHPStan, would be good to know if this is intentional or not.
