### ISSUE TITLE
Call to undefined method BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()

### ISSUE THREAD

**Issue by Kauto** [rectorphp/rector#8063]
After running rector over my code I get the error
```
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 483
                                                                                                                        
```

Running with debug-options returns the log:
```
                                                                                                                       
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(504):                  
         PhpParser\PrettyPrinterAbstract->pFallback()                                                                   
         #1 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #3 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #5 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #7 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                  
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #9 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #11 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #13 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #15 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #17 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #19 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #21 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #23 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #25 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #26 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #27 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #28 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #29 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #30 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #31 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #32 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #33 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #34 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #35 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #36 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #37 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #38 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #39 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #40 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #41 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #42 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #43 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #44 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(471):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #45 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(101):                                 
         PhpParser\PrettyPrinterAbstract->printFormatPreserving()                                                       
         #46 vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(44):                                
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving()                                   
         #47 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(192):                              
         Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString()                     
         #48 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(122):                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile()                                            
         #49 vendor/rector/rector/packages/Parallel/WorkerRunner.php(136):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #50 vendor/rector/rector/packages/Parallel/WorkerRunner.php(107): Rector\Parallel\WorkerRunner->processFile()  
         #51 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #52 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #53 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\Clue\React\NDJson\Decoder->handleData()                                                     
         #54 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #55 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\React\Stream\Util::RectorPrefix202307\React\Stream\{closure}()                              
         #56 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #57 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202307\React\Stream\DuplexResourceStream->handleData()                                             
         #58 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #59 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->run()                                                     
         #60 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #61 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202307\Symfony\Component\Console\Command\Command->run()                                            
         #62 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202307\Symfony\Component\Console\Application->doRunCommand()                                       
         #63 vendor/rector/rector/src/Console/ConsoleApplication.php(54):                                               
         RectorPrefix202307\Symfony\Component\Console\Application->doRun()                                              
         #64 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #65 vendor/rector/rector/bin/rector.php(132): RectorPrefix202307\Symfony\Component\Console\Application->run()  
         #66 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #67 vendor/bin/rector(119): include('...')                                                                     
         #68 {main}". On line: 483                                                                                      
                               
```

The Compare-File:
```PHP
<?php

namespace App\JsonApi;

use App\JsonApi\Types\BaseItem;
use Exception;
use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use JsonException;

class Compare
{
    protected Client $client;

    public string $itemClassName;

    public string $modelClassName;

    public string $tableName;

    public string $model;

    /**
     * @throws GuzzleException
     */
    public function __construct($model, public ?string $endpointName = null)
    {
        $this->client = new Client($endpointName);
        $this->model = Str::of($model)->singular()->snake()->__toString();
        $this->modelClassName = Str::of($this->model)->studly()->prepend('App\\Models\\')->__toString();
        $this->itemClassName = Str::of($this->model)->studly()->prepend('App\\JsonApi\\Types\\')->append('Item')->__toString();
        $this->tableName = Str::of($this->model)->plural()->snake()->__toString();
    }

    public function databaseColumns(): array
    {
        return Schema::getColumnListing($this->tableName);
    }

    public function modelClassExists(): bool
    {
        return class_exists($this->modelClassName);
    }

    public function itemClass(): ?BaseItem
    {
        return class_exists($this->itemClassName) ? new ($this->itemClassName)() : null;
    }

    public function itemRegistered(): bool
    {
        return $this->client->hasModel($this->itemClassName);
    }

    public function itemClassExists(): bool
    {
        return class_exists($this->itemClassName);
    }

    public function getDefinedType(): ?string
    {
        try {
            return $this->client->getTypeByModel($this->model);
        } catch (Exception $e) {
            return null;
        }
    }

    public function getType(): ?string
    {
        $type = $this->getDefinedType();

        if (! $type) {
            $types = array_keys($this->client->call('/jsonapi')->getLinks()->toArray());
            $type = Arr::first($types, fn ($type) => Str::of($type)->endsWith($this->model));
        }

        return $type;
    }

    /**
     * @throws GuzzleException
     * @throws JsonException
     */
    public function getMissingDatabaseColumns(): array
    {
        $columns = $this->databaseColumns() ?? [];
        $creator = new Creator($this->getType(), $this->endpointName);
        $cleanedList = ['id' => true, ...$creator->getSchemaCleanedAttributes(), ...$creator->getSchemaCleanedRelations()];
        $ignoreList = $this->itemClass()?->ignoredAttributes() ?? [];
        $missingCleanedColumns = array_diff_key($cleanedList, array_flip($columns), array_flip($ignoreList));

        return collect($missingCleanedColumns)
            ->map(function ($column, $key) {
                switch ($key) {
                    case 'id':
                        return "{$key}:id";
                    case 'uuid':
                        return "{$key}:uuid:unique";
                    case 'uri':
                        return "{$key}:string:unique";
                    default:
                        if (! empty($column['asJson'])) {
                            return "{$key}:json:nullable";
                        }
                        $tableName = Str::of($key)->plural()->snake()->__toString();

                        return match ($column['type']) {
                            'array', 'object' => "{$key}:json:nullable",
                            'boolean' => "{$key}:boolean:default(".(empty($column['default']) ? 'false' : 'true').')',
                            'hasOne'  => "{$key}_id:foreignId:nullable:constrained({$tableName}):nullOnDelete",
                            'morphTo' => "{$key}:morphs",
                            'hasMany', 'morphToMany' => null,
                            default   => "{$key}:{$column['type']}:nullable",
                        };
                }
            })
            ->filter()
            ->all();
    }

    /**
     * @throws GuzzleException
     * @throws JsonException
     */
    public function modifyDatabase()
    {
        $mode = $this->databaseColumns() ? 'add' : 'create';
        $schema = $this->getMissingDatabaseColumns();

        Artisan::call('make:migration:schema', [
            'name'     => "{$mode}_{$this->tableName}_table",
            '--schema' => implode(',', $schema),
        ]);

        if (! $this->databaseColumns()) {
            Artisan::call('make:model', [
                'name' => basename($this->modelClassName),
            ]);
        }

        $creator = new Creator($this->getType(), $this->endpointName);
        $relations = $creator->getSchemaCleanedRelations();
        foreach ($relations as $key => $relation) {
            if ('hasMany' === $relation['type']) {
                Artisan::call('make:migration:pivot', [
                    'tableOne' => $this->tableName,
                    'tableTwo' => Str::of($key)->plural()->snake(),
                ]);
            }
        }
    }
}
```

**Comment by samsonasik** [comment]
What Rector version you're using? It should already resolved in latest version.

**Comment by Kauto** [comment]
it's happening with 0.17.6.

**Comment by samsonasik** [comment]
Could you reproduce at https://getrector.com/demo ?

**Comment by Kauto** [comment]
yes, here: https://getrector.com/demo/b2898d76-9439-483d-8e4f-35e50b5347cc

**Comment by samsonasik** [comment]
Ok, reproduced with single rule: `OptionalParametersAfterRequiredRector` ref https://getrector.com/demo/bf537a77-1c66-474c-b415-9b2794835341

**Comment by samsonasik** [comment]
Not sure why it can't be reproduced via unit test and e2e test, could you try latest dev-main ?

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

then run:

```
vendor/bin/rector process --clear-cache
```

**Comment by Kauto** [comment]
Thank you for the help! I tried the latest dev-main. Same error:
```                                                      
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 483
```

with debug:
```
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(504):                  
         PhpParser\PrettyPrinterAbstract->pFallback()                                                                   
         #1 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #3 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #5 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #7 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                  
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #9 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #11 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #13 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #15 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #17 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #19 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #21 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #23 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #25 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #26 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #27 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #28 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #29 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #30 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #31 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #32 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #33 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #34 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #35 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #36 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #37 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #38 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #39 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #40 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #41 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #42 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #43 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #44 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(471):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #45 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(101):                                 
         PhpParser\PrettyPrinterAbstract->printFormatPreserving()                                                       
         #46 vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(44):                                
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving()                                   
         #47 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(192):                              
         Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString()                     
         #48 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(122):                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile()                                            
         #49 vendor/rector/rector/packages/Parallel/WorkerRunner.php(136):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #50 vendor/rector/rector/packages/Parallel/WorkerRunner.php(107): Rector\Parallel\WorkerRunner->processFile()  
         #51 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #52 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #53 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\Clue\React\NDJson\Decoder->handleData()                                                     
         #54 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #55 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\React\Stream\Util::RectorPrefix202307\React\Stream\{closure}()                              
         #56 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #57 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202307\React\Stream\DuplexResourceStream->handleData()                                             
         #58 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #59 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->run()                                                     
         #60 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #61 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202307\Symfony\Component\Console\Command\Command->run()                                            
         #62 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202307\Symfony\Component\Console\Application->doRunCommand()                                       
         #63 vendor/rector/rector/src/Console/ConsoleApplication.php(54):                                               
         RectorPrefix202307\Symfony\Component\Console\Application->doRun()                                              
         #64 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #65 vendor/rector/rector/bin/rector.php(132): RectorPrefix202307\Symfony\Component\Console\Application->run()  
         #66 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #67 vendor/bin/rector(119): include('...')                                                                     
         #68 {main}". On line: 483   
```

**Comment by samsonasik** [comment]
Could you create simple reproducible github repo? I can't reproducible locally, so it possibly related with pointing config rector.php which not in root project

**Comment by samsonasik** [comment]
@Kauto the issue seems happen when there is method call `->filter()` directly 

https://getrector.com/demo/bf537a77-1c66-474c-b415-9b2794835341

when it moved to new variable first, it seems working ok

https://getrector.com/demo/5c9fc6bd-fb31-4e39-895a-fada0a2be378

For workaround, I think refactor to new variable first is the way to go.

**Comment by samsonasik** [comment]
@TomasVotruba I tried manually on server, it seems can be tweaked by verify MethodCall var is not callike:

```php
if ($methodCall->var instanceof Node\Expr\CallLike) { return null; }
```

**Comment by samsonasik** [comment]
@TomasVotruba no, that not fluent call, that bug is on fluent call

https://getrector.com/demo/431c4ae4-1981-4204-b3d3-1ebca0cf9e9f

**Comment by TomasVotruba** [comment]
I see, could you add that test fixture in a new PR so we have it failing in CI? 

I'll check it now

**Comment by samsonasik** [comment]
It infortunatelly can't be reproduced via unit test, it possibly some server php extension cause too early printing so it caugh early

The test is at https://github.com/rectorphp/rector-src/pull/4533/files#diff-43d18b6e54a143fee5835ef6d23e0c69d497b74dfa8856561c4e180605114389 but it show green in CI

**Comment by TomasVotruba** [comment]
@samsonasik I see. We'll need that reproducer to avoid shots in the dark.

@Kauto Could you share minimal reproducible repository where this happens? It will be few lines from the `app/JsonApi/Compare.php` file. Only that way we can fix it.
