### ISSUE TITLE
Parse failure: JNDAEL_128""

### ISSUE THREAD

**Issue by jtheuerkauf** [rectorphp/rector#8118]
Working on a hobby project to see if/how I can bring ZF1 into PHP 8.2. Figured Rector would be the perfect tool to help.
Let me know what other info I can send that might help.

Report from `--debug` run:

```
library/Zend/Service/ReCaptcha/MailHide.php
[file] library/Zend/Service/ReCaptcha/MailHide.php
[rule] Rector\Php80\Rector\Catch_\RemoveUnusedVariableInCatchRector
--- consumed 2 MB, total 82 MB, took 0.00 s

[file] library/Zend/Service/ReCaptcha/MailHide.php
[rule] Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector
--- consumed 0 B, total 82 MB, took 0.00 s

[file] library/Zend/Service/ReCaptcha/MailHide.php
[rule] Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector
--- consumed 0 B, total 82 MB, took 0.00 s

[file] library/Zend/Service/ReCaptcha/MailHide.php
[rule] Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector


R] Could not process "C:\dev\code\php\zf1-future/library/Zend/Service/ReCaptcha/MailHide.php" file, due to:
                                                JNDAEL_128""

#0  ...\vendor\rector\rector\src\PhpParser\Node\Value\ValueResolver.php(273): defined()
#1  ...\vendor\rector\rector\src\PhpParser\Node\Value\ValueResolver.php(206):
    Rector\Core\PhpParser\Node\Value\ValueResolver->resolveClassConstFetch()
#2  ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\ConstExprEvaluator.php(131):
    Rector\Core\PhpParser\Node\Value\ValueResolver->Rector\Core\PhpParser\Node\Value\{closure}()
#3  ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\ConstExprEvaluator.php(96):
    PhpParser\ConstExprEvaluator->evaluate()
#4  ...\vendor\rector\rector\src\PhpParser\Node\Value\ValueResolver.php(181):
    PhpParser\ConstExprEvaluator->evaluateDirectly()
#5  ...\vendor\rector\rector\src\PhpParser\Node\Value\ValueResolver.php(113):
    Rector\Core\PhpParser\Node\Value\ValueResolver->resolveExprValueForConst()
#6  ...\vendor\rector\rector\rules\Php73\Rector\FuncCall\JsonThrowOnErrorRector.php(139):
    Rector\Core\PhpParser\Node\Value\ValueResolver->getValue()
#7  ...\vendor\rector\rector\rules\Php73\Rector\FuncCall\JsonThrowOnErrorRector.php(102):
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector->isFirstValueStringOrArray()
#8  ...\vendor\rector\rector\rules\Php73\Rector\FuncCall\JsonThrowOnErrorRector.php(66):
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector->shouldSkipFuncCall()
#9  ...\vendor\rector\rector\packages\PhpDocParser\NodeVisitor\CallableNodeVisitor.php(34):
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector->Rector\Php73\Rector\FuncCall\{closure}()
#10 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(113):
    Rector\PhpDocParser\NodeVisitor\CallableNodeVisitor->enterNode()
#11 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(133):
    PhpParser\NodeTraverser->traverseNode()
#12 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
    PhpParser\NodeTraverser->traverseNode()
#13 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
    PhpParser\NodeTraverser->traverseArray()
#14 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
    PhpParser\NodeTraverser->traverseNode()
#15 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
    PhpParser\NodeTraverser->traverseArray()
#16 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
    PhpParser\NodeTraverser->traverseNode()
#17 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):
    PhpParser\NodeTraverser->traverseArray()
#18 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):
    PhpParser\NodeTraverser->traverseNode()
#19 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):
    PhpParser\NodeTraverser->traverseArray()
#20 ...\vendor\rector\rector\packages\PhpDocParser\NodeTraverser\SimpleCallableNodeTraverser.php(27):
    PhpParser\NodeTraverser->traverse()
#21 ...\vendor\rector\rector\src\Rector\AbstractRector.php(278):
    Rector\PhpDocParser\NodeTraverser\SimpleCallableNodeTraverser->traverseNodesWithCallable()
#22 ...\vendor\rector\rector\rules\Php73\Rector\FuncCall\JsonThrowOnErrorRector.php(62):
    Rector\Core\Rector\AbstractRector->traverseNodesWithCallable()
#23 ...\vendor\rector\rector\src\Rector\AbstractRector.php(204):
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector->refactor()
#24 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(176):
    Rector\Core\Rector\AbstractRector->enterNode()
#25 ...\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):
    PhpParser\NodeTraverser->traverseArray()
#26 ...\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(43):
    PhpParser\NodeTraverser->traverse()
#27 ...\vendor\rector\rector\src\Application\FileProcessor.php(44):
    Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
#28 ...\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(101):
    Rector\Core\Application\FileProcessor->refactor()
#29 ...\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(171):
    Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#30 ...\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(144):
    Rector\Core\Application\ApplicationFileProcessor->processFile()
#31 ...\vendor\rector\rector\packages\Parallel\WorkerRunner.php(65):
    Rector\Core\Application\ApplicationFileProcessor->processFiles()
#32 ...\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):
    Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()
#33 ...\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(117):
    RectorPrefix202308\Evenement\EventEmitter->emit()
#34 ...\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):
    RectorPrefix202308\Clue\React\NDJson\Decoder->handleData()
#35 ...\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
    RectorPrefix202308\Evenement\EventEmitter->emit()
#36 ...\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):
    RectorPrefix202308\React\Stream\Util::RectorPrefix202308\React\Stream\{closure}()
#37 ...\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):
    RectorPrefix202308\Evenement\EventEmitter->emit()
#38 ...\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):
    RectorPrefix202308\React\Stream\DuplexResourceStream->handleData()
#39 ...\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):
    RectorPrefix202308\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#40 ...\vendor\rector\rector\src\Console\Command\WorkerCommand.php(63):
    RectorPrefix202308\React\EventLoop\StreamSelectLoop->run()
#41 ...\vendor\rector\rector\vendor\symfony\console\Command\Command.php(325):
    Rector\Core\Console\Command\WorkerCommand->execute()
#42 ...\vendor\rector\rector\vendor\symfony\console\Application.php(944):
    RectorPrefix202308\Symfony\Component\Console\Command\Command->run()
#43 ...\vendor\rector\rector\vendor\symfony\console\Application.php(326):
    RectorPrefix202308\Symfony\Component\Console\Application->doRunCommand()
#44 ...\vendor\rector\rector\src\Console\ConsoleApplication.php(54):
    RectorPrefix202308\Symfony\Component\Console\Application->doRun()
#45 ...\vendor\rector\rector\vendor\symfony\console\Application.php(212):
    Rector\Core\Console\ConsoleApplication->doRun()
#46 ...\vendor\rector\rector\bin\rector.php(132):
    RectorPrefix202308\Symfony\Component\Console\Application->run()
#47 ...\vendor\rector\rector\bin\rector(5): require_once('...')
#48 ...\bin\rector(119): include('...')
#49 {main}". On line: 273
```

The PHP file is attached (as plain text)

[MailHide.txt](https://github.com/rectorphp/rector/files/12268793/MailHide.txt)

**Comment by samsonasik** [comment]
The `MCRYPT_RIJNDAEL_128` seems not exists, it available when you have mcrypt extension

https://stackoverflow.com/questions/29993399/use-of-undefined-constant-mcrypt-rijndael-128-assumed-mcrypt-rijndael-128

**Comment by jtheuerkauf** [comment]
Ahhh, that makes sense. Sorry for the hasty issue report. Unfortunately, because the PECL site is still unable to build DLLs, i guess i have to skip that one for now. i'll set up WSL to do the scan eventually.

Thanks for the assist.
