### ISSUE TITLE
Failed to create directory "/tmp/cache/PHPStan" (unknown cause)

### ISSUE THREAD

**Issue by dimitriBouteille** [rectorphp/rector#8139]
# Bug Report

| Subject        | Details  |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.12 |
| PHP version | 8.1 |
| PHPStan version | 1.10.29 |
| bitexpert/phpstan-magento version | 0.30.1 |

# The bug

I test to set up Rector on a Magento project, for that I use a PHPStan extension for Magento: [bitExpert/phpstan-magento](https://github.com/bitExpert/phpstan-magento).

When I run `php vendor/bin/rector` I have several times the following error: 

```txt
Could not process "/home/***/Service/TransactionUrlsGenerator.php" file, due to:                                                                                      
         "System error: "Failed to create directory "tmp/cache/PHPStan/44/58" (unknown cause)."
```
<details>
<summary>Full log with --debug flag</summary>

```txt
  [ERROR] Could not process                                                      
         "/***/composer/magento/swissbilling-payme
         nt/Controller/Adminhtml/Logs/Index.php" file, due to:                  
         "System error: "Failed to create directory "/tmp/cache/PHPStan"        
         (unknown cause)."                                                      
                                                                                
         Stack trace:                                                           
         #0                                                                     
         vendor/bitexpert/phpstan-magento/src/bitExpert/PHPStan/Magento/Autoload
         /Cache/FileCacheStorage.php(61):                                       
         bitExpert\PHPStan\Magento\Autoload\Cache\FileCacheStorage->makeDir()   
         #1                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Cac
         he/Cache.php(28):                                                      
         bitExpert\PHPStan\Magento\Autoload\Cache\FileCacheStorage->save()      
         #2                                                                     
         vendor/bitexpert/phpstan-magento/src/bitExpert/PHPStan/Magento/Autoload
         /FactoryAutoloader.php(53): PHPStan\Cache\Cache->save()                
         #3                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(272): 
         bitExpert\PHPStan\Magento\Autoload\FactoryAutoloader->autoload()       
         #4                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/FileReadTrapStreamWrapper.php(62
         ):                                                                     
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ::PHPStan\Reflection\BetterReflection\SourceLocator\{closure}()        
         #5                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(284): 
         PHPStan\Reflection\BetterReflection\SourceLocator\FileReadTrapStreamWra
         pper::withStreamWrapperOverride()                                      
         #6                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(119): 
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ->locateClassByName()                                                  
         #7                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLo
         cator.php(26):                                                         
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ->locateIdentifier()                                                   
         #8                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLo
         cator.php(33):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->lo 
         cateIdentifier()                                                       
         #9                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLo
         cator.php(26):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->lo 
         cateIdentifier()                                                       
         #10                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLo
         cator.php(33):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->lo 
         cateIdentifier()                                                       
         #11                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/Reflector/DefaultReflector.php(32): 
         PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->lo 
         cateIdentifier()                                                       
         #12                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/Reflector/MemoizingReflector.php(45):         
         PHPStan\BetterReflection\Reflector\DefaultReflector->reflectClass()    
         #13                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/BetterReflectionProvider.php(147):            
         PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector->refl 
         ectClass()                                                             
         #14                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/ReflectionProvider/MemoizingReflectionProvider.php(35):        
         PHPStan\Reflection\BetterReflection\BetterReflectionProvider->hasClass 
         ()                                                                     
         #15                                                                    
         vendor/rector/rector/rules/TypeDeclaration/PHPStan/TypeSpecifier/SameNa
         mespacedTypeSpecifier.php(30):                                         
         PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->has 
         Class()                                                                
         #16                                                                    
         vendor/rector/rector/rules/TypeDeclaration/PHPStan/ObjectTypeSpecifier.
         php(57):                                                               
         Rector\TypeDeclaration\PHPStan\TypeSpecifier\SameNamespacedTypeSpecifie
         r->match()                                                             
         #17                                                                    
         vendor/rector/rector/packages/NodeTypeResolver/NodeTypeResolver.php(168
         ):                                                                     
         Rector\TypeDeclaration\PHPStan\ObjectTypeSpecifier->narrowToFullyQuali 
         fiedOrAliasedObjectType()                                              
         #18 vendor/rector/rector/src/Reflection/ReflectionResolver.php(158):   
         Rector\NodeTypeResolver\NodeTypeResolver->getType()                    
         #19 vendor/rector/rector/src/Reflection/ReflectionResolver.php(176):   
         Rector\Core\Reflection\ReflectionResolver->resolveMethodReflectionFrom 
         MethodCall()                                                           
         #20                                                                    
         vendor/rector/rector/rules/CodeQuality/Rector/ClassMethod/OptionalParam
         etersAfterRequiredRector.php(148):                                     
         Rector\Core\Reflection\ReflectionResolver->resolveFunctionLikeReflecti 
         onFromCall()                                                           
         #21                                                                    
         vendor/rector/rector/rules/CodeQuality/Rector/ClassMethod/OptionalParam
         etersAfterRequiredRector.php(98):                                      
         Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRe
         ctor->refactorMethodCall()                                             
         #22 vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php(43):  
         Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRe
         ctor->refactorWithScope()                                              
         #23 vendor/rector/rector/src/Rector/AbstractRector.php(190):           
         Rector\Core\Rector\AbstractScopeAwareRector->refactor()                
         #24                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(113): Rector\Core\Rector\AbstractRector->enterNode()             
         #25                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(133): PhpParser\NodeTraverser->traverseNode()                    
         #26                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #27                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #28                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #29                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #30                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #31                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #32                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #33                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(85): PhpParser\NodeTraverser->traverseArray()                    
         #34                                                                    
         vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.ph
         p(43): PhpParser\NodeTraverser->traverse()                             
         #35 vendor/rector/rector/src/Application/FileProcessor.php(44):        
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()    
         #36                                                                    
         vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php
         (101): Rector\Core\Application\FileProcessor->refactor()               
         #37                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(176):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()      
         #38                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(149):
         Rector\Core\Application\ApplicationFileProcessor->processFile()        
         #39                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(126):
         Rector\Core\Application\ApplicationFileProcessor->processFiles()       
         #40 vendor/rector/rector/src/Console/Command/ProcessCommand.php(124):  
         Rector\Core\Application\ApplicationFileProcessor->run()                
         #41                                                                    
         vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):  
         Rector\Core\Console\Command\ProcessCommand->execute()                  
         #42 vendor/rector/rector/vendor/symfony/console/Application.php(944):  
         RectorPrefix202308\Symfony\Component\Console\Command\Command->run()    
         #43 vendor/rector/rector/vendor/symfony/console/Application.php(326):  
         RectorPrefix202308\Symfony\Component\Console\Application->doRunCommand 
         ()                                                                     
         #44 vendor/rector/rector/src/Console/ConsoleApplication.php(65):       
         RectorPrefix202308\Symfony\Component\Console\Application->doRun()      
         #45 vendor/rector/rector/vendor/symfony/console/Application.php(212):  
         Rector\Core\Console\ConsoleApplication->doRun()                        
         #46 vendor/rector/rector/bin/rector.php(132):                          
         RectorPrefix202308\Symfony\Component\Console\Application->run()        
         #47 vendor/rector/rector/bin/rector(5): require_once('...')            
         #48 {main}". On line: 107                                              

 [ERROR] Could not process                                                      
         "/***/composer/magento/swissbilling-payme
         nt/Controller/Adminhtml/Logs/View.php" file, due to:                   
         "System error: "Failed to create directory "/tmp/cache/PHPStan"        
         (unknown cause)."                                                      
                                                                                
         Stack trace:                                                           
         #0                                                                     
         vendor/bitexpert/phpstan-magento/src/bitExpert/PHPStan/Magento/Autoload
         /Cache/FileCacheStorage.php(61):                                       
         bitExpert\PHPStan\Magento\Autoload\Cache\FileCacheStorage->makeDir()   
         #1                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Cac
         he/Cache.php(28):                                                      
         bitExpert\PHPStan\Magento\Autoload\Cache\FileCacheStorage->save()      
         #2                                                                     
         vendor/bitexpert/phpstan-magento/src/bitExpert/PHPStan/Magento/Autoload
         /FactoryAutoloader.php(53): PHPStan\Cache\Cache->save()                
         #3                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(272): 
         bitExpert\PHPStan\Magento\Autoload\FactoryAutoloader->autoload()       
         #4                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/FileReadTrapStreamWrapper.php(62
         ):                                                                     
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ::PHPStan\Reflection\BetterReflection\SourceLocator\{closure}()        
         #5                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(284): 
         PHPStan\Reflection\BetterReflection\SourceLocator\FileReadTrapStreamWra
         pper::withStreamWrapperOverride()                                      
         #6                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(119): 
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ->locateClassByName()                                                  
         #7                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLo
         cator.php(26):                                                         
         PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator
         ->locateIdentifier()                                                   
         #8                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLo
         cator.php(33):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->lo 
         cateIdentifier()                                                       
         #9                                                                     
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLo
         cator.php(26):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->lo 
         cateIdentifier()                                                       
         #10                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLo
         cator.php(33):                                                         
         PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->lo 
         cateIdentifier()                                                       
         #11                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/
         ondrejmirtes/better-reflection/src/Reflector/DefaultReflector.php(32): 
         PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->lo 
         cateIdentifier()                                                       
         #12                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/Reflector/MemoizingReflector.php(45):         
         PHPStan\BetterReflection\Reflector\DefaultReflector->reflectClass()    
         #13                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/BetterReflection/BetterReflectionProvider.php(147):            
         PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector->refl 
         ectClass()                                                             
         #14                                                                    
         phar://vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Ref
         lection/ReflectionProvider/MemoizingReflectionProvider.php(35):        
         PHPStan\Reflection\BetterReflection\BetterReflectionProvider->hasClass 
         ()                                                                     
         #15                                                                    
         vendor/rector/rector/rules/TypeDeclaration/PHPStan/TypeSpecifier/SameNa
         mespacedTypeSpecifier.php(30):                                         
         PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->has 
         Class()                                                                
         #16                                                                    
         vendor/rector/rector/rules/TypeDeclaration/PHPStan/ObjectTypeSpecifier.
         php(57):                                                               
         Rector\TypeDeclaration\PHPStan\TypeSpecifier\SameNamespacedTypeSpecifie
         r->match()                                                             
         #17                                                                    
         vendor/rector/rector/packages/NodeTypeResolver/NodeTypeResolver.php(168
         ):                                                                     
         Rector\TypeDeclaration\PHPStan\ObjectTypeSpecifier->narrowToFullyQuali 
         fiedOrAliasedObjectType()                                              
         #18 vendor/rector/rector/src/Reflection/ReflectionResolver.php(158):   
         Rector\NodeTypeResolver\NodeTypeResolver->getType()                    
         #19 vendor/rector/rector/src/Reflection/ReflectionResolver.php(176):   
         Rector\Core\Reflection\ReflectionResolver->resolveMethodReflectionFrom 
         MethodCall()                                                           
         #20 vendor/rector/rector/src/NodeAnalyzer/VariadicAnalyzer.php(51):    
         Rector\Core\Reflection\ReflectionResolver->resolveFunctionLikeReflecti 
         onFromCall()                                                           
         #21                                                                    
         vendor/rector/rector/rules/Php71/Rector/FuncCall/RemoveExtraParametersR
         ector.php(135):                                                        
         Rector\Core\NodeAnalyzer\VariadicAnalyzer->hasVariadicParameters()     
         #22                                                                    
         vendor/rector/rector/rules/Php71/Rector/FuncCall/RemoveExtraParametersR
         ector.php(66):                                                         
         Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector->shouldSkip() 
         #23 vendor/rector/rector/src/Rector/AbstractRector.php(190):           
         Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector->refactor()   
         #24                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(113): Rector\Core\Rector\AbstractRector->enterNode()             
         #25                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(133): PhpParser\NodeTraverser->traverseNode()                    
         #26                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #27                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #28                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #29                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #30                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #31                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #32                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #33                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(105): PhpParser\NodeTraverser->traverseArray()                   
         #34                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(196): PhpParser\NodeTraverser->traverseNode()                    
         #35                                                                    
         vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverse
         r.php(85): PhpParser\NodeTraverser->traverseArray()                    
         #36                                                                    
         vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.ph
         p(43): PhpParser\NodeTraverser->traverse()                             
         #37 vendor/rector/rector/src/Application/FileProcessor.php(44):        
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()    
         #38                                                                    
         vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php
         (101): Rector\Core\Application\FileProcessor->refactor()               
         #39                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(176):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()      
         #40                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(149):
         Rector\Core\Application\ApplicationFileProcessor->processFile()        
         #41                                                                    
         vendor/rector/rector/src/Application/ApplicationFileProcessor.php(126):
         Rector\Core\Application\ApplicationFileProcessor->processFiles()       
         #42 vendor/rector/rector/src/Console/Command/ProcessCommand.php(124):  
         Rector\Core\Application\ApplicationFileProcessor->run()                
         #43                                                                    
         vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):  
         Rector\Core\Console\Command\ProcessCommand->execute()                  
         #44 vendor/rector/rector/vendor/symfony/console/Application.php(944):  
         RectorPrefix202308\Symfony\Component\Console\Command\Command->run()    
         #45 vendor/rector/rector/vendor/symfony/console/Application.php(326):  
         RectorPrefix202308\Symfony\Component\Console\Application->doRunCommand 
         ()                                                                     
         #46 vendor/rector/rector/src/Console/ConsoleApplication.php(65):       
         RectorPrefix202308\Symfony\Component\Console\Application->doRun()      
         #47 vendor/rector/rector/vendor/symfony/console/Application.php(212):  
         Rector\Core\Console\ConsoleApplication->doRun()                        
         #48 vendor/rector/rector/bin/rector.php(132):                          
         RectorPrefix202308\Symfony\Component\Console\Application->run()        
         #49 vendor/rector/rector/bin/rector(5): require_once('...')            
         #50 {main}". On line: 107                                                                                                
```
</summary>

**Comment by samsonasik** [comment]
You can configure your own writable cache dir and container dir, see example:

https://github.com/rectorphp/rector/blob/4930b08d4488a80e78796882f53de24651d03422/config/config.php#L22-L23

**Comment by dimitriBouteille** [comment]
@samsonasik 

I couldn’t find the information, but do you know why phpstan is running when I do `php vendor/bin/rector process` ?

**Comment by samsonasik** [comment]
That's probably due to `bitexpert/phpstan-magento` autoload, in most cases, can't write to cache is due to not writable dir, if you need specific user per run, you may need to configure:

```php
return static function (RectorConfig $rectorConfig): void {
// ...
    $user = getenv('USERNAME') ?: getenv('USER');

    $rectorConfig->cacheDirectory(sys_get_temp_dir() . '/' . $user .  '/rector_cached_files');
    $rectorConfig->containerCacheDirectory(sys_get_temp_dir() . '/' . $user);
// ...
};
```

see https://github.com/rectorphp/rector/issues/8112#issuecomment-1664110914
