### ISSUE TITLE
System error: assert

### ISSUE THREAD

**Issue by Knallcharge** [rectorphp/rector#8188]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.2                  |

After updating to v0.18.2 I get this strange error:

```

 [ERROR] Could not process "(...)\tests\DatatableTest.php" file, due
         to: 
                                                                                                          
         "System error: "assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos)"
                      
         
                                                                                                              
         Stack trace:
                                                                                                  
         #0                                                                                                             
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(693): assert(false, 'assert($itemSta...')                                                        
         #1                                                                                                             
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(20
         2): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 306, 0, 'Expr_New', 'args', NULL)                    
         #2                                                                                                             
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(542): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 306, 0,          
         'Expr_New', 'args', NULL)                                                                                      
         #3                                                                                                             
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\New_), true)                                 
         #4                                                                                                             
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(620): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Expr\New_),   
         true)                                                                                                          
         #5                                                                                                             
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\Assign), true)                               
         #6                                                                                                             
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(620): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Expr\Assign), 
         true)                                                                                                          
         #7                                                                                                             
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)                           
         #8                                                                                                             
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(805):                                                                                            
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Stmt\Expression), true)           
         #9                                                                                                             
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(20
         2): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 252, 0, 'Stmt_ClassMetho...', 'stmts', NULL)         
         #10                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(542): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 252, 0,          
         'Stmt_ClassMetho...', 'stmts', NULL)                                                                           
         #11                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\ClassMethod), true)                          
         #12                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(805):                                                                                            
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Stmt\ClassMethod), true)          
         #13                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(20
         2): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 171, 0, 'Stmt_Class', 'stmts', NULL)                 
         #14                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(542): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 171, 0,          
         'Stmt_Class', 'stmts', NULL)                                                                                   
         #15                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Class_), true)                               
         #16                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(805): Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Stmt\Class_), 
         true)                                                                                                          
         #17                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(20
         2): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 98, 0, 'Stmt_Namespace', 'stmts', NULL)              
         #18                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(542): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 98, 0,           
         'Stmt_Namespace', 'stmts', NULL)                                                                               
         #19                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(13
         5): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Namespace_), true)                           
         #20                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(805):                                                                                            
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p(Object(PhpParser\Node\Stmt\Namespace_), true)           
         #21                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(20
         2): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 8, 0, 'File', 'stmts', NULL)                         
         #22                                                                                                            
         (...)\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinte
         rAbstract.php(475): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 8, 0, 'File',    
         'stmts', NULL)                                                                                                 
         #23                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php(93
         ): PhpParser\PrettyPrinterAbstract->printFormatPreserving(Array, Array, Array)                                 
         #24                                                                                                            
         (...)\vendor\rector\rector\src\PhpParser\Printer\FormatPerservingPrinter.php(
         44): Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving(Array, Array, Array)           
         #25                                                                                                            
         (...)\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php
         (160):                                                                                                         
         Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString(Object(Rector\Core\Va 
         lueObject\Application\File))                                                                                   
         #26                                                                                                            
         (...)\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php
         (107):                                                                                                         
         Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile(Object(Rector\Core\ValueObject\Application\F 
         ile), Object(Rector\Core\ValueObject\Configuration))                                                           
         #27                                                                                                            
         (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(154):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #28                                                                                                            
         (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(131):
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Array, Object(Rector\Core\ValueObject\Configuration))                                                        
         #29                                                                                                            
         (...)\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(108):
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,                                          
         Object(Rector\Core\ValueObject\Configuration), false)                                                          
         #30 (...)\vendor\rector\rector\src\Console\Command\ProcessCommand.php(124):  
         Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration),           
         Object(RectorPrefix202309\Symfony\Component\Console\Input\ArgvInput))                                          
         #31                                                                                                            
         (...)\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):  
         Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202309\Symfony\Component\Console\Input\ 
         ArgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                         
         #32 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(944):  
         RectorPrefix202309\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202309\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))           
         #33 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(326):  
         RectorPrefix202309\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Proc 
         essCommand), Object(RectorPrefix202309\Symfony\Component\Console\Input\ArgvInput),                             
         Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #34 (...)\vendor\rector\rector\src\Console\ConsoleApplication.php(61):       
         RectorPrefix202309\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202309\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))             
         #35 (...)\vendor\rector\rector\vendor\symfony\console\Application.php(212):  
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202309\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202309\Symfony\Component\Console\Output\ConsoleOutput))                               
         #36 (...)\vendor\rector\rector\bin\rector.php(132):                          
         RectorPrefix202309\Symfony\Component\Console\Application->run()                                                
         #37 (...)\vendor\rector\rector\bin\rector(5):                                
         require_once('C:\\xampp\\htdocs...')                                                                           
         #38 (...)\vendor\bin\rector(119): include('C:\\xampp\\htdocs...')            
         #39 {main}". On line: 693    

```

**Comment by samsonasik** [comment]
Hi, could you share minimal code and config that reproduce it at https://getrector.com/demo ?

**Comment by Knallcharge** [comment]
Unfortunately not, the debug information doesn't give me any information about which rule causes this and which line of the file (DatatableTest) is affected.

What I can see from the rector-results is that it seems to be connected to a closure that I'm using in a unit-test:

```
-        $fakeDatatable = new class() extends UserDatatable {
-            public function __construct()
-            {
-            }
-        };
-        $lineFormatter = $fakeDatatable->getLineFormatter();
+        $filesystemLoader = new FilesystemLoader;
```

Rector suggests to remove the closure completely (so the test will run into an error because $fakeDatatable is not defined anymore) and instead add "new FilesystemLoader" which is of no use. Also it lists "TwigBundleFilesystemLoaderToTwigRector" under "Applied rules" which makes no sense to me as neither the test nor anything else in that class has anything to do with Twig.

I'll try to ignore that rule via the config and run rector again.

**Comment by samsonasik** [comment]
It seems reproduced by extends PHPUnit Test case with `__construct()` method instead of `setUp(), see

https://getrector.com/demo/693a074f-96b4-45b4-832b-96d6abceb3f4

I will check if fixing that also fixing your issue :)

**Comment by samsonasik** [comment]
Reproduced with single rule: `ConstructClassMethodToSetUpTestCaseRector`, see https://getrector.com/demo/cd043c4f-0be8-439f-b218-24f7efadae94

**Comment by Knallcharge** [comment]
Great, thanks for the quick check!

**Comment by samsonasik** [comment]
The issue seems happen on CodeIgniter 4 project as well:

- https://github.com/codeigniter4/CodeIgniter4/pull/7904#pullrequestreview-1615277671

**Comment by Knallcharge** [comment]
Also the error (as well as the strange suggestion to remove the anonymous class mentioned above) goes away when ignoring TwigBundleFilesystemLoaderToTwigRector for the effected files.

**Comment by samsonasik** [comment]
@Knallcharge that's probably need new issue, let's focus on per rule basis for now :), the error:

```
assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos
```

is usually happen on usage of BetterReflection 6.x which require startLine and endLine attribute when create new Node..

**Comment by samsonasik** [comment]
The issue seems on SetupMethodDecorator:

https://github.com/rectorphp/rector-phpunit/blob/d163fa907e8f2c48656565bcb1647403a3368141/src/NodeAnalyzer/SetUpMethodDecorator.php#L29-L34

which return type bring from `AstResolver`, which make `Identifier` void not get correct startLine and endLine attribute.
