### ISSUE TITLE
Error unexpected T_CONSTANT_ENCAPSED_STRING when using UP_TO_PHP_55 and code contains preg_replace with /e

### ISSUE THREAD

**Issue by barzog** [rectorphp/rector#8231]
Using Rector 0.18.3.
With simple config like:
```
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/usr',
    ]);

    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_55
    ]);
};
```
When code contains following string
``$string .= preg_replace("/\<\{(.*?)\}\>/e", "$$1", $inner_match);``
rector fails with error:
```
 [ERROR] Could not process "/mnt/helpdesk/print_ticket.php" file, due to:
         "System error: "Syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting T_VARIABLE or '{' or '$'1"

         Stack trace:
         #0 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(146):
         PhpParser\ParserAbstract->doParse()
         #1 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(48):
         PhpParser\ParserAbstract->parse()
         #2 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31):
         PhpParser\Parser\Multiple->tryParse()
         #3 /vendor/rector/rector/src/PhpParser/Parser/SimplePhpParser.php(45): PhpParser\Parser\Multiple->parse()
         #4 /vendor/rector/rector/rules/Php72/NodeFactory/AnonymousFunctionFactory.php(160):
         Rector\Core\PhpParser\Parser\SimplePhpParser->parseString()
         #5 /vendor/rector/rector/rules/Php55/Rector/FuncCall/PregReplaceEModifierRector.php(98):
         Rector\Php72\NodeFactory\AnonymousFunctionFactory->createAnonymousFunctionFromExpr()
         #6 /vendor/rector/rector/src/Rector/AbstractRector.php(156):
         Rector\Php55\Rector\FuncCall\PregReplaceEModifierRector->refactor()
         #7 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode()
         #8 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode()
         #9 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #10 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #11 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #12 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #13 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #14 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #15 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #16 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #17 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #18 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #19 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #20 /vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #21 /vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):
         PhpParser\NodeTraverser->traverse()
         #22 /vendor/rector/rector/src/Application/FileProcessor.php(110):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #23 /vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):
         Rector\Core\Application\FileProcessor->processFile()
         #24 /vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):
         Rector\Core\Application\ApplicationFileProcessor->processFile()
         #25 /vendor/rector/rector/src/Console/Command/WorkerCommand.php(116):
         Rector\Core\Application\ApplicationFileProcessor->processFiles()
         #26 /vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()
         #27 /vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202309\Evenement\EventEmitter->emit()
         #28 /vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202309\Clue\React\NDJson\Decoder->handleData()
         #29 /vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202309\Evenement\EventEmitter->emit()
         #30 /vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202309\React\Stream\Util::RectorPrefix202309\React\Stream\{closure}()
         #31 /vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202309\Evenement\EventEmitter->emit()
         #32 /vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202309\React\Stream\DuplexResourceStream->handleData()
         #33 /vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #34 /vendor/rector/rector/src/Console/Command/WorkerCommand.php(88):
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->run()
         #35 /vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #36 /vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202309\Symfony\Component\Console\Command\Command->run()
         #37 /vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202309\Symfony\Component\Console\Application->doRunCommand()
         #38 /vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202309\Symfony\Component\Console\Application->doRun()
         #39 /vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun()
         #40 /vendor/rector/rector/bin/rector.php(132): RectorPrefix202309\Symfony\Component\Console\Application->run()
         #41 /vendor/rector/rector/bin/rector(5): require_once('/vendor/rector/...')
         #42 {main}". On line: 272
```
When I modify string to 
``$string .= preg_replace("/\<\{(.*?)\}\>/", "$$1", $inner_match); ``
So - drop unsupported e in regexp - all is working as intended.

**Comment by samsonasik** [comment]
Reproduced by single rule: `PregReplaceEModifierRector` ref https://getrector.com/demo/72577043-cf25-4288-bc91-62421e9165a6

**Comment by samsonasik** [comment]
It seems changing content require global access as it access new variable, I suggest to change the code manually to something like this for now:

```diff
-        echo preg_replace("/\<\{(.*?)\}\>/e", "$$1", $text);
+        echo preg_replace_callback('/<\{(.*?)\}\>/', function ($matches) {
+            global $$matches[1];
+            return $$matches[1];
+        }, $text);
```

see https://3v4l.org/i4N2G#v5.4.45

**Comment by samsonasik** [comment]
I am closing it as the manual solution provided above, it is too cryptic to make it automatically solved. 

Rule of thumb: don't use global variable when possible.
