### ISSUE TITLE
v1.80.4 broke "git clone" installs

### ISSUE THREAD

**Issue by baconsalad** [rectorphp/rector#8241]
I'm too lazy to do a proper bug report right now. Here is how the issue can be recreated on a linux host.

```

$ git clone https://github.com/rectorphp/rector.git
$ cd rector/
$ bin/rector --version

PHP Fatal error:  Uncaught Error: Class "PHPStan\DependencyInjection\ContainerFactory" not found in /rec/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php:33
Stack trace:
#0 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#1 /rec/rector/vendor/illuminate/container/Container.php(818): ReflectionClass->newInstanceArgs()
#2 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#3 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#4 /rec/rector/src/DependencyInjection/LazyContainerFactory.php(289): RectorPrefix202309\Illuminate\Container\Container->make()
#5 /rec/rector/vendor/illuminate/container/Container.php(785): Rector\Core\DependencyInjection\LazyContainerFactory::Rector\Core\DependencyInjection\{closure}()
#6 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#7 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#8 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#9 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#10 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#11 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#12 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#13 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#14 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#15 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#16 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#17 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#18 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#19 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#20 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#21 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#22 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#23 /rec/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202309\Illuminate\Container\Container->make()
#24 [internal function]: RectorPrefix202309\Illuminate\Container\Container->RectorPrefix202309\Illuminate\Container\{closure}()
#25 /rec/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array()
#26 /rec/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202309\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202309\Illuminate\Container\{closure}()
#27 /rec/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202309\Illuminate\Container\Util::unwrapIfClosure()
#28 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolvePrimitive()
#29 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#30 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#31 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#32 /rec/rector/src/DependencyInjection/LazyContainerFactory.php(254): RectorPrefix202309\Illuminate\Container\Container->make()
#33 /rec/rector/vendor/illuminate/container/Container.php(785): Rector\Core\DependencyInjection\LazyContainerFactory::Rector\Core\DependencyInjection\{closure}()
#34 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#35 /rec/rector/vendor/illuminate/container/Container.php(644): RectorPrefix202309\Illuminate\Container\Container->resolve()
#36 /rec/rector/bin/rector.php(129): RectorPrefix202309\Illuminate\Container\Container->get()
#37 /rec/rector/bin/rector(5): require_once('...')
#38 {main}
  thrown in /rec/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php on line 33
Fatal error: Uncaught Error: Class "PHPStan\DependencyInjection\ContainerFactory" not found in /rec/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php:33
Stack trace:
#0 [internal function]: Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory->__construct()
#1 /rec/rector/vendor/illuminate/container/Container.php(818): ReflectionClass->newInstanceArgs()
#2 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#3 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#4 /rec/rector/src/DependencyInjection/LazyContainerFactory.php(289): RectorPrefix202309\Illuminate\Container\Container->make()
#5 /rec/rector/vendor/illuminate/container/Container.php(785): Rector\Core\DependencyInjection\LazyContainerFactory::Rector\Core\DependencyInjection\{closure}()
#6 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#7 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#8 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#9 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#10 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#11 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#12 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#13 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#14 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#15 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#16 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#17 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#18 /rec/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202309\Illuminate\Container\Container->make()
#19 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolveClass()
#20 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#21 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#22 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#23 /rec/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202309\Illuminate\Container\Container->make()
#24 [internal function]: RectorPrefix202309\Illuminate\Container\Container->RectorPrefix202309\Illuminate\Container\{closure}()
#25 /rec/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array()
#26 /rec/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202309\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202309\Illuminate\Container\{closure}()
#27 /rec/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202309\Illuminate\Container\Util::unwrapIfClosure()
#28 /rec/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202309\Illuminate\Container\Container->resolvePrimitive()
#29 /rec/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202309\Illuminate\Container\Container->resolveDependencies()
#30 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#31 /rec/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202309\Illuminate\Container\Container->resolve()
#32 /rec/rector/src/DependencyInjection/LazyContainerFactory.php(254): RectorPrefix202309\Illuminate\Container\Container->make()
#33 /rec/rector/vendor/illuminate/container/Container.php(785): Rector\Core\DependencyInjection\LazyContainerFactory::Rector\Core\DependencyInjection\{closure}()
#34 /rec/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202309\Illuminate\Container\Container->build()
#35 /rec/rector/vendor/illuminate/container/Container.php(644): RectorPrefix202309\Illuminate\Container\Container->resolve()
#36 /rec/rector/bin/rector.php(129): RectorPrefix202309\Illuminate\Container\Container->get()
#37 /rec/rector/bin/rector(5): require_once('...')
#38 {main}
  thrown in /rec/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php on line 33

$ git checkout tags/0.18.3
$ bin/rector --version

Rector 0.18.3
```

**Comment by samsonasik** [comment]
You don't. Use composer require --dev instead. 

For source, there is rector-src for that 

https://github.com/rectorphp/rector-src

That you can add test case for your issue.
