### ISSUE TITLE
System error: "enterNode() returned invalid value of type array

### ISSUE THREAD

**Issue by dejagersh** [rectorphp/rector#8271]
Hi!

I am running into this error:

```
 [ERROR] Could not process "/Users/johandejager/Projects/foo/bar/src/Services/Vat/Result.php" file, due to:   
         "System error: "enterNode() returned invalid value of type array"                                              
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                           
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #3 vendor/rector/rector/packages/PhpDocParser/NodeTraverser/SimpleCallableNodeTraverser.php(27):               
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #4 vendor/rector/rector/src/Rector/AbstractRector.php(249):                                                    
         Rector\PhpDocParser\NodeTraverser\SimpleCallableNodeTraverser->traverseNodesWithCallable(Array,                
         Object(Closure))                                                                                               
         #5 vendor/rector/rector/rules/DeadCode/Rector/If_/RemoveTypedPropertyDeadInstanceOfRector.php(107):            
         Rector\Core\Rector\AbstractRector->traverseNodesWithCallable(Array, Object(Closure))                           
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(170):                                                    
         Rector\DeadCode\Rector\If_\RemoveTypedPropertyDeadInstanceOfRector->refactor(Object(PhpParser\Node\Stmt\Class_ 
         ))                                                                                                             
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))                               
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #11 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #12 vendor/rector/rector/src/Application/FileProcessor.php(116):                                               
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #13 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                    
         Rector\Core\Application\FileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File),           
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #14 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                    
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Object(Rector\Core\ValueObject\Configuration))                                                               
         #15 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):                                           
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,                                          
         Object(Rector\Core\ValueObject\Configuration), Object(Closure))                                                
         #16 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}(Array)                        
         #17 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)                                                 
         #18 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202310\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #19 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)                                                 
         #20 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202310\React\Stream\Util::RectorPrefix202310\React\Stream\{closure}('{"action":"main...')          
         #21 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)                                                 
         #22 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202310\React\Stream\DuplexResourceStream->handleData(Resource id #2042)                            
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #24 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):                                            
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->run()                                                     
         #25 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202310\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))                          
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202310\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202310\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))           
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202310\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202310\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #28 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202310\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202310\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))             
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202310\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))                               
         #30 vendor/rector/rector/bin/rector.php(130): RectorPrefix202310\Symfony\Component\Console\Application->run()  
         #31 vendor/rector/rector/bin/rector(5): require_once('/Users/johandej...')                                     
         #32 vendor/bin/rector(119): include('/Users/johandej...')                                                      
         #33 {main}". On line: 191                                                                                      

```

This is the file it's breaking on, after I removed a bunch of stuff that wasn't necessary to trigger the error:

```php
<?php

declare(strict_types=1);

namespace App\Services\Vat;

use LogicException;
use App\Models\Country\Country;

class Result
{
    private Country $country;

    /** @var string[] */
    private array $debugLines = [];

    public function finalize(Country $country): void
    {
        $this->country = $country;
    }

    public function addDebugLine(string $line): void
    {
        if ($this->country instanceof Country) {
            throw new LogicException(
                'Woop',
            );
        }

        $this->debugLines[] = $line;
    }
}
```

**Comment by samsonasik** [comment]
Could you create reproducible on https://getrector.com/demo ? Thank you.

**Comment by samsonasik** [comment]
please try latest dev-main: 

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

Please provide reproducible code and config if the issue persist, otherwise, nothing we can do :)

**Comment by samsonasik** [comment]
I am closing it as it possibly already solved on latest version.

Feel free to provide reproducible test / repo if the issue persist. Thank you.
