### ISSUE TITLE
Matching of regular expressions is no longer supported when parsing seemingly irrelevant line

### ISSUE THREAD

**Issue by danielr0y** [rectorphp/rector#8282]
I received the following error running rector process src --debug --dry-run

```
 [ERROR] Could not process "/src/class-excel-file-builder.php" file, due to:
         "System error: "Matching of regular expressions is no longer supported. Use $this->getName() and compare with  
         e.g. str_ends_with() or str_starts_with() instead."

         Stack trace:
         #0 vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php(215):
         Rector\NodeNameResolver\NodeNameResolver->isStringName('getRowIterator', '*ByColumnAndRow')
         #1 vendor/rector/rector/packages/NodeNameResolver/NodeNameResolver.php(82):
         Rector\NodeNameResolver\NodeNameResolver->isSingleName(Object(PhpParser\Node\Identifier), '*ByColumnAndRow')   
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(219):
         Rector\NodeNameResolver\NodeNameResolver->isName(Object(PhpParser\Node\Identifier), '*ByColumnAndRow')
         #3 vendor/rector/rector-phpoffice/src/Rector/MethodCall/IncreaseColumnIndexRector.php(92):
         Rector\Core\Rector\AbstractRector->isName(Object(PhpParser\Node\Identifier), '*ByColumnAndRow')
         #4 vendor/rector/rector/src/Rector/AbstractRector.php(170):
         Rector\PHPOffice\Rector\MethodCall\IncreaseColumnIndexRector->refactor(Object(PhpParser\Node\Expr\MethodCall)) 
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\TryCatch))
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))      
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #16 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):
         PhpParser\NodeTraverser->traverse(Array)
         #17 vendor/rector/rector/src/Application/FileProcessor.php(116):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #18 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):
         Rector\Core\Application\FileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):
         Rector\Core\Application\ApplicationFileProcessor->processFile(Object(Rector\Core\ValueObject\Application\File) 
         , Object(Rector\Core\ValueObject\Configuration))
         #20 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):
         Rector\Core\Application\ApplicationFileProcessor->processFiles(Array,
         Object(Rector\Core\ValueObject\Configuration), Object(Closure))
         #21 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}(Array)
         #22 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)
         #23 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202310\Clue\React\NDJson\Decoder->handleData(Array)
         #24 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)
         #25 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202310\React\Stream\Util::RectorPrefix202310\React\Stream\{closure}('{"action":"main...')
         #26 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202310\Evenement\EventEmitter->emit('data', Array)
         #27 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202310\React\Stream\DuplexResourceStream->handleData(Resource id #1584)
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #29 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->run()
         #30 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202310\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))
         #31 vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202310\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202310\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202310\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202310\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))
         #33 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202310\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202310\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))
         #34 vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202310\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202310\Symfony\Component\Console\Output\ConsoleOutput))
         #35 vendor/rector/rector/bin/rector.php(129): RectorPrefix202310\Symfony\Component\Console\Application->run()  
         #36 vendor/rector/rector/bin/rector(5): require_once('/var/www/script...')
         #37 vendor/bin/rector(119): include('/var/www/script...')
         #38 {main}". On line: 190
```

And was able to track the offending line down to the following...

```
/src/class-excel-file-builder.php

foreach ( $in_sheet->getRowIterator() as $row ) {
    [...omitted]
}
```

I simply commented it out (leaving the code in block uncommented) and was able to run the migration successfully.

```
// foreach ( $in_sheet->getRowIterator() as $row ) {
    [...not commented]
// }
```

```
composer.json

{
    "require": {
        "phpoffice/phpspreadsheet": "^1.29"
    },
    "require-dev": {
        "rector/rector": "^0.18.6",
        "rector/rector-phpoffice": "^0.14.0"
    }
}
```

```
PHP 8.1.20 (cli) (built: Jun 13 2023 12:02:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by samsonasik** [comment]
`rector/rector-phpoffice` is abandoned, you can copy the code and modify as custom rule for your use case :)
