### ISSUE TITLE
Scope not available on "PhpParser\Node\Expr\MethodCall" node

### ISSUE THREAD

**Issue by ianef** [rectorphp/rector#8288]
# Bug Report

| Subject            | Details |
| :--------------- | :-------|
| Rector version | 0.18.6  |
| PHP Version    | 8.2       |
| Symfony          | 5.4       |

Running a dry-run against the following Symfony command class fails:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Throwable;

class RectorFailCommand extends Command
{
    protected const COMMAND_NAME = 'app:rector-fail';

    // phpcs:ignore SlevomatCodingStandard.TypeHints.ParameterTypeHint.MissingNativeTypeHint, SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingAnyTypeHint
    protected static $defaultName = self::COMMAND_NAME;

    protected function configure(): void
    {
        $this
            ->setDescription('Test command.')
            ->addOption('command-id', null, InputOption::VALUE_OPTIONAL, 'The ID of the ScheduledCommand entity.');
    }

    /**
     * Execute the command
     */
    // phpcs:ignore SlevomatCodingStandard.Functions.UnusedParameter.UnusedParameter
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        try {
            $output->writeln("<info>Running the rector-fail command.</info>");
            return 0;
        } catch (Throwable $e) {
            throw new \Exception("Failed to run the rector-fail command: {$e->getMessage()}");
        }
    }
}
```

If the throw new \Exception line (37) is commented out, the error does not occur.

rector.php:
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

    $rectorConfig->symfonyContainerXml(__DIR__ . '/var/cache/dev/App_KernelDevDebugContainer.xml');
    // define sets of rules
    $rectorConfig->sets([
        SetList::CODE_QUALITY,
    ]);
};
```

Error log:
```
 [ERROR] Could not process "src/Command/RectorFailCommand.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a
         refactorWithScope() method of "Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector"
         rule. Fix scope refresh on changed nodes first"

         Stack trace:
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(170):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor()
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode()
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode()
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #17 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):
         PhpParser\NodeTraverser->traverse()
         #18 vendor/rector/rector/src/Application/FileProcessor.php(116):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):
         Rector\Core\Application\FileProcessor->processFile()
         #20 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):
         Rector\Core\Application\ApplicationFileProcessor->processFile()
         #21 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):
         Rector\Core\Application\ApplicationFileProcessor->processFiles()
         #22 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()
         #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202310\Evenement\EventEmitter->emit()
         #24 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202310\Clue\React\NDJson\Decoder->handleData()
         #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202310\Evenement\EventEmitter->emit()
         #26 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):
         RectorPrefix202310\React\Stream\Util::RectorPrefix202310\React\Stream\{closure}()
         #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202310\Evenement\EventEmitter->emit()
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202310\React\Stream\DuplexResourceStream->handleData()
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->run()
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202310\Symfony\Component\Console\Command\Command->run()
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202310\Symfony\Component\Console\Application->doRunCommand()
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202310\Symfony\Component\Console\Application->doRun()
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun()
         #36 vendor/rector/rector/bin/rector.php(129): RectorPrefix202310\Symfony\Component\Console\Application->run()
         #37 vendor/rector/rector/bin/rector(5): require_once('...')
         #38 vendor/bin/rector(119): include('...')
         #39 {main}". On line: 25
```

**Comment by samsonasik** [comment]
it should already resolved at https://github.com/rectorphp/rector-src/pull/5207

Please try latest dev-main

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
