### ISSUE TITLE
System error: "enterNode() returned invalid value of type array

### ISSUE THREAD

**Issue by ItsReddi** [rectorphp/rector#8295]
Hi,
the following class is producing an rector error.
The issue seems to be in line `if ($this->request instanceof Request) {`, since request is not optional it wants to remove it and fails.

```php
<?php

namespace App\Auth;

use Illuminate\Http\Request;

class RectorFail
{
    public function __construct(protected Request $request)
    {
    }

    public function handle()
    {
        $this->failing();
    }

    

    protected function failing(): bool
    {
        if ($this->request instanceof Request) {
            return isset(1);
        }
        return false;
    }
}
```

Rector Log:
```
"System error: "enterNode() returned invalid value of type array"                                              
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                           
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #3 vendor/rector/rector/packages/PhpDocParser/NodeTraverser/SimpleCallableNodeTraverser.php(27):               
         PhpParser\NodeTraverser->traverse()                                                                            
         #4 vendor/rector/rector/src/Rector/AbstractRector.php(235):                                                    
         Rector\PhpDocParser\NodeTraverser\SimpleCallableNodeTraverser->traverseNodesWithCallable()                     
         #5 vendor/rector/rector/rules/DeadCode/Rector/If_/RemoveTypedPropertyDeadInstanceOfRector.php(107):            
         Rector\Core\Rector\AbstractRector->traverseNodesWithCallable()                                                 
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(156):                                                    
         Rector\DeadCode\Rector\If_\RemoveTypedPropertyDeadInstanceOfRector->refactor()                                 
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                          
         Rector\Core\Rector\AbstractRector->enterNode()                                                                 
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #12 vendor/rector/rector/src/Application/FileProcessor.php(110):                                               
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                            
         #13 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                    
         Rector\Core\Application\FileProcessor->processFile()                                                           
         #14 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                    
         Rector\Core\Application\ApplicationFileProcessor->processFile()                                                
         #15 vendor/rector/rector/src/Console/Command/WorkerCommand.php(116):                                           
         Rector\Core\Application\ApplicationFileProcessor->processFiles()                                               
         #16 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()                             
         #17 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202309\Evenement\EventEmitter->emit()                                                              
         #18 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202309\Clue\React\NDJson\Decoder->handleData()                                                     
         #19 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202309\Evenement\EventEmitter->emit()                                                              
         #20 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202309\React\Stream\Util::RectorPrefix202309\React\Stream\{closure}()                              
         #21 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202309\Evenement\EventEmitter->emit()                                                              
         #22 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202309\React\Stream\DuplexResourceStream->handleData()                                             
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #24 vendor/rector/rector/src/Console/Command/WorkerCommand.php(88):                                            
         RectorPrefix202309\React\EventLoop\StreamSelectLoop->run()                                                     
         #25 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202309\Symfony\Component\Console\Command\Command->run()                                            
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202309\Symfony\Component\Console\Application->doRunCommand()                                       
         #28 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202309\Symfony\Component\Console\Application->doRun()                                              
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #30 vendor/rector/rector/bin/rector.php(132): RectorPrefix202309\Symfony\Component\Console\Application->run()  
         #31 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #32 vendor/bin/rector(119): include('...')                                                                     
         #33 {main}". On line: 191
```

**Comment by samsonasik** [comment]
same with https://github.com/rectorphp/rector/issues/8271, it require reproducible rule that apply it  https://getrector.com/demo

**Comment by ItsReddi** [comment]
Not reproducable there i added my rector config.
https://getrector.com/demo/7d87dd85-2c1a-4918-abc7-6d44d1d29856

Using rector:
```
vendor/bin/rector --version
Rector 0.18.6
```

**Comment by samsonasik** [comment]
Could you try latest dev-main?

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

If the issue persist, a simple repo may probably needed.

**Comment by ItsReddi** [comment]
I can confirm it is fixed in main
