### ISSUE TITLE
System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a                       refactorWithScope()

### ISSUE THREAD

**Issue by adrigar94** [rectorphp/rector#8297]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.18.6             |

I just installed the package. 

With the rules:

```
$rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    $rectorConfig->sets([[
        LevelSetList::UP_TO_PHP_82
    ]);
```

Everything went fine, but when adding the `SetList::CODE_QUALITY` rule in the sets it started to give the following error:

```
[ERROR] Could not process "/home/adrian/projects/ScooterVolt-Catalog/src/Shared/Application/CurrencyConversor.php"     
         file, due to:                                                                                                  
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a             
         refactorWithScope() method of "Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector"    
         rule. Fix scope refresh on changed nodes first"                                                                
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(170):                                                    
         Rector\Core\Rector\AbstractScopeAwareRector->refactor()                                                        
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Core\Rector\AbstractRector->enterNode()                                                                 
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #17 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #18 vendor/rector/rector/src/Application/FileProcessor.php(116):                                               
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                            
         #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                    
         Rector\Core\Application\FileProcessor->processFile()                                                           
         #20 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                    
         Rector\Core\Application\ApplicationFileProcessor->processFile()                                                
         #21 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):                                           
         Rector\Core\Application\ApplicationFileProcessor->processFiles()                                               
         #22 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()                             
         #23 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202310\Evenement\EventEmitter->emit()                                                              
         #24 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202310\Clue\React\NDJson\Decoder->handleData()                                                     
         #25 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202310\Evenement\EventEmitter->emit()                                                              
         #26 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202310\React\Stream\Util::RectorPrefix202310\React\Stream\{closure}()                              
         #27 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202310\Evenement\EventEmitter->emit()                                                              
         #28 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202310\React\Stream\DuplexResourceStream->handleData()                                             
         #29 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #30 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):                                            
         RectorPrefix202310\React\EventLoop\StreamSelectLoop->run()                                                     
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202310\Symfony\Component\Console\Command\Command->run()                                            
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202310\Symfony\Component\Console\Application->doRunCommand()                                       
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202310\Symfony\Component\Console\Application->doRun()                                              
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #36 vendor/rector/rector/bin/rector.php(129): RectorPrefix202310\Symfony\Component\Console\Application->run()  
         #37 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #38 vendor/bin/rector(119): include('...')                                                                     
         #39 {main}". On line: 25 
```

File CurrencyConversor.php:

```
<?php

declare(strict_types=1);

namespace ScooterVolt\CatalogService\Shared\Application;

use Exception;

class CurrencyConversor
{
    private const endpoint = 'https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/';

    private string $fromCurrency;

    private array $rates;

    public function __construct(string $fromCurrency)
    {
        $this->fromCurrency = strtolower($fromCurrency);
        $this->rates = self::getCurrencyRates();
    }

    public function convert(float $value, string $toCurrency): float
    {

        $toCurrency = strtolower($toCurrency);

        if (!isset($this->rates[$this->fromCurrency][$toCurrency])) {
            throw new \RuntimeException('Invalid currency');
        }

        $rate = $this->rates[$this->fromCurrency][$toCurrency];

        return $value * $rate;
    }


    private function getCurrencyRates(): array
    {
        $url = self::endpoint . $this->fromCurrency . '.json';
        try {
            $jsonData = file_get_contents($url);
            $rates = json_decode($jsonData ?: "", true);

            if (is_null($rates)) {
                throw new Exception('"' . print_r($jsonData, true) . '" can\'t be decoded');
            }
        } catch (Exception $e) {
            throw new Exception("Can't get currency rates\n" . $e->getMessage());
        }
        return $rates;
    }
}
```

**Comment by samsonasik** [comment]
it should already resolved at https://github.com/rectorphp/rector-src/pull/5207

Please try latest dev-main

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main

**Comment by adrigar94** [comment]
works fine
