### ISSUE TITLE
System error: "Call to a member function getAttribute() on null                                           

### ISSUE THREAD

**Issue by gkalligeros** [rectorphp/rector#8320]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.18.8             |

Hello i  got this while i was running ` ./vendor/bin/rector process`

```
 [ERROR] Could not process "*****" file, due to:                                                          
         "System error: "Call to a member function getAttribute() on null"                                              
                                                                                                                        
         Stack trace:                                                                                                   
         #0 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3479):                            
         PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs()                                                
         #1 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1379):                            
         PHPStan\Analyser\MutatingScope->methodCallReturnType()                                                         
         #2 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1385):                            
         PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                   
         #3 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(567):                             
         PHPStan\Analyser\MutatingScope->resolveType()                                                                  
         #4 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1560):                        
         PHPStan\Analyser\MutatingScope->getType()                                                                      
         #5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(613):                         
         PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr()                                                 
         #6 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357):                         
         PHPStan\Analyser\NodeScopeResolver->processStmtNode()                                                          
         #7 vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(211):             
         PHPStan\Analyser\NodeScopeResolver->processNodes()                                                             
         #8 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(58):                                     
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()                                 
         #9 vendor/rector/rector/src/Rector/AbstractRector.php(276):                                                    
         Rector\Core\Application\ChangedNodeScopeRefresher->refresh()                                                   
         #10 vendor/rector/rector/src/Rector/AbstractRector.php(266):                                                   
         Rector\Core\Rector\AbstractRector->refreshScopeNodes()                                                         
         #11 vendor/rector/rector/src/Rector/AbstractRector.php(160):                                                   
         Rector\Core\Rector\AbstractRector->postRefactorProcess()                                                       
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                         
         Rector\Core\Rector\AbstractRector->enterNode()                                                                 
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #21 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(50):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #22 vendor/rector/rector/src/Application/FileProcessor.php(116):                                               
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                            
         #23 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(177):                                    
         Rector\Core\Application\FileProcessor->processFile()                                                           
         #24 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(153):                                    
         Rector\Core\Application\ApplicationFileProcessor->processFile()                                                
         #25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(132):                                           
         Rector\Core\Application\ApplicationFileProcessor->processFiles()                                               
         #26 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Core\Console\Command\WorkerCommand->Rector\Core\Console\Command\{closure}()                             
         #27 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202311\Evenement\EventEmitter->emit()                                                              
         #28 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202311\Clue\React\NDJson\Decoder->handleData()                                                     
         #29 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202311\Evenement\EventEmitter->emit()                                                              
         #30 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202311\React\Stream\Util::RectorPrefix202311\React\Stream\{closure}()                              
         #31 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202311\Evenement\EventEmitter->emit()                                                              
         #32 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202311\React\Stream\DuplexResourceStream->handleData()                                             
         #33 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202311\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #34 vendor/rector/rector/src/Console/Command/WorkerCommand.php(90):                                            
         RectorPrefix202311\React\EventLoop\StreamSelectLoop->run()                                                     
         #35 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #36 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202311\Symfony\Component\Console\Command\Command->run()                                            
         #37 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202311\Symfony\Component\Console\Application->doRunCommand()                                       
         #38 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202311\Symfony\Component\Console\Application->doRun()                                              
         #39 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #40 vendor/rector/rector/bin/rector.php(129): RectorPrefix202311\Symfony\Component\Console\Application->run()  
         #41 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #42 vendor/bin/rector(119): include('...')                                                                     

```
## Minimal PHP Code Causing Issue
The file that is causing this is huge not sure which part causes the issue 

rules 

```php 
    $rectorConfig->rules([
        InlineConstructorDefaultToPropertyRector::class,
        ReturnTypeFromStrictNativeCallRector::class,
        ReturnTypeFromStrictScalarReturnExprRector::class,
        ReturnTypeFromStrictBoolReturnExprRector::class,
        CompleteDynamicPropertiesRector::class
    ]);
    $rectorConfig->skip([
        FirstClassCallableRector::class,
        LongArrayToShortArrayRector::class,
        JsonThrowOnErrorRector::class,
    ]);
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_82
    ]);
``` 

```php

```

## Expected Behaviour
Rector refactor the code 

Refactor

**Comment by gkalligeros** [comment]
Hello this the part that gets me the error 
https://getrector.com/demo/8c8b80a1-59c7-480d-8782-d76e1092fc9c

**Comment by samsonasik** [comment]
Could you try latest rector/rector:dev-main ? If the issue persist, we need a simple reproducible repo for that, better with github action running

**Comment by samsonasik** [comment]
I am closing it as it can't be reproduced, try latest dev-main, if the issue persist, feel free to provide a simple reproducible repo, better with github action that reproduce the issue.
