### ISSUE TITLE
Rector crashes with PHPStan 1.10.55

### ISSUE THREAD

**Issue by X-Coder264** [rectorphp/rector#8395]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.13             |

Updating from PHPStan 1.10.54 to 1.10.55 causes Rector to crash.

```
Fatal error: Uncaught Error: Call to a member function end() on null in /srv/app/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php:120
Stack trace:
#0 /srv/app/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php(49): RectorPrefix202312\Symplify\EasyParallel\ValueObject\ParallelProcess->quit()
#1 /srv/app/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php(59): RectorPrefix202312\Symplify\EasyParallel\ValueObject\ProcessPool->quitProcess()
#2 /srv/app/vendor/rector/rector/packages/Parallel/Application/ParallelFileProcessor.php(145): RectorPrefix202312\Symplify\EasyParallel\ValueObject\ProcessPool->quitAll()
#3 /srv/app/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php(130): Rector\Parallel\Application\ParallelFileProcessor->Rector\Parallel\Application\{closure}()
#4 /srv/app/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202312\Symplify\EasyParallel\ValueObject\ParallelProcess->RectorPrefix202312\Symplify\EasyParallel\ValueObject\{closure}()
#5 /srv/app/vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117): RectorPrefix202312\Evenement\EventEmitter->emit()
#6 /srv/app/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202312\Clue\React\NDJson\Decoder->handleData()
#7 /srv/app/vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202312\Evenement\EventEmitter->emit()
#8 /srv/app/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202312\React\Stream\Util::RectorPrefix202312\React\Stream\{closure}()
#9 /srv/app/vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154): RectorPrefix202312\Evenement\EventEmitter->emit()
#10 /srv/app/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201): RectorPrefix202312\React\Stream\DuplexResourceStream->handleData()
#11 /srv/app/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173): RectorPrefix202312\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#12 /srv/app/vendor/rector/rector/packages/Parallel/Application/ParallelFileProcessor.php(184): RectorPrefix202312\React\EventLoop\StreamSelectLoop->run()
#13 /srv/app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(230): Rector\Parallel\Application\ParallelFileProcessor->process()
#14 /srv/app/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(126): Rector\Core\Application\ApplicationFileProcessor->runParallel()
#15 /srv/app/vendor/rector/rector/src/Console/Command/ProcessCommand.php(117): Rector\Core\Application\ApplicationFileProcessor->run()
#16 /srv/app/vendor/rector/rector/vendor/symfony/console/Command/Command.php(327): Rector\Core\Console\Command\ProcessCommand->execute()
#17 /srv/app/vendor/rector/rector/vendor/symfony/console/Application.php(960): RectorPrefix202312\Symfony\Component\Console\Command\Command->run()
#18 /srv/app/vendor/rector/rector/vendor/symfony/console/Application.php(333): RectorPrefix202312\Symfony\Component\Console\Application->doRunCommand()
#19 /srv/app/vendor/rector/rector/src/Console/ConsoleApplication.php(53): RectorPrefix202312\Symfony\Component\Console\Application->doRun()
#20 /srv/app/vendor/rector/rector/vendor/symfony/console/Application.php(216): Rector\Core\Console\ConsoleApplication->doRun()
#21 /srv/app/vendor/rector/rector/bin/rector.php(129): RectorPrefix202312\Symfony\Component\Console\Application->run()
#22 /srv/app/vendor/rector/rector/bin/rector(5): require_once('...')
#23 /srv/app/vendor/bin/rector(117): include('...')
#24 {main}
  thrown in /srv/app/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php on line 120
```

If I add the `disableParallel` call in my Rector config and I re-run it then I get a bunch of these errors in the output:

```
 [ERROR] Could not process "src/Foo/Bar.php" file, due
         to:                                                                                                            
         "Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getRequireExtendsTagValues()". On line:  
         330
```

**Comment by X-Coder264** [comment]
I can confirm that there are no crashes with the `dev-main` version. When can we expect a tag for it?

**Comment by TomasVotruba** [comment]
@X-Coder264 I'll look into tagging today to tomorrow, to fix this one. We'll heading towards 0.19 release, as there was change in namespace for Core classes.

**Comment by samsonasik** [comment]
Rector 0.19.0 released https://github.com/rectorphp/rector/releases/tag/0.19.0

**Comment by alexander-schranz** [comment]
Is there any fix for 0.18.x version of rector for this?

**Comment by TomasVotruba** [comment]
@alexander-schranz The BC break came in a time we've also done change in Rector namespace, so no. We could do such release, but it would miss other dozens of fixes we've done in coming up to 0.19. 

Bump to Rector 0.19 and let us know what you need help with :+1:

**Comment by alexander-schranz** [comment]
Thought that. I currently conflict the `1.10.55` version in `sulu/rector` for all which are on rector `0.18`. And then do a seperate release which require atleast rector `0.19`.

**Comment by devin-purple** [comment]
> Rector 0.19.0 released https://github.com/rectorphp/rector/releases/tag/0.19.0

can you bump packagist? still on 0.18.6

**Comment by samsonasik** [comment]
@devin-purple you can bump your composer.json to use `"rector/rector": "^0.19"

**Comment by alexander-schranz** [comment]
@devin-purple Composer follows Semantic Versioning when you use `^0.18` and in semantic versioning 0.x version are not auto updated e.g. 0.x versions `0.18` -> `0.19` are interpreted as major releases as they can contain bc breaks. So to jump to `0.19` you need to use `^0.19`. Only in 1.x semantic versioning contains minor releases without bc breaks.
