### ISSUE TITLE
[ERROR] Could not process 

### ISSUE THREAD

**Issue by gemal** [rectorphp/rector#8399]
```
rector process app\src\TestSuite\ControllerAssertionsTrait.php --debug
app\src\TestSuite\ControllerAssertionsTrait.php


                           "app\src\TestSuite\ControllerAssertionsTrait.php" file, due to:
                                            nction getAttribute() on null"


         #0
         phar://C:/Users/henri/AppData/Roaming/Composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(2186): PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs()
         #1
         phar://C:/Users/henri/AppData/Roaming/Composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(627): PHPStan\Analyser\NodeScopeResolver->processExprNode()
         #2
         phar://C:/Users/henri/AppData/Roaming/Composer/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(370): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
         #3
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(217): PHPStan\Analyser\NodeScopeResolver->processNodes()
         #4
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Application\ChangedNodeScopeRefresher.php(58)
         : Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes()
         #5 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Rector\AbstractRector.php(295):
         Rector\Application\ChangedNodeScopeRefresher->refresh()
         #6 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Rector\AbstractRector.php(285):
         Rector\Rector\AbstractRector->refreshScopeNodes()
         #7 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Rector\AbstractRector.php(164):
         Rector\Rector\AbstractRector->postRefactorProcess()
         #8
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(113): Rector\Rector\AbstractRector->enterNode()
         #9
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(133): PhpParser\NodeTraverser->traverseNode()
         #10
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(196): PhpParser\NodeTraverser->traverseNode()
         #11
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray()
         #12
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(196): PhpParser\NodeTraverser->traverseNode()
         #13
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray()
         #14
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(196): PhpParser\NodeTraverser->traverseNode()
         #15
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray()
         #16
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(196): PhpParser\NodeTraverser->traverseNode()
         #17
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(85): PhpParser\NodeTraverser->traverseArray()
         #18
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.p
         hp(50): PhpParser\NodeTraverser->traverse()
         #19 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Application\FileProcessor.php(116):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #20
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(177)
         : Rector\Application\FileProcessor->processFile()
         #21
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(153)
         : Rector\Application\ApplicationFileProcessor->processFile()
         #22 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Console\Command\WorkerCommand.php(132):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #23
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.
         php(111): Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}()
         #24
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(117):
         RectorPrefix202401\Evenement\EventEmitter->emit()
         #25
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.
         php(111): RectorPrefix202401\Clue\React\NDJson\Decoder->handleData()
         #26 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\react\stream\src\Util.php(62):
         RectorPrefix202401\Evenement\EventEmitter->emit()
         #27
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\evenement\evenement\src\EventEmitterTrait.
         php(111): RectorPrefix202401\React\Stream\Util::RectorPrefix202401\React\Stream\{closure}()
         #28
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(
         154): RectorPrefix202401\Evenement\EventEmitter->emit()
         #29
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(
         201): RectorPrefix202401\React\Stream\DuplexResourceStream->handleData()
         #30
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(
         173): RectorPrefix202401\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #31 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Console\Command\WorkerCommand.php(90):
         RectorPrefix202401\React\EventLoop\StreamSelectLoop->run()
         #32
         C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Console\Command\WorkerCommand->execute()
         #33 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202401\Symfony\Component\Console\Command\Command->run()
         #34 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202401\Symfony\Component\Console\Application->doRunCommand()
         #35 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202401\Symfony\Component\Console\Application->doRun()
         #36 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #37 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\bin\rector.php(131):
         RectorPrefix202401\Symfony\Component\Console\Application->run()
         #38 C:\Users\henri\AppData\Roaming\Composer\vendor\rector\rector\bin\rector(4):
         require_once('C:\\Users\\henri\\...')
         #39 C:\Users\henri\AppData\Roaming\Composer\vendor\bin\rector(115): include('C:\\Users\\henri\\...')
         #40 {main}". On line: 74

```

file in question:
```
<?php

declare(strict_types=1);

namespace App\TestSuite;

use PHPUnit\Framework\Assert;
use finfo;

trait ControllerAssertionsTrait
{
    use CommonAssertionsTrait;

    /**
     * Asserts that the file is really the right file mimetype.
     *
     * @param string $fileContent File content.
     * @param string $mimeType Mimetype.
     * @return void
     */
    protected function assertMimeType(string $fileContent, string $mimeType): void
    {
        $finfo = new finfo(FILEINFO_MIME_TYPE);
        $actualMimeType = $finfo->buffer($fileContent);
        Assert::assertIsString($actualMimeType);
        Assert::assertStringStartsWith($mimeType, $actualMimeType);
    }
}

```

php 7.4

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by Nommyde** [comment]
phpstan 1.10.55 breaks rector. could you please update phpstan on getrector.com/demo?

**Comment by samsonasik** [comment]
getrector.org already use phpstan 1.10.55, see

https://github.com/rectorphp/getrector-com/blob/6f31c2707022eed1b82566cf0bb77eb90c077fe3/composer.lock#L2124

please create simple reproducible repo for it, with step by step to reproduce the error, better with github action running

**Comment by samsonasik** [comment]
@zrajic that should be resolved in Rector 0.19.0, please update your composer.json to `"rector/rector": "^0.19.0"`

**Comment by zrajic** [comment]
@samsonasik thank you, my issue is gone :)

**Comment by TomasVotruba** [comment]
The solution is to upgrade to Rector 0.19, where we fixed the broken dependency version

Closing as resolved, thank you :+1:
