### ISSUE TITLE
`DowngradeLevelSetList` to PHP <8.1 in Rector Versions >0.18.5 Cannot Be Run On PHP Versions <8.1

### ISSUE THREAD

**Issue by Kenneth-Sills** [rectorphp/rector#8471]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.6 -> 1.0.0 |
| `DowngradeLevelSetList values` | `DOWN_TO_PHP_71` -> `DOWN_TO_PHP_80` |
| PHP Versions | 7.3 -> 8.0 |

When running any version of Rector above 0.18.5 in a PHP environment below version 8.1, the use of `DowngradeLevelSetList` rules below the PHP 8.1 target causes Rector to completely crash on startup.

## Minimal PHP Code Causing Issue

Cannot be reproduced in the playground, due to requiring custom execution environment.

You can reproduce this by creating a blank PHP project with a `rector.php` containing:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\DowngradeLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_71,
    ]);
};
```

*You can swap the `DOWN_TO_PHP_` set as needed. I've tested all possible values.* 

Then open the directory in a clean PHP environment with docker and run rector:

```sh
VERSION=8.0
docker run --rm -it -v `pwd`:/app webdevops/php:$VERSION bash
cd app
touch index.php
composer exec rector -- --dry-run index.php
```

*You can swap the `VERSION` as needed, I've tested the range `7.3 -> 8.3` to reflect my available environments.*

You will receive a large dump stemming from the dependency injection layer:

```txt
PHP Fatal error:  Uncaught Error: Undefined constant "MHASH_XXH32" in /app/vendor/rector/rector/vendor/illuminate/container/Container.php:818
Stack trace:
#0 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(818): ReflectionClass->newInstanceArgs(Array)
#1 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Downgrad...')
#2 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#3 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#4 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Downgrad...', Array)
#5 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Downgrad...')
#6 [internal function]: RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}()
#7 /app/vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202402\Illuminate\Container\RewindableGenerator))
#8 /app/vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202402\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#9 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202402\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#10 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#11 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#12 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Configur...')
#13 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Configur...', Array)
#14 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Configur...')
#15 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#16 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#17 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Console\\...')
#18 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#19 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#20 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#21 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Console\\...')
#22 [internal function]: RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}()
#23 /app/vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202402\Illuminate\Container\RewindableGenerator))
#24 /app/vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202402\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#25 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202402\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#26 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#27 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#28 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Console\\...')
#29 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#30 /app/vendor/rector/rector/src/DependencyInjection/LazyContainerFactory.php(244): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Console\\...')
#31 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): Rector\DependencyInjection\LazyContainerFactory::Rector\DependencyInjection\{closure}(Object(Rector\Config\RectorConfig), Array)
#32 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#33 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(644): RectorPrefix202402\Illuminate\Container\Container->resolve('RectorPrefix202...')
#34 /app/vendor/rector/rector/bin/rector.php(129): RectorPrefix202402\Illuminate\Container\Container->get('RectorPrefix202...')
#35 /app/vendor/rector/rector/bin/rector(5): require_once('/app/vendor/rec...')
#36 /app/vendor/bin/rector(119): include('/app/vendor/rec...')
#37 {main}
  thrown in /app/vendor/rector/rector/vendor/illuminate/container/Container.php on line 818
Fatal error: Uncaught Error: Undefined constant "MHASH_XXH32" in /app/vendor/rector/rector/vendor/illuminate/container/Container.php:818
Stack trace:
#0 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(818): ReflectionClass->newInstanceArgs(Array)
#1 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Downgrad...')
#2 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#3 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#4 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Downgrad...', Array)
#5 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Downgrad...')
#6 [internal function]: RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}()
#7 /app/vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202402\Illuminate\Container\RewindableGenerator))
#8 /app/vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202402\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#9 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202402\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#10 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#11 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#12 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Configur...')
#13 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Configur...', Array)
#14 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(912): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Configur...')
#15 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#16 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#17 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Console\\...')
#18 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#19 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#20 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#21 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Console\\...')
#22 [internal function]: RectorPrefix202402\Illuminate\Container\Container->RectorPrefix202402\Illuminate\Container\{closure}()
#23 /app/vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202402\Illuminate\Container\RewindableGenerator))
#24 /app/vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202402\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202402\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#25 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(891): RectorPrefix202402\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#26 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(842): RectorPrefix202402\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#27 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(812): RectorPrefix202402\Illuminate\Container\Container->resolveDependencies(Array)
#28 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build('Rector\\Console\\...')
#29 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(634): RectorPrefix202402\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#30 /app/vendor/rector/rector/src/DependencyInjection/LazyContainerFactory.php(244): RectorPrefix202402\Illuminate\Container\Container->make('Rector\\Console\\...')
#31 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(785): Rector\DependencyInjection\LazyContainerFactory::Rector\DependencyInjection\{closure}(Object(Rector\Config\RectorConfig), Array)
#32 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(687): RectorPrefix202402\Illuminate\Container\Container->build(Object(Closure))
#33 /app/vendor/rector/rector/vendor/illuminate/container/Container.php(644): RectorPrefix202402\Illuminate\Container\Container->resolve('RectorPrefix202...')
#34 /app/vendor/rector/rector/bin/rector.php(129): RectorPrefix202402\Illuminate\Container\Container->get('RectorPrefix202...')
#35 /app/vendor/rector/rector/bin/rector(5): require_once('/app/vendor/rec...')
#36 /app/vendor/bin/rector(119): include('/app/vendor/rec...')
#37 {main}
  thrown in /app/vendor/rector/rector/vendor/illuminate/container/Container.php on line 818
```

I have not attempted to find if this is caused by a specific set list or rule, I've only identified the level set list that causes it.

## Expected Behaviour

Rector should be able to be executed with any of the downgrade rulesets on all platforms marked as compatible in `composer.json` (`^7.2|^8.0` as of time of writing).

**Comment by samsonasik** [comment]
Looking at the error, you don't have `MHASH_XXH32` constant, I guess you have different php version between cli and web, could you create a reproducible repo? Thank you.

**Comment by Kenneth-Sills** [comment]
> Looking at the error, you don't have `MHASH_XXH32` constant,

Not sure what this is, searches don't turn up anything and given it's happening in the [DI layer](https://github.com/rectorphp/rector/blob/main/vendor/illuminate/container/Container.php#L818), I assumed it was a dynamically generated name.

The [WebDevops PHP Image](https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php.html#php-modules) should contain pretty much all PHP modules by default, and I don't see any special requirements listed for Rector so I'm not sure what would cause it. This also happens on production servers (Debian via Sury) and a local machine (Arch via official packages), so seems to reproduce across several real-world cases.

> could you create a reproducible repo?

Of course! [Here you go](https://github.com/Kenneth-Sills/rector-847-reproduction).

The reproductions steps are similar to the above:

```
git clone https://github.com/Kenneth-Sills/rector-847-reproduction
cd rector-847-reproduction
docker run --rm -it -v `pwd`:/app webdevops/php:8.0 bash
cd app
composer exec rector -- --dry-run process index.php
```

Let me know if you need anything else from me. :smile:

**Comment by samsonasik** [comment]
Ok, reproduced in php 8.0:

```
➜  rector-847-reproduction git:(main) php80 vendor/bin/rector process index.php --dry-run
PHP Fatal error:  Uncaught Error: Undefined constant "MHASH_XXH32" in /Users/samsonasik/www/rector-847-reproduction/vendor/rector/rector/vendor/illuminate/container/Container.php:818
Stack trace:
```

**Comment by samsonasik** [comment]
Ok, it seems the following constant need to be added:

```php
if (PHP_VERSION_ID < 80100) {
    if (! defined('MHASH_XXH32')) {
        define('MHASH_XXH32', 38);
    }

    if (! defined('MHASH_XXH64')) {
        define('MHASH_XXH64', 39);
    }

    if (! defined('MHASH_XXH3')) {
        define('MHASH_XXH3', 40);
    }

    if (! defined('MHASH_XXH128')) {
        define('MHASH_XXH128', 41);
    }
}
```

**Comment by samsonasik** [comment]
@Kenneth-Sills could you try latest `rector/rector:dev-main`:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

and verify if it now resolved? thank you.

**Comment by Kenneth-Sills** [comment]
Wonderful, that works!

Thank you for such a quick turnaround. 😄
