### ISSUE TITLE
System error: ""numeric-string" is not a valid property name

### ISSUE THREAD

**Issue by vladdnepr** [rectorphp/rector#8512]
Hi. 

I got next one

`System error: ""numeric-string" is not a valid property name`

Here is rector.php

```
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__.'/src',
    ]);
    $rectorConfig->importNames();
    $rectorConfig->importShortClasses(false);
    $rectorConfig->removeUnusedImports();
    $rectorConfig->parallel(360);

    // define sets of rules
    $rectorConfig->sets([
        SetList::NAMING,
    ]);
};

```

File Test.php

```
<?php

class Test
{
    /**
     * @var numeric-string|null
     */
    private ?string $value = null;

    /**
     * @return numeric-string|null
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * @param numeric-string|null $value
     *
     * @return $this
     */
    public function setValue(?string $value): self
    {
        $this->value = $value;

        return $this;
    }
}

```

and --debug output

```
                                                                                                                        
 [ERROR] Could not process "/app/src/Test.php" file, due to:                                                             
         "System error: ""numeric-string" is not a valid property name"                                                 
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Validation/RectorAssert.php(58):                                                   
         Rector\Validation\RectorAssert::elementName('numeric-string', '#^[a-zA-Z_\\x7f-...', 'property')               
         #1 vendor/rector/rector/rules/Naming/ValueObject/PropertyRename.php(53):                                       
         Rector\Validation\RectorAssert::propertyName('numeric-string')                                                 
         #2 vendor/rector/rector/rules/Naming/ValueObjectFactory/PropertyRenameFactory.php(25):                         
         Rector\Naming\ValueObject\PropertyRename->__construct(Object(PhpParser\Node\Stmt\Property), 'numeric-string',  
         'value', Object(PhpParser\Node\Stmt\Class_), 'Test', Object(PhpParser\Node\Stmt\PropertyProperty))             
         #3 vendor/rector/rector/rules/Naming/Rector/Class_/RenamePropertyToMatchTypeRector.php(117):                   
         Rector\Naming\ValueObjectFactory\PropertyRenameFactory->createFromExpectedName(Object(PhpParser\Node\Stmt\Clas 
         s_), Object(PhpParser\Node\Stmt\Property), 'numeric-string')                                                   
         #4 vendor/rector/rector/rules/Naming/Rector/Class_/RenamePropertyToMatchTypeRector.php(100):                   
         Rector\Naming\Rector\Class_\RenamePropertyToMatchTypeRector->refactorClassProperties(Object(PhpParser\Node\Stm 
         t\Class_))                                                                                                     
         #5 vendor/rector/rector/src/Rector/AbstractRector.php(136):                                                    
         Rector\Naming\Rector\Class_\RenamePropertyToMatchTypeRector->refactor(Object(PhpParser\Node\Stmt\Class_))      
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                          
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Class_))                                    
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(Rector\PhpParser\Node\CustomNode\FileWithoutNamespace))           
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                           
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #10 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #11 vendor/rector/rector/src/Application/FileProcessor.php(105):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #12 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #13 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #14 vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):                                           
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         Object(Closure))                                                                                               
         #15 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)                                  
         #16 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #17 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202402\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #18 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #19 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}('{"action":"main...')          
         #20 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #21 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202402\React\Stream\DuplexResourceStream->handleData(Resource id #1731)                            
         #22 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #23 vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):                                            
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()                                                     
         #24 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                               
         #25 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202402\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))           
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCom 
         mand), Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput),                                   
         Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #27 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202402\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202402\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))             
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #29 vendor/rector/rector/bin/rector.php(130): RectorPrefix202402\Symfony\Component\Console\Application->run()  
         #30 vendor/rector/rector/bin/rector(5): require_once('vendor/rec...')                                          
         #31 vendor/bin/rector(119): include('vendor/rec...')                                                           
         #32 {main}". On line: 77 
```

**Comment by samsonasik** [comment]
Reproduced by rule: `RenamePropertyToMatchTypeRector` at https://getrector.com/demo/d3d4f307-c982-40ef-9db6-6b608660af99
