### ISSUE TITLE
[Laravel] hasMany relationship + conditional results in `"System error: "Scope not available`

### ISSUE THREAD

**Issue by Treggats** [rectorphp/rector#8513]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.1             |

Running Rector with the snippet and config provided results in a System error.
Key things to note are
- hasMany relation
- chained `when()` method
- `validated()` method from the request class

When changing closure to a short closure Rector finishes OK!

## Minimal PHP Code Causing Issue

https://getrector.com/demo/1b0db50e-9439-4934-8b21-e7a1a75e3218

## Debug output

<details>
<summary>Details</summary>

```
/Users/tonko/PhpstormProjects/project-x/app/Http/Controllers/RectorTestController.php

 [ERROR] Could not process "/Users/tonko/PhpstormProjects/project-x/app/Http/Controllers/RectorTestController.php"  
         file, due to:                                                                                                  
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a             
         refactorWithScope() method of "Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector"    
         rule. Fix scope refresh on changed nodes first"                                                                
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(136):                                                    
         Rector\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Expr\MethodCall))                       
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))                                
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))                                              
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\MethodCall))                                  
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))                                     
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #13 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #14 vendor/rector/rector/src/Application/FileProcessor.php(105):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #15 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #16 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #17 vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):                                           
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         Object(Closure))                                                                                               
         #18 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)                                  
         #19 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #20 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202402\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #21 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #22 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}('{"action":"main...')          
         #23 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202402\Evenement\EventEmitter->emit('data', Array)                                                 
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202402\React\Stream\DuplexResourceStream->handleData(Resource id #1944)                            
         #25 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #26 vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):                                            
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()                                                     
         #27 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                               
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202402\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))           
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCom 
         mand), Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput),                                   
         Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #30 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202402\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202402\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))             
         #31 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202402\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202402\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #32 vendor/rector/rector/bin/rector.php(130): RectorPrefix202402\Symfony\Component\Console\Application->run()  
         #33 vendor/rector/rector/bin/rector(5): require_once('/Users/tonko/Ph...')                                     
         #34 vendor/bin/rector(119): include('/Users/tonko/Ph...')                                                      
         #35 {main}". On line: 25                                                                                       
```

</details>

## Expected Behaviour

Rector should change nothing, and return `[OK] Rector is done!`

**Comment by samsonasik** [comment]
Reproduced by `OptionalParametersAfterRequiredRector` https://getrector.com/demo/e50ddeb6-9163-4111-929a-70c1e030f933
