### ISSUE TITLE
rectorphp or rector have a problem with fluent function \TYPO3\CMS\Core\Database\Query\Expression\CompositeExpression::add

### ISSUE THREAD

**Issue by hdietrich-timespin** [rectorphp/rector#8563]
The following Code throw an Error durinfg process

sabbelasichon/typo3-rector  version 2.0.0 

```
return RectorConfig::configure()
 ->withSets([
        Typo3LevelSetList::UP_TO_TYPO3_12,
        LevelSetList::UP_TO_PHP_82,
    ])
    // uncomment to reach your current PHP version
    // ->withPhpSets()
    ->withRules([
        AddVoidReturnTypeWhereNoReturnRector::class,
    ]);
```

Code: 
```
 /** @var \TYPO3\CMS\Core\Database\Query\QueryBuilder $queryBuilder */
            $or = $queryBuilder->expr()->or();
            $or->add($queryBuilder->expr()->like('city', ":search"))
                  ->add($queryBuilder->expr()->like('zip', ":search"))
                  ->add($queryBuilder->expr()->like('company_name', ":search"))
                  ->add($queryBuilder->expr()->like('scope', ":search"))
            ;
```
Error:  (see trace in the end of that description!) 
```
[ERROR] Could not process
         "/www/typo3conf
         /ext/myext/Classes/Domain/Repository/CertificateGlkRepository.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a
         refactorWithScope() method of "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on
         changed nodes first"
```

if i change the Code to: 
```
            /** @var \TYPO3\CMS\Core\Database\Query\QueryBuilder $queryBuilder */
            $or = $queryBuilder->expr()->or();
            $or->add($queryBuilder->expr()->like('city', ":search"));
            $or->add($queryBuilder->expr()->like('zip', ":search"));
            $or->add($queryBuilder->expr()->like('company_name', ":search"));
            $or->add($queryBuilder->expr()->like('scope', ":search"));
```

It will be processed without Error: 
![grafik](https://github.com/rectorphp/rector/assets/117842214/8571e7fd-3063-4f7f-8763-897743b36e5e)

Errortrace: 
```

[ERROR] Could not process
         "/www/typo3conf
         /ext/myext/Classes/Domain/Repository/CertificateGlkRepository.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a
         refactorWithScope() method of "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on
         changed nodes first"

         Stack trace:
         #0 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Rector/AbstractRector.php(136):
         Rector\Rector\AbstractScopeAwareRector->refactor()
         #1
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(113): Rector\Rector\AbstractRector->enterNode()
         #2
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(133): PhpParser\NodeTraverser->traverseNode()
         #3
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(133): PhpParser\NodeTraverser->traverseNode()
         #4
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #5
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #6
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #7
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #8
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #9
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #10
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #11
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #12
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #13
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(85): PhpParser\NodeTraverser->traverseArray()
         #14
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverse
         r.php(41): PhpParser\NodeTraverser->traverse()
         #15 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/FileProcessor.php(105):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #16
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(1
         84): Rector\Application\FileProcessor->processFile()
         #17
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(1
         61): Rector\Application\ApplicationFileProcessor->processFile()
         #18
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #19
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}()
         #20
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #21
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): RectorPrefix202402\Clue\React\NDJson\Decoder->handleData()
         #22 /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #23
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}()
         #24
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.p
         hp(154): RectorPrefix202402\Evenement\EventEmitter->emit()
         #25
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.p
         hp(201): RectorPrefix202402\React\Stream\DuplexResourceStream->handleData()
         #26
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.p
         hp(173): RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #27 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()
         #28
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Command/Command.php(327
         ): Rector\Console\Command\WorkerCommand->execute()
         #29
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run()
         #30
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand()
         #31 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202402\Symfony\Component\Console\Application->doRun()
         #32
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #33 /www/typo3-rector-2.0.0/vendor/rector/rector/bin/rector.php(130):
         RectorPrefix202402\Symfony\Component\Console\Application->run()
         #34 /www/typo3-rector-2.0.0/vendor/rector/rector/bin/rector(5): require_once('...')
         #35 /www/typo3-rector-2.0.0/vendor/bin/rector(119): include('...')
         #36 {main}". On line: 25
```

**Comment by samsonasik** [comment]
Could you create reproducible code and config at https://getrector.com/demo or reproducible repo for it? Thank you.

**Comment by hdietrich-timespin** [comment]
It is unpossible in Demo, you need complete Typo3-Core-Package \TYPO3\CMS\Core\Database or complete Typo3Core

**Comment by samsonasik** [comment]
You can provide sample repository to reproduce it, anyway, could you try manually patch from PR:

- https://github.com/rectorphp/rector-src/pull/5743

and verify if that resolve it?

**Comment by hdietrich-timespin** [comment]
> You can provide sample repository to reproduce it, anyway, could you try manually patch from PR:
> 
>     * [[Scope] Fix resolve Scope from fluent call rector-src#5743](https://github.com/rectorphp/rector-src/pull/5743)
> 
> 
> and verify if that resolve it?

I use sabbelasichon/typo3-rector version 2.0.0 an i can not fin class ExprScopeFromStmtNodeVisitor

**Comment by samsonasik** [comment]
You should can check under `vendor/rector/rector/src/PHPStan/NodeVisitor/ExprScopeFromStmtNodeVisitor.php`

**Comment by hdietrich-timespin** [comment]
I use sabbelasichon/typo3-rector version 2.2.0 with rector/rector version 1.0.3. I test your path, but not solved the problem! 
I report that problem to https://github.com/sabbelasichon/typo3-rector/issues/4196

**Comment by samsonasik** [comment]
It is better to create a github repo with step by step to reproduce, otherwise, nothing we can do.

I am closing it until you have a chance to create reproducible repo, thank you.

**Comment by samsonasik** [comment]
This should be fixed at https://github.com/rectorphp/rector-src/pull/5743

**Before**

```
➜  MyProject git:(bug_issues_4196) ../vendor/bin/rector process typo3conf/ext/t3tstest/Classes/Domain/Repository --dry-run -vvv --debug 
/Users/samsonasik/www/typo3-rector-testrepo/MyProject/typo3conf/ext/t3tstest/Classes/Domain/Repository/TestRepository.php
string(57) "$or->add($queryBuilder->expr()->eq('znumber', ":search"))"

                                                                                                                        
 [ERROR] Could not process                                                                                              
         "/Users/samsonasik/www/typo3-rector-testrepo/MyProject/typo3conf/ext/t3tstest/Classes/Domain/Repository/TestRep
         ository.php" file, due to:                                                                                     
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a             
         refactorWithScope() method of "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on
```

**After**

```
1) typo3conf/ext/t3tstest/Classes/Domain/Repository/TestRepository.php:28

    ---------- begin diff ----------
@@ @@

         $or = $queryBuilder->expr()->or();

-        $or->add($queryBuilder->expr()->eq('znumber', ":search"))
-            ->add($queryBuilder->expr()->eq('type', ":search"))
-            ->add($queryBuilder->expr()->like('first_name', ":likeSearch"))
-            ->add($queryBuilder->expr()->like('last_name', ":likeSearch"))
+        ((($or = $or->with($queryBuilder->expr()->eq('znumber', ":search"))) = ($or = $or->with($queryBuilder->expr()->eq('znumber', ":search")))->with($queryBuilder->expr()->eq('type', ":search"))) = ($or->add($queryBuilder->expr()->eq('znumber', ":search")) = ($or = $or->with($queryBuilder->expr()->eq('znumber', ":search")))->with($queryBuilder->expr()->eq('type', ":search")))->with($queryBuilder->expr()->like('first_name', ":likeSearch"))) = ($or->add($queryBuilder->expr()->eq('znumber', ":search"))
+            ->add($queryBuilder->expr()->eq('type', ":search")) = ($or->add($queryBuilder->expr()->eq('znumber', ":search")) = ($or = $or->with($queryBuilder->expr()->eq('znumber', ":search")))->with($queryBuilder->expr()->eq('type', ":search")))->with($queryBuilder->expr()->like('first_name', ":likeSearch")))->with($queryBuilder->expr()->like('last_name', ":likeSearch"))
         ;

         return $queryBuilder->execute();
    ----------- end diff -----------

Applied rules:
 * ReplaceInjectAnnotationWithMethodRector (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-90799-DependencyInjectionWithNonPublicPropertiesHasBeenRemoved.html)
 * SubstituteCompositeExpressionAddMethodsRector (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97244-CompositeExpressionMethodsAddAndAddMultiple.html)
```

**Comment by hdietrich-timespin** [comment]
Yes it works fine.  Thanks!

**Comment by hdietrich-timespin** [comment]
Is it not possible that the changed code more human readable is?

**Comment by samsonasik** [comment]
Feel free to provide feature improvement PR :)

**Comment by hdietrich-timespin** [comment]
If I do not use fluent calls the rector changes are very better: 

![grafik](https://github.com/sabbelasichon/typo3-rector/assets/117842214/f5721d49-df85-4b4e-a53d-7ca4033cbf49)

**Comment by samsonasik** [comment]
Again, feel free to provide feature improvement PR :)
