### ISSUE TITLE
System error: "Warning: Uninitialized string offset -1

### ISSUE THREAD

**Issue by DominicLuidold** [rectorphp/rector#8787]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.3             |

When running `vendor/bin/rector process` (best reproducible when appending `--clear-cache`), the following error occurs (not always, but roughly 7 out 10 times):

(_Note:_ the stack trace was gathered using `-vvv`; `--debug` did not produce any stack trace)

<details><summary>Error stack trace</summary>

```
vendor/bin/rector --clear-cache -vvv

                                                                                                                        
 [ERROR] Could not process "/var/www/sylius/src/Kernel.php" file, due to:                                               
         "System error: "Warning: Uninitialized string offset -1"                                                       
                                                                                                                        
         Stack trace:                                                                                                   
         #0 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(2039):                            
         PHPStan\Type\Constant\ConstantStringType->getOffsetValueType(Object(PHPStan\Type\Constant\ConstantIntegerType) 
         )                                                                                                              
         #1 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1601):                            
         PHPStan\Analyser\MutatingScope->getTypeFromArrayDimFetch(Object(PhpParser\Node\Expr\ArrayDimFetch),            
         Object(PHPStan\Type\Constant\ConstantIntegerType), Object(PHPStan\Type\Constant\ConstantStringType))           
         #2 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599):                             
         PHPStan\Analyser\MutatingScope->resolveType('$rawChunk[\\strl...', Object(PhpParser\Node\Expr\ArrayDimFetch))  
         #3 phar://vendor/phpstan/phpstan/phpstan.phar/src/Rules/Comparison/ImpossibleCheckTypeHelper.php(109):         
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\ArrayDimFetch))                             
         #4                                                                                                             
         phar://vendor/phpstan/phpstan/phpstan.phar/src/Type/Php/TypeSpecifyingFunctionsDynamicReturnTypeExtension.php(6
         7):                                                                                                            
         PHPStan\Rules\Comparison\ImpossibleCheckTypeHelper->findSpecifiedType(Object(PHPStan\Analyser\MutatingScope),  
         Object(PhpParser\Node\Expr\FuncCall))                                                                          
         #5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1764):                            
         PHPStan\Type\Php\TypeSpecifyingFunctionsDynamicReturnTypeExtension->getTypeFromFunctionCall(Object(PHPStan\Ref 
         lection\Native\NativeFunctionReflection), Object(PhpParser\Node\Expr\FuncCall),                                
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #6 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599):                             
         PHPStan\Analyser\MutatingScope->resolveType('\\in_array($rawC...', Object(PhpParser\Node\Expr\FuncCall))       
         #7 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(695):                             
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\FuncCall))                                  
         #8 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(599):                             
         PHPStan\Analyser\MutatingScope->resolveType('!\\in_array($raw...', Object(PhpParser\Node\Expr\BooleanNot))     
         #9 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(822):                         
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\BooleanNot))                                
         #10 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_),                           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #11 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(859):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ElseIf_), Array,               
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #12 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_),                           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #13 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1153):                       
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\For_), Array,                  
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #14 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\For_),                          
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #15 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(646):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #16 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),                   
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),                          
         Object(PHPStan\Analyser\StatementContext))                                                                     
         #17 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(783):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,                
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),                          
         Object(PHPStan\Analyser\StatementContext))                                                                     
         #18 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(458):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),                        
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #19 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(753):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array,            
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #20 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(423):                        
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),                    
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #21 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(271):                 
         PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope),                
         Object(Closure))                                                                                               
         #22 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(255):                 
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))                                                       
         #23 vendor/rector/rector/src/NodeTypeResolver/NodeScopeAndMetadataDecorator.php(43):                           
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, '/var/www/sylius...')      
         #24 vendor/rector/rector/src/PhpParser/AstResolver.php(298):                                                   
         Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile('/var/www/sylius...', Array)      
         #25 vendor/rector/rector/src/PhpParser/AstResolver.php(112):                                                   
         Rector\PhpParser\AstResolver->parseFileNameToDecoratedNodes('/var/www/sylius...')                              
         #26 vendor/rector/rector/rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php(132):       
         Rector\PhpParser\AstResolver->resolveClassMethodFromMethodReflection(Object(PHPStan\Reflection\Php\PhpMethodRe 
         flection))                                                                                                     
         #27 vendor/rector/rector/src/Rector/AbstractRector.php(139):                                                   
         Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector->refactor(Object(PhpParser\Node\Stmt\Cl 
         assMethod))                                                                                                    
         #28 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):                         
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))                               
         #29 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #30 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #31 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #32 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #33 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #34 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #35 vendor/rector/rector/src/Application/FileProcessor.php(113):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #36 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #37 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #38 vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):                                           
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         NULL)                                                                                                          
         #39 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}(Array)                                  
         #40 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202408\Evenement\EventEmitter->emit('data', Array)                                                 
         #41 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202408\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #42 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202408\Evenement\EventEmitter->emit('data', Array)                                                 
         #43 vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111):                            
         RectorPrefix202408\React\Stream\Util::RectorPrefix202408\React\Stream\{closure}('{"action":"main...')          
         #44 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(168):                                
         RectorPrefix202408\Evenement\EventEmitter->emit('data', Array)                                                 
         #45 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202408\React\Stream\DuplexResourceStream->handleData(Resource id #3459)                            
         #46 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202408\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #47 vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):                                            
         RectorPrefix202408\React\EventLoop\StreamSelectLoop->run()                                                     
         #48 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\WorkerCommand->execute(Object(RectorPrefix202408\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202408\Symfony\Component\Console\Output\ConsoleOutput))                               
         #49 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202408\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202408\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202408\Symfony\Component\Console\Output\ConsoleOutput))           
         #50 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202408\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\WorkerCom 
         mand), Object(RectorPrefix202408\Symfony\Component\Console\Input\ArgvInput),                                   
         Object(RectorPrefix202408\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #51 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202408\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202408\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202408\Symfony\Component\Console\Output\ConsoleOutput))             
         #52 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202408\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202408\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #53 vendor/rector/rector/bin/rector.php(130): RectorPrefix202408\Symfony\Component\Console\Application->run()  
         #54 vendor/rector/rector/bin/rector(5): require_once('/var/www/sylius...')                                     
         #55 vendor/bin/rector(119): include('/var/www/sylius...')                                                      
         #56 {main}". On line: 311  
```

</details>

Our Rector config looks like this:

<details><summary><code>rector.php</code></summary>

```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Identical\FlipTypeControlToUseExclusiveTypeRector;
use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Php81\Rector\Class_\MyCLabsClassToEnumRector;
use Rector\Php81\Rector\Class_\SpatieEnumClassToEnumRector;
use Rector\Php81\Rector\MethodCall\MyCLabsMethodCallToEnumConstRector;
use Rector\Php81\Rector\MethodCall\SpatieEnumMethodCallToEnumConstRector;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\PHPUnit\CodeQuality\Rector\Class_\PreferPHPUnitThisCallRector;
use Rector\Symfony\CodeQuality\Rector\Class_\EventListenerToEventSubscriberRector;
use Rector\Symfony\CodeQuality\Rector\ClassMethod\ActionSuffixRemoverRector;
use Rector\Symfony\Set\SymfonySetList;
use Rector\Symfony\Symfony34\Rector\Closure\ContainerGetNameToTypeInTestsRector;

return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    ->withPHPStanConfigs([__DIR__.'/phpstan.neon'])
    ->withSymfonyContainerXml(__DIR__.'/var/cache/dev/App_KernelDevDebugContainer.xml')
    ->withPhpSets(php82: true)
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true,
        typeDeclarations: true,
        privatization: true,
        instanceOf: true,
        strictBooleans: true,
        phpunitCodeQuality: true,
        doctrineCodeQuality: true,
        symfonyCodeQuality: true,
        symfonyConfigs: true,
        phpunit: true,
    )
    ->withSets([
        // Symfony
        SymfonySetList::SYMFONY_64,
        SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,

        // Doctrine
        DoctrineSetList::DOCTRINE_ORM_214,
        DoctrineSetList::DOCTRINE_DBAL_211,
        DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
    ])
    ->withSkip([
        ActionSuffixRemoverRector::class,
        ContainerGetNameToTypeInTestsRector::class,
        EventListenerToEventSubscriberRector::class => [
            __DIR__.'/src/EventListener/ShipmentShipListenerDecorator.php',
        ],
        FlipTypeControlToUseExclusiveTypeRector::class,
        MyCLabsClassToEnumRector::class,
        MyCLabsMethodCallToEnumConstRector::class,
        PreferPHPUnitThisCallRector::class,
        ReadOnlyPropertyRector::class => [
            __DIR__.'/src/Entity/Customer/Customer.php',
            __DIR__.'/src/Entity/Payment/PaymentMethod.php',
        ],
        SpatieEnumClassToEnumRector::class,
        SpatieEnumMethodCallToEnumConstRector::class,
    ]);

```

</details>

And our PHPStan config (as it is included using `withPHPStanConfigs()`) looks like this:

<details>
<summary><code>phpstan.neon</code></summary>

```neon
parameters:
    level: 8
    paths:
        - config/
        - src/
        - tests/
    symfony:
        consoleApplicationLoader: tests/phpstan/console-application.php
        containerXmlPath: var/cache/test/App_KernelTestDebugContainer.xml
    doctrine:
        objectManagerLoader: tests/phpstan/object-manager.php
    scanDirectories:
        - var/cache/test/Symfony/Config
    scanFiles:
        - vendor/symfony/dependency-injection/Loader/Configurator/ContainerConfigurator.php
    type_coverage:
        return: 98
        param: 98
        property: 96

includes:
    - phpstan-baseline.neon
    - vendor/jangregor/phpstan-prophecy/extension.neon
    - vendor/phpstan/phpstan-deprecation-rules/rules.neon
    - vendor/phpstan/phpstan-doctrine/extension.neon
    - vendor/phpstan/phpstan-doctrine/rules.neon
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon
    - vendor/phpstan/phpstan-symfony/extension.neon
    - vendor/phpstan/phpstan-symfony/rules.neon
    - vendor/phpstan/phpstan-webmozart-assert/extension.neon
    - vendor/tomasvotruba/type-coverage/config/extension.neon

```

</details>

## Minimal PHP Code Causing Issue

Our `Kernel` file looks like this - nothing out of the ordinary as far as we can tell.

<details><summary><code>Kernel.php</code></summary>

```php
<?php

declare(strict_types=1);

namespace App;

use App\DependencyInjection\CompilerPass\BehatCalendarCompilerPass;
use App\DependencyInjection\CompilerPass\BehatMailerCompilerPass;
use App\DependencyInjection\CompilerPass\RoutePaymentCompleteTransitionSubscriberRemovalCompilerPass;
use App\DependencyInjection\CompilerPass\SyliusMigrationCompilerPass;
use App\DependencyInjection\CompilerPass\SyliusOrderCheckoutStateMachineCompilerPass;
use App\DependencyInjection\CompilerPass\SyliusOrderGridCompilerPass;
use App\DependencyInjection\CompilerPass\SyliusRemoveDeprecatedProductFixturesCompilerPass;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

final class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        parent::build($container);

        $container->addCompilerPass(new BehatCalendarCompilerPass());
        $container->addCompilerPass(new BehatMailerCompilerPass());
        $container->addCompilerPass(new SyliusOrderCheckoutStateMachineCompilerPass());
        $container->addCompilerPass(new RoutePaymentCompleteTransitionSubscriberRemovalCompilerPass());
        $container->addCompilerPass(new SyliusOrderGridCompilerPass());
        $container->addCompilerPass(new SyliusMigrationCompilerPass());
        $container->addCompilerPass(new SyliusRemoveDeprecatedProductFixturesCompilerPass());
    }
}

```

</details>

## Expected Behaviour

No error occurs.

**Comment by DominicLuidold** [comment]
> Could you reproduce at https://getrector.com/demo or reproducible repo for it? Thank you.

Of course, I will see what I can do in this regard. It will probably take some time though, as the error only occurs in one specific private project(which we cannot readily share due to contractual obligations) even though we use the same PHPStan/Rector configuration combination across multiple other projects.

I'll let you know and ping you if we find any more information. :)

**Comment by samsonasik** [comment]
For internal phpstan error, and only happen on single file, I guess you can just skip it

```php
<?php

use Rector\Config\RectorConfig;
use Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector;

return RectorConfig::configure()
    ->withSkip([
        
            __DIR__ . '/src/Kernel.php'
       
    ]);
```

**Comment by DominicLuidold** [comment]
@samsonasik Thanks for you support. So far, we haven't had any issues with this. 🤞 

I'll keep you updated if we find out any more information. Until then, I'm closing this as resolved. 😃
