### ISSUE TITLE
System error: "Call to undefined method PHPStan\Type\Generic\TemplateTypeParameterStrategy::describe()"

### ISSUE THREAD

**Issue by matbech** [rectorphp/rector#8834]
Rector 1.2.5

 ```[ERROR] Could not process "C:\Projects\Web\www.test.com\htdocs\shared\fff\XmlHttpRequest.php" file, due to:
         "System error: "Call to undefined method PHPStan\Type\Generic\TemplateTypeParameterStrategy::describe()"

         #0
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/VerbosityLevel.php
         (161):
         PHPStan\Type\Generic\TemplateObjectWithoutClassType->{closure:PHPStan\Type\Generic\TemplateTypeTrait::describ
         e():68}()
         #1
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/Generic/TemplateTy
         peTrait.php(68): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure), Object(Closure))
         #2
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Type/Generic/TypeProjec
         tionHelper.php(13):
         PHPStan\Type\Generic\TemplateObjectWithoutClassType->describe(Object(PHPStan\Type\VerbosityLevel))
         #3
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflect
         ion.php(378):
         PHPStan\Type\Generic\TypeProjectionHelper::describe(Object(PHPStan\Type\Generic\TemplateObjectWithoutClassType
         ), Object(PHPStan\Type\Generic\TemplateTypeVariance), Object(PHPStan\Type\VerbosityLevel))
         #4
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpClass
         ReflectionExtension.php(350): PHPStan\Reflection\ClassReflection->getCacheKey()
         #5
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflect
         ion.php(580):
         PHPStan\Reflection\Php\PhpClassReflectionExtension->getNativeMethod(Object(PHPStan\Reflection\ClassReflection
         ), 'getIterator')
         #6
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(
         239): PHPStan\Reflection\ClassReflection->getNativeMethod('getIterator')
         #7
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(
         208): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockFromClass(Object(PHPStan\Reflection\ClassReflection),
         'getIterator', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', true, Array)
         #8
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(
         180): PHPStan\PhpDoc\PhpDocBlock::resolveParentPhpDocBlocks(Object(PHPStan\Reflection\ClassReflection),
         'getIterator', 'hasNativeMethod', 'getNativeMethod', 'resolvePhpDocBl...', true, Array)
         #9
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocBlock.php(
         172): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockTree('/**\n     * Retu...',
         Object(PHPStan\Reflection\ClassReflection), NULL, 'getIterator', 'phar://C:\\Proje...', 'hasNativeMethod',
         'getNativeMethod', 'resolvePhpDocBl...', NULL, Array, Array)
         #10
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/PhpDoc/PhpDocInheritanc
         eResolver.php(41): PHPStan\PhpDoc\PhpDocBlock::resolvePhpDocBlockForMethod('/**\n     * Retu...',
         Object(PHPStan\Reflection\ClassReflection), NULL, 'getIterator', 'phar://C:\\Proje...', NULL, Array, Array)
         #11
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(4652): PHPStan\PhpDoc\PhpDocInheritanceResolver->resolvePhpDocForMethod('/**\n     * Retu...',
         'phar://C:\\Proje...', Object(PHPStan\Reflection\ClassReflection), NULL, 'getIterator', Array)
         #12
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(612): PHPStan\Analyser\NodeScopeResolver->getPhpDocs(Object(PHPStan\Analyser\MutatingScope),
         Object(PhpParser\Node\Stmt\ClassMethod))
         #13
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(464): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
         Object(PHPStan\Analyser\StatementContext))
         #14
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(789): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,
         Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
         Object(PHPStan\Analyser\StatementContext))
         #15
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(429): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #16
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(288): PHPStan\Analyser\NodeScopeResolver->processNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #17
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(169):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #18
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(534):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->{closure:Rector\NodeTypeResolver\PHPStan\Scop
         e\PHPStanNodeScopeResolver::processNodes():141}(Object(Rector\PhpParser\Node\CustomNode\FileWithoutNamespace),
         Object(PHPStan\Analyser\MutatingScope))
         #19
         phar://C:/Projects/Web/www.test.com/htdocs/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResol
         ver.php(429):
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(Rector\PhpParser\Node\CustomNode\FileWithoutNamesp
         ace), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
         #20
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(288): PHPStan\Analyser\NodeScopeResolver->processNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #21
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\PHPStan\Scope\PHPStanNodeSco
         peResolver.php(260):
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))
         #22
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\NodeTypeResolver\NodeScopeAndMetadataDecorato
         r.php(43): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array,
         'phar://C:\\Proje...')
         #23 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\AstResolver.php(298):
         Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile('phar://C:\\Proje...', Array)
         #24 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\AstResolver.php(112):
         Rector\PhpParser\AstResolver->parseFileNameToDecoratedNodes('phar://C:\\Proje...')
         #25
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\rules\Php80\Rector\ClassMethod\AddParamBasedOnPar
         entClassMethodRector.php(132):
         Rector\PhpParser\AstResolver->resolveClassMethodFromMethodReflection(Object(PHPStan\Reflection\Native\NativeM
         ethodReflection))
         #26 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Rector\AbstractRector.php(139):
         Rector\Php80\Rector\ClassMethod\AddParamBasedOnParentClassMethodRector->refactor(Object(PhpParser\Node\Stmt\C
         lassMethod))
         #27
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(178): Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #28
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray(Array)
         #29
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(198): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #30
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(105): PhpParser\NodeTraverser->traverseArray(Array)
         #31
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(198): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #32
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTravers
         er.php(85): PhpParser\NodeTraverser->traverseArray(Array)
         #33
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.p
         hp(47): PhpParser\NodeTraverser->traverse(Array)
         #34 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\FileProcessor.php(113):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #35
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(184)
         : Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #36
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(161)
         : Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #37
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Application\ApplicationFileProcessor.php(138)
         : Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),
         Object(Closure), Object(Closure))
         #38 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Console\Command\ProcessCommand.php(149):
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),
         Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput))
         #39
         C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Command\Command.php(327):
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202409\Symfony\Component\Console\Input\Argv
         Input), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #40 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(960):
         RectorPrefix202409\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202409\Symfony\Component
         \Console\Input\ArgvInput), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #41 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(333):
         RectorPrefix202409\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessC
         ommand), Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #42 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\src\Console\ConsoleApplication.php(53):
         RectorPrefix202409\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202409\Symfony\Component\C
         onsole\Input\ArgvInput), Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #43 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\vendor\symfony\console\Application.php(216):
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202409\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202409\Symfony\Component\Console\Output\ConsoleOutput))
         #44 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\bin\rector.php(130):
         RectorPrefix202409\Symfony\Component\Console\Application->run()
         #45 C:\Projects\Web\www.test.com\htdocs\vendor\rector\rector\bin\rector(5):
         require_once('C:\\Projects\\Web...')
         #46 C:\Projects\Web\www.test.com\htdocs\vendor\bin\rector(119): include('C:\\Projects\\Web...')
         #47 {main}". On line: 69
```

## PHP file
```
<?php
declare(strict_types=1);

namespace vdvdvdvd;

class XmlHttpException extends \Exception
{
	private readonly int $_httpCode;

	public function __construct(int $httpCode, string $message)
	{
		parent::__construct($message);
		$this->_httpCode = $httpCode;
	}

	public function getHttpCode(): int
	{
		return $this->_httpCode;
	}

	#[\Override]
	public function __toString(): string
	{
		return __CLASS__ . ": [{$this->_httpCode}]: {$this->message}\n";
	}
}
```

## Expected Behaviour
No error

**Comment by samsonasik** [comment]
Could you create reproducible demo for it at https://getrector.com/demo/58883db2-4630-4880-ad58-ddd02cfab083 ? Thank you.

**Comment by matbech** [comment]
I'm unable to reproduce it on the demo page. Maybe the culprit is PHP 8.4.0 Beta 5

**Comment by samsonasik** [comment]
Just looking at the error, you have error:

```
        Rector\PhpParser\AstResolver->parseFileNameToDecoratedNodes('phar://C:\\Proje...')
```

did you read phar file somewhere, how you define `paths()` config ? ensure not include third party code https://getrector.com/documentation/ignoring-rules-or-paths

**Comment by matbech** [comment]
I have downgraded from PHP 8.4.0 Beta 5 to PHP 8.3 and I can no longer reproduce the issue. It looks like PHP 8.4 has something to do with it.

**Comment by samsonasik** [comment]
Ok, closing then ;) PHP 8.4 is not released so I think phpstan will catch up ;)
