### ISSUE TITLE
Call to a member function end() on null

### ISSUE THREAD

**Issue by brendt** [rectorphp/rector#8863]
# Bug Report

Rector 1.2.6

```php
> vendor/bin/rector process --no-ansi
 784/961 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  81%Fatal error: Uncaught Error: Call to a member function end() on null in /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php:120
Stack trace:
#0 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php(49): RectorPrefix202410\Symplify\EasyParallel\ValueObject\ParallelProcess->quit()
#1 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ProcessPool.php(59): RectorPrefix202410\Symplify\EasyParallel\ValueObject\ProcessPool->quitProcess('t52yldsdt3')
#2 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Parallel/Application/ParallelFileProcessor.php(138): RectorPrefix202410\Symplify\EasyParallel\ValueObject\ProcessPool->quitAll()
#3 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php(130): Rector\Parallel\Application\ParallelFileProcessor->Rector\Parallel\Application\{closure}(Array)
#4 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202410\Symplify\EasyParallel\ValueObject\ParallelProcess->RectorPrefix202410\Symplify\EasyParallel\ValueObject\{closure}(Array)
#5 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117): RectorPrefix202410\Evenement\EventEmitter->emit('data', Array)
#6 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202410\Clue\React\NDJson\Decoder->handleData(Array)
#7 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202410\Evenement\EventEmitter->emit('data', Array)
#8 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTrait.php(111): RectorPrefix202410\React\Stream\Util::RectorPrefix202410\React\Stream\{closure}('{"action":"resu...')
#9 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(168): RectorPrefix202410\Evenement\EventEmitter->emit('data', Array)
#10 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201): RectorPrefix202410\React\Stream\DuplexResourceStream->handleData(Resource id #3322)
#11 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173): RectorPrefix202410\React\EventLoop\StreamSelectLoop->waitForStreamActivity(65118)
#12 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Parallel/Application/ParallelFileProcessor.php(177): RectorPrefix202410\React\EventLoop\StreamSelectLoop->run()
#13 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(240): Rector\Parallel\Application\ParallelFileProcessor->process(Object(RectorPrefix202410\Symplify\EasyParallel\ValueObject\Schedule), 'vendor/bin/rect...', Object(Closure), Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput))
#14 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(136): Rector\Application\ApplicationFileProcessor->runParallel(Array, Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(Closure))
#15 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Console/Command/ProcessCommand.php(156): Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration), Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput))
#16 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symfony/console/Command/Command.php(327): Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202410\Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symfony/console/Application.php(960): RectorPrefix202410\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202410\Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symfony/console/Application.php(333): RectorPrefix202410\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessCommand), Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202410\Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/src/Console/ConsoleApplication.php(53): RectorPrefix202410\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202410\Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symfony/console/Application.php(216): Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202410\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202410\Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/bin/rector.php(130): RectorPrefix202410\Symfony\Component\Console\Application->run()
#22 /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/bin/rector(5): require_once('/Users/brentroo...')
#23 /Users/brentroose/Dev/tempest-framework/vendor/bin/rector(119): include('/Users/brentroo...')
#24 {main}
  thrown in /Users/brentroose/Dev/tempest-framework/vendor/rector/rector/vendor/symplify/easy-parallel/src/ValueObject/ParallelProcess.php on line 120
Script vendor/bin/rector process --no-ansi handling the rector event returned with error code 255
```

## Minimal PHP Code Causing Issue

```php
<?php

declare(strict_types=1);

use Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector;
use Rector\Caching\ValueObject\Storage\FileCacheStorage;
use Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector;
use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPublicMethodParameterRector;
use Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector;
use Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector;
use Rector\Php74\Rector\Ternary\ParenthesizeNestedTernaryRector;
use Rector\Php81\Rector\Array_\FirstClassCallableRector;
use Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\Php82\Rector\Class_\ReadOnlyClassRector;
use Rector\Php82\Rector\Param\AddSensitiveParameterAttributeRector;
use Rector\Php83\Rector\ClassMethod\AddOverrideAttributeToOverriddenMethodsRector;
use Rector\Php84\Rector\Param\ExplicitNullableParamTypeRector;
use Rector\TypeDeclaration\Rector\ArrowFunction\AddArrowFunctionReturnTypeRector;
use Rector\TypeDeclaration\Rector\ClassMethod\ReturnNeverTypeRector;
use Rector\TypeDeclaration\Rector\Closure\ClosureReturnTypeRector;
use Rector\TypeDeclaration\Rector\Empty_\EmptyOnNullableObjectToInstanceOfRector;

return RectorConfig::configure()
    ->withCache('./.cache/rector', FileCacheStorage::class)
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withConfiguredRule(AddSensitiveParameterAttributeRector::class, [
        'sensitive_parameters' => [
            'password',
            'secret',
        ],
    ])
    ->withRules([
        ParenthesizeNestedTernaryRector::class,
        ExplicitNullableParamTypeRector::class,
    ])
    ->withSkip([
        AddOverrideAttributeToOverriddenMethodsRector::class,
        ArgumentAdderRector::class,
        ClosureToArrowFunctionRector::class,
        EmptyOnNullableObjectToInstanceOfRector::class,
        FirstClassCallableRector::class,
        NullToStrictStringFuncCallArgRector::class,
        ReadOnlyClassRector::class,
        ReadOnlyPropertyRector::class,
        RemoveNullPropertyInitializationRector::class,
        AddSensitiveParameterAttributeRector::class,
        RemoveUnusedPublicMethodParameterRector::class,
        RestoreDefaultNullToNullableTypePropertyRector::class,
        ReturnNeverTypeRector::class,
        StaticCallOnNonStaticToInstanceCallRector::class,
        ClosureReturnTypeRector::class,
        EncapsedStringsToSprintfRector::class,
        AddArrowFunctionReturnTypeRector::class,
    ])
    ->withSkipPath(__DIR__  .'/src/Tempest/Http/src/Exceptions/HttpExceptionHandler.php')
    ->withSkipPath(__DIR__  .'/src/Tempest/Http/src/Exceptions/exception.php')
    ->withPreparedSets(
        codeQuality: false,
        codingStyle: true,
        privatization: true,
        naming: false,
        earlyReturn: true,
    )
    ->withDeadCodeLevel(40)
    ->withMemoryLimit('3G')
    ->withPhpSets(php83: true)
    ->withTypeCoverageLevel(37);
```

## Expected Behaviour

Rector to work

**Comment by samsonasik** [comment]
we need reproducible code that reproduce that, otherwise, nothing we can do :)

also, it may related with php 8.4 phpstan support if you're using it, see similar issue:

- https://github.com/rectorphp/rector/issues/8835
