### ISSUE TITLE
Node "PhpParser\Node\Scalar\String_" with is missing scope required for scope refresh

### ISSUE THREAD

**Issue by rognales** [rectorphp/rector#8924]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.2.10             |

On one of my file, this error come up. Running that specific test is green on my test suite. Do advise if you need more info.
All other 3k files processed successfully.

```console
[ERROR] Could not process                                                                                              
         "/Users/rognales/Codes/website/tests/Feature/ApiService/Actions/PreparePeopleRequestActionTest.php" 
         file, due to:                                                                                                  
         "System error: "Node "PhpParser\Node\Scalar\String_" with is missing scope required for scope refresh"  
```

Here's the stacktrace.

```console
[ERROR] Could not process                                                                                              
         "/Users/rognales/Codes/website/tests/Feature/ApiService/Actions/PreparePeopleRequestActionTest.php" 
         file, due to:                                                                                                  
         "System error: "Node "PhpParser\Node\Scalar\String_" with is missing scope required for scope refresh"         
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(309):                                                    
         Rector\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Scalar\String_),                   
         '/Users/rognales...', NULL)                                                                                    
         #1 vendor/rector/rector/src/Rector/AbstractRector.php(299):                                                    
         Rector\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Scalar\String_), '/Users/rognales...',   
         NULL)                                                                                                          
         #2 vendor/rector/rector/src/Rector/AbstractRector.php(168):                                                    
         Rector\Rector\AbstractRector->postRefactorProcess(Object(PhpParser\Node\Scalar\String_),                       
         Object(PhpParser\Node\Scalar\String_), Object(PhpParser\Node\Scalar\String_), '/Users/rognales...')            
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114):                          
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Scalar\String_))                                 
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))                                              
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(134):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\StaticCall))                                  
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(134):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #16 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(47):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #17 vendor/rector/rector/src/Application/FileProcessor.php(113):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #18 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #19 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #20 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(138):                                    
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         Object(Closure), Object(Closure))                                                                              
         #21 vendor/rector/rector/src/Console/Command/ProcessCommand.php(156):                                          
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),                     
         Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput))                                          
         #22 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvI 
         nput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))                              
         #23 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202411\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202411\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))           
         #24 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202411\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessCo 
         mmand), Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput),                                  
         Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #25 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202411\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202411\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))             
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #27 vendor/rector/rector/bin/rector.php(130): RectorPrefix202411\Symfony\Component\Console\Application->run()  
         #28 vendor/rector/rector/bin/rector(5): require_once('/Users/rognales...')                                     
         #29 vendor/bin/rector(119): include('/Users/rognales...')                                                      
         #30 {main}". On line: 55                                                                                       
                                      
```

## Minimal PHP Code Causing Issue

Running rector using `.\vendor\bin\rector\`

Here's my rector config

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php53\Rector\FuncCall\DirNameFileConstantToDirConstantRector;
use Rector\Php55\Rector\String_\StringClassNameToClassConstantRector;
use Rector\Php70\Rector\FuncCall\RandomFunctionRector;
use Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector;
use Rector\Php70\Rector\Ternary\TernaryToNullCoalescingRector;
use Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector;
use Rector\Php71\Rector\List_\ListToArrayDestructRector;
use Rector\Php73\Rector\FuncCall\StringifyStrNeedlesRector;
use Rector\Php74\Rector\Assign\NullCoalescingOperatorRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector;
use Rector\Php74\Rector\Ternary\ParenthesizeNestedTernaryRector;
use Rector\Php80\Rector\Catch_\RemoveUnusedVariableInCatchRector;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Php80\Rector\ClassConstFetch\ClassOnThisVariableObjectRector;
use Rector\Php80\Rector\FuncCall\ClassOnObjectRector;
use Rector\Php80\Rector\FunctionLike\MixedTypeRector;
use Rector\Php80\Rector\Identical\StrEndsWithRector;
use Rector\Php80\Rector\Identical\StrStartsWithRector;
use Rector\Php80\Rector\NotIdentical\StrContainsRector;
use Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector;
use Rector\Php81\Rector\Array_\FirstClassCallableRector;
use Rector\Php81\Rector\ClassMethod\NewInInitializerRector;
use Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\Php82\Rector\Encapsed\VariableInStringInterpolationFixerRector;
use Rector\Php83\Rector\FuncCall\RemoveGetClassGetParentClassNoArgsRector;
use Rector\Php84\Rector\Param\ExplicitNullableParamTypeRector;
use Rector\PHPUnit\CodeQuality\Rector\Class_\YieldDataProviderRector;
use Rector\PHPUnit\CodeQuality\Rector\ClassMethod\DataProviderArrayItemsNewLinedRector;
use Rector\PHPUnit\CodeQuality\Rector\MethodCall\AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector;
use Rector\PHPUnit\CodeQuality\Rector\MethodCall\AssertEqualsToSameRector;
use Rector\PHPUnit\Set\PHPUnitSetList;
use Rector\Transform\Rector\String_\StringToClassConstantRector;
use Rector\TypeDeclaration\Rector\ClassMethod\ReturnNeverTypeRector;
use RectorLaravel\Rector\Class_\AddExtendsAnnotationToModelFactoriesRector;
use RectorLaravel\Rector\PropertyFetch\ReplaceFakerInstanceWithHelperRector;
use RectorLaravel\Rector\StaticCall\MinutesToSecondsInCacheRector;
use RectorLaravel\Rector\StaticCall\Redirect301ToPermanentRedirectRector;
use RectorLaravel\Rector\StaticCall\RouteActionCallableRector;
use RectorLaravel\Set\LaravelLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__.'/app',
        __DIR__.'/tests',
        __DIR__.'/modules',
        __DIR__.'/database',
        __DIR__.'/routes',
    ]);

    $rectorConfig->rules([
        RouteActionCallableRector::class,

        ClassPropertyAssignToConstructorPromotionRector::class,
        NewInInitializerRector::class,

        StrEndsWithRector::class,
        StrStartsWithRector::class,
        StrContainsRector::class,
        VariableInStringInterpolationFixerRector::class,
        StringifyStrNeedlesRector::class,

        ChangeSwitchToMatchRector::class,

        ClassOnObjectRector::class,
        ClassOnThisVariableObjectRector::class,
        RemoveGetClassGetParentClassNoArgsRector::class,
        DirNameFileConstantToDirConstantRector::class,

        StringClassNameToClassConstantRector::class,

        RandomFunctionRector::class,

        TernaryToNullCoalescingRector::class,
        NullCoalescingOperatorRector::class,
        ParenthesizeNestedTernaryRector::class,

        ThisCallOnStaticMethodToStaticCallRector::class,

        ListToArrayDestructRector::class,

        RemoveExtraParametersRector::class,
    ]);

    // Apply sets offered by rector-laravel
    $rectorConfig->sets([
        LaravelLevelSetList::UP_TO_LARAVEL_110,
        PHPUnitSetList::PHPUNIT_110,
    ]);

    // Exclude rules from sets
    $rectorConfig->skip([
        // rector-laravel
        MinutesToSecondsInCacheRector::class, // We already consider this
        ReplaceFakerInstanceWithHelperRector::class,
        AddExtendsAnnotationToModelFactoriesRector::class,
        Redirect301ToPermanentRedirectRector::class,
        // rector-core
        AssertEqualsToSameRector::class,
        YieldDataProviderRector::class,
        ClosureToArrowFunctionRector::class,
        NullToStrictStringFuncCallArgRector::class,
        AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector::class,
        ReadOnlyPropertyRector::class,
        ReturnNeverTypeRector::class,
        DataProviderArrayItemsNewLinedRector::class,
        RemoveUnusedVariableInCatchRector::class,
        RestoreDefaultNullToNullableTypePropertyRector::class,
        MixedTypeRector::class,
        FirstClassCallableRector::class,
        ExplicitNullableParamTypeRector::class,
    ]);
};

```

## Expected Behaviour

It should run the rules without error

**Comment by samsonasik** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.

**Comment by samsonasik** [comment]
Closing as no code sample provided, feel free to reopen issue with provide minimal code and config (usually 1 or 2 rules)

You need to invest time to narrow down rules half by half until it found the minimal rule(s) that cause it,
and the expected output.

Read this post: https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/
