### ISSUE TITLE
PhpDocInfoFqnTypeDecorator: "no such service exists"

### ISSUE THREAD

**Issue by voku** [rectorphp/rector#943]
**install command:**
```
php7.1 vendor/composer/bin/rector require --dev rector/rector
```

**run command:**
```
php7.1 vendor/composer/bin/rector process src/ --config vendor/composer/thecodingmachine/safe/rector-migrate.yml
```

**error:**
```
Cannot autowire service "Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\PhpDocInfoFqnTypeDecorator": argument "$nodeTraverser" of method "__c  
  onstruct()" references class "Symplify\BetterPhpDocParser\Ast\NodeTraverser" but no such service exists.
```

**Comment by TomasVotruba** [comment]
Version?

**Comment by voku** [comment]
the current master (d95f878cc2b706dff133e8e9f432abf22ec27513)

---

```
Testing started at 15:00 ...
/usr/bin/php7.1 /home/lmoelleken/testing/git/rector/vendor/phpunit/phpunit/phpunit --configuration /home/lmoelleken/testing/git/rector/phpunit.xml /home/lmoelleken/testing/git/rector/tests --teamcity
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockAnalyzer": argument "$phpDocInfoFactory" of method "__construct()" references class "Symplify\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory" but no such service exists. in /home/lmoelleken/testing/git/rector/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /home/lmoelleken/testing/git/rector/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /home/lmoelleken/testing/git/rector/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /home/lmoelleken/testing/git/rector/vendor/symfony/dependency-injection/Compil in /home/lmoelleken/testing/git/rector/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 54
```

**Comment by TomasVotruba** [comment]
How is this installed? It doesn't seem like `composer require`.

What is non-standard about this install relate to paths?

**Comment by TomasVotruba** [comment]
Try to add new correct path - C - here: https://github.com/rectorphp/rector/blob/master/packages/NodeTypeResolver/src/config/config.yml

**Comment by jakubvojacek** [comment]
Hello, same here

**Comment by TomasVotruba** [comment]
Just confirmed the bug, fix in progress

**Comment by TomasVotruba** [comment]
It was former bug, release fixes it (tested):

```bash
composer require rector/rector # v0.3.33
vendor/bin/rector # fails

composer require rector/rector # v0.3.34
vendor/bin/rector # success
```

**Comment by orklah** [comment]
The error is not there anymore. Can't confirm everything else is working, this was my first install.

**Comment by orklah** [comment]
I used a few levels and everything seems to work

**Comment by TomasVotruba** [comment]
Thanks for checking it
