### ISSUE TITLE
Problem with getting value of variable ...

### ISSUE THREAD

**Issue by subabrain** [rectorphp/rector#997]
So now my Code to get the original Value of an Variable somewhere in some php code:

```
<?php

declare(strict_types=1);

namespace Rector\Rector;

require __DIR__ . '/../../../vendor/autoload.php';

use PhpParser\Node;
use PhpParser\Node\Expr\PropertyFetch;
use PHPStan\Type\StringType;
use Rector\Rector\AbstractRector;
use Rector\RectorDefinition\RectorDefinition;
use PhpParser\ParserFactory;

final class GetStringValueRector extends AbstractRector
{
    /**
     * @return string[]
     */
    public function getNodeTypes(): array
    {
        return [PropertyFetch::class];
    }
    /**
     * @param PropertyFetch $node
     */
    public function refactor(Node $node): Node
    {
        
        $nodeStaticType = $this->getStaticType($node);
        dump($nodeStaticType);
        if ($nodeStaticType instanceof StringType) {
            // get string value, unfortunatelly mixed is provided
            //echo "test";
        }
        return null;
    }
    public function getDefinition(): RectorDefinition
    {
    }
}

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7); # or PREFER_PHP5, if your code is older
$nodes = $parser->parse(file_get_contents('test.php'));

/*
 * 
 * test.php
 * 
 * <?php

$test = "test";
$test2 = $test;

echo $test2;

?>
 * 
 * 
 */

var_dump($nodes[0]);

$inst = new GetStringValueRector();
$inst->refactor($nodes[0]);

?>
```

but it isnt working -> here the following output:

```
object(PhpParser\Node\Stmt\Expression)#1093 (2) {
  ["expr"]=>
  object(PhpParser\Node\Expr\Assign)#1092 (3) {
    ["var"]=>
    object(PhpParser\Node\Expr\Variable)#1089 (2) {
      ["name"]=>
      string(4) "test"
      ["attributes":protected]=>
      array(2) {
        ["startLine"]=>
        int(3)
        ["endLine"]=>
        int(3)
      }
    }
    ["expr"]=>
    object(PhpParser\Node\Scalar\String_)#1090 (2) {
      ["value"]=>
      string(4) "test"
      ["attributes":protected]=>
      array(3) {
        ["startLine"]=>
        int(3)
        ["endLine"]=>
        int(3)
        ["kind"]=>
        int(2)
      }
    }
    ["attributes":protected]=>
    array(2) {
      ["startLine"]=>
      int(3)
      ["endLine"]=>
      int(3)
    }
  }
  ["attributes":protected]=>
  array(2) {
    ["startLine"]=>
    int(3)
    ["endLine"]=>
    int(3)
  }
}
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getNodeStaticType() on null in E:\xampp\htdocs\rector\src\Rector\TypeAnalyzerTrait.php:76
Stack trace:
#0 E:\xampp\htdocs\rector\utils\showcase\src\GetStringValueRector.php(31): Rector\Rector\AbstractRector-&gt;getStaticType(Object(PhpParser\Node\Stmt\Expression))
#1 E:\xampp\htdocs\rector\utils\showcase\src\GetStringValueRector.php(66): Rector\Rector\GetStringValueRector-&gt;refactor(Object(PhpParser\Node\Stmt\Expression))
#2 {main}
  thrown in <b>E:\xampp\htdocs\rector\src\Rector\TypeAnalyzerTrait.php</b> on line <b>76</b><br />

```

maybe someone could help me - thanks!

**Comment by TomasVotruba** [comment]
Hi, 

- How do you register the service in `rector.yml`?
- What exact `vendor/bin/rector` command do you run?

**Comment by TomasVotruba** [comment]
Oh, I see it now. This cannot work, as you use Rector without container: 

```php
var_dump($nodes[0]);

$inst = new GetStringValueRector();
$inst->refactor($nodes[0]);
```

You need to register is to config:

```yaml
# rector.yml
services:
    GetStringValueRector: ~
```

Then run Rector on your code:

```bash
vendor/bin/rector process src/YourFile.php --dry-run
vendor/bin/rector process src/YourFile.php
```
